/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import java.nio.charset.StandardCharsets;
import java.util.*;
import org.w3c.dom.*;

/** Data-only stock-derived pipeline admission, before any native XML deserialization. */
public final class NativePortablePipelines {
    private NativePortablePipelines() {}
    // Generated by NativePortablePipelineTest from settled, freshly generated pinned native defaults.
    // Every non-editable attribute, child, stage name and ordering participates in the digest.
    // Context binding prevents adopting a valid stock pipeline into a different native consumer.
    static final Map<String,Set<String>> TRUSTED = Map.ofEntries(
        Map.entry("openpnp-machine/machine/cameras/camera[org.openpnp.machine.reference.camera.SimulatedUpCamera]/advanced-calibration/pipeline",Set.of("25f7c7404510b474e9302c036405a2d4ceba29e23735d4b0c7c3e2078f70f35c")),
        Map.entry("openpnp-machine/machine/feeders/feeder[org.openpnp.machine.reference.feeder.ReferenceStripFeeder]/pipeline",Set.of("688e75cc2f22973371cb0daa7143b9c4dcc8d088bdfe2fe789bb727893923d3f")),
        Map.entry("openpnp-machine/machine/heads/head/cameras/camera[org.openpnp.machine.reference.camera.ImageCamera]/advanced-calibration/pipeline",Set.of("25f7c7404510b474e9302c036405a2d4ceba29e23735d4b0c7c3e2078f70f35c")),
        Map.entry("openpnp-machine/machine/nozzle-tips/nozzle-tip/calibration/pipeline",Set.of("f63c7ec906e9ae8dcc121efa39ef51c34a59274670bb03c387a57213b900a8c1")),
        Map.entry("openpnp-vision-settings/vision-settings[org.openpnp.model.BottomVisionSettings]/cv-pipeline",Set.of("4e048f9fbd55f40b38b5e3f3e8dc6a14f662ffef5ad9dcdbd97fbdad9e36f975","85ca4667cd719dc65e390bf8cb179b61e2e690f6271be9b40c7c0b2187d5a2c7","b0657cf3566eb64b20b84d8fd826c71cff50cf1325d0b6016db1353f61d1ab9e")),
        Map.entry("openpnp-vision-settings/vision-settings[org.openpnp.model.FiducialVisionSettings]/cv-pipeline",Set.of("019eb7ec010806498e626dc6b313b2082d0984b1e44084b95eeab3df90373a9d","3e38bbc102a215f11a75f5dfe80bf9675ec7a6f736eabf0d2ab2ae166f588fc6"))
    );
    static Set<String> editable(Element stage) {
        switch(stage.getAttribute("class")) {
        case "org.openpnp.vision.pipeline.stages.BlurGaussian":return Set.of("kernel-size");
        case "org.openpnp.vision.pipeline.stages.Threshold":return Set.of("threshold","auto","invert");
        case "org.openpnp.vision.pipeline.stages.MaskHsv":return "true".equals(stage.getAttribute("auto"))?Set.of():Set.of("hue-min","hue-max","saturation-min","saturation-max","value-min","value-max","invert");
        default:return Set.of();
        }
    }
    static String context(Element pipeline) {
        List<String> parts=new ArrayList<>();for(Node n=pipeline;n instanceof Element;n=n.getParentNode()){
            Element e=(Element)n;String tag=e.getTagName();if(Set.of("camera","vision-settings","feeder").contains(tag))tag+="["+e.getAttribute("class")+"]";parts.add(tag);
        }Collections.reverse(parts);return String.join("/",parts);
    }
    static String fingerprint(Element pipeline)throws Exception {
        Element copy=(Element)pipeline.cloneNode(true);NodeList stages=copy.getElementsByTagName("cv-stage");
        Map<String,Element> named=new HashMap<>();for(int i=0;i<stages.getLength();i++){Element stage=(Element)stages.item(i);named.put(stage.getAttribute("name"),stage);for(String field:editable(stage))stage.removeAttribute(field);}
        // Native parameter execution writes these target fields. The parameter definition itself
        // remains fully hashed, including its exact target, type, bounds, default and namespace.
        Map<String,String> targetFields=Map.of("threshold","threshold","minArea","min-area","minFeatureSize","min-feature-size","maxDistance","max-distance","symmetricLeftRight","symmetric-left-right","symmetricUpperLower","symmetric-upper-lower");
        for(int i=0;i<stages.getLength();i++){Element stage=(Element)stages.item(i);if(stage.getAttribute("class").endsWith(".ParameterNumeric")||stage.getAttribute("class").endsWith(".ParameterBool")){Element target=named.get(stage.getAttribute("stage-name"));String field=targetFields.get(stage.getAttribute("property-name"));if(target!=null&&field!=null)target.removeAttribute(field);}}
        return NativePortableConfiguration.sha(NativePortableConfiguration.JSON.toJson(NativePortableConfiguration.node(copy)).getBytes(StandardCharsets.UTF_8));
    }
    static void validate(Element pipeline)throws Exception {
        if(!TRUSTED.getOrDefault(context(pipeline),Set.of()).contains(fingerprint(pipeline)))NativePortableLimits.reject("Pipeline does not match a pinned stock-derived structure in its native consumer; unsupported fields/topology are never dropped or clamped");
    }
    public static Map<String,Object> describe(){return Bridge.map("profile","pinned-stock-derived-v1","upstream_commit",Bridge.UPSTREAM,"consumer_contexts",TRUSTED.size(),"editable_stage_fields",Bridge.map("BlurGaussian",List.of("kernel-size"),"Threshold",List.of("threshold","auto","invert"),"MaskHsv",List.of("hue-min","hue-max","saturation-min","saturation-max","value-min","value-max","invert")),"parameter_definitions","exact-stock-names-targets-bounds-defaults","parameter_assignments","bounded-declared-scalars","parameter_written_target_fields","bounded-target-values-with-exact-stock-parameter-definition","other_fields_and_topology","exact-stock","unsupported_custom_pipelines","rejected-without-modification");}
}
