import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {projectProgress} from '../../src/openpnp/node/progress.mjs';import {requireControllerProfile} from '../../plugins/openpnp/scripts/controller-profile.mjs';
const receipt=async name=>JSON.parse(await readFile(new URL(`./fixtures/controller-diagnostic/recorded-native/${name}.json`,import.meta.url),'utf8'));
test('actual receipt fixtures retain exact native source hashes',async()=>{const p=JSON.parse(await readFile(new URL('./fixtures/controller-diagnostic/recorded-native/provenance.json',import.meta.url),'utf8'));for(const row of p.entries){const b=await readFile(new URL(`./fixtures/controller-diagnostic/recorded-native/${row.case}.json`,import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),row.sha256);}});
function checkObservation(actual,source){assert.equal(actual.phase,source.phase);assert.equal(actual.observed_at,source.observed_at);assert.equal(actual.observation_sequence,source.observation_sequence);if(source.native){assert.deepEqual(actual.native,source.native);assert.equal(actual.native.current_model_validation_performed_by_snapshot,false);assert.equal(actual.native.durable_receipt,false);}}
for(const name of ['normal','wrapper-error'])test(`actual ${name} projects exact protocol flags and wrapper/body distinction`,async()=>{
 const x=await receipt(name);assert.equal(requireControllerProfile(x.capabilities,{fresh:true}),true);const p=projectProgress('openpnp_get_operation',x.operation);assert.equal(p.state,x.operation.state);assert.equal(p.controller_instance_id,x.operation.controller_instance_id);
 const a=name==='normal'?p.result:p.result.known_body_outcome.result,b=name==='normal'?x.operation.result:x.operation.result.known_body_outcome.result;assert.equal(a.completed_recipe,b.completed_recipe);assert.equal(a.outcome_unknown,b.outcome_unknown);assert.equal(a.steps_attempted,b.steps_attempted);checkObservation(a.observation,b.observation);
 if(name==='wrapper-error'){assert.equal(p.state,'outcome_unknown');assert.equal(p.result.code,'NATIVE_WRAPPER_FAILED');assert.equal(a.completed_recipe,true);}
 const status=projectProgress('openpnp_get_status',x.status);assert.equal(status.controller_history.steps_count,4);assert.equal(status.controller_history.retired,true);assert.equal(status.controller_history.native_authority_restored,false);checkObservation(status.controller_diagnostic.observation,x.status.controller_diagnostic.observation);
});
test('actual admission force failure retains uncommitted IDs and false authority facts',async()=>{
 const x=await receipt('admission-force'),p=projectProgress('openpnp_get_request_status',x.request_receipt);assert.deepEqual(p.uncommitted_admission,x.request_receipt.uncommitted_admission);assert.equal(p.uncommitted_admission.native_dispatch_performed,false);assert.equal(p.uncommitted_admission.durable_admission_confirmed,false);
 const s=projectProgress('openpnp_get_status',x.status);assert.equal(s.journal_fault,true);assert.equal(s.controller_diagnostic.generation_spent,true);assert.equal(s.controller_diagnostic.uncommitted_observation.publication_confirmed,false);assert.equal(s.controller_diagnostic.uncommitted_observation.admission.operation_id,p.uncommitted_admission.operation_id);
});
test('actual outcome force failure keeps body unknown under nonterminal publication fault and cached native provenance',async()=>{
 const x=await receipt('outcome-force'),p=projectProgress('openpnp_get_request_status',x.request_receipt);assert.equal(p.operation.state,'running');assert.equal(p.operation.native_completion.phase,'publication-fault');assert.equal(p.operation.publication_fault.durable,false);const body=p.operation.publication_fault.known_body_outcome.result;assert.equal(body.outcome_unknown,true);assert.equal(body.completed_recipe,false);checkObservation(body.observation,x.request_receipt.operation.native_completion.publication_fault.known_body_outcome.result.observation);
 const s=projectProgress('openpnp_get_status',x.status),u=s.controller_diagnostic.uncommitted_observation;assert.equal(u.publication_confirmed,false);assert.equal(u.known_native_outcome.native_returned,true);assert.equal(s.controller_history.pending.step,'identify');assert.equal(s.controller_history.native_authority_restored,false);assert.ok(Buffer.byteLength(JSON.stringify(s))<32768);assert.equal(s.response_view.retained_snapshot,false);
});
