import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { setTimeout as delay } from 'node:timers/promises';
import { Client } from '../../src/openpnp/node/node_modules/@modelcontextprotocol/sdk/dist/esm/client/index.js';
import { StdioClientTransport } from '../../src/openpnp/node/node_modules/@modelcontextprotocol/sdk/dist/esm/client/stdio.js';
import { readCompleteResponse } from '../../scripts/openpnp-read-response.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const connectionFile=process.env.OPENPNP_MATERIAL_CONNECTION_FILE,out=process.env.OPENPNP_MATERIAL_EVIDENCE_DIR;
const server=process.env.OPENPNP_MATERIAL_MCP_SERVER??path.join(root,'plugins/openpnp/mcp/server.mjs');
const sha=b=>createHash('sha256').update(b).digest('hex');

test('official SDK runs two native jobs through explicit four-slot virtual tray changeover', {skip:!connectionFile,timeout:210000},async()=>{
 assert.ok(out,'Evidence output is required');await mkdir(out,{recursive:true});const state=path.join(out,'mcp-state');await mkdir(state,{mode:0o700});
 const files=[server,path.join(root,'plugins/openpnp/bridge/openpnp-codex-bridge.jar'),fileURLToPath(import.meta.url)];const hashes=async()=>Object.fromEntries(await Promise.all(files.map(async f=>[path.relative(root,f),sha(await readFile(f))])));
 const before=await hashes();const evidence={kind:'official-sdk-native-material-changeover',started_at:new Date().toISOString(),node:process.version,source_hashes:before,simulation_only:true,physical_inventory_verified:false,restart_authority_qualified:false,checks:[],operations:[],requests:[]};
 const client=new Client({name:'native-material-changeover',version:'1'});const transport=new StdioClientTransport({command:process.execPath,args:[server,'--stdio'],cwd:state,env:{PATH:process.env.PATH??'',OPENPNP_STATE_DIR:state,OPENPNP_CONNECTION_FILE:connectionFile},stderr:'pipe'});let session;
 const check=(name,fn)=>{fn();evidence.checks.push(name);};
 async function call(name,args={}){const raw=await client.callTool({name:`openpnp_${name}`,arguments:args});const v=await readCompleteResponse(raw.structuredContent,p=>call('read_response_page',p));if(raw.isError)throw Object.assign(new Error(v.error.message),v.error);return v;}
 async function status(){return call('get_status',{view:'progress'});}
 async function request(name,args={}){const bound={session_id:session,request_id:randomUUID(),expected_config_revision:(await status()).config_revision,...args};evidence.requests.push({name,...bound,session_id:'<redacted>'});return {bound,handle:await call(name,bound)};}
 async function observe(handle){const until=Date.now()+150000;let op=handle;while(['accepted','running'].includes(op.state)){assert.ok(Date.now()<until,'Timed out observing original operation; no replay');await delay(25);op=await call('get_operation',{operation_id:handle.operation_id,view:'progress'});}const full=await call('get_operation',{operation_id:handle.operation_id,view:'full'});while((await status()).native_busy){assert.ok(Date.now()<until,'Native wrapper did not release; no replay');await delay(10);}evidence.operations.push(full);return full;}
 async function operation(name,args={},expected='succeeded'){const{handle}=await request(name,args);const op=await observe(handle);assert.equal(op.state,expected,JSON.stringify(op));return op.result;}
 const counts=async()=>Object.fromEntries((await call('get_configuration')).settings.feeders.map(f=>[f.feeder_id,f.feed_count]));
 async function importJob(count,label,part){const rows=Array.from({length:count},(_,i)=>`R${i+1},1K,${part.package_id},${7+i*2},5,0,top,${part.id},${part.height_mm}`).join('\n');const imported=await call('import_job',{format:'reference-csv',content:`Ref,Val,Package,PosX,PosY,Rot,Side,PartId,Height\n${rows}\n`,units:'mm',widthMm:30,heightMm:20,boardId:`material-${label}`});return operation('prepare_job',{artifact_id:imported.artifact_id});}
 try{
  await client.connect(transport);const caps=await call('get_capabilities');evidence.bridge=caps.bridge;
  check('native advertises exact simulator material scope',()=>{assert.equal(caps.connected,true);assert.equal(caps.bridge.simulation,true);assert.equal(caps.bridge.hardware_qualified,false);for(const name of ['get_material_loads','register_material_load'])assert.ok(caps.tools.includes(`openpnp_${name}`));assert.ok(!caps.tools.includes('openpnp_run_controller_diagnostic'));});
  const catalog=await client.listTools();check('packaged 61 tool catalog includes local board inspection request and readback',()=>{assert.equal(catalog.tools.length,61);for(const name of ['openpnp_request_board_inspection','openpnp_get_board_inspection'])assert.ok(catalog.tools.some(tool=>tool.name===name));});
  const initial=await status();assert.equal(initial.job_state,'absent');assert.equal(initial.machine.enabled,false);assert.equal((await call('get_material_loads')).loads.length,0);
  session=(await call('request_control_session',{request_id:randomUUID(),ttl_seconds:600})).session_id;
  const conf=await call('get_configuration'),part=conf.parts.find(p=>p.id==='R0603-1K');assert.ok(part?.height_mm>0);const target=conf.settings.feeders.filter(f=>f.part_id===part.id&&f.enabled);assert.equal(target.length,1);const feeder=target[0];evidence.starting_feed_counts=await counts();
  const beforeInventory=await call('get_material_loads');const oldDigest=beforeInventory.available_trays.find(f=>f.feeder_id===feeder.feeder_id).geometry_sha256;
  const plan=await call('plan_configuration',{session_id:session,expected_config_revision:conf.config_revision,changes:[{type:'set_tray_feeder_geometry',feeder_id:feeder.feeder_id,location:feeder.location,count_x:2,count_y:2,pitch_x_mm:2,pitch_y_mm:2,feed_count:0}]});
  await operation('apply_configuration',{plan_id:plan.plan_id});const inventory=await call('get_material_loads'),observed=inventory.available_trays.find(f=>f.feeder_id===feeder.feeder_id);
  check('typed pre-enrollment geometry refresh supplies current digest and observation timestamp',()=>{assert.equal(observed.capacity,4);assert.notEqual(observed.geometry_sha256,oldDigest);assert.match(observed.geometry_sha256,/^[a-f0-9]{64}$/);assert.ok(inventory.available_trays_observed_at);});
  const selected={feeder_id:feeder.feeder_id,part_id:part.id,expected_geometry_sha256:observed.geometry_sha256};const binding={...selected,action:'bind-existing',expected_material_revision:inventory.material_setup_revision};
  const beforeReject=await call('get_status',{view:'full'});await assert.rejects(request('register_material_load',{...binding,request_id:'1-1-1-1-1'}),{code:'INVALID_ARGUMENT'});await assert.rejects(request('register_material_load',{...binding,quantity:4}),{code:'INVALID_ARGUMENT'});assert.equal((await call('get_status',{view:'full'})).metrics.operation_count,beforeReject.metrics.operation_count);const mismatch=await operation('register_material_load',{...binding,expected_geometry_sha256:'0'.repeat(64)},'failed');assert.equal(mismatch.code,'MATERIAL_MODEL_CHANGED');assert.deepEqual(await counts(),evidence.starting_feed_counts);assert.equal((await call('get_material_loads')).loads.length,0);evidence.pre_schema_operation_count=beforeReject.metrics.operation_count;
  const bound=await operation('register_material_load',binding),first=bound.load.load_id;assert.equal(bound.load.observed_advances,0);assert.equal(bound.load.capacity,4);
  const backup=await operation('backup_configuration');await assert.rejects(call('plan_configuration',{session_id:session,expected_config_revision:(await status()).config_revision,changes:[{type:'set_machine_speed',speed:0.5}]}),{code:'MATERIAL_CONFIGURATION_LOCKED'});assert.equal((await operation('restore_configuration',{artifact_id:backup.artifact_id},'failed')).code,'MATERIAL_CONFIGURATION_LOCKED');assert.equal((await operation('test_feeder',{feeder_id:feeder.feeder_id},'failed')).code,'MATERIAL_MANUAL_FEED_UNSUPPORTED');
  await operation('set_machine_enabled',{enabled:true});await operation('home_machine');
  const jobA=await importJob(3,'A',part);assert.equal((await operation('validate_job')).valid,true);const resultA=await operation('start_job',{job_id:jobA.job_id});assert.equal(resultA.placed,3);
  let loads=await call('get_material_loads');let old=loads.loads.find(x=>x.load_id===first);assert.equal(old.current_index,3);assert.equal(old.observed_advances,3);assert.equal(old.remaining_configured_slots,1);
  const jobB=await importJob(2,'B',part);const rejected=await operation('validate_job');assert.equal(rejected.valid,false);assert.match(JSON.stringify(rejected.errors),/INSUFFICIENT_CONFIGURED_CAPACITY/);assert.equal((await operation('start_job',{job_id:jobB.job_id},'failed')).code,'JOB_NOT_VALIDATED');assert.equal((await counts())[feeder.feeder_id],3);
  check('finite capacity blocks the second native job before any feed',()=>{assert.equal(resultA.placed,3);assert.equal(rejected.valid,false);});
  assert.equal((await operation('register_material_load',{...selected,action:'replace-full-tray',expected_material_revision:loads.material_setup_revision,expected_load_id:first},'failed')).code,'MACHINE_ENABLED');
  await operation('set_machine_enabled',{enabled:false});const replacement=await request('register_material_load',{...selected,action:'replace-full-tray',expected_material_revision:loads.material_setup_revision,expected_load_id:first});const replaced=await observe(replacement.handle);assert.equal(replaced.state,'succeeded');const second=replaced.result.load.load_id;assert.notEqual(second,first);assert.equal((await counts())[feeder.feeder_id],0);
  const duplicate=await call('register_material_load',replacement.bound);assert.equal(duplicate.operation_id,replaced.operation_id);assert.equal((await call('get_material_loads')).loads.length,2);assert.equal(replaced.result.job_validation,'requires-revalidation');
  await operation('set_machine_enabled',{enabled:true});await operation('home_machine');assert.equal((await operation('start_job',{job_id:jobB.job_id},'failed')).code,'JOB_NOT_VALIDATED');assert.equal((await operation('validate_job')).valid,true);const resultB=await operation('start_job',{job_id:jobB.job_id});assert.equal(resultB.placed,2);
  loads=await call('get_material_loads');old=loads.loads.find(x=>x.load_id===first);const current=loads.loads.find(x=>x.load_id===second);evidence.material_loads=loads;
  check('retired and active material identities retain 3 + 2 actual native slot advances',()=>{assert.equal(old.observed_advances,3);assert.equal(old.current_index,3);assert.equal(old.remaining_configured_slots,1);assert.equal(current.observed_advances,2);assert.equal(current.current_index,2);assert.equal(current.remaining_configured_slots,2);assert.equal(loads.pending_changes.length,0);assert.equal(loads.pending_feeds.length,0);assert.equal(loads.physical_inventory_verified,false);});
  const boardLoads=await call('get_board_loads');assert.equal(boardLoads.loads.reduce((sum,l)=>sum+l.placed_history_count,0),5);evidence.completed_native_placements=5;
  const connection=JSON.parse(await readFile(connectionFile,'utf8'));assert.ok(connection.url.startsWith('http://127.0.0.1:'));
  // Read only the test-owned native journal selected by the runner's connection path.
  const journalPath=path.join(path.dirname(connectionFile),'journal/operations.jsonl');const bytes=await readFile(journalPath);const journal=bytes.toString('utf8').trim().split('\n').map(JSON.parse);const feedRows=journal.filter(x=>['native_action_intent','native_action_outcome'].includes(x.type)&&x.payload.kind==='feed');
  check('forced journal associates exactly five native feeds with the two explicit material loads',()=>{assert.equal(feedRows.filter(x=>x.type==='native_action_intent').length,5);assert.equal(feedRows.filter(x=>x.type==='native_action_outcome').length,5);for(const r of feedRows)assert.ok([first,second].includes(r.payload.context.material_load.load_id));assert.equal(journal.filter(x=>x.type==='material_load_intent').length,2);assert.equal(journal.filter(x=>x.type==='material_load_outcome').length,2);});
  evidence.native_feed_intents=5;evidence.native_feed_outcomes=5;evidence.journal_sha256=sha(bytes);evidence.native_feed_records=feedRows;evidence.board_loads=boardLoads;
  await operation('set_machine_enabled',{enabled:false});await call('release_control_session',{session_id:session});session=null;assert.deepEqual(await hashes(),before);evidence.passed=true;
 }catch(e){evidence.passed=false;evidence.failure={code:e.code,message:e.message,stack:e.stack,details:e.details,known_response:e.known_response};try{evidence.failure_status=await status();}catch(statusError){evidence.status_error={code:statusError.code,message:statusError.message};}throw e;}
 finally{if(session)try{await call('release_control_session',{session_id:session});}catch{}await client.close();evidence.finished_at=new Date().toISOString();await writeFile(path.join(out,'mcp-native-material-loads.json'),JSON.stringify(evidence,(k,v)=>k==='configuration_root'?'<owned-native-configuration>':v,2)+'\n');}
});
