/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.Callable;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.model.*;

/** Actual native material models, existing coordinator permits and forced component journals.
 * Fault/wrapper observations come from the explicitly synthetic continuation fixture. Reflected
 * corruption is negative-test-only. No native job execution, Bridge/UI, or restart reattachment. */
public final class NativeMaterialContinuationAdoptionTest {
 static final List<String> checks=new ArrayList<>();static int refusals,adoptions;static Path root;
 interface Work {void run()throws Exception;}
 static void yes(boolean condition,String why){if(!condition)throw new AssertionError(why);checks.add(why);}
 static Map<String,Object> o(Object value)throws Exception{return NativeFaultedJobReplacement.object(value);}
 static Map<String,Object> copy(Map<String,Object> value)throws Exception{return NativeFaultedJobReplacement.mutable(value);}
 static <T>T task(Callable<T> work)throws Exception{return NativeReplacementContinuationTest.task(work);}
 static void no(String why,Work work)throws Exception{try{work.run();throw new AssertionError("Accepted "+why);}catch(java.io.IOException|Bridge.Fault|NativeJobLineage.Fault expected){refusals++;yes(true,why+" refused: "+expected.getMessage());}}
 static void same(Object a,Object b,String why)throws Exception{yes(NativeFaultedJobReplacement.same(a,b),why);}
 static List<String> ids(NativeReplacementContinuationTest.Fixture f)throws Exception{return new ArrayList<>((List<String>)f.e.capture.dependencies().get("material_load_ids"));}
 static ReferenceTrayFeeder feeder(NativeReplacementContinuationTest.Fixture f,String old)throws Exception{return (ReferenceTrayFeeder)NativeReplacementContinuationTest.config.getMachine().getFeeder((String)o(o(f.e.oldMaterial.get("loads")).get(old)).get("feeder_id"));}
 static void write(String name,Object value)throws Exception{Files.writeString(root.resolve(name),NativeReplacementContinuationTest.JSON.toJson(value)+"\n",StandardOpenOption.CREATE_NEW);}
 static Map<String,Object> stable(NativeReplacementContinuationTest.Fixture f)throws Exception{return NativeFaultedJobReplacement.frozen(NativeFaultedJobReplacement.map("material",f.e.material.captureReplacementState(),"original",NativeReplacementContinuationTest.immutableOriginal(f.e),"history",f.e.oldJob.getPlacedStatusSnapshot(),"configuration_files",NativeReplacementContinuationTest.configurationFiles(),"counters",NativeReplacementContinuationTest.counters()));}
 static void unchangedRefusal(NativeReplacementContinuationTest.Fixture f,String why,Work work)throws Exception{Map<String,Object> before=stable(f);byte[] journal=Files.readAllBytes(f.e.file);int receipts=((List<?>)f.e.material.snapshot().get("continuation_adoption_receipts")).size();no(why,work);same(before,stable(f),why+" preserves material, original outcomes, native counters and configuration files");yes(Arrays.equals(journal,Files.readAllBytes(f.e.file))&&receipts==((List<?>)f.e.material.snapshot().get("continuation_adoption_receipts")).size(),why+" writes no journal or adoption receipt");}
 @SuppressWarnings("unchecked") static Map<String,Object> internal(NativeMaterialLoads m,String name)throws Exception{var field=NativeMaterialLoads.class.getDeclaredField(name);field.setAccessible(true);return (Map<String,Object>)field.get(m);}
 static void recordNegatives(NativeReplacementContinuationTest.Fixture f,Map<String,Object> receipt)throws Exception{
  Map<String,Object> bad=copy(receipt);bad.put("receipt_id",UUID.randomUUID().toString());
  unchangedRefusal(f,"duplicate continuation and old-load pair",()->f.e.material.prepareEvent("material_continuation_adoption",bad));
  // The original already-committed target is used only for closed-schema/component checks.
  for(String key:List.of("schema_version","old_load_id","parent_outcome_id","parent_outcome_sha256","old_load_sha256","old_feed_facts_sha256","physical_inventory_verified","execution_authority_restored")){
   Map<String,Object> altered=copy(receipt);altered.put("receipt_id",UUID.randomUUID().toString());altered.put("continuation_id",UUID.randomUUID().toString());
   if(key.equals("schema_version"))altered.put(key,2);else if(key.endsWith("_id"))altered.put(key,UUID.randomUUID().toString());else if(key.endsWith("sha256"))altered.put(key,"e".repeat(64));else altered.put(key,true);
   unchangedRefusal(f,"changed material receipt "+key,()->f.e.material.prepareEvent("material_continuation_adoption",altered));
  }
  Map<String,Object> collision=copy(receipt);collision.put("receipt_id",receipt.get("parent_outcome_id"));collision.put("continuation_id",UUID.randomUUID().toString());unchangedRefusal(f,"adoption receipt collides with original replacement receipt",()->f.e.material.prepareEvent("material_continuation_adoption",collision));
  Map<String,Object> extra=copy(receipt);extra.put("unexpected","no");unchangedRefusal(f,"unknown material adoption field",()->f.e.material.prepareEvent("material_continuation_adoption",extra));
  Map<String,Object> wrongPhase=copy(receipt);wrongPhase.put("receipt_id",UUID.randomUUID().toString());wrongPhase.put("phase_row_sha256","d".repeat(64));unchangedRefusal(f,"foreign captured phase digest",()->f.e.replacement.prepareContinuationObservation("material_continuation_adoption",wrongPhase));
  Map<String,Object> wrongAuthority=copy(receipt);wrongAuthority.put("receipt_id",UUID.randomUUID().toString());wrongAuthority.put("recovery_operation_id",UUID.randomUUID().toString());unchangedRefusal(f,"foreign fresh local operation",()->f.e.replacement.prepareContinuationObservation("material_continuation_adoption",wrongAuthority));
  Map<String,Object> badNative=copy(receipt);badNative.put("receipt_id",UUID.randomUUID().toString());badNative.put("continuation_id",UUID.randomUUID().toString());o(badNative.get("native_observation")).put("native_feed_count",1);unchangedRefusal(f,"nonzero adopted native counter observation",()->f.e.material.prepareEvent("material_continuation_adoption",badNative));
 }
 static void nativeRefusals(NativeReplacementContinuationTest.Fixture f,NativeFaultedJobReplacement.ContinuationPermit permit,String old)throws Exception{
  unchangedRefusal(f,"adoption outside native executor",()->f.e.material.adoptCompletedReplacement(permit,old));
  task(()->{ReferenceTrayFeeder feeder=feeder(f,old);int index=feeder.getFeedCount();feeder.setFeedCount(1);try{unchangedRefusal(f,"changed native counter",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{feeder.setFeedCount(index);}return null;});
  task(()->{ReferenceTrayFeeder feeder=feeder(f,old);Location offsets=feeder.getOffsets();feeder.setOffsets(offsets.derive(offsets.getX()+1,null,null,null));try{unchangedRefusal(f,"changed native tray geometry",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{feeder.setOffsets(offsets);}return null;});
  task(()->{ReferenceTrayFeeder feeder=feeder(f,old);Part part=feeder.getPart();Part other=part==NativeReplacementContinuationTest.tray.getPart()?NativeReplacementContinuationTest.otherTray.getPart():NativeReplacementContinuationTest.tray.getPart();feeder.setPart(other);try{unchangedRefusal(f,"changed native part identity",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{feeder.setPart(part);}return null;});
  task(()->{NativeReplacementContinuationTest.config.getMachine().setEnabled(true);try{unchangedRefusal(f,"enabled machine",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{NativeReplacementContinuationTest.config.getMachine().setEnabled(false);}return null;});
  task(()->{var nozzle=NativeReplacementContinuationTest.config.getMachine().getDefaultHead().getDefaultNozzle();var field=org.openpnp.spi.base.AbstractNozzle.class.getDeclaredField("part");field.setAccessible(true);Object previous=field.get(nozzle);field.set(nozzle,feeder(f,old).getPart());try{unchangedRefusal(f,"nonempty native nozzle model",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{field.set(nozzle,previous);}return null;});
  task(()->{String feeder=feeder(f,old).getId();Map<String,Object> bindings=internal(f.e.material,"bindings");Object binding=bindings.remove(feeder);try{unchangedRefusal(f,"missing retained native binding",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{bindings.put(feeder,binding);}return null;});
  task(()->{Map<String,Object> loads=internal(f.e.material,"loads");Object oldRecord=loads.get(old);Map<String,Object> changed=copy(o(oldRecord));changed.put("current_index",1);loads.put(old,changed);try{unchangedRefusal(f,"changed original load fact",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{loads.put(old,oldRecord);}return null;});
  task(()->{Map<String,Object> feeds=internal(f.e.material,"feeds");String action=feeds.keySet().iterator().next();Object previous=feeds.get(action);Map<String,Object> changed=copy(o(previous));changed.put("state","negative-test-corruption");feeds.put(action,changed);try{unchangedRefusal(f,"changed original pending feed fact",()->f.e.material.adoptCompletedReplacement(permit,old));}finally{feeds.put(action,previous);}return null;});
  task(()->{unchangedRefusal(f,"foreign original load",()->f.e.material.adoptCompletedReplacement(permit,UUID.randomUUID().toString()));NativeMaterialLoads other=new NativeMaterialLoads(NativeReplacementContinuationTest.config,(type,payload)->{throw new AssertionError("Foreign ledger append");});unchangedRefusal(f,"foreign material ledger",()->other.adoptCompletedReplacement(permit,old));return null;});
 }
 static void completed()throws Exception{
  try(var f=new NativeReplacementContinuationTest.Fixture("material-completed","completed")){
   f.closeOriginal("outcome_unknown");var fresh=f.fresh(f.capture(),"continue-faulted-job-replacement");var permit=fresh.begin();String old=(String)o(f.e.oldMaterial.get("active")).get(NativeReplacementContinuationTest.tray.getId());nativeRefusals(f,permit,old);
   Map<String,Object> before=stable(f);int eventCount=f.e.events.size();Map<String,Object> receipt=task(()->f.e.material.adoptCompletedReplacement(permit,old));adoptions++;
   same(before,stable(f),"Actual material adoption preserves every load/feed fact, original outcome/history, native counter and configuration byte/mtime");yes(f.e.events.size()==eventCount+1&&f.e.events.get(eventCount).get("type").equals("material_continuation_adoption"),"Actual completed adoption appends exactly one separate forced receipt");same(receipt,f.e.events.get(eventCount).get("payload"),"Returned adoption equals exact forced journal payload");same(receipt,f.e.material.continuationAdoptionReceipt((String)receipt.get("receipt_id")),"Historical accessor returns exact authoritative adoption receipt");
   Map<String,Object> parent=f.e.material.replacementReceipt((String)receipt.get("parent_outcome_id"));same(parent.get("new_load"),receipt.get("adopted_load"),"Adoption retains original completed replacement load");yes(NativeFaultedJobReplacement.digest(parent).equals(receipt.get("parent_outcome_sha256")),"Adoption retains exact original completed outcome hash");
   yes(Boolean.FALSE.equals(receipt.get("execution_authority_restored"))&&Boolean.TRUE.equals(receipt.get("original_outcomes_preserved")),"Adoption is a separate disposition without restored execution authority");
   try{receipt.put("fake",true);throw new AssertionError("Mutable receipt");}catch(UnsupportedOperationException expected){yes(true,"Adoption receipt is immutable");}
   task(()->{unchangedRefusal(f,"repeated actual permit target adoption",()->f.e.material.adoptCompletedReplacement(permit,old));return null;});recordNegatives(f,receipt);
   write("completed-adoption.json",receipt);write("completed-material.json",f.e.material.snapshot());
   try(var replay=new NativeReplacementContinuationTest.Env("material-adoption-replay",true)){
    Map<String,Integer> counters=NativeReplacementContinuationTest.counters();Map<String,String> files=NativeReplacementContinuationTest.configurationFiles();replay.replay(f.e.events);same(receipt,replay.material.continuationAdoptionReceipt((String)receipt.get("receipt_id")),"Replay retains exact separate material adoption receipt");
    for(Object raw:(List<?>)replay.material.snapshot().get("loads"))yes(Boolean.FALSE.equals(o(raw).get("native_authority")),"Replayed material load receives no native authority");
    task(()->{no("replay receipt cannot restore ready binding",replay.material::requireReady);return null;});yes(Files.size(replay.file)==0,"Adoption replay appends no bytes");same(counters,NativeReplacementContinuationTest.counters(),"Adoption replay never resets native counters");same(files,NativeReplacementContinuationTest.configurationFiles(),"Adoption replay never saves native configuration");write("replayed-adoption.json",replay.material.snapshot());
   }
   fresh.revoke();task(()->{unchangedRefusal(f,"revoked coordinator continuation permit",()->f.e.material.adoptCompletedReplacement(permit,ids(f).get(1)));return null;});permit.close();
  }
 }
 static void mixed()throws Exception{
  try(var f=new NativeReplacementContinuationTest.Fixture("material-mixed","lineage")){
   List<String> ids=ids(f);String completed=ids.get(0),pending=ids.get(1);task(()->f.e.material.replaceRetiredLoad(f.e.permit,completed));f.e.failType="material_replacement_outcome";f.e.failAfterForce=false;f.e.failOccurrence=1;f.e.seenFailures=0;
   task(()->{no("actual interruption before second tray outcome force",()->f.e.material.replaceRetiredLoad(f.e.permit,pending));return null;});f.e.failType=null;
   Map<String,Object> progress=f.e.material.replacementProgress(f.oldRecovery,f.e.faultCapture.digest,ids);yes(((Number)o(progress.get("counts")).get("completed")).intValue()==1&&((Number)o(progress.get("counts")).get("pending")).intValue()==1,"Actual prior material steps retain one completed and one pending target");
   f.closeOriginal("outcome_unknown");var fresh=f.fresh(f.capture(),"continue-faulted-job-replacement");var permit=fresh.begin();Map<String,Object> before=stable(f);Map<String,Object> receipt=task(()->f.e.material.adoptCompletedReplacement(permit,completed));adoptions++;same(before,stable(f),"Completed-target adoption leaves other pending replacement and native state unchanged");
   task(()->{unchangedRefusal(f,"pending target cannot use completed adoption",()->f.e.material.adoptCompletedReplacement(permit,pending));return null;});same(progress,f.e.material.replacementProgress(f.oldRecovery,f.e.faultCapture.digest,ids),"Adoption cannot turn the other pending native replacement into completion");Map<String,Object> pendingIntent=o(((List<?>)f.e.material.snapshot().get("replacement_intents")).get(0)),collision=copy(receipt);collision.put("receipt_id",pendingIntent.get("receipt_id"));collision.put("continuation_id",UUID.randomUUID().toString());unchangedRefusal(f,"adoption receipt collides with unresolved replacement intent",()->f.e.material.prepareEvent("material_continuation_adoption",collision));write("mixed-adoption.json",receipt);write("mixed-progress.json",progress);permit.close();
  }
 }
 static void terminalize(NativeReplacementContinuationTest.Fresh fresh,NativeFaultedJobReplacement.ContinuationPermit permit)throws Exception {
  fresh.revoke();permit.close();Map<String,Object> terminal=NativeReplacementContinuationTest.freshOperation(fresh);terminal.put("state","outcome_unknown");terminal.put("native_completion",NativeFaultedJobReplacement.map("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));fresh.fixture.e.append("operation",terminal);fresh.fixture.e.terminalWrappers.add(fresh.operation);
 }
 static void refusedFreshChangedTarget(NativeReplacementContinuationTest.Fixture f,NativeFaultedJobReplacement.ContinuationPermit permit,String old,boolean stillActive,String why)throws Exception {
  task(()->{permit.check();Map<String,Object> captured=o(permit.authorizeMaterial(f.e.material,old).get("phase_row"));yes("completed".equals(captured.get("phase"))&&Boolean.FALSE.equals(captured.get("current_matches_replacement_receipt"))&&Boolean.valueOf(stillActive).equals(captured.get("replacement_still_active")),"Fresh decision captures the actual changed material state for "+why);
   for(Object raw:(List<?>)f.e.material.snapshot().get("continuation_adoption_receipts"))yes(!permit.continuationId().equals(o(raw).get("continuation_id")),"Fresh decision has no prior adoption receipt that could cause duplicate refusal");
   unchangedRefusal(f,why,()->{try{f.e.material.adoptCompletedReplacement(permit,old);throw new AssertionError("Fresh changed target accepted");}catch(Bridge.Fault error){yes("MATERIAL_CONTINUATION_SCOPE".equals(error.code),"Fresh changed target is refused by material state guard, not a duplicate or stale permit");throw error;}});return null;});
 }
 static void consumedAndChanged()throws Exception {
  try(var f=new NativeReplacementContinuationTest.Fixture("material-consumed","completed")){
   f.closeOriginal("outcome_unknown");var fresh=f.fresh(f.capture(),"continue-faulted-job-replacement");var permit=fresh.begin();String old=(String)o(f.e.oldMaterial.get("active")).get(NativeReplacementContinuationTest.tray.getId());
   Map<String,Object> receipt=task(()->f.e.material.adoptCompletedReplacement(permit,old));adoptions++;String replacementId=(String)o(receipt.get("adopted_load")).get("load_id");Map<String,Object> original=NativeReplacementContinuationTest.immutableOriginal(f.e);
   task(()->{ReferenceTrayFeeder feeder=feeder(f,old);var nozzle=NativeReplacementContinuationTest.config.getMachine().getDefaultHead().getDefaultNozzle();String operationId=UUID.randomUUID().toString();Map<String,Object> operation=NativeFaultedJobReplacement.map("operation_id",operationId,"job_id",f.attempt,"job_revision",f.e.boards.jobRevision(),"board_load_revision",f.e.boards.revision(),"request_id",UUID.randomUUID().toString(),"request_digest","a".repeat(64),"config_revision","cfg-2","method","openpnp_start_job","job_lineage",f.e.lineage.admissionFacts(f.attempt),"state","accepted");f.e.append("operation",operation);
    Map<String,Object> scope=f.e.boards.ledgerScope(f.e.freshJob);NativeActionLedger ledger=new NativeActionLedger(f.e::append,operationId,f.attempt,"cfg-2",(String)scope.get("scope_id"),f.e.freshJob,scope).withMaterialObserver(f.e.material);int before=feeder.getFeedCount();
    try(NativeActionLedger.StepScope step=ledger.openStep(1)){NativeReplacementContinuationTest.config.getScripting().on("Feeder.BeforeFeed",NativeFaultedJobReplacement.map("nozzle",nozzle,"feeder",feeder,"part",feeder.getPart()));feeder.feed(nozzle);NativeReplacementContinuationTest.config.getScripting().on("Feeder.AfterFeed",NativeFaultedJobReplacement.map("nozzle",nozzle,"feeder",feeder,"part",feeder.getPart()));}
    yes(feeder.getFeedCount()==before+1,"Actual native ReferenceTrayFeeder.feed consumes one replacement slot");operation.put("state","succeeded");f.e.append("operation",operation);return null;});
   task(()->{unchangedRefusal(f,"consumed replacement cannot be adopted again",()->f.e.material.adoptCompletedReplacement(permit,old));return null;});same(receipt,f.e.material.continuationAdoptionReceipt((String)receipt.get("receipt_id")),"Historical adoption receipt remains exact after actual feed");
   terminalize(fresh,permit);var consumedDecision=f.fresh(f.capture(),"continue-faulted-job-replacement");var consumedPermit=consumedDecision.begin();yes(!consumedPermit.continuationId().equals(permit.continuationId()),"Consumed replacement is evaluated under a newly minted continuation");refusedFreshChangedTarget(f,consumedPermit,old,true,"fresh decision refuses consumed active replacement");terminalize(consumedDecision,consumedPermit);
   task(()->{ReferenceTrayFeeder feeder=feeder(f,old);f.e.material.register(feeder.getId(),feeder.getPart().getId(),(String)NativeMaterialLoads.describe(feeder).get("geometry_sha256"),"replace-full-tray",replacementId,f.e.material.revision());yes(feeder.getFeedCount()==0,"Later ordinary full-tray replacement establishes another actual zero counter");unchangedRefusal(f,"closed prior decision cannot adopt later full tray",()->f.e.material.adoptCompletedReplacement(permit,old));return null;});
   var changedDecision=f.fresh(f.capture(),"continue-faulted-job-replacement");var changedPermit=changedDecision.begin();yes(!changedPermit.continuationId().equals(consumedPermit.continuationId())&&!changedPermit.continuationId().equals(permit.continuationId()),"Later different full tray is evaluated under another new continuation");refusedFreshChangedTarget(f,changedPermit,old,false,"fresh decision refuses later different zero-counter full tray");terminalize(changedDecision,changedPermit);
   same(receipt,f.e.material.continuationAdoptionReceipt((String)receipt.get("receipt_id")),"Historical adoption receipt remains exact after later full tray replacement");same(original,NativeReplacementContinuationTest.immutableOriginal(f.e),"Later actual feed/change retains original faulted operation and native actions");
   try(var replay=new NativeReplacementContinuationTest.Env("material-consumed-replay",true)){var counters=NativeReplacementContinuationTest.counters();replay.replay(f.e.events);same(receipt,replay.material.continuationAdoptionReceipt((String)receipt.get("receipt_id")),"Replay preserves adoption recorded before later native feed and tray replacement");task(()->{no("consumed historical adoption restores no native authority",replay.material::requireReady);return null;});same(counters,NativeReplacementContinuationTest.counters(),"Consumed history replay resets no current native tray");yes(Files.size(replay.file)==0,"Consumed history replay appends no bytes");}
   write("adoption-after-native-feed-and-tray-change.json",f.e.material.snapshot());permit.close();
  }
 }
 static void uncertainPublication()throws Exception {
  try(var f=new NativeReplacementContinuationTest.Fixture("material-uncertain-publication","completed")){
   f.closeOriginal("outcome_unknown");var fresh=f.fresh(f.capture(),"continue-faulted-job-replacement");var permit=fresh.begin();String old=ids(f).get(0);Map<String,Object> before=stable(f);int events=f.e.events.size();f.e.failType="material_continuation_adoption";f.e.failAfterForce=true;f.e.failOccurrence=1;f.e.seenFailures=0;
   task(()->{no("actual forced adoption with interrupted reducer publication",()->f.e.material.adoptCompletedReplacement(permit,old));return null;});f.e.failType=null;
   yes(f.e.events.size()==events+1&&f.e.events.get(events).get("type").equals("material_continuation_adoption"),"Interrupted append already forced exactly one actual adoption record");Map<String,Object> forced=o(f.e.events.get(events).get("payload"));
   same(before,stable(f),"Uncertain receipt publication performs no native setter, save, load/feed update or original outcome change");yes(Boolean.TRUE.equals(f.e.material.snapshot().get("continuation_adoption_publication_uncertain"))&&f.e.material.continuationAdoptionReceipt((String)forced.get("receipt_id"))==null,"Uncommitted in-memory adoption remains explicitly publication-uncertain");
   task(()->{unchangedRefusal(f,"same permit cannot retry after uncertain force",()->f.e.material.adoptCompletedReplacement(permit,old));unchangedRefusal(f,"other completed target cannot bypass uncertain force",()->f.e.material.adoptCompletedReplacement(permit,ids(f).get(1)));return null;});
   f.e.material.finishRecovery();yes(Boolean.TRUE.equals(f.e.material.snapshot().get("continuation_adoption_publication_uncertain")),"finishRecovery cannot clear same-instance uncertain publication fence");
   task(()->{unchangedRefusal(f,"same instance finishRecovery cannot reopen adoption",()->f.e.material.adoptCompletedReplacement(permit,old));return null;});
   try(var replay=new NativeReplacementContinuationTest.Env("material-uncertain-replay",true)){
    var counters=NativeReplacementContinuationTest.counters();var files=NativeReplacementContinuationTest.configurationFiles();replay.replay(f.e.events);same(forced,replay.material.continuationAdoptionReceipt((String)forced.get("receipt_id")),"New reducer replays the exact already-forced adoption once");
    yes(((List<?>)replay.material.snapshot().get("continuation_adoption_receipts")).size()==1,"Verified replay creates only the one previously forced adoption disposition");task(()->{no("verified receipt replay still grants no native binding",replay.material::requireReady);return null;});same(counters,NativeReplacementContinuationTest.counters(),"Uncertain adoption replay changes no native counter");same(files,NativeReplacementContinuationTest.configurationFiles(),"Uncertain adoption replay saves no configuration");yes(Files.size(replay.file)==0,"Uncertain adoption replay appends no new record");write("uncertain-replayed-material.json",replay.material.snapshot());
   }
   write("uncertain-forced-adoption.json",forced);permit.close();
  }
 }
 public static void main(String[]args)throws Exception{
  root=Path.of(args[1]);int exit=0;try{NativeReplacementContinuationTest.initialize(root);completed();mixed();consumedAndChanged();uncertainPublication();write("proof.json",NativeFaultedJobReplacement.map("passed",true,"assertions",checks.size(),"refusals",refusals,"actual_completed_material_adoptions",adoptions,"actual_forced_interrupted_adoption_publications",1,"actual_native_feeds",1,"ordinary_full_tray_replacements",1,"fresh_continuation_changed_load_refusals",2,"checks",checks,"native_jobs_initialized",0,"native_placements",0,"scope","Real native material models and coordinator-issued continuation permits; actual forced separate adoption receipts; explicit synthetic original fault/wrapper contract fixture; reflection only negative corruption tests; no Bridge/UI or restart reattachment"));System.out.println("NATIVE_MATERIAL_CONTINUATION_ADOPTION_PASS "+checks.size()+" assertions "+refusals+" refusals "+adoptions+" actual adoptions");}catch(Throwable error){error.printStackTrace();exit=1;}finally{if(NativeReplacementContinuationTest.config!=null)NativeReplacementContinuationTest.config.getMachine().close();}System.exit(exit);
 }
}
