/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.io.*;
import java.nio.*;
import java.nio.channels.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.spi.*;

/** Actual pinned native Job/tray/load setters plus real forced files. Action and sensing hooks
 * are explicitly synthetic contract fixtures; this test does not initialize or run a PnP job. */
public final class NativeFaultedJobReplacementTest {
 static final Gson JSON=new GsonBuilder().serializeNulls().create();static Configuration config;static ReferenceTrayFeeder tray;static Path root;static int checks,refusals;
 interface Work{void run()throws Exception;}static void yes(boolean x,String why){checks++;if(!x)throw new AssertionError(why);}static void no(String why,Work w)throws Exception{try{w.run();throw new AssertionError("Accepted "+why);}catch(IOException|Bridge.Fault|NativeJobLineage.Fault expected){checks++;refusals++;}}
 static Map<String,Object> m(Object...v){return NativeFaultedJobReplacement.map(v);}static Map<String,Object> o(Object p)throws IOException{return NativeFaultedJobReplacement.object(p);}static String id(){return UUID.randomUUID().toString();}
 static <T>T task(Callable<T> c)throws Exception{try{return config.getMachine().submit(c,null,true).get(30,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Error)throw(Error)e.getCause();throw(Exception)e.getCause();}}
 static final class Env implements AutoCloseable {
  final String jobId=id(),opId=id(),requestId=id();final NativeMaterialLoads material;final NativeBoardLoads boards;final NativeJobLineage lineage;final NativeFaultedJobReplacement replacement;final Path file;final FileChannel channel;
  final List<Map<String,Object>> events=new ArrayList<>();Job oldJob,freshJob;Map<String,Object> operation,oldMaterial,oldBoard,oldLineage;NativeFaultedJobReplacement.Capture capture;NativeFaultedJobReplacement.Permit permit;NativeSensingReconciliation.Capture faultCapture;NativeSensingReconciliation coordinator;NativeVacuumJournal vacuum;final Object localOwner=new Object();String failType;boolean failAfterForce;int setters;long seq;
  Env(String name,boolean replay)throws Exception {
   file=root.resolve(name+".jsonl");channel=FileChannel.open(file,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE);lineage=new NativeJobLineage(this::append);boards=new NativeBoardLoads(this::append);material=new NativeMaterialLoads(config,this::append);replacement=new NativeFaultedJobReplacement(config,material,boards,lineage,this::append);
   if(!replay)task(()->{tray.setFeedCount(2);material.register(tray.getId(),tray.getPart().getId(),(String)NativeMaterialLoads.describe(tray).get("geometry_sha256"),"bind-existing",null,material.revision());oldJob=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(tray.getPart()));lineage.createFresh(jobId,"canonical-simulator");boards.bindJob(oldJob,jobId,true);BoardLocation board=oldJob.getBoardLocations().get(0);oldJob.storePlacedStatus(board,"R1",true);boards.checkpoint(oldJob);
     operation=m("operation_id",opId,"job_id",jobId,"job_revision",boards.jobRevision(),"board_load_revision",boards.revision(),"request_id",requestId,"request_digest","a".repeat(64),"config_revision","cfg-2","method","openpnp_start_job","job_lineage",lineage.admissionFacts(jobId),"state","accepted");append("operation",operation);
     Map<String,Object> loadScope=boards.ledgerScope(oldJob);NativeActionLedger ledger=new NativeActionLedger(this::append,opId,jobId,"cfg-2",(String)loadScope.get("scope_id"),oldJob,loadScope).withMaterialObserver(material);
     try(NativeActionLedger.StepScope step=ledger.openStep(1)){config.getScripting().on("Feeder.BeforeFeed",m("nozzle",config.getMachine().getDefaultHead().getDefaultNozzle(),"feeder",tray,"part",tray.getPart()));tray.setFeedCount(3);}catch(NativeActionLedger.UnresolvedActionFence expected){}
     operation.put("state","outcome_unknown");append("operation",operation);oldMaterial=material.captureReplacementState();oldBoard=boards.captureReplacementState(jobId);oldLineage=lineage.captureReplacementState(jobId);capture=replacement.capture(oldJob,jobId,opId);freshJob=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(tray.getPart()));return null;});
  }
  void append(String type,Map<String,Object> p)throws Exception {
   Runnable mat=material==null?()->{}:material.prepareEvent(type,p);Runnable lin=lineage==null||type.startsWith("job_lineage_")?()->{}:lineage.prepareObservation(type,p);
   if(type.equals(failType)&&!failAfterForce)throw new IOException("injected before force: "+type);Map<String,Object> event=NativeFaultedJobReplacement.frozen(m("sequence",++seq,"type",type,"payload",p));byte[] bytes=(JSON.toJson(event)+"\n").getBytes(java.nio.charset.StandardCharsets.UTF_8);ByteBuffer buffer=ByteBuffer.wrap(bytes);while(buffer.hasRemaining())channel.write(buffer);channel.force(true);events.add(event);if(type.equals(failType)&&failAfterForce)throw new IOException("injected uncertain return after actual force: "+type);mat.run();lin.run();if(boards!=null)boards.observeNativeEvent(type,p);if(replacement!=null)replacement.observe(type,p);
  }
  void admit()throws Exception {
   vacuum=new NativeVacuumJournal();coordinator=new NativeSensingReconciliation(vacuum,(op,instance,replay)->false,replacement::verified);
   String instance=NativeSensingReconciliationTest.INSTANCE,source=NativeSensingReconciliationTest.SOURCE,machine=NativeSensingReconciliationTest.MACHINE;
   Map<String,Object> jobContext=m("job_id",jobId,"job_revision",oldBoard.get("job_revision"),"board_load_revision",oldBoard.get("revision"),"material_setup_revision",oldMaterial.get("revision"),"lineage_id",oldLineage.get("lineage_id"),"lineage_revision",oldLineage.get("lineage_revision"));
   Map<String,Object> context=NativeSensingReconciliationTest.context();context.put("operation_id",opId);context.put("scope","job");context.put("job_context",jobContext);
   Map<String,Object> event=NativeSensingReconciliationTest.event("read.before",100,null,context,source);vacuum.prepare("vacuum_observation_intent",event,instance).run();Map<String,Object> scope=NativeSensingReconciliationTest.scope(instance,source);scope.put("job_context",jobContext);scope.put("dependencies",capture.dependencies());faultCapture=vacuum.captureFaultSet(scope);
   String task=id(),requestOperation=id(),recovery=id();Map<String,Object> taskRecord=coordinator.taskRecord(task,requestOperation,id(),faultCapture,"replace-faulted-job-attempt",1,"2030-01-01T00:00:00Z");coordinator.prepare("sensing_reconciliation_task",taskRecord,instance).run();coordinator.prepare("sensing_reconciliation_intent",coordinator.intentRecord(task,recovery,id(),"2026-09-14T00:00:00Z",1,"synthetic-local-test"),instance).run();NativeSensingReconciliation.Permit recoveryPermit=coordinator.issuePermit(task,recovery,faultCapture.digest,localOwner);
   permit=replacement.begin(capture,freshJob,coordinator,recoveryPermit,localOwner);
  }
  void replay(List<Map<String,Object>> source)throws Exception {for(Map<String,Object> event:source){String t=(String)event.get("type");Map<String,Object> p=o(event.get("payload"));material.recoverEvent(t,p);boards.recoverEvent(t,p);boards.observeNativeEvent(t,p);lineage.observe(t,p);replacement.observe(t,p);if(t.startsWith("faulted_job_replacement_"))replacement.recover(t,p);}material.finishRecovery();boards.finishRecovery();}
  public void close()throws Exception{channel.close();}
 }
 public static void main(String[]args)throws Exception {
  root=Paths.get(args[1]);Files.createDirectories(root);int exit=0;Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);for(Feeder f:config.getMachine().getFeeders())if(f.getPart()==config.getPart("R0603-1K"))tray=(ReferenceTrayFeeder)f;tray.setTrayCountX(3);tray.setTrayCountY(2);
  try {
   try(Env e=new Env("success",false)){
    yes(((List<?>)e.capture.dependencies().get("action_ids")).equals(List.of(e.opId+"/native-action-1")),"capture retains exact native action identity");yes(((List<?>)e.capture.dependencies().get("board_load_ids")).size()==2,"capture includes both affected board roots");yes(o(e.capture.payload.get("action_summaries")).size()==1,"capture retains native unknown action summary");
    no("foreign thread capture",()->e.replacement.capture(e.oldJob,e.jobId,e.opId));task(()->{no("ordinary unknown material readiness",e.material::requireReady);no("same native Job reuse",()->NativeBoardLoads.requireDetachedReplacement(e.oldJob,e.oldJob));Job nativeCopy=new Job();for(BoardLocation original:e.oldJob.getBoardLocations())nativeCopy.addBoardOrPanelLocation(new BoardLocation(original));no("native copy retains old mutable definitions/listeners",()->NativeBoardLoads.requireDetachedReplacement(e.oldJob,nativeCopy));
     Job placementAlias=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(tray.getPart()));Placement linked=placementAlias.getBoardLocations().get(0).getBoard().getPlacement(0);linked.setDefinition(e.oldJob.getBoardLocations().get(0).getBoard().getPlacement(0));try{no("placement definition alias",()->NativeBoardLoads.requireDetachedReplacement(e.oldJob,placementAlias));}finally{linked.setDefinition(linked);}NativeBoardLoads.requireDetachedReplacement(e.oldJob,e.freshJob);yes(true,"canonical fresh graphs share no mutable native definitions");e.admit();return null;});Map<String,Boolean> oldHistory=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());
    task(()->{ReferenceTrayFeeder alias=new ReferenceTrayFeeder();alias.setPart(tray.getPart());alias.setEnabled(true);config.getMachine().addFeeder(alias);try{String oldId=(String)((List<?>)e.capture.dependencies().get("material_load_ids")).get(0);no("unknown material via another enabled feeder alias",()->e.material.replaceRetiredLoad(e.permit,oldId));}finally{config.getMachine().removeFeeder(alias);}return null;});
    Map<String,Object> compound=task(()->e.replacement.replace(e.permit));String attempt=(String)compound.get("replacement_attempt_id");Map<String,Object> d=e.replacement.dispositions(attempt,"none-present");
    yes(e.replacement.verified(e.faultCapture.payload,d,false),"only concrete forced material board lineage receipts validate");yes(oldHistory.equals(e.oldJob.getPlacedStatusSnapshot()),"old native complete placed history unchanged");yes(tray.getFeedCount()==0,"new native tray initialized at zero after durable replacement intent");yes(NativeFaultedJobReplacement.same(o(e.oldMaterial.get("loads")).values().iterator().next(),o(e.material.captureReplacementState().get("loads")).get(o(e.oldMaterial.get("active")).values().iterator().next())),"old material counters retained without decrement");yes(o(e.material.captureReplacementState().get("pending_feeds")).size()==1,"old unknown feed is retained after explicit retirement");yes(e.lineage.retiredJob(e.jobId)&&!e.lineage.retiredJob(attempt),"old attempt retired and fresh lineage distinct");
    task(()->{e.material.requireReady();e.boards.requireReady(e.freshJob);no("old board admission",()->e.boards.requireReady(e.oldJob));no("old alias binding",()->e.boards.bindJob(e.oldJob,e.jobId,false));no("old lineage admission",()->e.lineage.admissionFacts(e.jobId));yes(!e.lineage.snapshot(attempt).admitted,"new job never initialized or admitted by replacement");return null;});
    Map<String,Object> oldFeed=null;for(Map<String,Object> event:e.events)if(event.get("type").equals("native_action_intent")){Map<String,Object> payload=o(event.get("payload"));if(payload.get("kind").equals("feed")){oldFeed=NativeFaultedJobReplacement.mutable(payload);break;}}final Map<String,Object> late=oldFeed;late.put("state","native_hook_returned");late.put("after_hook","Feeder.AfterFeed");late.put("material_after",m("after_index",3,"expected_delta_observed",true,"observation","native-feedCount-at-after-hook","physical_inventory_verified",false));no("late old feed outcome cannot rewrite retired unknown",()->e.material.prepareEvent("native_action_outcome",late));
    Map<String,Object> forged=NativeFaultedJobReplacement.mutable(d);o(((List<?>)forged.get("feeder_loads")).get(0)).put("receipt_sha256","f".repeat(64));yes(!e.replacement.verified(e.faultCapture.payload,forged,false),"forged subreceipt digest refused");Map<String,Object> omitted=NativeFaultedJobReplacement.mutable(d);omitted.put("board_loads",List.of());yes(!e.replacement.verified(e.faultCapture.payload,omitted,false),"partial board union refused");
    try(Env replay=new Env("replay",true)){int before=tray.getFeedCount();replay.replay(e.events);yes(tray.getFeedCount()==before&&oldHistory.equals(e.oldJob.getPlacedStatusSnapshot()),"journal replay never resets tray or old placed history");yes(replay.replacement.verified(e.faultCapture.payload,d,true),"full exact replay verifies historical compound disposition");yes(!replay.replacement.verified(e.faultCapture.payload,d,false),"historical disposition never grants process-local replacement authority");task(()->{no("replayed material has no native binding",replay.material::requireReady);return null;});yes(replay.events.isEmpty()&&Files.size(replay.file)==0,"replay does not append or repeat any native action");}
    try(Env bad=new Env("forged-replay",true)){List<Map<String,Object>> rows=JSON.fromJson(JSON.toJson(e.events),List.class);for(Map<String,Object> r:rows)if(r.get("type").equals("faulted_job_replacement_outcome")){o(r.get("payload")).put("lineage_receipt_sha256","f".repeat(64));break;}no("forged lineage replay digest",()->bad.replay(rows));}
    try(Env missing=new Env("missing-material-intent",true)){List<Map<String,Object>> rows=new ArrayList<>(e.events);rows.removeIf(r->r.get("type").equals("material_replacement_intent"));no("replacement outcome without material intent",()->missing.replay(rows));}
    e.permit.close();task(()->{no("closed permit native reuse",()->e.replacement.replacementJob(e.permit));return null;});yes(!e.replacement.verified(e.faultCapture.payload,d,false),"closed permit cannot supply current authority");
   }
   try(Env e=new Env("failed-material-outcome",false)){task(()->{e.admit();return null;});Map<String,Boolean> history=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());e.failType="material_replacement_outcome";task(()->{no("unforced material outcome",()->e.replacement.replace(e.permit));no("interrupted replacement cannot admit material",e.material::requireReady);return null;});yes(tray.getFeedCount()==0&&history.equals(e.oldJob.getPlacedStatusSnapshot()),"setter failure window preserves old board and explicit unknown new tray");yes(e.replacement.snapshot().isEmpty(),"no compound success after incomplete tray receipt");try(Env replay=new Env("failed-material-replay",true)){replay.replay(e.events);yes(replay.replacement.snapshot().isEmpty()&&o(replay.material.captureReplacementState().get("replacement_intents")).size()==1,"crash prefix retains exact unmatched replacement intent");}}
   for(String boundary:List.of("job_lineage_replacement","material_replacement_intent","board_replacement_intent","board_replacement_outcome","faulted_job_replacement_outcome")){
    try(Env e=new Env("failure-"+boundary,false)){task(()->{e.admit();return null;});Map<String,Boolean> history=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());e.failType=boundary;task(()->{no("force failure at "+boundary,()->e.replacement.replace(e.permit));return null;});yes(e.replacement.snapshot().isEmpty()&&history.equals(e.oldJob.getPlacedStatusSnapshot()),"no compound success or old placed rewrite at "+boundary);try(Env replay=new Env("replay-failure-"+boundary,true)){int before=tray.getFeedCount();replay.replay(e.events);yes(replay.replacement.snapshot().isEmpty()&&tray.getFeedCount()==before&&Files.size(replay.file)==0,"failure prefix replay preserves ambiguity without effects at "+boundary);}}
   }
   try(Env e=new Env("compound-after-force",false)){task(()->{e.admit();return null;});e.failType="faulted_job_replacement_outcome";e.failAfterForce=true;task(()->{no("compound force returned uncertain",()->e.replacement.replace(e.permit));return null;});yes(e.replacement.snapshot().isEmpty()&&Boolean.TRUE.equals(e.replacement.status().get("publication_fault")),"uncertain force return fences current compound authority");try(Env replay=new Env("compound-after-force-replay",true)){int before=tray.getFeedCount();replay.replay(e.events);Map<String,Object> d=replay.replacement.dispositions(e.permit.attemptId(),"none-present");yes(replay.replacement.verified(e.faultCapture.payload,d,true)&&!replay.replacement.verified(e.faultCapture.payload,d,false)&&tray.getFeedCount()==before,"exact forced outcome recovers as historical only without effects");}}
   System.out.println("NATIVE_FAULTED_JOB_REPLACEMENT_PASS "+checks+" checks "+refusals+" refusals; actual pinned native models/tray setters/FileChannel.force; synthetic action/sensing contract events; native jobs initialized 0; native feeds 0; native placements 0; no GUI, process-kill, wrapper, sensor, or hardware qualification");
  }catch(Throwable t){t.printStackTrace();exit=1;}finally{config.getMachine().close();}System.exit(exit);
 }
}
