/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.openpnp.model.*;
import org.openpnp.spi.Machine;
import org.openpnp.machine.reference.ReferencePnpJobProcessor;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;

/** Actual native pause/resume regression: preserved report, exact step/ledger binding and no replay.
 * Canonical entrypoint accepts SAMPLE_ROOT; timing fields are diagnostic observations only. */
public final class NativeStepScalarResumeTest {
 static final Gson G=new Gson();static Bridge bridge;static Machine machine;static String session;static int assertions;
 static void check(boolean yes,String name){if(!yes)throw new AssertionError(name);assertions++;}
 static JsonObject json(Object...v){return G.toJsonTree(Bridge.map(v)).getAsJsonObject();}
 @SuppressWarnings("unchecked")static Map<String,Object> call(String method,JsonObject p)throws Exception{return(Map<String,Object>)bridge.call("openpnp_"+method,p);}
 static Map<String,Object> read(String method,Object...v)throws Exception{return call(method,json(v));}
 static JsonObject mutation(Object...v)throws Exception{JsonObject p=json("request_id",UUID.randomUUID().toString(),"session_id",session,"expected_config_revision",read("get_configuration").get("config_revision"));for(Map.Entry<String,JsonElement> e:json(v).entrySet())p.add(e.getKey(),e.getValue());return p;}
 static Map<String,Object> await(Map<String,Object> initial)throws Exception{String id=(String)initial.get("operation_id");long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(120);while(true){Map<String,Object> op=read("get_operation","operation_id",id);if(!Arrays.asList("accepted","running").contains(op.get("state"))&&!machine.isBusy())return op;if(System.nanoTime()>end)throw new AssertionError("Bounded operation timeout "+id);Thread.sleep(20);}}
 @SuppressWarnings("unchecked")static Map<String,Object> result(Map<String,Object> o){return(Map<String,Object>)o.get("result");}
 static Map<String,Object> run(String m,Object...v)throws Exception{Map<String,Object> o=await(call(m,mutation(v)));check("succeeded".equals(o.get("state")),m+" succeeded: "+G.toJson(o));return o;}
 static long steps(Map<String,Object> o){return((Number)o.get("native_steps_started")).longValue();}
 static JsonObject canonical(Part p,int count,String id){double h=p.getHeight().convertToUnits(LengthUnit.Millimeters).getValue();List<Object> placements=new ArrayList<>();for(int i=0;i<count;i++)placements.add(Bridge.map("ref","R"+i,"partId",p.getId(),"packageId",p.getPackage().getId(),"heightMm",h,"x",5+1.4*(i%100),"y",5+1.4*(i/100),"z",0,"rotation",0,"side","top","enabled",true,"type","placement"));return json("schemaVersion",1,"id",id,"units","mm","coordinateConvention","openpnp-top-view","parts",List.of(Bridge.map("id",p.getId(),"packageId",p.getPackage().getId(),"heightMm",h)),"boards",List.of(Bridge.map("id","board","widthMm",150,"heightMm",150,"placements",placements)),"panels",List.of(),"instances",List.of(Bridge.map("id","A","kind","board","definitionId","board","x",0,"y",0,"z",0,"rotation",0,"side","top","enabled",true)));}
 static String sha(byte[] b)throws Exception{StringBuilder out=new StringBuilder();for(byte x:MessageDigest.getInstance("SHA-256").digest(b))out.append(String.format("%02x",x&255));return out.toString();}
 public static void main(String[]args)throws Exception{
  if(args.length==1){Path artifact=Paths.get(Bridge.class.getProtectionDomain().getCodeSource().getLocation().toURI());Path parent=Files.createTempDirectory("openpnp-step-scalar-resume-");args=new String[]{args[0],parent.resolve("fixture").toString(),sha(Files.readAllBytes(artifact)),"canonical-regression"};}
  if(args.length!=4)throw new IllegalArgumentException("SAMPLE_ROOT NEW_FIXTURE_DIR EXPECTED_BRIDGE_SHA LABEL");Path root=Paths.get(args[1]);Files.createDirectory(root);Path cfg=root.resolve("config");Files.createDirectory(cfg);Path token=root.resolve("token");Files.writeString(token,UUID.randomUUID().toString()+UUID.randomUUID());
  Path jar=Paths.get(Bridge.class.getProtectionDomain().getCodeSource().getLocation().toURI());check(Files.isRegularFile(jar)&&sha(Files.readAllBytes(jar)).equals(args[2]),"exact selected Bridge JAR loaded, no class shadow");
  Configuration.initialize(cfg.toFile());Configuration config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);machine=config.getMachine();int exit=0;
  try{
   check(((ReferencePnpJobProcessor)machine.getPnpJobProcessor()).getJobOrder()==ReferencePnpJobProcessor.JobOrderHint.Unsorted,"matched public native order");
   bridge=new Bridge(config,token,root.resolve("journal"),Paths.get(args[0]),0,true,"sustained-workload");session=(String)read("request_control_session","request_id",UUID.randomUUID().toString(),"ttl_seconds",600).get("session_id");
   run("set_machine_enabled","enabled",true);run("home_machine");Part part=config.getPart("R0603-1K");ReferenceTrayFeeder tray=(ReferenceTrayFeeder)machine.getFeeders().stream().filter(f->f.getPart()==part).findFirst().orElseThrow();check(tray.getFeedCount()==0,"fresh finite inventory");
   String warm=(String)result(run("prepare_job","canonical_job",canonical(part,20,"warmup"))).get("job_id");check(Boolean.TRUE.equals(result(run("validate_job")).get("valid")),"warmup valid");Map<String,Object> warmop=run("start_job","job_id",warm);check(tray.getFeedCount()==20&&((Number)result(warmop).get("placed")).intValue()==20,"twenty real warmup placements/feeds");
   JsonObject job=canonical(part,200,"measured");String id=(String)result(run("prepare_job","canonical_job",job)).get("job_id");check(Boolean.TRUE.equals(result(run("validate_job")).get("valid")),"measured valid");
   JsonObject first=mutation("job_id",id);Map<String,Object> paused=await(call("step_job",first));String operation=(String)paused.get("operation_id");check("paused".equals(paused.get("state"))&&steps(paused)==1,"deterministic first-next native pause");check(((List<?>)result(paused).get("placements")).size()==200&&((Number)result(paused).get("placed")).intValue()==0,"substantial actual paused report, no placements");check(tray.getFeedCount()==20,"first-next pause does not consume a feed");String retained=G.toJson(result(paused));check(retained.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>30000,"retained report exceeds thirty KiB");check(steps(call("step_job",first))==1,"same first-step request does not replay");
   long worker=machine.submit(()->Thread.currentThread().getId(),null,true).get(10,TimeUnit.SECONDS);java.lang.management.ThreadMXBean bean=java.lang.management.ManagementFactory.getThreadMXBean();com.sun.management.ThreadMXBean allocation=bean instanceof com.sun.management.ThreadMXBean?(com.sun.management.ThreadMXBean)bean:null;boolean allocationAvailable=allocation!=null&&allocation.isThreadAllocatedMemorySupported();if(allocationAvailable&&!allocation.isThreadAllocatedMemoryEnabled())allocation.setThreadAllocatedMemoryEnabled(true);long allocatedBefore=allocationAvailable?allocation.getThreadAllocatedBytes(worker):-1;long cpuBefore=bean.isThreadCpuTimeSupported()?bean.getThreadCpuTime(worker):-1;
   JsonObject resume=mutation("operation_id",operation);long started=System.nanoTime();Map<String,Object> accepted=call("resume_job",resume);check(operation.equals(accepted.get("operation_id")),"resume uses original operation");check(retained.equals(G.toJson(result(accepted))),"accepted resume preserves historical result");Map<String,Object> retry=call("resume_job",resume);check(operation.equals(retry.get("operation_id")),"in-flight same resume request deduplicates");Map<String,Object> done=await(retry);double seconds=(System.nanoTime()-started)/1e9;long allocatedAfter=allocationAvailable?allocation.getThreadAllocatedBytes(worker):-1;long cpuAfter=bean.isThreadCpuTimeSupported()?bean.getThreadCpuTime(worker):-1;check(worker==machine.submit(()->Thread.currentThread().getId(),null,true).get(10,TimeUnit.SECONDS),"same native worker throughout timed interval");
   check("succeeded".equals(done.get("state"))&&steps(done)==4004,"all native steps complete once");check(((Number)result(done).get("placed")).intValue()==200&&tray.getFeedCount()==220,"exact measured placements and finite feeds");check("completed".equals(((Map<?,?>)done.get("native_completion")).get("phase")),"terminal receipt waits for native wrapper");check(steps(call("resume_job",resume))==4004&&tray.getFeedCount()==220,"terminal same-request receipt adds no effect");check(retained.equals(G.toJson(result(paused))),"earlier returned paused DTO unchanged");
   Path journal=root.resolve("journal/operations.jsonl");List<String> lines=Files.readAllLines(journal);long stepIntent=0,stepComplete=0,placed=0;Map<String,Integer> outcomes=new TreeMap<>();Set<Long> intents=new HashSet<>();long latestIntent=0;int actionChecks=0;
   for(String line:lines){JsonObject row=new JsonParser().parse(line).getAsJsonObject(),p=row.getAsJsonObject("payload");if(!p.has("operation_id")||!operation.equals(p.get("operation_id").getAsString()))continue;String type=row.get("type").getAsString();if(type.equals("native_step_intent")){long step=p.get("step_index").getAsLong();check(step==++stepIntent&&intents.add(step),"monotonic unique native intent "+step);latestIntent=step;}else if(type.equals("native_step_complete")){stepComplete++;check(stepComplete==latestIntent,"completion follows corresponding intent");}else if(type.startsWith("native_action_")||type.equals("native_placement_checkpoint")){check(p.get("native_step_index").getAsLong()==latestIntent&&intents.contains(latestIntent),"ledger matches exact preceding step intent");actionChecks++;if(type.equals("native_action_outcome")){String key=p.get("kind").getAsString()+":"+p.get("state").getAsString();outcomes.merge(key,1,Integer::sum);}if(type.equals("native_placement_checkpoint")&&p.get("state").getAsString().equals("native-placement-complete-hook"))placed++;}}
   check(stepIntent==4004&&stepComplete==4004,"exact paired durable step counts");for(String k:List.of("feed","pick","align","release"))check(outcomes.getOrDefault(k+":native_hook_returned",0)==200,"exact native outcome "+k);check(placed==200,"exact native placement completion hooks");
   Map<String,Object> status=read("get_status");Map<?,?> progress=(Map<?,?>)status.get("job_progress");check(((Number)progress.get("placed")).intValue()==200&&progress.get("observed_at")!=null&&progress.get("through_sequence")!=null,"final native progress retains freshness");
   System.out.println("STEP_SCALAR_RESUME_RESULT "+G.toJson(Bridge.map("passed",true,"label",args[3],"assertions",assertions,"bridge_sha256",args[2],"bridge_code_source",jar.toString(),"canonical_job_sha256",sha(job.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)),"warmup_placements",20,"measured_placements",200,"total_native_feeds",tray.getFeedCount(),"paused_native_step",1,"resumed_native_steps",4003,"total_native_steps",stepIntent,"native_step_completions",stepComplete,"action_step_binding_checks",actionChecks,"native_action_outcomes",outcomes,"measured_resume_seconds",seconds,"native_worker_allocated_bytes",allocatedBefore>=0&&allocatedAfter>=allocatedBefore?allocatedAfter-allocatedBefore:null,"native_worker_cpu_seconds",cpuBefore>=0&&cpuAfter>=cpuBefore?(cpuAfter-cpuBefore)/1e9:null,"allocation_scope","JDK native worker Java allocation counter; excludes callers, image native allocations and RSS","retained_result_bytes",retained.getBytes(java.nio.charset.StandardCharsets.UTF_8).length,"retained_result_sha256",sha(retained.getBytes(java.nio.charset.StandardCharsets.UTF_8)),"journal_sha256",sha(Files.readAllBytes(journal)),"journal_records",lines.size(),"journal_bytes",Files.size(journal),"poll_ms",20,"native_job_order","Unsorted","physical_qualification",false,"five_percent_target_claimed",false)));
  }catch(Throwable failure){failure.printStackTrace();exit=1;}finally{if(bridge!=null)bridge.close();machine.close();}System.exit(exit);
 }
}
