/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.openpnp.model.*;
import org.openpnp.spi.*;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
public final class NativeLineageBridgeTest {
 static final Gson G=new Gson();static Bridge bridge;static Machine machine;static Configuration config;static String session;static int checks;
 static void check(boolean value,String label){checks++;if(!value)throw new AssertionError(label);}
 static JsonObject obj(Object...p){return G.toJsonTree(Bridge.map(p)).getAsJsonObject();}
 @SuppressWarnings("unchecked")static Map<String,Object> call(String m,JsonObject p)throws Exception{return(Map<String,Object>)bridge.call("openpnp_"+m,p);}
 static JsonObject mutation(Object...p)throws Exception{JsonObject q=obj("session_id",session,"request_id",UUID.randomUUID().toString(),"expected_config_revision",call("get_status",obj()).get("config_revision"));for(var e:obj(p).entrySet())q.add(e.getKey(),e.getValue());return q;}
 static JsonObject scope(Object...p)throws Exception{Map<String,Object> loads=call("get_board_loads",obj());JsonObject q=mutation("job_id",loads.get("job_id"),"expected_job_revision",loads.get("job_revision"),"expected_board_load_revision",loads.get("board_load_revision"));for(var e:obj(p).entrySet())q.add(e.getKey(),e.getValue());return q;}
 static Map<String,Object> await(Map<String,Object> op)throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(30);while(true){op=call("get_operation",obj("operation_id",op.get("operation_id")));if(!Set.of("accepted","running").contains(op.get("state"))&&!machine.isBusy())return op;if(System.nanoTime()>end)throw new AssertionError("operation timeout");Thread.sleep(5);}}
 @SuppressWarnings("unchecked")static Map<String,Object> result(Map<String,Object> op){return(Map<String,Object>)op.get("result");}
 static Map<String,Object> success(String m,JsonObject p)throws Exception{Map<String,Object> op=await(call(m,p));check("succeeded".equals(op.get("state")),m+" failed: "+G.toJson(op));return result(op);}
 static void reject(String code,String m,JsonObject p)throws Exception{try{Map<String,Object> op=await(call(m,p));check("failed".equals(op.get("state"))&&code.equals(result(op).get("code")),"Expected "+code+" actual "+G.toJson(op));}catch(Bridge.Fault e){check(code.equals(e.code),"Expected "+code+" got "+e.code);}}
 static JsonObject canonical(){Part p=config.getPart("R0603-1K");double h=p.getHeight().convertToUnits(LengthUnit.Millimeters).getValue();return obj("schemaVersion",1,"id","lineage-test","units","mm","coordinateConvention","openpnp-top-view","parts",List.of(Bridge.map("id",p.getId(),"packageId",p.getPackage().getId(),"heightMm",h)),"boards",List.of(Bridge.map("id","board","widthMm",20,"heightMm",20,"placements",List.of(Bridge.map("ref","R1","partId",p.getId(),"packageId",p.getPackage().getId(),"heightMm",h,"x",10,"y",10,"z",0,"rotation",0,"side","top","enabled",true,"type","placement")))),"panels",List.of(),"instances",List.of(Bridge.map("id","board-1","kind","board","definitionId","board","x",0,"y",0,"z",0,"rotation",0,"side","top","enabled",true)));}
 static JsonArray add(String ref){return G.toJsonTree(List.of(Bridge.map("action","add","scope","job_instance","holder_instance_id","board-1","placement_id",ref,"placement",Bridge.map("location",Bridge.map("frame","holder","units","mm","x",12,"y",12,"z",0,"rotation",0),"side","Top","type","Placement","part_id","R0603-1K","enabled",true,"error_handling","Alert","comments","","rank",0)))).getAsJsonArray();}
 static JsonArray remove(String ref){return G.toJsonTree(List.of(Bridge.map("action","remove","scope","job_instance","holder_instance_id","board-1","placement_id",ref))).getAsJsonArray();}
 static Map<String,Object> edit(JsonArray changes)throws Exception{Map<String,Object> plan=success("plan_placement_structure",scope("changes",changes));return success("apply_placement_structure",scope("plan_id",plan.get("plan_id")));}
 @SuppressWarnings("unchecked")static Map<String,Object> lineage(Map<String,Object> job){return(Map<String,Object>)job.get("job_lineage");}
 @SuppressWarnings("unchecked")static String save()throws Exception{return(String)((Map<String,Object>)success("save_job",mutation()).get("artifact")).get("artifact_id");}
 static long feeds(){long n=0;for(Feeder f:machine.getFeeders())n+=((ReferenceTrayFeeder)f).getFeedCount();return n;}
 static void setup(Path root,Path samples)throws Exception{Files.createDirectory(root.resolve("config"));Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);SimulatorMain.settleFreshFixture(root.resolve("config"));config=Configuration.get();machine=config.getMachine();Files.writeString(root.resolve("token"),UUID.randomUUID().toString()+UUID.randomUUID());bridge=new Bridge(config,root.resolve("token"),root.resolve("journal"),samples,0,true,"sustained-workload");session=(String)call("request_control_session",obj("request_id",UUID.randomUUID().toString(),"ttl_seconds",300)).get("session_id");}
 @SuppressWarnings("unchecked")public static void main(String[]args)throws Exception{Path root=Files.createTempDirectory("native-lineage-bridge-"),samples=Path.of(args[0]);int exit=0;try{
  setup(root,samples);check(!machine.isEnabled()&&feeds()==0,"fresh disabled finite fixture");
  Map<String,Object> prepared=success("prepare_job",mutation("canonical_job",canonical()));String lineage=(String)lineage(prepared).get("lineage_id");check("known".equals(lineage(prepared).get("status"))&&Boolean.TRUE.equals(lineage(prepared).get("durable_pristine")),"fresh import has durable pristine lineage");
  String original=save();Map<String,Object> plan=success("plan_placement_structure",scope("changes",add("R2")));JsonObject apply=scope("plan_id",plan.get("plan_id"));Map<String,Object> admitted=call("apply_placement_structure",apply);Map<String,Object> applied=await(admitted);check("succeeded".equals(applied.get("state")),"real structure publication succeeds: "+G.toJson(applied));check(call("apply_placement_structure",apply).get("operation_id").equals(applied.get("operation_id")),"apply request deduplicates exact operation");check(((Number)((Map<?,?>)result(applied).get("job")).get("requested")).intValue()==2,"native graph gained real placement");
  String edited=save();Map<String,Object> old=success("load_job",mutation("artifact_id",original));check(((Number)lineage((Map<String,Object>)old.get("job")).get("model_lineage_revision")).longValue()==1,"old native archive retains historical model revision");reject("LINEAGE_DOCUMENT_STALE","plan_placement_structure",scope("changes",add("R3")));
  Map<String,Object> fresh=success("load_job",mutation("artifact_id",edited));check(lineage.equals(lineage((Map<String,Object>)fresh.get("job")).get("lineage_id")),"signed reload preserves same durable lineage");
  edit(remove("R2"));reject("STRUCTURE_ID_REUSED","plan_placement_structure",scope("changes",add("R2")));check(feeds()==0,"model-only publication did not feed");
  Map<String,Object> loads=call("get_board_loads",obj());Map<?,?> location=(Map<?,?>)((List<?>)loads.get("roots")).get(0);
  success("register_board_load",mutation("job_id",loads.get("job_id"),"root_instance_id","board-1","action","replace","side","top","expected_load_id",location.get("load_id"),"expected_board_load_revision",loads.get("board_load_revision")));
  String beforeRun=save();success("set_machine_enabled",mutation("enabled",true));success("home_machine",mutation());check(Boolean.TRUE.equals(success("validate_job",mutation()).get("valid")),"actual native job validates after explicit replacement");
  String job=(String)call("get_board_loads",obj()).get("job_id");JsonObject step=mutation("job_id",job);Map<String,Object> op=await(call("step_job",step));check("paused".equals(op.get("state"))&&((Number)op.get("native_steps_started")).longValue()==1,"first actual next call paused");check(op.get("job_id").equals(job)&&op.get("job_revision").equals(call("get_board_loads",obj()).get("job_revision"))&&((Map<?,?>)op.get("job_lineage")).get("lineage_id").equals(lineage),"initial operation carries exact durable job lineage binding");check(feeds()==0,"admission consumed authority before any feed");
  await(call("abort_job",mutation("operation_id",op.get("operation_id"))));success("set_machine_enabled",mutation("enabled",false));reject("LINEAGE_EXECUTED","plan_placement_structure",scope("changes",add("R9")));
  Map<String,Object> restored=success("load_job",mutation("artifact_id",beforeRun));check(Boolean.TRUE.equals(lineage((Map<String,Object>)restored.get("job")).get("processor_admitted")),"older pre-run document cannot erase later processor admission");reject("LINEAGE_EXECUTED","plan_placement_structure",scope("changes",add("R9")));
  bridge.close();bridge=null;bridge=new Bridge(config,root.resolve("token"),root.resolve("journal"),samples,0,true,"sustained-workload");session=(String)call("request_control_session",obj("request_id",UUID.randomUUID().toString(),"ttl_seconds",300)).get("session_id");
  Map<String,Object> replayed=success("load_job",mutation("artifact_id",beforeRun));check(Boolean.TRUE.equals(lineage((Map<String,Object>)replayed.get("job")).get("processor_admitted")),"complete journal replay preserves admitted lineage across a fresh Bridge");reject("LINEAGE_EXECUTED","plan_placement_structure",scope("changes",add("R10")));check(feeds()==0,"recovery and stale archive cause no feed");
  System.out.println(G.toJson(Bridge.map("passed",true,"assertions",checks,"native_next_calls",1,"native_feeds",feeds(),"physical_qualification",false)));
 }catch(Throwable e){e.printStackTrace();exit=1;}finally{if(bridge!=null)bridge.close();if(machine!=null)machine.close();}System.exit(exit);}
}
