/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.math.BigDecimal;
import org.openpnp.model.*;
import org.openpnp.spi.*;
import org.openpnp.machine.reference.camera.*;
import org.openpnp.machine.reference.camera.AbstractSettlingCamera.SettleMethod;
import org.w3c.dom.*;

/** Actual default head+machine camera models, native persistence and typed restart snapshot restore. */
public final class NativeCameraSettlingTest {
    static final Gson GSON=new Gson();static int checks;static final List<String> groups=new ArrayList<>();static Configuration config;static Path root;
    interface Action{void run()throws Exception;}
    static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    static void reject(String code,Action action)throws Exception{try{action.run();throw new AssertionError("Expected "+code);}catch(Bridge.Fault fault){check(code.equals(fault.code),"Expected "+code+", got "+fault.code+": "+fault.getMessage());}}
    static JsonObject obj(Object...values){return GSON.toJsonTree(Bridge.map(values)).getAsJsonObject();}
    static JsonArray rows(JsonObject...values){JsonArray rows=new JsonArray();for(JsonObject value:values)rows.add(value);return rows;}
    static ReferenceCamera top()throws Exception{return (ReferenceCamera)config.getMachine().getDefaultHead().getDefaultCamera();}
    static ReferenceCamera bottom(){return (ReferenceCamera)config.getMachine().getCameras().get(0);}
    static JsonObject dynamic(ReferenceCamera camera,String method){return obj("type",NativeCameraSettling.TYPE,"camera_id",camera.getId(),"method",method,"timeout_ms",80,"debounce",2,"threshold_percent",0.5,"full_color",false);}
    static JsonObject fixed(ReferenceCamera camera,int ms){return obj("type","set_camera_settling","camera_id",camera.getId(),"settle_time_ms",ms);}
    static void apply(JsonObject...values)throws Exception{NativeSettings.stage(config,rows(values)).apply();}
    static JsonObject view(ReferenceCamera camera){return GSON.toJsonTree(NativeCameraSettling.describe(camera)).getAsJsonObject();}
    static void reload()throws Exception{config.save();config.getMachine().close();Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();}
    public static void main(String[]args)throws Exception {
        root=Files.createTempDirectory("openpnp-camera-settling-");Path home=root.resolve("config");Configuration.initialize(home.toFile());Configuration.get().load();SimulatorMain.accelerateFixture(Configuration.get());SimulatorMain.settleFreshFixture(home);config=Configuration.get();int exit=0;
        try{strict();roundtrip();snapshots();omissions();fixedInactiveOmission();snapshotCapacity();portable();check(!config.getMachine().isEnabled()&&!config.getMachine().isHomed(),"model/restore/export tests never enable or home");for(Feeder f:config.getMachine().getFeeders())if(f instanceof org.openpnp.machine.reference.feeder.ReferenceStripFeeder)check(((org.openpnp.machine.reference.feeder.ReferenceStripFeeder)f).getFeedCount()==0,"model tests never consume native material");System.out.println("OPENPNP_CAMERA_SETTLING_SETTINGS_RESULT "+GSON.toJson(Bridge.map("checks",checks,"groups",groups,"upstream_commit",Bridge.UPSTREAM,"native_camera_classes",Arrays.asList(top().getClass().getName(),bottom().getClass().getName()),"native_model_save_load",true,"native_camera_capture",false,"hardware_qualified",false)));
        }catch(Throwable failure){failure.printStackTrace();exit=1;}finally{config.getMachine().close();}System.exit(exit);
    }
    static void strict()throws Exception {
        check(NativeSettings.types().contains(NativeCameraSettling.TYPE),"native capability includes additive dynamic type");check(top().getClass()==ImageCamera.class&&bottom().getClass()==SimulatedUpCamera.class,"actual default mounted/down and machine/up cameras");
        String id=top().getId();top().setId("Camera:top+");apply(dynamic(top(),"Mean"));check(top().getSettleMethod()==SettleMethod.Mean,"native identifier syntax includes colon and plus");top().setId(id);
        double speed=config.getMachine().getSpeed();JsonObject before=view(top()),bad=dynamic(bottom(),"Motion");reject("UNSUPPORTED_CAMERA_SETTLING",()->NativeSettings.stage(config,rows(obj("type","set_machine_speed","speed",0.4),dynamic(top(),"Maximum"),bad)));check(config.getMachine().getSpeed()==speed&&before.equals(view(top())),"bad late camera row leaves speed and preceding camera untouched");
        for(String key:Arrays.asList("script","source_uri","class","settle_gaussian_blur")){JsonObject extra=dynamic(top(),"Mean");extra.addProperty(key,"untrusted");reject("UNKNOWN_FIELD",()->NativeSettings.stage(config,rows(extra)));}
        for(String field:Arrays.asList("timeout_ms","debounce")){JsonObject fraction=dynamic(top(),"Mean");fraction.addProperty(field,new BigDecimal(field.equals("timeout_ms")?"20.00000000000000000001":"2.00000000000000000001"));reject("INVALID_ARGUMENT",()->NativeSettings.stage(config,rows(fraction)));}
        for(double n:new double[]{0,101,Double.NaN,Double.POSITIVE_INFINITY}){JsonObject nonfinite=dynamic(top(),"Mean");nonfinite.addProperty("threshold_percent",n);reject("OUT_OF_RANGE",()->NativeSettings.stage(config,rows(nonfinite)));}
        ImageCamera subclass=new ImageCamera(){};subclass.setId("subclass");config.getMachine().addCamera(subclass);reject("UNSUPPORTED_NATIVE_CLASS",()->NativeSettings.stage(config,rows(dynamic(subclass,"Mean"))));config.getMachine().removeCamera(subclass);
        top().setSettleMaskCircle(0.5);reject("UNSUPPORTED_CAMERA_PROCESSING",()->NativeSettings.stage(config,rows(dynamic(top(),"Mean"))));check(top().getSettleMaskCircle()==0.5,"processing refusal preserves native value");top().setSettleMaskCircle(0);
        top().setSettleGaussianBlur(3);reject("UNSUPPORTED_CAMERA_PROCESSING",()->NativeSettings.stage(config,rows(dynamic(top(),"Mean"))));top().setSettleGaussianBlur(0);
        top().setSettleDiagnostics(true);reject("UNSUPPORTED_CAMERA_PROCESSING",()->NativeSettings.stage(config,rows(dynamic(top(),"Mean"))));top().setSettleDiagnostics(false);
        ImageCamera camera=(ImageCamera)top();int[] callbacks={0};camera.startCalibration((found,goal,complete)->callbacks[0]++);reject("CAMERA_CALIBRATION_ACTIVE",()->NativeSettings.stage(config,rows(dynamic(camera,"Mean"))));reject("CAMERA_CALIBRATION_ACTIVE",()->NativeCameraSettling.admitCapture(camera,"settled"));reject("CAMERA_CALIBRATION_ACTIVE",()->NativeCameraSettling.admitCapture(camera,"raw"));check(camera.isCalibrating()&&callbacks[0]==0,"admission leaves the separate native calibration active and unsampled");camera.cancelCalibration();
        camera.setViewWidth(Integer.MAX_VALUE);reject("CAMERA_FRAME_LIMIT",()->NativeSettings.stage(config,rows(dynamic(camera,"Mean"))));reject("CAMERA_FRAME_LIMIT",()->NativeCameraSettling.admitCapture(camera,"raw"));camera.setViewWidth(640);
        camera.setScaleWidth(2049);camera.setScaleHeight(480);reject("CAMERA_FRAME_LIMIT",()->NativeSettings.stage(config,rows(dynamic(camera,"Mean"))));reject("CAMERA_FRAME_LIMIT",()->NativeCameraSettling.admitCapture(camera,"raw"));camera.setScaleWidth(0);camera.setScaleHeight(0);
        camera.setViewWidth(2048);camera.setViewHeight(2048);camera.setRotation(45);reject("CAMERA_FRAME_LIMIT",()->NativeSettings.stage(config,rows(dynamic(camera,"Mean"))));camera.setRotation(0);camera.setViewWidth(640);camera.setViewHeight(480);
        camera.getAdvancedCalibration().setEnabled(true);reject("UNSUPPORTED_CAMERA_TRANSFORMS",()->NativeSettings.stage(config,rows(dynamic(camera,"Mean"))));reject("UNSUPPORTED_CAMERA_TRANSFORMS",()->NativeCameraSettling.admitCapture(camera,"raw"));camera.getAdvancedCalibration().setEnabled(false);
        JsonObject change=dynamic(top(),"Square");NativeSettings.Patch patch=NativeSettings.stage(config,rows(change));change.addProperty("method","Motion");patch.apply();check(top().getSettleMethod()==SettleMethod.Square,"immutable staged settings ignore later caller JSON changes");reject("PATCH_ALREADY_APPLIED",patch::apply);
        check(!((Boolean)patch.metadata().get(0).get("camera_geometric_calibration_changed")),"setting effects do not invalidate geometric model");check("not-assessed".equals(patch.metadata().get(0).get("physical_calibration_validity")),"settings cannot qualify calibration");groups.add("default camera identities, exact schema/integer/model boundaries, whole-patch rejection and unchanged calibration/geometry semantics");
    }
    static void roundtrip()throws Exception {for(String method:NativeCameraSettling.METHODS){Location topPose=top().getHeadOffsets(),upp=top().getUnitsPerPixelPrimary();boolean valid=top().getAdvancedCalibration().isValid();JsonObject b=dynamic(bottom(),method);b.addProperty("timeout_ms",125);b.addProperty("debounce",5);b.addProperty("threshold_percent",0.125);b.addProperty("full_color",true);apply(fixed(top(),321),fixed(bottom(),654),dynamic(top(),method),b);JsonObject expectedTop=view(top()),expectedBottom=view(bottom());check(top().getHeadOffsets().equals(topPose)&&top().getUnitsPerPixelPrimary().equals(upp)&&top().getAdvancedCalibration().isValid()==valid,"dynamic edits preserve native geometry and calibration model status");reload();check(expectedTop.equals(view(top()))&&expectedBottom.equals(view(bottom())),"native XML roundtrip all five fields and inactive dwell "+method);check(top().getHeadOffsets().equals(topPose)&&top().getUnitsPerPixelPrimary().equals(upp),"native saved camera geometry retained "+method);}groups.add("all four dynamic methods on native head and machine cameras survive actual XML save/load with fixed dwell and geometry");}
    static void snapshots()throws Exception {apply(fixed(top(),123),fixed(bottom(),234),dynamic(top(),"Maximum"),dynamic(bottom(),"Euclidean"));JsonObject topBefore=view(top()),bottomBefore=view(bottom());NativeConfigurationSnapshots.Snapshot snap=NativeConfigurationSnapshots.capture(config);JsonObject document=GSON.toJsonTree(snap.document).getAsJsonObject();JsonArray changes=document.getAsJsonArray("typed_changes");int dynamicCount=0;Map<String,Integer> seenFixed=new HashMap<>();for(int i=0;i<changes.size();i++){JsonObject row=changes.get(i).getAsJsonObject();if(!row.has("camera_id"))continue;String type=row.get("type").getAsString(),id=row.get("camera_id").getAsString();if(type.equals("set_camera_settling"))seenFixed.put(id,i);if(type.equals(NativeCameraSettling.TYPE)){dynamicCount++;check(seenFixed.containsKey(id)&&seenFixed.get(id)<i,"snapshot fixed-dwell row precedes dynamic method restoration");}}check(dynamicCount==2,"snapshot includes mounted and machine dynamic camera settings");
        NativeConfigurationSnapshots.Snapshot decoded=NativeConfigurationSnapshots.decode(document);document.getAsJsonArray("typed_changes").get(0).getAsJsonObject().addProperty("unexpected","caller mutation");apply(fixed(top(),900),fixed(bottom(),901));NativeConfigurationSnapshots.Restore restore=NativeConfigurationSnapshots.prepareRestore(config,decoded);check(top().getSettleMethod()==SettleMethod.FixedTime,"restore planning is passive");restore.apply();check(topBefore.equals(view(top()))&&bottomBefore.equals(view(bottom())),"restart-decoded typed restore faithfully restores all active fields and inactive dwell");
        JsonObject forged=GSON.toJsonTree(snap.document).getAsJsonObject();for(JsonElement row:forged.getAsJsonArray("typed_changes"))if(NativeCameraSettling.TYPE.equals(row.getAsJsonObject().get("type").getAsString()))row.getAsJsonObject().addProperty("source_uri","https://invalid.example");NativeConfigurationSnapshots.Snapshot bad=NativeConfigurationSnapshots.decode(forged);apply(fixed(top(),777));JsonObject preserved=view(top());reject("UNKNOWN_FIELD",()->NativeConfigurationSnapshots.prepareRestore(config,bad));check(preserved.equals(view(top())),"late invalid dynamic restore changes no earlier camera/speed field");NativeConfigurationSnapshots.prepareRestore(config,decoded).apply();reload();check(topBefore.equals(view(top()))&&bottomBefore.equals(view(bottom())),"restored dynamic settings also persist natively");groups.add("typed snapshot encode/decode restore including fixed/dynamic order, copied documents, strict late-row rejection and persisted restored values");}
    static void omissions()throws Exception {top().setSettleMethod(SettleMethod.Motion);JsonObject before=view(top());NativeConfigurationSnapshots.Snapshot motion=NativeConfigurationSnapshots.capture(config);JsonArray changes=(JsonArray)motion.document.get("typed_changes");boolean omitted=false;for(JsonElement row:changes)if(row.getAsJsonObject().has("camera_id")&&row.getAsJsonObject().get("camera_id").getAsString().equals(top().getId()))check(!row.getAsJsonObject().get("type").getAsString().contains("settling"),"unsupported Motion has no fixed/dynamic settling restore row");for(Object row:(List<?>)motion.document.get("omissions"))if(((Map<?,?>)row).get("target_id").equals(top().getId())&&((Map<?,?>)row).get("type").equals(NativeCameraSettling.TYPE))omitted=true;check(omitted,"unsupported Motion omission reason retained");NativeConfigurationSnapshots.prepareRestore(config,motion).apply();check(before.equals(view(top())),"snapshot with Motion omission never silently resets camera method");
        top().setSettleMethod(SettleMethod.Mean);top().setSettleGradients(true);NativeConfigurationSnapshots.Snapshot processing=NativeConfigurationSnapshots.capture(config);for(JsonElement row:(JsonArray)processing.document.get("typed_changes"))if(row.getAsJsonObject().has("camera_id")&&row.getAsJsonObject().get("camera_id").getAsString().equals(top().getId()))check(!row.getAsJsonObject().get("type").getAsString().contains("settling"),"nondefault preprocessing never emits a fixed fallback row");top().setSettleGradients(false);groups.add("Motion and unsupported processing produce truthful omissions without changing native method or resetting to fixed dwell");}
    static void fixedInactiveOmission()throws Exception {apply(dynamic(top(),"Mean"),fixed(top(),123));NativeConfigurationSnapshots.Snapshot snapshot=NativeConfigurationSnapshots.capture(config);boolean omission=false;for(Object raw:(List<?>)snapshot.document.get("omissions")){Map<?,?> row=(Map<?,?>)raw;if("INACTIVE_CAMERA_PARAMETERS_NOT_RESTORED".equals(row.get("code"))&&top().getId().equals(row.get("target_id"))){String message=(String)row.get("message");for(String field:Arrays.asList("settle_timeout_ms","settle_debounce","settle_threshold_percent","settle_full_color"))check(message.contains(field),"FixedTime omission identifies "+field);omission=true;}}check(omission,"FixedTime snapshot declares inactive dynamic fields readback-only");JsonObject changed=dynamic(top(),"Square");changed.addProperty("timeout_ms",250);changed.addProperty("debounce",4);changed.addProperty("threshold_percent",2);changed.addProperty("full_color",true);apply(changed,fixed(top(),999));NativeConfigurationSnapshots.prepareRestore(config,snapshot).apply();check(top().getSettleMethod()==SettleMethod.FixedTime&&top().getSettleTimeMs()==123,"FixedTime active method/dwell restores");check(top().getSettleTimeoutMs()==250&&top().getSettleDebounce()==4&&top().getSettleThreshold()==2&&top().isSettleFullColor(),"explicitly omitted inactive values remain current without transient dynamic restoration");groups.add("FixedTime snapshots explicitly omit four inactive dynamic parameters while restoring active method/dwell");}
    static void snapshotCapacity()throws Exception {apply(dynamic(top(),"Mean"));JsonObject before=view(top());JsonArray nearlyFull=new JsonArray();for(int i=0;i<9999;i++)nearlyFull.add(obj("type","set_machine_speed","speed",1));List<Map<String,Object>> omissions=new ArrayList<>();JsonObject cameraView=new JsonParser().parse(before.toString()).getAsJsonObject();cameraView.addProperty("camera_id",top().getId());reject("SNAPSHOT_CAPACITY",()->NativeConfigurationSnapshots.captureCameraSettling(config,nearlyFull,omissions,cameraView));check(omissions.isEmpty(),"capacity is not converted into unsupported dynamic omission after fixed row");check(before.equals(view(top())),"capacity abort has no native setter effects");groups.add("9999-row boundary aborts complete snapshot instead of publishing fixed fallback when dynamic append exceeds capacity");}
    static void portable()throws Exception {apply(fixed(top(),0),fixed(bottom(),0));Path archive=root.resolve("fixed.zip");NativePortableConfiguration.export(config,archive);Map<String,byte[]> entries=NativePortableConfiguration.unzip(Files.readAllBytes(archive));for(String method:Arrays.asList("Mean","Motion")){Map<String,byte[]> modified=new TreeMap<>(entries);Document xml=NativePortableConfiguration.xml(modified.get("config/machine.xml"));((Element)xml.getElementsByTagName("camera").item(0)).setAttribute("settle-method",method);modified.put("config/machine.xml",NativePortableConfiguration.encode(xml));byte[] bytes=NativePortableConfigurationTest.rehash(modified);Path input=root.resolve(method+".zip"),destination=root.resolve("adopt-"+method);Files.write(input,bytes);reject("PORTABLE_PROFILE_LIMIT",()->NativePortableConfiguration.prepare(input,NativePortableConfiguration.sha(bytes),destination));check(!Files.exists(destination),"nonfixed archive refused before destination reservation "+method);}
        apply(dynamic(top(),"Mean"));JsonObject before=view(top());Path denied=root.resolve("dynamic-export.zip");reject("PORTABLE_PROFILE_LIMIT",()->NativePortableConfiguration.export(config,denied));check(!Files.exists(denied)&&before.equals(view(top())),"dynamic export refuses without archive publication or source resetting");apply(fixed(top(),0),fixed(bottom(),0));check(!config.getMachine().isEnabled(),"portable attempts leave simulator disabled");groups.add("fixed portable export still works; nonfixed export/adoption refuse while preserving source and destination absence");}
}
