/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import com.google.gson.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.BooleanSupplier;
import org.openpnp.model.*;
import org.openpnp.spi.*;
import org.openpnp.spi.base.*;

/** Public Bridge + actual native ownership gate and processor, using a declared non-Swing
 * local adapter. Observations are synthetic test inputs, never physical measurements.
 * The callback is obtained only through GuiOwnership.presentLoadedBoardInspection(). */
public final class NativeBoardInspectionBridgeTest {
    static final Gson JSON=new Gson();static final List<String> checks=Collections.synchronizedList(new ArrayList<>());
    static Configuration config;static Bridge bridge;static LocalAdapter local;static String session;static Path state;
    static void check(boolean condition,String label){if(!condition)throw new AssertionError(label);checks.add(label);}
    static JsonObject object(Object... fields){return JSON.toJsonTree(Bridge.map(fields)).getAsJsonObject();}
    static Map<String,Object> map(Object value){return (Map<String,Object>)value;}
    static Map<String,Object> plain(JsonObject value){return NativeJournalJson.parseObject(value.toString());}
    static Map<String,Object> call(String name,JsonObject arguments)throws Exception{return map(bridge.call("openpnp_"+name,arguments));}
    static Map<String,Object> read(String name,Object... values)throws Exception{return call(name,object(values));}
    static JsonObject command(Object... values)throws Exception {JsonObject p=object("session_id",session,"request_id",UUID.randomUUID().toString(),"expected_config_revision",read("get_status").get("config_revision"));for(Map.Entry<String,JsonElement> e:object(values).entrySet())p.add(e.getKey(),e.getValue());return p;}
    static Map<String,Object> result(Map<String,Object> operation){return map(operation.get("result"));}
    static Map<String,Object> await(Map<String,Object> operation,String expected)throws Exception {long until=System.nanoTime()+TimeUnit.SECONDS.toNanos(60);while(System.nanoTime()<until){operation=read("get_operation","operation_id",operation.get("operation_id"));String status=(String)operation.get("state");if(Set.of("succeeded","failed","aborted","outcome_unknown").contains(status)&&!config.getMachine().isBusy()){if(!expected.equals(status))throw new AssertionError("Operation terminal state expected "+expected+": "+JSON.toJson(operation));check(true,"Public "+operation.get("method")+" reached "+expected);return operation;}Thread.sleep(10);}throw new AssertionError("Operation did not complete: "+JSON.toJson(operation));}
    static Map<String,Object> run(String name,JsonObject p)throws Exception{return await(call(name,p),"succeeded");}
    static Map<String,Object> task(String id)throws Exception{return read("get_board_inspection","task_id",id);}
    static Map<String,Object> awaitTask(String id,String target)throws Exception {long until=System.nanoTime()+TimeUnit.SECONDS.toNanos(15);Map<String,Object> view=null;while(System.nanoTime()<until){view=task(id);if(target.equals(view.get("state")))return view;Thread.sleep(10);}throw new AssertionError("Task did not reach "+target+": "+JSON.toJson(view));}
    static final class Presentation {final Map<String,Object> task;final GuiOwnership.InspectionSubmission callback;Presentation(Map<String,Object> task,GuiOwnership.InspectionSubmission callback){this.task=task;this.callback=callback;}}
    /** Actual native guard. This is an adapter integration test, not Swing or desktop qualification. */
    static final class LocalAdapter implements GuiOwnership {
        final AbstractMachine machine=(AbstractMachine)config.getMachine();final ExternalExecutionControl gate=machine.getExternalExecutionControl();final Object token;
        final BlockingQueue<Presentation> presentations=new LinkedBlockingQueue<>();final List<String> dismissals=Collections.synchronizedList(new ArrayList<>());volatile Job job;volatile boolean granted=true;String displayedTask;
        LocalAdapter()throws Exception{token=gate.claim("inspection75 native adapter fixture");}
        public void checkAttachment(Configuration c,Machine m)throws Exception{if(c!=config||m!=machine)throw new Bridge.Fault("GUI_ATTACHMENT_CHANGED","Fixture attachment changed");Bridge.verifyNativeSimulatorClasses(m);}
        public void requireNativeOwnership()throws Exception{if(!gate.owns(token))throw new Bridge.Fault("LOCAL_GRANT_REQUIRED","Native fixture gate is not owned");}
        public void requireRemoteGrant()throws Exception{requireNativeOwnership();if(!granted)throw new Bridge.Fault("OWNERSHIP_REVOKED","Local fixture grant revoked");}
        public <T>T invokeNative(Callable<T> action)throws Exception{return gate.withOwner(token,action);}
        public <T>Future<T> submitNative(Callable<T> action,boolean ignoreEnabled)throws Exception{return gate.withOwner(token,()->machine.submit(action,null,ignoreEnabled));}
        public void publishJob(Job value)throws Exception{check(machine.isTask(Thread.currentThread()),"Public Bridge publishes the actual job on the native executor");job=value;}
        public Map<String,Object> snapshot(){return Bridge.map("validation_only",true,"local_grant",granted,"native_ownership_held",gate.owns(token),"swing_qualification",false);}
        public boolean supportsLoadedBoardInspection(){return true;}
        public synchronized void presentLoadedBoardInspection(Map<String,Object> task,InspectionSubmission callback){if(displayedTask!=null)throw new IllegalStateException("Prior local inspection view was not dismissed");displayedTask=(String)task.get("task_id");presentations.add(new Presentation(task,callback));}
        public synchronized void dismissLoadedBoardInspection(String id,String reason){if(id.equals(displayedTask))displayedTask=null;dismissals.add(id+":"+reason);}
        void release()throws Exception{gate.release(token);}
    }
    static JsonObject bound(String loaded)throws Exception {Map<String,Object> status=read("get_status");return command("job_id",status.get("job_id"),"expected_job_revision",status.get("job_revision"),"expected_board_load_revision",status.get("board_load_revision"),"loaded_board_id",loaded);}
    static String selectedBoard()throws Exception {List<?> roots=(List<?>)read("get_board_loads").get("roots");for(Object raw:roots)for(Object board:(List<?>)map(raw).get("boards"))if(Boolean.TRUE.equals(map(board).get("enabled")))return (String)map(board).get("loaded_board_id");throw new AssertionError("No enabled loaded board");}
    static Presentation request(String loaded)throws Exception {
        JsonObject args=bound(loaded);Map<String,Object> operation=run("request_board_inspection",args);Map<String,Object> again=call("request_board_inspection",args);check(operation.get("operation_id").equals(again.get("operation_id")),"Public request replay returns the same durable operation");
        Presentation shown=local.presentations.poll(15,TimeUnit.SECONDS);check(shown!=null,"Local callback is delivered through the actual GuiOwnership presentation seam");String id=(String)shown.task.get("task_id");
        Map<String,Object> view=task(id);check(view.get("request_operation_id").equals(operation.get("operation_id")),"Presented task binds the exact successful public request operation");check(Boolean.TRUE.equals(view.get("task_active")),"Fresh task is active only in its owning bridge");
        check(countEvents("inspection_task_pending",id)==1,"One durable task record despite repeated public request");return shown;
    }
    static Map<String,Object> observations(Presentation shown,boolean mixed){Map<String,Object> snapshot=map(shown.task.get("snapshot"));List<Object> rows=new ArrayList<>();int index=0;
        for(Object raw:(List<?>)snapshot.get("required_placements")){Map<String,Object> required=map(raw);Map<String,Object> row=Bridge.map("holder_instance_id",required.get("holder_instance_id"),"placement_id",required.get("placement_id"));
            if(mixed&&index++<2)row.putAll(Bridge.map("presence",index==1?"missing":"unknown","polarity","unknown"));
            else row.putAll(Bridge.map("presence","present","polarity","not_applicable","dx_mm",0.03,"dy_mm",0.04,"rotation_deg",1,"xy_uncertainty_mm",0.01,"rotation_uncertainty_deg",0.2));rows.add(row);}
        return Bridge.map("operator_label","Native adapter test operator","operator_note","Synthetic local test observations after actual OpenPnP simulator execution; no instrument or physical inspection.","tolerances",Bridge.map("xy_mm",0.1,"rotation_deg",2),"records",rows,"artifact_refs",new ArrayList<>());
    }
    static Map<String,Object> submit(Presentation shown,Map<String,Object> observations)throws Exception {
        CompletionStage<Map<String,Object>> result=shown.callback.submit(observations,()->true);check(result!=null,"Local callback returns an asynchronous completion");result.toCompletableFuture().get(30,TimeUnit.SECONDS);return awaitTask((String)shown.task.get("task_id"),"receipt-recorded");
    }
    interface Action {void run()throws Exception;}
    static void refused(Action action,String label)throws Exception {boolean rejected=false;try{action.run();}catch(Bridge.Fault expected){rejected=true;}catch(ExecutionException expected){check(expected.getCause()!=null,"Asynchronous local refusal exposes a cause");rejected=true;}check(rejected,label);}
    static long feedCount(){long count=0;for(Feeder feeder:config.getMachine().getFeeders())if(feeder instanceof org.openpnp.machine.reference.feeder.ReferenceTrayFeeder)count+=((org.openpnp.machine.reference.feeder.ReferenceTrayFeeder)feeder).getFeedCount();return count;}
    static List<Map<String,Object>> events()throws Exception {List<Map<String,Object>> rows=new ArrayList<>();for(String line:Files.readAllLines(state.resolve("journal/operations.jsonl")))rows.add(NativeJournalJson.parseObject(line));return rows;}
    static long countEvents(String type,String task)throws Exception {long count=0;for(Map<String,Object> row:events())if(type.equals(row.get("type"))&&task.equals(map(row.get("payload")).get("task_id")))count++;return count;}
    static long nativeEvents()throws Exception {long count=0;for(Map<String,Object> row:events())if(Set.of("native_action_intent","native_action_outcome","native_step_intent","native_step_outcome","native_placement_checkpoint").contains(row.get("type")))count++;return count;}
    static String sha(byte[] bytes)throws Exception {StringBuilder out=new StringBuilder();for(byte b:MessageDigest.getInstance("SHA-256").digest(bytes))out.append(String.format("%02x",b));return out.toString();}
    static Map<String,Object> artifact(Map<String,Object> receipt)throws Exception {Map<String,Object> descriptor=map(receipt.get("artifact")),fetched=read("get_artifact","artifact_id",descriptor.get("artifact_id"));byte[] bytes=Base64.getDecoder().decode((String)fetched.get("base64"));check(sha(bytes).equals(descriptor.get("sha256"))&&bytes.length==((Number)descriptor.get("size")).intValue(),"Read-only artifact UUID returns exact receipt bytes/hash/size");check("application/json".equals(fetched.get("mime_type")),"Inspection receipt is a retained JSON artifact");return NativeJournalJson.parseObject(new String(bytes,StandardCharsets.UTF_8));}
    public static void main(String[] args)throws Exception {
        if(args.length==3){child(args[0],Path.of(args[1]),Path.of(args[2]));return;}if(args.length!=1)throw new IllegalArgumentException("Expected pinned native sample root");
        Path root=Files.createTempDirectory("openpnp-inspection-bridge-");List<Object> phases=new ArrayList<>();
        for(String phase:List.of("exercise","reopen","unknown","unknown-reopen")){Path phaseRoot=phase.startsWith("unknown")?root.resolve("unknown-state"):root;Files.createDirectories(phaseRoot);Path home=Files.createDirectory(phaseRoot.resolve(phase+"-home")),log=phaseRoot.resolve(phase+".log");List<String> command=new ArrayList<>(List.of(Path.of(System.getProperty("java.home"),"bin/java").toString(),"-Xmx1g","-XX:+ExitOnOutOfMemoryError","-Djava.awt.headless=true","-Djava.util.prefs.PreferencesFactory=org.openpnp.codex.IsolatedPreferencesFactory","-Duser.home="+home,"-Djava.io.tmpdir="+home,"--add-opens=java.base/java.lang=ALL-UNNAMED","--add-opens=java.desktop/java.awt=ALL-UNNAMED","--add-opens=java.desktop/java.awt.color=ALL-UNNAMED","-cp",System.getProperty("java.class.path"),NativeBoardInspectionBridgeTest.class.getName(),phase,phaseRoot.toString(),Path.of(args[0]).toAbsolutePath().toString()));
            Process process=new ProcessBuilder(command).redirectErrorStream(true).redirectOutput(log.toFile()).start();if(!process.waitFor(110,TimeUnit.SECONDS)){process.destroyForcibly();process.waitFor(10,TimeUnit.SECONDS);throw new AssertionError("Inspection bridge phase timeout "+phase);}if(process.exitValue()!=0)throw new AssertionError("Inspection bridge phase failed "+phase+"\n"+Files.readString(log));phases.add(Bridge.map("phase",phase,"pid",process.pid(),"exit_code",process.exitValue(),"log",log.toString(),"log_sha256",sha(Files.readAllBytes(log)),"proof",phaseRoot.resolve(phase+"-proof.json").toString()));}
        System.out.println("OPENPNP_NATIVE_BOARD_INSPECTION_BRIDGE_RESULT "+JSON.toJson(Bridge.map("passed",true,"phases",phases,"native_jvm_phases",4,"actual_simulator_placements",64,"synthetic_local_observations",true,"gui_adapter","native-guarded non-Swing test adapter","swing_qualification",false,"physical_qualification",false,"root",root.toString())));
    }
    static void child(String phase,Path root,Path samples)throws Exception {
        state=root;Path expectedHome=root.resolve(phase+"-home");check(Path.of(System.getProperty("user.home")).equals(expectedHome)&&Path.of(System.getProperty("java.io.tmpdir")).equals(expectedHome),"Fresh JVM home and temp directory are owned by this phase");
        Path configRoot=root.resolve("config");Files.createDirectories(configRoot);Configuration.initialize(configRoot.toFile());config=Configuration.get();config.load();if(phase.equals("exercise")||phase.equals("unknown")){SimulatorMain.accelerateFixture(config);SimulatorMain.settleFreshFixture(configRoot);config=Configuration.get();Files.writeString(root.resolve("token"),UUID.randomUUID().toString()+UUID.randomUUID(),StandardOpenOption.CREATE_NEW);}
        int exit=0;Map<String,Object> proof=new LinkedHashMap<>();try{local=new LocalAdapter();bridge=new Bridge(config,root.resolve("token"),root.resolve("journal"),samples,0,true,"gui-simulator",local);if(phase.equals("exercise"))exercise(proof);else if(phase.equals("unknown"))unknown(proof);else if(phase.equals("unknown-reopen"))unknownReopen(proof);else reopen(proof);proof.put("passed",true);
            if(phase.equals("exercise")||phase.equals("unknown")){check(!config.getMachine().isEnabled()&&!config.getMachine().isBusy(),"Deliberate abrupt restart boundary is idle and disabled");proof.put("deliberate_abrupt_halt",true);writeProof(phase,root,proof);System.out.flush();System.err.flush();Runtime.getRuntime().halt(0);}
        }catch(Throwable failure){failure.printStackTrace();proof.put("passed",false);proof.put("failure",failure.toString());exit=1;}finally{if(bridge!=null)bridge.close();if(local!=null)local.release();config.getMachine().close();}
        writeProof(phase,root,proof);System.exit(exit);
    }
    static void writeProof(String phase,Path root,Map<String,Object> proof)throws Exception {proof.putAll(Bridge.map("phase",phase,"checks",checks,"assertions",checks.size(),"native_jvm_pid",ProcessHandle.current().pid(),"synthetic_local_observations",true,"native_ownership_gate",true,"swing_qualification",false,"hardware_qualified",false));Files.writeString(root.resolve(phase+"-proof.json"),JSON.toJson(proof),StandardOpenOption.CREATE_NEW);System.out.println("OPENPNP_NATIVE_BOARD_INSPECTION_PHASE "+JSON.toJson(proof));}
    static void completedSample()throws Exception {
        session=(String)read("request_control_session","request_id",UUID.randomUUID().toString(),"ttl_seconds",600).get("session_id");run("set_machine_enabled",command("enabled",true));run("home_machine",command());Map<String,Object> prepared=result(run("prepare_job",command("sample","pnp-test")));run("validate_job",command());Map<String,Object> completed=result(run("start_job",command("job_id",prepared.get("job_id"))));check(((Number)completed.get("placed")).intValue()==32,"Actual native job processor completes the stock32-placement sample");run("set_machine_enabled",command("enabled",false));
        check(local.job!=null&&"completed".equals(read("get_status").get("job_state")),"Completed actual native job is retained by the attachment");
    }
    static void exercise(Map<String,Object> proof)throws Exception {
        completedSample();Map<String,Boolean> history=new TreeMap<>(local.job.getPlacedStatusSnapshot());long feeds=feedCount(),actions=nativeEvents();String selected=selectedBoard();
        Presentation positive=request(selected);Map<String,Object> submitted=observations(positive,false),invalidForm=observations(positive,false);invalidForm.put("operator_note","");String positiveId=(String)positive.task.get("task_id");refused(()->positive.callback.submit(invalidForm,()->true).toCompletableFuture().get(10,TimeUnit.SECONDS),"Invalid local form is refused before consuming the capability");check(Boolean.TRUE.equals(task(positiveId).get("task_active"))&&countEvents("inspection_submission_intent",positiveId)==0&&positiveId.equals(local.displayedTask),"Correctable invalid form retains its local view without durable submission");Map<String,Object> positiveView=submit(positive,submitted),positiveReceipt=map(positiveView.get("receipt")),positiveResult=map(positiveReceipt.get("result"));
        check("passed".equals(positiveResult.get("outcome"))&&Boolean.TRUE.equals(positiveResult.get("complete_coverage")),"Local synthetic observations produce complete passing receipt");check(Boolean.FALSE.equals(positiveResult.get("hardware_qualified"))&&Boolean.FALSE.equals(positiveResult.get("production_authority_granted")),"Receipt grants neither physical qualification nor production authority");
        Map<String,Object> bytes=artifact(positiveReceipt);check(positiveId.equals(bytes.get("task_id"))&&positiveResult.equals(bytes.get("result")),"Retained receipt artifact binds the exact local task and observation result");long intents=countEvents("inspection_submission_intent",positiveId),receipts=countEvents("inspection_receipt",positiveId);refused(()->positive.callback.submit(submitted,()->true).toCompletableFuture().get(10,TimeUnit.SECONDS),"Consumed local callback refuses duplicate submission");check(intents==1&&receipts==1&&countEvents("inspection_submission_intent",positiveId)==1&&countEvents("inspection_receipt",positiveId)==1,"Duplicate local callback cannot append another submission or receipt");
        Presentation mixed=request(selected);Map<String,Object> mixedView=submit(mixed,observations(mixed,true)),mixedResult=map(map(mixedView.get("receipt")).get("result"));check("failed".equals(mixedResult.get("outcome"))&&((Number)mixedResult.get("failed_count")).intValue()==1&&((Number)mixedResult.get("uncertain_count")).intValue()==1,"Missing and unknown component outcomes remain distinct in durable receipt");artifact(map(mixedView.get("receipt")));
        Presentation artifactFailure=request(selected);String artifactFailureId=(String)artifactFailure.task.get("task_id");Map<String,Object> missingArtifact=observations(artifactFailure,false);((List<Object>)missingArtifact.get("artifact_refs")).add(Bridge.map("artifact_id",UUID.randomUUID().toString(),"sha256","a".repeat(64),"kind","image"));refused(()->artifactFailure.callback.submit(missingArtifact,()->true).toCompletableFuture().get(15,TimeUnit.SECONDS),"Missing owned artifact fails after local capability admission");Map<String,Object> failedArtifactView=awaitTask(artifactFailureId,"closed");check(!failedArtifactView.containsKey("receipt")&&countEvents("inspection_submission_intent",artifactFailureId)==0&&local.displayedTask==null,"Consumed pre-intent failure closes and dismisses the terminal local view");
        Presentation cancelled=request(selected);String cancelledId=(String)cancelled.task.get("task_id");cancelled.callback.cancel("cancelled");Map<String,Object> closed=awaitTask(cancelledId,"closed");check("cancelled".equals(map(closed.get("closure")).get("reason"))&&!closed.containsKey("receipt")&&countEvents("inspection_submission_intent",cancelledId)==0,"Local cancellation closes pending task without submission intent or receipt");
        Presentation stale=request(selected);String staleId=(String)stale.task.get("task_id");local.submitNative(()->{BoardLocation orphan=new BoardLocation();orphan.setId("inspection-stale-orphan");local.job.storePlacedStatus(orphan,"explicit-false",false);return null;},true).get(10,TimeUnit.SECONDS);refused(()->stale.callback.submit(observations(stale,false),()->true).toCompletableFuture().get(15,TimeUnit.SECONDS),"Direct native opaque-history drift refuses the captured local submission");Map<String,Object> staleView=task(staleId);check(!staleView.containsKey("receipt"),"Stale native scope cannot retain a passing receipt");
        check(feedCount()==feeds&&nativeEvents()==actions&&!config.getMachine().isEnabled(),"All inspection requests/submissions/cancellations add no native feed, job steps or machine enable");Map<String,Boolean> now=new TreeMap<>(local.job.getPlacedStatusSnapshot());now.remove("inspection-stale-orphan"+PlacementsHolderLocation.ID_DELIMITTER+"explicit-false");check(history.equals(now),"All original native placed history survives inspection outcomes unchanged");
        // A final pending callback is deliberately left unused. Fresh JVM replay must expose
        // historical data only and must never reconstruct or present the local capability.
        Presentation pending=request(selected);String pendingId=(String)pending.task.get("task_id");config.save();Map<String,Object> retained=Bridge.map("positive_task_id",positiveId,"pending_task_id",pendingId,"receipt_artifact",positiveReceipt.get("artifact"),"bridge_instance_id",read("get_status").get("bridge_instance_id"),"feeds",feedCount(),"native_events",nativeEvents());Files.writeString(state.resolve("retained.json"),JSON.toJson(retained),StandardOpenOption.CREATE_NEW);proof.putAll(retained);proof.put("actual_native_placements",32);
    }
    static void unknown(Map<String,Object> proof)throws Exception {
        completedSample();config.save();long feeds=feedCount(),actions=nativeEvents();Map<String,Boolean> history=new TreeMap<>(local.job.getPlacedStatusSnapshot());Presentation shown=request(selectedBoard());String id=(String)shown.task.get("task_id");java.util.concurrent.atomic.AtomicBoolean sawDurableIntent=new java.util.concurrent.atomic.AtomicBoolean();
        BooleanSupplier localAuthority=()->{try{boolean durable=countEvents("inspection_submission_intent",id)>0;if(durable)sawDurableIntent.set(true);return !durable;}catch(Exception failure){throw new IllegalStateException(failure);}};
        refused(()->shown.callback.submit(observations(shown,false),localAuthority).toCompletableFuture().get(30,TimeUnit.SECONDS),"Local authority revocation after durable intent refuses receipt publication");Map<String,Object> view=task(id);Map<String,Object> operation=map(view.get("submission_operation"));check(sawDurableIntent.get()&&"outcome_unknown".equals(operation.get("state")),"Actual durable-intent boundary retains an unknown local publication outcome");check(countEvents("inspection_submission_intent",id)==1&&countEvents("inspection_receipt",id)==0&&!view.containsKey("receipt"),"Unresolved task keeps one intent and no fabricated receipt");check(history.equals(local.job.getPlacedStatusSnapshot())&&feeds==feedCount()&&actions==nativeEvents(),"Unknown local publication changes neither native placed history nor machine actions");Map<String,Object> retained=Bridge.map("unknown_task_id",id,"bridge_instance_id",read("get_status").get("bridge_instance_id"),"submission_operation_id",operation.get("operation_id"));Files.writeString(state.resolve("unknown-retained.json"),JSON.toJson(retained),StandardOpenOption.CREATE_NEW);proof.putAll(retained);proof.put("unknown_task",view);proof.put("actual_native_placements",32);
    }
    static void unknownReopen(Map<String,Object> proof)throws Exception {
        Map<String,Object> retained=NativeJournalJson.parseObject(Files.readString(state.resolve("unknown-retained.json")));byte[] before=Files.readAllBytes(state.resolve("journal/operations.jsonl"));Map<String,Object> view=task((String)retained.get("unknown_task_id"));check(Boolean.TRUE.equals(view.get("historical"))&&Boolean.FALSE.equals(view.get("task_active"))&&"outcome_unknown".equals(view.get("state")),"Fresh JVM preserves the unresolved inspection intent as outcome_unknown without capability restoration");check(!view.containsKey("receipt")&&countEvents("inspection_submission_intent",(String)retained.get("unknown_task_id"))==1&&countEvents("inspection_receipt",(String)retained.get("unknown_task_id"))==0,"Restart neither retries nor fabricates an unresolved inspection receipt");check(local.presentations.poll(300,TimeUnit.MILLISECONDS)==null&&Arrays.equals(before,Files.readAllBytes(state.resolve("journal/operations.jsonl"))),"Unknown historical readback creates no local view or journal record");check(!config.getMachine().isEnabled()&&!config.getMachine().isHomed(),"Unknown historical replay never enables or homes the fresh native simulator");proof.put("unknown_task",view);proof.put("journal_sha256",sha(before));
    }
    static void reopen(Map<String,Object> proof)throws Exception {
        Map<String,Object> retained=NativeJournalJson.parseObject(Files.readString(state.resolve("retained.json")));check(!retained.get("bridge_instance_id").equals(read("get_status").get("bridge_instance_id")),"Fresh bridge JVM has a distinct native bridge instance");byte[] journal=Files.readAllBytes(state.resolve("journal/operations.jsonl"));long feeds=feedCount();Map<String,Object> historical=task((String)retained.get("positive_task_id"));check(Boolean.TRUE.equals(historical.get("historical"))&&Boolean.FALSE.equals(historical.get("task_active"))&&"receipt-recorded".equals(historical.get("state")),"Original receipt is historical read-only data after fresh JVM restart");artifact(map(historical.get("receipt")));Map<String,Object> pending=task((String)retained.get("pending_task_id"));check(Boolean.TRUE.equals(pending.get("historical"))&&Boolean.FALSE.equals(pending.get("task_active"))&&"pending".equals(pending.get("recorded_state"))&&!pending.containsKey("receipt"),"Unused pre-restart task never regains a local submission capability");check(local.presentations.poll(300,TimeUnit.MILLISECONDS)==null,"Historical inspection tasks never reopen the local form");check(Arrays.equals(journal,Files.readAllBytes(state.resolve("journal/operations.jsonl"))),"Historical task/artifact reads append no journal records");check(feeds==feedCount()&&!config.getMachine().isEnabled()&&!config.getMachine().isHomed(),"Fresh restart/readback executes no job, feed, enable or home");proof.putAll(Bridge.map("positive_task",historical,"pending_task",pending,"journal_sha256",sha(journal),"read_only_native_feed_count",feeds));
    }
}
