/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.io.*;
import java.nio.*;
import java.nio.channels.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.spi.*;

/** Actual pinned native Job/tray/load setters plus real forced files. Action and sensing hooks
 * are explicitly synthetic contract fixtures; this test does not initialize or run a PnP job. */
public final class NativeMaterialReplacementProgressTest {
 static final Gson JSON=new GsonBuilder().serializeNulls().create();static Configuration config;static ReferenceTrayFeeder tray;static List<ReferenceTrayFeeder> trays=new ArrayList<>();static Path root;static int checks,refusals;
 interface Work{void run()throws Exception;}static void yes(boolean x,String why){checks++;if(!x)throw new AssertionError(why);}static void no(String why,Work w)throws Exception{try{w.run();throw new AssertionError("Accepted "+why);}catch(IOException|Bridge.Fault|NativeJobLineage.Fault expected){checks++;refusals++;}}
 static Map<String,Object> m(Object...v){return NativeFaultedJobReplacement.map(v);}static Map<String,Object> o(Object p)throws IOException{return NativeFaultedJobReplacement.object(p);}static String id(){return UUID.randomUUID().toString();}
 static <T>T task(Callable<T> c)throws Exception{try{return config.getMachine().submit(c,null,true).get(30,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Error)throw(Error)e.getCause();throw(Exception)e.getCause();}}
 static final class Env implements AutoCloseable {
  final String jobId=id(),opId=id(),requestId=id();final NativeMaterialLoads material;final NativeBoardLoads boards;final NativeJobLineage lineage;final NativeFaultedJobReplacement replacement;final Path file;final FileChannel channel;
  final List<Map<String,Object>> events=new ArrayList<>();Job oldJob,freshJob;Map<String,Object> operation,oldMaterial,oldBoard,oldLineage,ordinaryIntentProgress;NativeFaultedJobReplacement.Capture capture;NativeFaultedJobReplacement.Permit permit;NativeSensingReconciliation.Capture faultCapture;NativeSensingReconciliation coordinator;NativeVacuumJournal vacuum;final Object localOwner=new Object();String failType,interruptAfterCommitOldId,recoveryOp;boolean failAfterForce;int setters;long seq;
  Env(String name,boolean replay)throws Exception {
   file=root.resolve(name+".jsonl");channel=FileChannel.open(file,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE);lineage=new NativeJobLineage(this::append);boards=new NativeBoardLoads(this::append);material=new NativeMaterialLoads(config,this::append);replacement=new NativeFaultedJobReplacement(config,material,boards,lineage,this::append);
   if(!replay)task(()->{for(ReferenceTrayFeeder t:trays){t.setFeedCount(2);material.register(t.getId(),t.getPart().getId(),(String)NativeMaterialLoads.describe(t).get("geometry_sha256"),"bind-existing",null,material.revision());}oldJob=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(tray.getPart()));lineage.createFresh(jobId,"canonical-simulator");boards.bindJob(oldJob,jobId,true);BoardLocation board=oldJob.getBoardLocations().get(0);oldJob.storePlacedStatus(board,"R1",true);boards.checkpoint(oldJob);
     operation=m("operation_id",opId,"job_id",jobId,"job_revision",boards.jobRevision(),"board_load_revision",boards.revision(),"request_id",requestId,"request_digest","a".repeat(64),"config_revision","cfg-2","method","openpnp_start_job","job_lineage",lineage.admissionFacts(jobId),"state","accepted");append("operation",operation);
     Map<String,Object> loadScope=boards.ledgerScope(oldJob);NativeActionLedger ledger=new NativeActionLedger(this::append,opId,jobId,"cfg-2",(String)loadScope.get("scope_id"),oldJob,loadScope).withMaterialObserver(material);
     try(NativeActionLedger.StepScope step=ledger.openStep(1)){config.getScripting().on("Feeder.BeforeFeed",m("nozzle",config.getMachine().getDefaultHead().getDefaultNozzle(),"feeder",tray,"part",tray.getPart()));tray.setFeedCount(3);}catch(NativeActionLedger.UnresolvedActionFence expected){}
     operation.put("state","outcome_unknown");append("operation",operation);oldMaterial=material.captureReplacementState();oldBoard=boards.captureReplacementState(jobId);oldLineage=lineage.captureReplacementState(jobId);capture=replacement.capture(oldJob,jobId,opId);freshJob=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(tray.getPart()));return null;});
  }
  void append(String type,Map<String,Object> p)throws Exception {
   Runnable mat=material==null?()->{}:material.prepareEvent(type,p);Runnable lin=lineage==null||type.startsWith("job_lineage_")?()->{}:lineage.prepareObservation(type,p);
   if(type.equals(failType)&&!failAfterForce)throw new IOException("injected before force: "+type);Map<String,Object> event=NativeFaultedJobReplacement.frozen(m("sequence",++seq,"type",type,"payload",p));byte[] bytes=(JSON.toJson(event)+"\n").getBytes(java.nio.charset.StandardCharsets.UTF_8);ByteBuffer buffer=ByteBuffer.wrap(bytes);while(buffer.hasRemaining())channel.write(buffer);channel.force(true);events.add(event);if(type.equals(failType)&&failAfterForce)throw new IOException("injected uncertain return after actual force: "+type);mat.run();lin.run();if(boards!=null)boards.observeNativeEvent(type,p);if(replacement!=null)replacement.observe(type,p);if(type.equals("material_load_intent")&&p.get("previous_load_id")!=null&&recoveryOp!=null)ordinaryIntentProgress=material.replacementProgress(recoveryOp,faultCapture.digest,ids(this));if(type.equals("material_replacement_intent")&&Objects.equals(interruptAfterCommitOldId,p.get("old_load_id")))throw new IOException("injected interruption after actual material intent force and commit, before native setter");
  }
  void admit()throws Exception {
   vacuum=new NativeVacuumJournal();coordinator=new NativeSensingReconciliation(vacuum,(op,instance,replay)->false,replacement::verified);
   String instance=NativeSensingReconciliationTest.INSTANCE,source=NativeSensingReconciliationTest.SOURCE,machine=NativeSensingReconciliationTest.MACHINE;
   Map<String,Object> jobContext=m("job_id",jobId,"job_revision",oldBoard.get("job_revision"),"board_load_revision",oldBoard.get("revision"),"material_setup_revision",oldMaterial.get("revision"),"lineage_id",oldLineage.get("lineage_id"),"lineage_revision",oldLineage.get("lineage_revision"));
   Map<String,Object> context=NativeSensingReconciliationTest.context();context.put("operation_id",opId);context.put("scope","job");context.put("job_context",jobContext);
   Map<String,Object> event=NativeSensingReconciliationTest.event("read.before",100,null,context,source);vacuum.prepare("vacuum_observation_intent",event,instance).run();Map<String,Object> scope=NativeSensingReconciliationTest.scope(instance,source);scope.put("job_context",jobContext);scope.put("dependencies",capture.dependencies());faultCapture=vacuum.captureFaultSet(scope);
   String task=id(),requestOperation=id(),recovery=id();recoveryOp=recovery;Map<String,Object> taskRecord=coordinator.taskRecord(task,requestOperation,id(),faultCapture,"replace-faulted-job-attempt",1,"2030-01-01T00:00:00Z");coordinator.prepare("sensing_reconciliation_task",taskRecord,instance).run();coordinator.prepare("sensing_reconciliation_intent",coordinator.intentRecord(task,recovery,id(),"2026-09-14T00:00:00Z",1,"synthetic-local-test"),instance).run();NativeSensingReconciliation.Permit recoveryPermit=coordinator.issuePermit(task,recovery,faultCapture.digest,localOwner);
   permit=replacement.begin(capture,freshJob,coordinator,recoveryPermit,localOwner);
  }
  void replay(List<Map<String,Object>> source)throws Exception {for(Map<String,Object> event:source){String t=(String)event.get("type");Map<String,Object> p=o(event.get("payload"));material.recoverEvent(t,p);boards.recoverEvent(t,p);boards.observeNativeEvent(t,p);lineage.observe(t,p);replacement.observe(t,p);if(t.startsWith("faulted_job_replacement_"))replacement.recover(t,p);}material.finishRecovery();boards.finishRecovery();}
  public void close()throws Exception{channel.close();}
 }
 static List<String> ids(Env e)throws Exception{List<String> out=new ArrayList<>((Collection<String>)e.capture.dependencies().get("material_load_ids"));String primary=(String)o(e.oldMaterial.get("active")).get(tray.getId());out.remove(primary);out.add(0,primary);return out;}
 static Map<String,Object> progress(Env e)throws Exception{return e.material.replacementProgress(e.recoveryOp,e.faultCapture.digest,ids(e));}
 static Map<String,Object> row(Map<String,Object> progress,String oldId)throws Exception{for(Object raw:(List<?>)progress.get("rows")){Map<String,Object> r=o(raw);if(oldId.equals(r.get("old_load_id")))return r;}throw new AssertionError("Missing row "+oldId);}
 static ReferenceTrayFeeder feeder(Env e,String oldId)throws Exception{return (ReferenceTrayFeeder)config.getMachine().getFeeder((String)o(o(e.oldMaterial.get("loads")).get(oldId)).get("feeder_id"));}
 static void phases(Env e,Map<String,String> expected)throws Exception{Map<String,Object> p=progress(e);yes(((List<?>)p.get("rows")).size()==expected.size(),"complete per-original tray union");for(Map.Entry<String,String> item:expected.entrySet())yes(item.getValue().equals(row(p,item.getKey()).get("phase")),"exact phase "+item.getValue());}
 static void parents(Env e,Map<String,Object> p)throws Exception{
  for(Object raw:(List<?>)p.get("rows")){Map<String,Object> r=o(raw);for(String field:List.of("parent_intent","parent_outcome")){if(r.get(field)==null)continue;Map<String,Object> parent=o(r.get(field));boolean found=false;for(Map<String,Object> event:e.events){if(parent.get("type").equals(event.get("type"))&&parent.get("receipt_id").equals(o(event.get("payload")).get("receipt_id"))){yes(NativeFaultedJobReplacement.same(parent.get("payload"),event.get("payload")),"exact forced parent payload");yes(parent.get("payload_sha256").equals(NativeFaultedJobReplacement.digest(o(event.get("payload")))),"exact forced parent canonical digest");found=true;break;}}yes(found,"parent exists in actual forced stream");}}
 }
 @SuppressWarnings("unchecked") static Map<String,Map<String,Object>> internal(NativeMaterialLoads material,String name)throws Exception{java.lang.reflect.Field f=NativeMaterialLoads.class.getDeclaredField(name);f.setAccessible(true);return(Map<String,Map<String,Object>>)f.get(material);}
 static void integrity(Env e)throws Exception{
  Map<String,Map<String,Object>> feeds=internal(e.material,"feeds");String action=feeds.keySet().iterator().next();Map<String,Object> original=feeds.get(action),changed=NativeFaultedJobReplacement.mutable(original);changed.put("state","fabricated-state");feeds.put(action,changed);try{no("changed old feed fact",()->progress(e));}finally{feeds.put(action,original);}
  Map<String,Map<String,Object>> loads=internal(e.material,"loads");String old=ids(e).get(0);Map<String,Object> originalLoad=loads.get(old),changedLoad=NativeFaultedJobReplacement.mutable(originalLoad);changedLoad.put("current_index",1);loads.put(old,changedLoad);try{no("changed old load record",()->progress(e));}finally{loads.put(old,originalLoad);}
  Map<String,Map<String,Object>> receipts=internal(e.material,"replacementReceipts");Map<String,Object> existing=receipts.values().iterator().next(),duplicate=NativeFaultedJobReplacement.mutable(existing);String duplicateId=id();duplicate.put("receipt_id",duplicateId);receipts.put(duplicateId,duplicate);try{no("repeated same-original replacement receipt",()->progress(e));}finally{receipts.remove(duplicateId);}
 }
 static void nativeReads(Env e)throws Exception{
  byte[] before=Files.readAllBytes(e.file);Map<String,Object> retained=progress(e);yes(retained.get("native_observations")==null,"generic phase read does not traverse native model");yes(Boolean.FALSE.equals(retained.get("execution_authority_restored")),"generic read grants no authority");
  no("native observation outside native owner",()->e.material.observeReplacementProgress(e.recoveryOp,e.faultCapture.digest,ids(e)));
  Map<String,Object> observed=task(()->e.material.observeReplacementProgress(e.recoveryOp,e.faultCapture.digest,ids(e)));yes(((List<?>)o(observed.get("native_observations")).get("loads")).size()==trays.size(),"native observations cover full requested union");yes(NativeFaultedJobReplacement.same(retained.get("rows"),observed.get("rows")),"native observations cannot rewrite retained phases");
  yes(Arrays.equals(before,Files.readAllBytes(e.file)),"read-only capture and observation append no journal bytes");
  try{o(((List<?>)retained.get("rows")).get(0)).put("phase","completed");throw new AssertionError("Mutable readback");}catch(UnsupportedOperationException expected){yes(true,"deeply immutable phase readback");}
 }
 static void consumeReplacement(Env e,String oldId)throws Exception{
  task(()->{ReferenceTrayFeeder f=feeder(e,oldId);Nozzle nozzle=config.getMachine().getDefaultHead().getDefaultNozzle();String operationId=id();Map<String,Object> op=NativeFaultedJobReplacement.mutable(e.operation);op.put("operation_id",operationId);op.put("request_id",id());op.put("state","accepted");e.append("operation",op);
   Map<String,Object> scope=e.boards.ledgerScope(e.oldJob);NativeActionLedger ledger=new NativeActionLedger(e::append,operationId,e.jobId,"cfg-2",(String)scope.get("scope_id"),e.oldJob,scope).withMaterialObserver(e.material);
   int before=f.getFeedCount();try(NativeActionLedger.StepScope step=ledger.openStep(1)){config.getScripting().on("Feeder.BeforeFeed",m("nozzle",nozzle,"feeder",f,"part",f.getPart()));f.feed(nozzle);config.getScripting().on("Feeder.AfterFeed",m("nozzle",nozzle,"feeder",f,"part",f.getPart()));}
   yes(f.getFeedCount()==before+1,"actual native ReferenceTrayFeeder.feed advanced once");op.put("state","succeeded");e.append("operation",op);e.material.requireReady();return null;});
 }
 public static void main(String[]args)throws Exception{
  root=Paths.get(args[1]);Files.createDirectories(root);int exit=0;Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);
  for(Feeder f:config.getMachine().getFeeders())if(f.getPart()==config.getPart("R0603-1K"))tray=(ReferenceTrayFeeder)f;tray.setTrayCountX(3);tray.setTrayCountY(2);trays.add(tray);
  task(()->{for(int i=2;i<=3;i++){Part p=new Part("PHASE-PART-"+i);p.setPackage(tray.getPart().getPackage());p.setHeight(tray.getPart().getHeight());config.addPart(p);ReferenceTrayFeeder f=new ReferenceTrayFeeder();f.setPart(p);f.setEnabled(true);f.setTrayCountX(3);f.setTrayCountY(2);f.setLocation(tray.getLocation());f.setOffsets(tray.getOffsets());config.getMachine().addFeeder(f);trays.add(f);}return null;});
  try{
   try(Env e=new Env("mixed",false)){
    task(()->{e.admit();return null;});List<String> union=ids(e);String first=union.get(0),second=union.get(1),third=union.get(2);
    phases(e,Map.of(first,"untouched",second,"untouched",third,"untouched"));nativeReads(e);
    int firstBefore=feeder(e,first).getFeedCount();task(()->e.material.replaceRetiredLoad(e.permit,first));yes(firstBefore>0&&feeder(e,first).getFeedCount()==0,"actual completed replacement reset native tray");
    int secondBefore=feeder(e,second).getFeedCount();e.interruptAfterCommitOldId=second;task(()->{no("real post-intent interruption before setter",()->e.material.replaceRetiredLoad(e.permit,second));return null;});
    yes(feeder(e,second).getFeedCount()==secondBefore,"post-intent interruption did not run native setter");phases(e,Map.of(first,"completed",second,"pending",third,"untouched"));Map<String,Object> mixed=progress(e);parents(e,mixed);nativeReads(e);
    yes(Boolean.FALSE.equals(o(row(mixed,second).get("binding_status")).get("retained_binding_present")),"pending intent revoked prior binding");yes(row(mixed,second).get("parent_outcome")==null,"pending has no fabricated outcome");
    Map<String,Boolean> oldHistory=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());yes(NativeFaultedJobReplacement.same(o(e.oldMaterial.get("loads")).get(first),row(mixed,first).get("old_load")),"completed old load unchanged");yes(NativeFaultedJobReplacement.same(o(e.oldMaterial.get("loads")).get(second),row(mixed,second).get("old_load")),"pending old load unchanged");
    task(()->{no("pending still blocks material readiness",e.material::requireReady);no("same original replacement cannot be repeated",()->e.material.replaceRetiredLoad(e.permit,second));return null;});
    no("omitted completed parent",()->e.material.replacementProgress(e.recoveryOp,e.faultCapture.digest,List.of(second,third)));no("omitted pending parent",()->e.material.replacementProgress(e.recoveryOp,e.faultCapture.digest,List.of(first,third)));no("duplicate original",()->e.material.replacementProgress(e.recoveryOp,e.faultCapture.digest,List.of(first,first,second,third)));no("foreign operation",()->e.material.replacementProgress(id(),e.faultCapture.digest,union));no("foreign fault digest",()->e.material.replacementProgress(e.recoveryOp,"f".repeat(64),union));no("unknown original load",()->e.material.replacementProgress(e.recoveryOp,e.faultCapture.digest,List.of(first,second,third,id())));integrity(e);
    task(()->{ReferenceTrayFeeder f=feeder(e,first);Location original=f.getOffsets();f.setOffsets(original.derive(original.getX()+1,null,null,null));try{Map<String,Object> read=e.material.observeReplacementProgress(e.recoveryOp,e.faultCapture.digest,union);Map<String,Object> n=null;for(Object raw:(List<?>)o(read.get("native_observations")).get("loads"))if(first.equals(o(raw).get("old_load_id")))n=o(raw);yes(n!=null&&Boolean.FALSE.equals(n.get("geometry_matches_original")),"explicit native observation reports real geometry drift separately");yes(Boolean.FALSE.equals(n.get("retained_binding_matches_current_objects")),"geometry drift grants no binding authority");yes("completed".equals(row(read,first).get("phase")),"native geometry drift cannot change forced completion phase");}finally{f.setOffsets(original);}return null;});
    try(Env replay=new Env("mixed-replay",true)){int[] indices=trays.stream().mapToInt(ReferenceTrayFeeder::getFeedCount).toArray();replay.replay(e.events);Map<String,Object> p=replay.material.replacementProgress(e.recoveryOp,e.faultCapture.digest,union);yes("completed".equals(row(p,first).get("phase"))&&"pending".equals(row(p,second).get("phase"))&&"untouched".equals(row(p,third).get("phase")),"replay retains exact mixed phases");for(Object r:(List<?>)p.get("rows"))yes(Boolean.FALSE.equals(o(o(r).get("binding_status")).get("retained_binding_present")),"replay read does not restore binding");task(()->{replay.material.observeReplacementProgress(e.recoveryOp,e.faultCapture.digest,union);no("native reobservation still cannot restore replay authority",replay.material::requireReady);return null;});yes(Arrays.equals(indices,trays.stream().mapToInt(ReferenceTrayFeeder::getFeedCount).toArray())&&Files.size(replay.file)==0,"replay and explicit observation perform no setter or append");}
    yes(oldHistory.equals(e.oldJob.getPlacedStatusSnapshot()),"old job placed history unchanged");Files.writeString(root.resolve("mixed-progress.json"),JSON.toJson(mixed));e.permit.close();
   }
   try(Env e=new Env("complete",false)){
    task(()->{e.admit();for(String oldId:ids(e))e.material.replaceRetiredLoad(e.permit,oldId);e.material.requireReady();return null;});Map<String,Object> p=progress(e);yes(((Number)o(p.get("counts")).get("completed")).intValue()==3,"all three actual native tray replacements completed");parents(e,p);nativeReads(e);integrity(e);
    task(()->{String oldId=ids(e).get(0);ReferenceTrayFeeder f=feeder(e,oldId);f.setFeedCount(1);try{Map<String,Object> read=e.material.observeReplacementProgress(e.recoveryOp,e.faultCapture.digest,ids(e));Map<String,Object> n=null;for(Object raw:(List<?>)o(read.get("native_observations")).get("loads"))if(oldId.equals(o(raw).get("old_load_id")))n=o(raw);yes(n!=null&&Boolean.FALSE.equals(n.get("index_matches_current_load")),"explicit native index mismatch remains separate from receipt");no("native index drift still blocks ready",e.material::requireReady);}finally{f.setFeedCount(0);}return null;});
    String consumedOld=ids(e).get(0);Map<String,Object> beforeUse=row(p,consumedOld);String replacementId=(String)o(beforeUse.get("new_load")).get("load_id");consumeReplacement(e,consumedOld);
    Map<String,Object> afterUse=progress(e),used=row(afterUse,consumedOld);yes("completed".equals(used.get("phase")),"consumption preserves historical completed replacement phase");yes(((Number)o(used.get("replacement_load_current")).get("current_index")).intValue()==1,"replacement load retains actual native consumption");yes(Boolean.FALSE.equals(used.get("current_matches_replacement_receipt"))&&Boolean.TRUE.equals(used.get("replacement_still_active")),"used active replacement differs from historic zero-index receipt");yes(NativeFaultedJobReplacement.same(beforeUse.get("parent_intent"),used.get("parent_intent"))&&NativeFaultedJobReplacement.same(beforeUse.get("parent_outcome"),used.get("parent_outcome")),"actual feed preserves exact historic parent records and hashes");nativeReads(e);
    task(()->{ReferenceTrayFeeder f=feeder(e,consumedOld);e.material.register(f.getId(),f.getPart().getId(),(String)NativeMaterialLoads.describe(f).get("geometry_sha256"),"replace-full-tray",replacementId,e.material.revision());e.material.requireReady();return null;});
    yes(e.ordinaryIntentProgress!=null&&o(e.ordinaryIntentProgress.get("pending_ordinary_changes")).size()==1,"ordinary pending change is reported without blocking historic phase read");yes("completed".equals(row(e.ordinaryIntentProgress,consumedOld).get("phase")),"ordinary change intent preserves completed replacement phase");
    Map<String,Object> afterChange=progress(e),changed=row(afterChange,consumedOld);yes("completed".equals(changed.get("phase"))&&Boolean.FALSE.equals(changed.get("replacement_still_active")),"subsequent full tray replacement preserves historical completion with inactive old replacement");yes(!replacementId.equals(changed.get("current_load_id"))&&((Number)o(changed.get("current_load")).get("current_index")).intValue()==0,"current load is distinct new full tray");yes(((Number)o(changed.get("replacement_load_current")).get("current_index")).intValue()==1,"historical replacement load still records its actual consumption");yes(NativeFaultedJobReplacement.same(beforeUse.get("old_feed_facts"),changed.get("old_feed_facts"))&&NativeFaultedJobReplacement.same(beforeUse.get("old_load"),changed.get("old_load"))&&NativeFaultedJobReplacement.same(beforeUse.get("parent_outcome"),changed.get("parent_outcome")),"ordinary replacement preserves original unknown feed, load and completed parent");parents(e,afterChange);nativeReads(e);Files.writeString(root.resolve("history-after-use.json"),JSON.toJson(m("after_feed",afterUse,"during_ordinary_change",e.ordinaryIntentProgress,"after_full_tray_change",afterChange)));
    try(Env replay=new Env("complete-replay",true)){replay.replay(e.events);Map<String,Object> read=task(()->replay.material.observeReplacementProgress(e.recoveryOp,e.faultCapture.digest,ids(e)));yes(((Number)o(read.get("counts")).get("completed")).intValue()==3,"historical completed phase remains available");task(()->{no("completed replay observation grants no authority",replay.material::requireReady);return null;});yes(Files.size(replay.file)==0,"completed replay observation appended nothing");}
    Files.writeString(root.resolve("complete-progress.json"),JSON.toJson(p));e.permit.close();
   }
   Files.writeString(root.resolve("proof.json"),JSON.toJson(m("passed",true,"checks",checks,"refusals",refusals,"actual_completed_tray_replacements",4,"actual_post_intent_interruptions",1,"native_jobs_initialized",0,"native_feeds",1,"ordinary_full_tray_replacements",1,"native_placements",0,"scope","Actual native models, original replaceRetiredLoad setter/save paths and forced files; synthetic action/sensing permit contract fixtures; reflective corruption negatives only")));
   System.out.println("NATIVE_MATERIAL_REPLACEMENT_PROGRESS_PASS "+checks+" checks "+refusals+" refusals; actual completed native tray replacements 4; post-intent interruption 1; native feeds 1; subsequent ordinary full tray replacements 1; native jobs/placements 0; no Bridge integration qualification");
  }catch(Throwable failure){failure.printStackTrace();exit=1;}finally{config.getMachine().close();}System.exit(exit);
 }
}
