/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.*;
import java.util.*;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.model.*;
import static org.openpnp.codex.NativeReplacementContinuationTest.*;
import org.openpnp.codex.NativeRestartSensingTaskTest.RestartFixture;
import org.openpnp.codex.NativeRestartSensingTaskTest.AdmissionEnv;

/** Actual reconstructed native graphs, local RestartPermit and forced child/root observations.
 * The initial fault, task decision and terminal authority come from explicit test fixtures. */
public final class NativeRestartLoadObservationTest {
    static int assertions,refusals;static final List<Map<String,Object>> groups=new ArrayList<>();
    interface Checked{void run()throws Exception;}
    static void check(boolean value,String why){assertions++;if(!value)throw new AssertionError(why);}
    static void reject(String why,Checked work)throws Exception{try{work.run();throw new AssertionError("Accepted: "+why);}catch(IOException|Bridge.Fault|NativeJobLineage.Fault expected){refusals++;check(true,why);}}
    static Map<String,Object> copy(Map<String,Object> row)throws Exception{return NativeFaultedJobReplacement.mutable(row);}
    static void same(Object a,Object b,String why)throws Exception{check(NativeFaultedJobReplacement.same(a,b),why);}
    static List<String> materialIds(RestartFixture f)throws Exception{List<String> ids=new ArrayList<>();for(Object id:(List<?>)f.source.capture.dependencies().get("material_load_ids"))ids.add((String)id);return ids;}
    static Map<String,Object> boardState(NativeBoardLoads boards)throws Exception{Map<String,Object> state=copy(boards.snapshot());state.remove("restart_observation_receipts");return state;}
    static int sizeField(Object owner,String name)throws Exception{Field field=owner.getClass().getDeclaredField(name);field.setAccessible(true);return ((Map<?,?>)field.get(owner)).size();}
    static Object field(Object owner,String name)throws Exception{Field field=owner.getClass().getDeclaredField(name);field.setAccessible(true);return field.get(owner);}
    static List<Map<String,Object>> exactEvents(Path path)throws Exception{List<Map<String,Object>> events=new ArrayList<>();for(String line:Files.readAllLines(path))events.add(NativeJournalJson.parseObject(line));return events;}
    static void readyRefused(RestartFixture f,NativeFaultedJobReplacement.RestartPermit permit)throws Exception{
        task(()->{reject("historical material cannot execute",f.replay.material::requireReady);reject("reconstructed old board cannot execute",()->f.replay.boards.requireReady(permit.original()));reject("detached candidate cannot execute",()->f.replay.boards.requireReady(permit.candidate().job()));return null;});
        check(sizeField(f.replay.material,"bindings")==0,"Observation creates no ordinary material binding");
        check(field(f.replay.boards,"boundNativeJob")==null&&((Set<?>)field(f.replay.boards,"confirmed")).isEmpty(),"Observation does not install a job or confirm any board");
    }
    static void schemaChecks(String name,List<Map<String,Object>> prefix,Map<String,Object> material,Map<String,Object> board)throws Exception{
        try(AdmissionEnv reducer=new AdmissionEnv(name+"-schema",prefix)){
            for(String key:List.of("phase_row_sha256","old_load_sha256","old_feed_facts_sha256","current_load_sha256","material_setup_revision","phase","current_load_id","old_load_id")){
                Map<String,Object> bad=copy(material);bad.put(key,key.endsWith("_id")?id():key.endsWith("sha256")?"e".repeat(64):"foreign");reject("material exact field "+key,()->reducer.material.prepareEvent("material_restart_observation",bad));
            }
            for(String key:List.of("execution_authority_restored","physical_inventory_verified")){Map<String,Object> bad=copy(material);bad.put(key,true);reject("material authority flag "+key,()->reducer.material.prepareEvent("material_restart_observation",bad));}
            Map<String,Object> bad=copy(material);bad.put("foreign",true);Map<String,Object> foreign=bad;reject("closed material receipt",()->reducer.material.prepareEvent("material_restart_observation",foreign));
            bad=copy(material);o(bad.get("native_observation")).put("geometry_sha256","e".repeat(64));Map<String,Object> geometry=bad;reject("material native geometry",()->reducer.material.prepareEvent("material_restart_observation",geometry));
            bad=copy(material);o(bad.get("native_observation")).put("index_matches_durable_load",!Boolean.TRUE.equals(o(material.get("native_observation")).get("index_matches_durable_load")));Map<String,Object> index=bad;reject("material native index claim",()->reducer.material.prepareEvent("material_restart_observation",index));
            for(String key:List.of("reattachment_id","replacement_attempt_id","recovery_operation_id","original_recovery_operation_id","fault_set_sha256","restart_capture_sha256","original_fault_set_sha256")){
                Map<String,Object> changed=copy(material);changed.put(key,key.endsWith("sha256")?"e".repeat(64):id());reject("root binds material authority "+key,()->reducer.replacement.prepareContinuationObservation("material_restart_observation",changed));
            }
            for(String key:List.of("board_progress_sha256","board_load_revision","execution_authority_restored","physical_load_verified")){
                Map<String,Object> changed=copy(board);changed.put(key,key.equals("board_load_revision")?"load-999":key.endsWith("sha256")?"e".repeat(64):true);reject("board exact field "+key,()->reducer.boards.recoverEvent("board_restart_observation",changed));
            }
            for(String key:List.of("phase_row_sha256","old_load_sha256","current_load_sha256","native_original_model_sha256","native_candidate_model_sha256","candidate_native_history_sha256","phase","side","current_load_id")){
                Map<String,Object> changed=copy(board);o(((List<?>)changed.get("roots")).get(0)).put(key,key.endsWith("_id")?id():key.endsWith("sha256")?"e".repeat(64):"foreign");reject("board root exact field "+key,()->reducer.boards.recoverEvent("board_restart_observation",changed));
            }
            bad=copy(board);List<Object> roots=new ArrayList<>((List<?>)bad.get("roots"));roots.add(roots.get(0));bad.put("roots",roots);Map<String,Object> duplicate=bad;reject("complete board union cannot duplicate roots",()->reducer.boards.recoverEvent("board_restart_observation",duplicate));
            bad=copy(board);o(((List<?>)bad.get("roots")).get(0)).put("foreign",true);Map<String,Object> rootShape=bad;reject("closed root observation",()->reducer.boards.recoverEvent("board_restart_observation",rootShape));
            bad=copy(board);boolean changedHistory=false;for(Object raw:(List<?>)bad.get("roots")){Map<String,Object> row=o(raw);if(!o(row.get("old_native_history")).isEmpty()){row.put("old_native_history",Map.of());changedHistory=true;break;}}check(changedHistory,"History mutation targets an actually nonempty native root");Map<String,Object> history=bad;reject("preserve complete old history",()->reducer.boards.recoverEvent("board_restart_observation",history));
            for(String key:List.of("reattachment_id","old_boards_sha256","replacement_attempt_id","restart_capture_sha256")){Map<String,Object> changed=copy(board);changed.put(key,key.endsWith("sha256")?"e".repeat(64):id());reject("root binds complete board scope "+key,()->reducer.replacement.prepareContinuationObservation("board_restart_observation",changed));}
            check(Files.size(reducer.file)==0,"All malformed read/replay checks force no bytes");
        }
    }
    static void positive(String prefix)throws Exception{
        try(RestartFixture f=new RestartFixture("loads-"+prefix,prefix)){
            f.admit();var permit=f.begin();List<String> ids=materialIds(f);Map<String,Object> beforeMaterial=f.replay.material.captureReplacementState(),beforeBoards=boardState(f.replay.boards),beforeProgress=f.replay.replacement.progress(f.attempt);Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();Map<String,Boolean> history=new TreeMap<>(permit.original().getPlacedStatusSnapshot());
            List<Map<String,Object>> replayPrefix=new ArrayList<>(f.replay.history);long bytes=Files.size(f.replay.file);readyRefused(f,permit);
            List<Map<String,Object>> materials=new ArrayList<>();for(String id:ids){Map<String,Object> receipt=task(()->f.replay.material.observeRestart(permit,id));materials.add(receipt);same(receipt,f.replay.material.restartObservationReceipt((String)receipt.get("receipt_id")),"Material exact retained observation");check(Boolean.FALSE.equals(receipt.get("execution_authority_restored"))&&Boolean.FALSE.equals(receipt.get("physical_inventory_verified")),"Native observation conveys no physical/execution authority");check(((Number)o(receipt.get("native_observation")).get("native_feed_count")).intValue()==counts.get((String)o(receipt.get("native_observation")).get("feeder_id")),"Receipt reports actual native tray counter");task(()->{permit.requireSealedMaterial(f.replay.material,id,(String)receipt.get("receipt_id"));reject("same local decision cannot re-observe material",()->f.replay.material.observeRestart(permit,id));return null;});}
            Map<String,Object> board=task(()->f.replay.boards.observeRestart(permit,permit.original(),permit.candidate().job(),f.attempt));same(board,f.replay.boards.restartObservationReceipt((String)board.get("receipt_id")),"Board exact retained observation");check(((List<?>)board.get("roots")).size()==((Map<?,?>)f.source.oldBoard.get("active")).size(),"Complete original board root union observed");
            for(Object raw:(List<?>)board.get("roots")){Map<String,Object> row=o(raw);Map<String,Boolean> subset=new TreeMap<>();for(var entry:history.entrySet())if(entry.getKey().startsWith(row.get("root_instance_id")+PlacementsHolderLocation.ID_DELIMITTER))subset.put(entry.getKey(),entry.getValue());same(subset,row.get("old_native_history"),"Exact scoped original history retained");}
            task(()->{permit.requireSealedBoards(f.replay.boards,permit.original(),permit.candidate().job(),f.attempt,(String)board.get("receipt_id"));reject("same local decision cannot repeat board union",()->f.replay.boards.observeRestart(permit,permit.original(),permit.candidate().job(),f.attempt));return null;});
            readyRefused(f,permit);same(beforeMaterial,f.replay.material.captureReplacementState(),"No load/feed fact changed");same(beforeBoards,boardState(f.replay.boards),"No board load/history/presence fact changed");same(beforeProgress,f.replay.replacement.progress(f.attempt),"Original replacement phases remain exact");same(counts,counters(),"No native tray counter setter effect");same(files,configurationFiles(),"No native configuration save");same(history,permit.original().getPlacedStatusSnapshot(),"Original reconstructed native history unchanged");check(permit.candidate().job().getPlacedStatusSnapshot().isEmpty(),"Candidate native history remains empty");
            List<Map<String,Object>> appended=f.replay.history.subList(replayPrefix.size(),f.replay.history.size());check(appended.size()==ids.size()+1&&Files.size(f.replay.file)>bytes,"Exactly one new forced receipt per tray and one full-board receipt");List<Map<String,Object>> onDisk=exactEvents(f.replay.file);same(f.replay.history.subList(f.source.events.size(),f.replay.history.size()),onDisk,"New root journal bytes match actual appended records");
            if(prefix.equals("pending-material")){check(materials.stream().anyMatch(r->"pending".equals(r.get("phase"))&&((Number)((Map<?,?>)r.get("native_observation")).get("native_feed_count")).intValue()==0),"Observed zero counter remains a pending unknown load");}
            if(prefix.equals("definition"))schemaChecks(prefix,replayPrefix,materials.get(0),board);
            try(AdmissionEnv replay=new AdmissionEnv("loads-"+prefix+"-history",new ArrayList<>(f.replay.history))){for(var row:materials)same(row,replay.material.restartObservationReceipt((String)row.get("receipt_id")),"Historical material receipt survives exact replay");same(board,replay.boards.restartObservationReceipt((String)board.get("receipt_id")),"Historical board receipt survives exact replay");check(sizeField(replay.material,"restartWitnesses")==0&&sizeField(replay.boards,"restartWitnesses")==0,"Replay creates no process-local witness");check(sizeField(replay.material,"bindings")==0&&field(replay.boards,"boundNativeJob")==null,"Replay creates no executable binding");check(Files.size(replay.file)==0,"History replay forces no bytes");task(()->{reject("replay cannot borrow live material capability",()->replay.material.observeRestart(permit,ids.get(0)));reject("replay cannot borrow live board capability",()->replay.boards.observeRestart(permit,permit.original(),permit.candidate().job(),f.attempt));return null;});}
            permit.close();task(()->{reject("closed material observation permit",()->f.replay.material.observeRestart(permit,ids.get(0)));reject("closed board observation permit",()->f.replay.boards.observeRestart(permit,permit.original(),permit.candidate().job(),f.attempt));permit.requireSealedMaterial(f.replay.material,ids.get(0),(String)materials.get(0).get("receipt_id"));permit.requireSealedBoards(f.replay.boards,permit.original(),permit.candidate().job(),f.attempt,(String)board.get("receipt_id"));return null;});readyRefused(f,permit);
            groups.add(m("name",prefix,"material_receipts",materials,"board_receipt",board,"same_process_fresh_root_replay",true,"readiness_restored",false));
        }
    }
    static void guards()throws Exception{
        try(RestartFixture f=new RestartFixture("loads-native-guards","completed")){f.admit();var permit=f.begin();String id=materialIds(f).get(0);Map<String,Object> authority=task(()->permit.authorizeMaterial(f.replay.material,id));String feederId=(String)o(o(authority.get("phase_row")).get("old_load")).get("feeder_id");ReferenceTrayFeeder feeder=(ReferenceTrayFeeder)config.getMachine().getFeeder(feederId);long bytes=Files.size(f.replay.file);
            reject("material owning executor required",()->f.replay.material.observeRestart(permit,id));reject("board owning executor required",()->f.replay.boards.observeRestart(permit,permit.original(),permit.candidate().job(),f.attempt));
            task(()->{reject("foreign old graph",()->f.replay.boards.observeRestart(permit,f.source.oldJob,permit.candidate().job(),f.attempt));reject("foreign new graph",()->f.replay.boards.observeRestart(permit,permit.original(),f.source.freshJob,f.attempt));reject("foreign attempt",()->f.replay.boards.observeRestart(permit,permit.original(),permit.candidate().job(),id()));reject("foreign material ID",()->f.replay.material.observeRestart(permit,id()));
                int index=feeder.getFeedCount();try{feeder.setFeedCount(1);reject("completed native tray cannot be consumed",()->f.replay.material.observeRestart(permit,id));}finally{feeder.setFeedCount(index);}int x=feeder.getTrayCountX();try{feeder.setTrayCountX(x+1);reject("native tray geometry drift",()->f.replay.material.observeRestart(permit,id));}finally{feeder.setTrayCountX(x);}return null;});
            check(Files.size(f.replay.file)==bytes,"Executor/identity/native drift refusals publish no observation");check(sizeField(f.replay.material,"restartWitnesses")==0&&sizeField(f.replay.boards,"restartWitnesses")==0,"Refused observations create no native witness");permit.close();groups.add(m("name","native-observation-guards","no_forced_receipts",true));
        }
        try(RestartFixture f=new RestartFixture("loads-untouched-counter-observed","definition")){f.admit();var permit=f.begin();String id=materialIds(f).get(0);Map<String,Object> a=task(()->permit.authorizeMaterial(f.replay.material,id));ReferenceTrayFeeder feeder=(ReferenceTrayFeeder)config.getMachine().getFeeder((String)o(o(a.get("phase_row")).get("old_load")).get("feeder_id"));Map<String,Object> old=f.replay.material.captureReplacementState();int before=feeder.getFeedCount();try{task(()->{feeder.setFeedCount(0);return null;});Map<String,Object> receipt=task(()->f.replay.material.observeRestart(permit,id));check("untouched".equals(receipt.get("phase"))&&Boolean.FALSE.equals(o(receipt.get("native_observation")).get("index_matches_durable_load")),"Reset counter observation does not rewrite consumed old tray identity");same(old,f.replay.material.captureReplacementState(),"Observed reset preserves old feed/index facts");readyRefused(f,permit);}finally{task(()->{feeder.setFeedCount(before);return null;});}permit.close();groups.add(m("name","untouched-native-counter-mismatch","old_outcomes_preserved",true));}
    }
    public static void main(String[] args)throws Exception{if(args.length!=1)throw new IllegalArgumentException("Expected exclusive native state directory");initialize(Path.of(args[0]));Throwable failure=null;int exit=0;try{for(String prefix:List.of("definition","pending-material","mixed-board","completed"))positive(prefix);guards();}catch(Throwable error){failure=error;exit=1;error.printStackTrace();}finally{config.getMachine().close();Map<String,Object> proof=m("passed",exit==0,"assertions",assertions,"refusals",refusals,"groups",groups,"error",failure==null?null:failure.toString(),"pid",ProcessHandle.current().pid(),"actual_native_job_initializations",0,"actual_native_placements",0,"scope","Actual native reconstructed graphs and feeder observations, fresh root and local RestartPermit, forced material/board receipts; synthetic initial faults/task decisions/terminal authority; same JVM replay only","restart_execution_qualified",false,"bridge_integration_qualified",false,"hardware_qualified",false);Files.writeString(root.resolve("proof.json"),JSON.toJson(proof)+"\n",StandardOpenOption.CREATE_NEW);System.out.println("NATIVE_RESTART_LOAD_OBSERVATION_RESULT "+JSON.toJson(proof));}System.exit(exit);}
}
