/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import com.google.gson.Gson;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Synthetic closed-record lifecycle tests using the pinned native Gson; no native machine. */
public final class NativeInspectionJournalTest {
    private static int checks,refusals;
    private static final String INSTANCE=id(1),OTHER=id(2),MACHINE=id(3),PROFILE=NativeInspectionJournal.PROFILE,HASH="a".repeat(64),SCOPE="b".repeat(64);
    private static final Gson JSON=new Gson();
    private interface Checked {void run()throws Exception;}
    private interface Change {void run(Map<String,Object> value)throws Exception;}
    private static String id(int n){return UUID.nameUUIDFromBytes(("inspection75-test-"+n).getBytes(StandardCharsets.UTF_8)).toString();}
    private static Map<String,Object> m(Object...values){Map<String,Object> p=new LinkedHashMap<>();for(int i=0;i<values.length;i+=2)p.put((String)values[i],values[i+1]);return p;}
    private static Map<String,Object> copy(Map<String,Object> p){return NativeJournalJson.copy(p);}
    @SuppressWarnings("unchecked")private static Map<String,Object> o(Map<String,Object> p,String k){return(Map<String,Object>)p.get(k);}
    @SuppressWarnings("unchecked")private static List<Object> a(Map<String,Object> p,String k){return(List<Object>)p.get(k);}
    private static void yes(boolean b,String label){checks++;if(!b)throw new AssertionError(label);}
    private static void refused(String label,Checked run)throws Exception{try{run.run();throw new AssertionError("Accepted "+label);}catch(IOException expected){checks++;refusals++;}}
    private static void commitRefused(String label,Runnable run){try{run.run();throw new AssertionError("Accepted "+label);}catch(IllegalStateException expected){checks++;refusals++;}}
    private static Map<String,Object> pending(int n){
        Map<String,Object> context=m("bridge_instance_id",INSTANCE,"machine_id",MACHINE,"job_id",id(4),"job_revision",HASH,"config_revision","cfg-5","board_load_revision","load-2","lineage_id",id(5),"lineage_revision",3,"ownership_epoch",2,"job_state","completed");
        Map<String,Object> scope=m("scope_id",HASH,"board_load_revision","load-2","job_revision",HASH,"authority","native-simulator","physical_load_verified",false,
            "boards",List.of(m("board_instance_id","P1/A","loaded_board_id",id(6),"root_instance_id","P1","side","top","enabled",true,"board_load_id",id(7))));
        Map<String,Object> snapshot=m("profile",PROFILE,"scope_fingerprint",SCOPE,"source_fingerprint",HASH,"library_fingerprint",HASH,"placed_history_fingerprint",HASH,"loaded_board_id",id(6),"board_load_id",id(7),"holder_instance_id","P1/A","root_instance_id","P1","board_side","top","context",context,"board_load_scope",scope,
            "required_count",1,"required_placements",List.of(m("holder_instance_id","P1/A","placement_id","R1","part_id","R0805-1K","location",m("x",0,"y",0,"z",0,"rotation",0,"units","mm"),"native_placed",true)),
            "coordinate_frame","holder","location_units","mm","rotation_units","degrees","limits",m("placements",200,"artifact_refs",32),"authority","local-operator-reported","simulation_only",true,"hardware_qualified",false,"production_authority_granted",false,"instrument_authenticity_verified",false);
        return m("schema_version",1,"profile",PROFILE,"task_id",id(1000+n*10),"request_operation_id",id(1001+n*10),"request_id",id(1002+n*10),"machine_id",MACHINE,"bridge_instance_id",INSTANCE,"created_at","2026-09-11T20:00:00Z","expires_at","2026-09-11T20:05:00Z","context",context,"snapshot",snapshot);
    }
    private static Map<String,Object> intent(int n){return m("task_id",pending(n).get("task_id"),"submission_operation_id",id(1003+n*10),"request_id",id(1004+n*10),"submission_sha256",HASH,"scope_fingerprint",SCOPE);}
    private static Map<String,Object> result(){
        Map<String,Object> measurements=m("dx_mm",0,"dy_mm",0,"rotation_deg",0,"xy_uncertainty_mm",0,"rotation_uncertainty_deg",0,"xy_error_mm",0,"rotation_error_deg",0,"xy_interval_mm",List.of(0,0),"rotation_interval_deg",List.of(0,0));
        return m("profile",PROFILE,"loaded_board_id",id(6),"holder_instance_id","P1/A","source_fingerprint",HASH,"scope_fingerprint",SCOPE,"operator_label","Fixture operator","operator_note","Synthetic test only.","tolerances",m("xy_mm",0.1,"rotation_deg",5),"artifact_refs",List.of(),
            "required_count",1,"observed_count",1,"complete_coverage",true,"passed_count",1,"failed_count",0,"uncertain_count",0,"outcome","passed","records",List.of(m("holder_instance_id","P1/A","placement_id","R1","presence","present","polarity","correct","measurements",measurements,"outcome","passed","failures",List.of(),"uncertainties",List.of(),"native_placed",true)),
            "authority","local-operator-reported","polarity_applicability","operator-reported","instrument_authenticity_verified",false,"artifact_bytes_verified_by_model",false,"native_placed_history_modified",false,"production_authority_granted",false,"simulation_only",true,"hardware_qualified",false);
    }
    private static Map<String,Object> receipt(int n){Map<String,Object> p=intent(n);p.put("artifact",m("artifact_id",id(1005+n*10),"mime_type","application/json","sha256",HASH,"size",400,"metadata",m("kind","loaded-board-inspection","physical_qualification",false)));p.put("result",result());return p;}
    private static NativeInspectionJournal prefix(int count)throws Exception{NativeInspectionJournal j=new NativeInspectionJournal();if(count>0)j.recover("inspection_task_pending",pending(0),INSTANCE);if(count>1)j.recover("inspection_submission_intent",intent(0),INSTANCE);return j;}
    private static void badPending(String label,Change change)throws Exception{Map<String,Object> p=copy(pending(0));change.run(p);refused(label,()->new NativeInspectionJournal().prepare("inspection_task_pending",p,INSTANCE));}
    private static void badIntent(String label,Change change)throws Exception{Map<String,Object> p=copy(intent(0));change.run(p);refused(label,()->prefix(1).prepare("inspection_submission_intent",p,INSTANCE));}
    private static void badReceipt(String label,Change change)throws Exception{Map<String,Object> p=copy(receipt(0));change.run(p);refused(label,()->prefix(2).prepare("inspection_receipt",p,INSTANCE));}
    @SuppressWarnings("unchecked")private static Map<String,Object> row(Map<String,Object> receipt){return(Map<String,Object>)a(o(receipt,"result"),"records").get(0);}
    private static void observed(Map<String,Object> p,String x,String y,String rotation,String ux,String ur,List<String> failures,List<String> uncertainties){
        Map<String,Object> r=row(p),measured=o(r,"measurements");double dx=Double.parseDouble(x),dy=Double.parseDouble(y),rot=Double.parseDouble(rotation),u=Double.parseDouble(ux),v=Double.parseDouble(ur),xy=Math.hypot(dx,dy),angle=Math.abs(Math.IEEEremainder(rot,360));
        measured.putAll(m("dx_mm",new BigDecimal(x),"dy_mm",new BigDecimal(y),"rotation_deg",new BigDecimal(rotation),"xy_uncertainty_mm",new BigDecimal(ux),"rotation_uncertainty_deg",new BigDecimal(ur),"xy_error_mm",xy,"rotation_error_deg",angle,"xy_interval_mm",List.of(Math.max(0,xy-u),xy+u),"rotation_interval_deg",List.of(Math.max(0,angle-v),Math.min(180,angle+v))));
        disposition(p,failures,uncertainties);
    }
    private static void disposition(Map<String,Object> p,List<String> failures,List<String> uncertainties){Map<String,Object> r=row(p),result=o(p,"result");String out=!failures.isEmpty()?"failed":!uncertainties.isEmpty()?"uncertain":"passed";r.putAll(m("failures",failures,"uncertainties",uncertainties,"outcome",out));result.putAll(m("outcome",out,"passed_count",out.equals("passed")?1:0,"failed_count",out.equals("failed")?1:0,"uncertain_count",out.equals("uncertain")?1:0));}
    private static void acceptedReceipt(String label,Change change)throws Exception{Map<String,Object> p=copy(receipt(0));change.run(p);NativeInspectionJournal j=prefix(2);j.recover("inspection_receipt",p,INSTANCE);yes("receipt-recorded".equals(j.get((String)p.get("task_id"),OTHER).get("state")),label);}
    public static void main(String[] args)throws Exception{
        NativeInspectionJournal j=new NativeInspectionJournal();Map<String,Object> source=pending(0);Runnable pendingCommit=j.prepare("inspection_task_pending",source,INSTANCE);
        yes(Boolean.FALSE.equals(j.get((String)source.get("task_id"),INSTANCE).get("found")),"No pending state before force/commit");source.put("profile","mutated-after-prepare");pendingCommit.run();
        Map<String,Object> live=j.get((String)pending(0).get("task_id"),INSTANCE);yes(PROFILE.equals(o(live,"pending").get("profile")),"Prepared state defensively copied");yes(Boolean.FALSE.equals(live.get("task_active")),"Reducer has no live authority");
        try{o(live,"pending").put("profile","bad");throw new AssertionError("Mutable get");}catch(UnsupportedOperationException expected){checks++;}
        commitRefused("reused post-force commit",pendingCommit);j.verifyMachineIdentity(MACHINE);checks++;refused("foreign durable machine",()->j.verifyMachineIdentity(OTHER));
        Runnable intentCommit=j.prepare("inspection_submission_intent",intent(0),INSTANCE);yes("pending".equals(j.get((String)pending(0).get("task_id"),INSTANCE).get("recorded_state")),"Failed intent append leaves prior state");intentCommit.run();
        yes("outcome_unknown".equals(j.get((String)pending(0).get("task_id"),OTHER).get("state")),"Interrupted submission historically unknown");
        Runnable receiptCommit=j.prepare("inspection_receipt",receipt(0),INSTANCE);yes(!j.get((String)pending(0).get("task_id"),INSTANCE).containsKey("receipt"),"Failed receipt append leaves incomplete intent");receiptCommit.run();
        Map<String,Object> historical=j.get((String)pending(0).get("task_id"),OTHER);yes("receipt-recorded".equals(historical.get("state"))&&Boolean.TRUE.equals(historical.get("historical"))&&!((Boolean)historical.get("task_active")),"Receipt is historical data only");
        refused("duplicate exact receipt",()->j.prepare("inspection_receipt",receipt(0),INSTANCE));refused("post-receipt closure",()->j.prepare("inspection_task_closed",m("task_id",pending(0).get("task_id"),"reason","cancelled"),INSTANCE));
        NativeInspectionJournal concurrent=new NativeInspectionJournal();Runnable c1=concurrent.prepare("inspection_task_pending",pending(0),INSTANCE),c2=concurrent.prepare("inspection_task_pending",pending(1),INSTANCE);c1.run();commitRefused("stale concurrently prepared commit",c2);yes(((Number)concurrent.snapshot(INSTANCE).get("retained_count")).intValue()==1,"Stale commit cannot replace committed history");
        NativeInspectionJournal replay=new NativeInspectionJournal();for(String t:List.of("inspection_task_pending","inspection_submission_intent","inspection_receipt")){Map<String,Object> p=t.endsWith("pending")?pending(0):t.endsWith("intent")?intent(0):receipt(0);String raw=JSON.toJson(m("type",t,"payload",p));NativeInspectionJournal.validateRawRecord(raw);replay.recover(t,NativeJournalJson.parseObject(JSON.toJson(p)),INSTANCE);}
        yes(replay.get((String)pending(0).get("task_id"),OTHER).equals(historical),"Fresh replay retains exact semantic receipt");
        NativeInspectionJournal cancelled=prefix(1);cancelled.recover("inspection_task_closed",m("task_id",pending(0).get("task_id"),"reason","cancelled"),INSTANCE);yes("closed".equals(cancelled.get((String)pending(0).get("task_id"),OTHER).get("state")),"Closed task retained");
        refused("submission after cancel",()->cancelled.prepare("inspection_submission_intent",intent(0),INSTANCE));refused("cancel while submitting",()->prefix(2).prepare("inspection_task_closed",m("task_id",pending(0).get("task_id"),"reason","cancelled"),INSTANCE));
        refused("unknown event",()->prefix(1).prepare("inspection_task_reopened",pending(0),INSTANCE));refused("missing pending",()->prefix(0).prepare("inspection_submission_intent",intent(0),INSTANCE));refused("receipt before intent",()->prefix(1).prepare("inspection_receipt",receipt(0),INSTANCE));refused("duplicate intent",()->prefix(2).prepare("inspection_submission_intent",intent(0),INSTANCE));
        refused("foreign intent envelope",()->prefix(1).prepare("inspection_submission_intent",intent(0),OTHER));refused("foreign receipt envelope",()->prefix(2).prepare("inspection_receipt",receipt(0),OTHER));refused("unsupported closure reason",()->prefix(1).prepare("inspection_task_closed",m("task_id",pending(0).get("task_id"),"reason","restart-authorized"),INSTANCE));
        badPending("unknown pending field",p->p.put("token",id(88)));badPending("missing pending field",p->p.remove("snapshot"));badPending("noncanonical UUID",p->p.put("task_id",((String)p.get("task_id")).toUpperCase(Locale.ROOT)));badPending("abbreviated UUID",p->p.put("task_id","1-1-1-1-1"));badPending("near-integer schema",p->p.put("schema_version",new BigDecimal("1.00000000000000001")));badPending("string schema",p->p.put("schema_version","1"));badPending("unknown profile",p->p.put("profile","other"));badPending("foreign pending instance",p->p.put("bridge_instance_id",OTHER));badPending("aliased identities",p->p.put("request_id",p.get("task_id")));badPending("expiry before creation",p->p.put("expires_at","2026-09-11T19:59:59Z"));badPending("expiry over limit",p->p.put("expires_at","2026-09-11T20:10:01Z"));badPending("noncanonical time",p->p.put("created_at","2026-09-11T20:00:00+00:00"));
        badPending("wrong live config shape",p->o(p,"context").put("config_revision",HASH));badPending("fractional context epoch",p->o(p,"context").put("ownership_epoch",new BigDecimal("2.00000000000000001")));badPending("foreign context machine",p->o(p,"context").put("machine_id",OTHER));badPending("context drift",p->o(p,"context").put("job_id",OTHER));badPending("required count fractional",p->o(p,"snapshot").put("required_count",new BigDecimal("1.00000000000000001")));badPending("native placement absent",p->((Map<String,Object>)a(o(p,"snapshot"),"required_placements").get(0)).put("native_placed",false));badPending("false simulation",p->o(p,"snapshot").put("simulation_only",false));badPending("hardware qualification",p->o(p,"snapshot").put("hardware_qualified",true));
        badIntent("original request reused",p->p.put("request_id",pending(0).get("request_id")));badIntent("original operation reused",p->p.put("submission_operation_id",pending(0).get("request_operation_id")));badIntent("scope drift",p->p.put("scope_fingerprint",HASH));badIntent("digest type",p->p.put("submission_sha256",7));badIntent("unknown intent key",p->p.put("token",new Object()));
        badReceipt("conflicting receipt digest",p->p.put("submission_sha256",SCOPE));badReceipt("conflicting receipt operation",p->p.put("submission_operation_id",OTHER));badReceipt("artifact too big",p->o(p,"artifact").put("size",1048577));badReceipt("artifact fractional size",p->o(p,"artifact").put("size",new BigDecimal("400.00000000000000001")));badReceipt("artifact type mismatch",p->o(p,"artifact").put("mime_type","image/png"));badReceipt("artifact grant",p->o(o(p,"artifact"),"metadata").put("execution_authority_granted",true));badReceipt("wrong result scope",p->o(p,"result").put("loaded_board_id",OTHER));badReceipt("unknown result key",p->o(p,"result").put("machine_enabled",true));badReceipt("missing result flag",p->o(p,"result").remove("production_authority_granted"));badReceipt("production grant",p->o(p,"result").put("production_authority_granted",true));badReceipt("pretend instrument",p->o(p,"result").put("instrument_authenticity_verified",true));badReceipt("altered placed history",p->o(p,"result").put("native_placed_history_modified",true));badReceipt("wrong counts",p->o(p,"result").put("passed_count",2));badReceipt("false outcome",p->o(p,"result").put("outcome","failed"));badReceipt("near-integer observed",p->o(p,"result").put("observed_count",new BigDecimal("1.00000000000000001")));badReceipt("unverified actor changed to verified",p->o(p,"result").put("authority","authenticated-instrument"));badReceipt("oversized operator note",p->o(p,"result").put("operator_note","x".repeat(1048576)));
        badReceipt("cross-holder row",p->((Map<String,Object>)a(o(p,"result"),"records").get(0)).put("holder_instance_id","P2/A"));badReceipt("unknown row placement",p->((Map<String,Object>)a(o(p,"result"),"records").get(0)).put("placement_id","R2"));badReceipt("missing row coverage",p->o(p,"result").put("records",List.of()));badReceipt("missing row invents measurements",p->((Map<String,Object>)a(o(p,"result"),"records").get(0)).put("presence","missing"));badReceipt("NaN measured",p->o((Map<String,Object>)a(o(p,"result"),"records").get(0),"measurements").put("dx_mm",Double.NaN));badReceipt("reversed interval",p->o((Map<String,Object>)a(o(p,"result"),"records").get(0),"measurements").put("xy_interval_mm",List.of(2,1)));
        badPending("unknown snapshot field",p->o(p,"snapshot").put("token","private"));badPending("omitted snapshot source identity",p->o(p,"snapshot").remove("library_fingerprint"));
        badPending("scope config disagreement",p->o(o(p,"snapshot"),"board_load_scope").put("board_load_revision","load-3"));badPending("missing selected binding",p->o(o(p,"snapshot"),"board_load_scope").put("boards",List.of()));
        badPending("duplicate selected binding",p->{Map<String,Object> scope=o(o(p,"snapshot"),"board_load_scope");scope.put("boards",List.of(a(scope,"boards").get(0),a(scope,"boards").get(0)));});
        badPending("load binding drift",p->o(p,"snapshot").put("board_load_id",OTHER));badPending("holder binding drift",p->o(p,"snapshot").put("holder_instance_id","P2/A"));badPending("root binding drift",p->o(p,"snapshot").put("root_instance_id","P2"));badPending("side binding drift",p->o(p,"snapshot").put("board_side","bottom"));
        badPending("unknown snapshot units",p->o(p,"snapshot").put("location_units","in"));badPending("fractional profile limit",p->o(o(p,"snapshot"),"limits").put("placements",new BigDecimal("200.0000000000000001")));
        badPending("unknown required row field",p->((Map<String,Object>)a(o(p,"snapshot"),"required_placements").get(0)).put("reset_placed",true));badPending("missing required part",p->((Map<String,Object>)a(o(p,"snapshot"),"required_placements").get(0)).remove("part_id"));
        badPending("required pose overflow",p->o((Map<String,Object>)a(o(p,"snapshot"),"required_placements").get(0),"location").put("x",10001));
        badReceipt("retained marginal XY false pass",p->observed(p,"0.100000000000000000001","0","0","0","0",List.of(),List.of()));
        badReceipt("retained marginal angular false pass",p->observed(p,"0","0","5.000000000000000000001","0","0",List.of(),List.of()));
        badReceipt("retained uncertainty false pass",p->observed(p,"0.1","0","0","0.01","0",List.of(),List.of()));
        badReceipt("spurious numerical failure",p->disposition(p,List.of("xy_out_of_tolerance"),List.of()));badReceipt("spurious categorical failure",p->disposition(p,List.of("component_missing"),List.of()));badReceipt("spurious uncertainty",p->disposition(p,List.of(),List.of("polarity_unknown")));
        badReceipt("invented display error",p->o(row(p),"measurements").put("xy_error_mm",0.05));badReceipt("invented display interval",p->o(row(p),"measurements").put("xy_interval_mm",List.of(0,0.05)));
        acceptedReceipt("Exact XY and angle boundary passes",p->observed(p,"0.1","0","5","0","0",List.of(),List.of()));
        acceptedReceipt("Exact decimal marginal XY failure survives",p->observed(p,"0.100000000000000000001","0","0","0","0",List.of("xy_out_of_tolerance"),List.of()));
        acceptedReceipt("Exact decimal marginal angular failure survives",p->observed(p,"0","0","5.000000000000000000001","0","0",List.of("rotation_out_of_tolerance"),List.of()));
        acceptedReceipt("Uncertainty crossing both tolerances retained",p->observed(p,"0.1","0","5","0.01","0.5",List.of(),List.of("xy_uncertainty_crosses_tolerance","rotation_uncertainty_crosses_tolerance")));
        acceptedReceipt("Failure dominates independent uncertainty",p->observed(p,"0.2","0","5","0","0.5",List.of("xy_out_of_tolerance"),List.of("rotation_uncertainty_crosses_tolerance")));
        acceptedReceipt("Wrapped negative angle matches native model",p->observed(p,"0","0","-359","0","0",List.of(),List.of()));
        acceptedReceipt("Missing plus unknown polarity retained",p->{row(p).putAll(m("presence","missing","polarity","unknown","measurements",m()));disposition(p,List.of("component_missing"),List.of("polarity_unknown"));});
        acceptedReceipt("Unknown presence retained",p->{row(p).putAll(m("presence","unknown","polarity","unknown","measurements",m()));disposition(p,List.of(),List.of("presence_unknown","polarity_unknown"));});
        NativeInspectionJournal capacity=new NativeInspectionJournal();for(int i=0;i<64;i++)capacity.recover("inspection_task_pending",pending(i),INSTANCE);yes(((Number)capacity.snapshot(OTHER).get("retained_count")).intValue()==64,"64 bounded retained tasks");refused("65th task",()->capacity.prepare("inspection_task_pending",pending(64),INSTANCE));refused("cross-task request reuse",()->{NativeInspectionJournal x=prefix(1);Map<String,Object> p=pending(1);p.put("request_id",pending(0).get("request_id"));x.prepare("inspection_task_pending",p,INSTANCE);});
        for(String raw:List.of("{\"a\":1,\"a\":2}","{\"x\":{\"a\":1,\"a\":2}}","{\"type\":\"inspection_receipt\",\"type\":\"inspection_task_pending\"}","{\"a\":1} {}","{\"a\":1","{\"a\":NaN}","{\"a\":1e9999}","{\"a\":\"\\ud800\"}","{\"a\":"+"[".repeat(66)+"0"+"]".repeat(66)+"}","{\"a\":\""+"x".repeat(1114112)+"\"}"))refused("raw closed JSON negative",()->NativeInspectionJournal.validateRawRecord(raw));
        NativeInspectionJournal.validateRawRecord("{\"a\":1.00000000000000001,\"b\":[true,false,null,\"unicode \\ud83d\\ude00\"]}");checks++;
        yes(!NativeInspectionJournal.matches("operation")&&NativeInspectionJournal.matches("inspection_receipt"),"Only inspection namespace observed");
        System.out.println("OPENPNP_NATIVE_INSPECTION_JOURNAL_RESULT "+JSON.toJson(m("passed",true,"assertions",checks,"refusals",refusals,"fixture_provenance","synthetic-data-only; pinned native Gson and production reducer","native_machine_loaded",false,"native_calls",0,"physical_qualification",false,"execution_authority_restored",false)));
    }
}
