/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.openpnp.model.*;
import org.openpnp.model.Abstract2DLocatable.Side;
import org.openpnp.spi.*;
import static org.openpnp.codex.NativePlacementEditsTest.*;

/** Native models/serializer/forced lineage; trusted test caller, not packaged Bridge admission. */
public final class NativePanelStructureTest {
    static int assertions,refusals,enabledEvents,homeEvents,headEvents;static Path evidence;static final Gson JSON=new Gson();static final List<String> groups=new ArrayList<>();
    interface Checked{void run()throws Exception;}
    static void verify(boolean b,String m){assertions++;if(!b)throw new AssertionError(m);}
    static void reject(String code,Checked f)throws Exception{try{f.run();throw new AssertionError("Expected "+code);}catch(NativePlacementEdits.Fault e){verify(code.equals(e.code),"Expected "+code+", got "+e.code+": "+e.getMessage());refusals++;}}
    static String sha(byte[] bytes)throws Exception{return NativePlacementStructureTest.Hex.sha(bytes);}
    static String library(Object object)throws Exception{java.io.ByteArrayOutputStream b=new java.io.ByteArrayOutputStream();Configuration.createSerializer().write(object,b);return sha(b.toByteArray());}
    static JsonObject clone(String parent,String from,String id){return object("action","clone_board_child","scope","job_instance","parent_instance_id",parent,"source_child_id",from,"new_child_id",id,"location",local(14,9,0,30),"side","Top","enabled",true,"check_fiducials",false);}
    static JsonObject remove(String parent,String id){return object("action","remove_board_child","scope","job_instance","parent_instance_id",parent,"child_id",id);}
    static Map<String,Object> map(JsonObject o){return NativeJournalJson.parseObject(o.toString());}
    static final class Guard implements NativePlacementEdits.StructureAuthority,NativePlacementEdits.PanelPublicationFence {
        Job owned;String jobId=UUID.randomUUID().toString();final Path file;final NativeJobLineage ledger;final NativeBoardLoads loads;NativeJobLineage.PendingPermit permit;
        boolean revoked,failBefore,failAfter,failFence;String mode="normal";int reservations,invalidations,callbacks;NativePlacementEdits.Publication retained;
        Guard(Job job,String name)throws Exception{
            owned=job;file=evidence.resolve(name+".jsonl");ledger=new NativeJobLineage((type,payload)->record(type,payload));ledger.createFresh(jobId,"canonical-simulator");
            loads=new NativeBoardLoads((type,payload)->{record(type,payload);ledger.observe(type,payload);});loads.bindJob(job,jobId,true);
        }
        void record(String type,Map<String,Object> payload)throws Exception{NativePlacementStructureTest.force(file,JSON.toJson(Bridge.map("type",type,"payload",payload)));}
        public synchronized NativePlacementEdits.StructureState requireUnexecuted(Configuration c,Job j)throws Exception{
            if(c!=config||j!=owned||revoked)throw new NativePlacementEdits.Fault("STRUCTURE_AUTHORITY_STALE","Test authority lost");
            NativeJobLineage.Snapshot s;try{s=ledger.requirePristine(jobId,permit);}catch(NativeJobLineage.Fault f){throw new NativePlacementEdits.Fault(f.code,f.getMessage());}
            loads.publishSnapshot();for(Object raw:(List<?>)loads.snapshot().get("loads")){Map<?,?> l=(Map<?,?>)raw;if(((Number)l.get("native_history_entries")).intValue()!=0)throw new NativePlacementEdits.Fault("LINEAGE_HISTORY_PRESENT","Retained native keys");}
            return new NativePlacementEdits.StructureState(s.lineageId,s.revision,s.reservedLogicalIds);
        }
        public synchronized void reserveAndForce(NativePlacementEdits.StructureState expected,JsonObject reservation)throws Exception{
            verify(expected.same(requireUnexecuted(config,owned)),"Exact reservation prestate");if(failBefore)throw new java.io.IOException("before force");List<String> keys=new ArrayList<>();for(JsonElement e:reservation.getAsJsonArray("logical_ids"))keys.add(e.getAsString());
            permit=ledger.reserve(jobId,expected.revision,reservation.get("transaction_id").getAsString(),reservation.get("source_fingerprint").getAsString(),keys);reservations++;if(failAfter)throw new java.io.IOException("after force");
        }
        public synchronized void invalidateBeforePublication(Job j,List<String> roots)throws Exception{verify(reservations==1,"Reservation before invalidation");invalidations++;if(failFence)throw new java.io.IOException("invalidation");loads.invalidateRegistration("cfg-1","model-panel");NativeBoardLoads.invalidateTransforms(j);}
        public synchronized void publishIfCurrent(Configuration c,Job j,NativePlacementEdits.StructureState expected,NativePlacementEdits.Publication publication)throws Exception{
            callbacks++;retained=publication;if(mode.equals("noop"))return;if(mode.equals("revoke"))revoked=true;if(mode.equals("change"))placement(j,"solo","R1").getDefinition().setRank(901);
            if(mode.equals("thread")){Thread t=new Thread(()->{try{publication.publish();}catch(Exception accepted){}});t.start();t.join();return;}
            verify(expected.same(requireUnexecuted(c,j)),"Commit callback owns exact current authority");publication.publish();
            if(mode.equals("repeat")){try{publication.publish();}catch(Exception suppressed){}}
        }
        void complete(Map<String,Object> result)throws Exception{loads.jobChanged(owned,jobId);ledger.publicationSucceeded(jobId,((Number)result.get("lineage_revision")).longValue(),(String)result.get("transaction_id"),(String)NativePlacementEdits.inspect(config,owned,0,1).get("source_fingerprint"));permit.close();permit=null;reservations=0;}
        NativeJobLineage replay()throws Exception{NativeJobLineage copy=new NativeJobLineage((t,p)->{throw new AssertionError("replay is read-only");});for(String line:Files.readAllLines(file)){Map<String,Object> row=NativeJournalJson.parseObject(line);copy.observe((String)row.get("type"),(Map<String,Object>)row.get("payload"));}return copy;}
        Job roundTripOwned()throws Exception{NativeJobLineage.Snapshot s=ledger.snapshot(jobId);NativeJobDocuments docs=new NativeJobDocuments(config,Files.createTempDirectory(temp,"panel-docs-"));NativeJobDocuments.Saved saved=docs.save(owned,new NativeJobDocuments.LineageMetadata(s.lineageId,s.revision));ledger.bindDocument(jobId,saved.sha256);NativeJobDocuments.Reloaded loaded=docs.reloadWithMetadata(saved.sha256);String alias=UUID.randomUUID().toString();ledger.bindReload(alias,saved.sha256,loaded.lineage.get().lineageId,loaded.lineage.get().lineageRevision);owned=loaded.job;jobId=alias;loads.jobChanged(owned,jobId);return owned;}
    }
    static NativePlacementEdits.PanelStructurePatch stage(Guard g,JsonObject row)throws Exception{return NativePlacementEdits.stagePanelStructure(config,g.owned,row,g,g);}
    static void apply(Guard g,JsonObject row)throws Exception{Map<String,Object> result=stage(g,row).apply();g.complete(result);}
    static void positive()throws Exception{
        Job job=fixture(true);Guard g=new Guard(job,"positive");Board original=board(job,"solo").getBoard().getDefinition();String originalHash=library(original),partHash=library(part),packageHash=library(part.getPackage());Job otherJob=new Job();otherJob.addBoardOrPanelLocation(boardLocation(original,"outside",Side.Top,pose(0,0,0,0)));Map<String,Object> outside=snapshot(otherJob),before=snapshot(job);AtomicInteger events=new AtomicInteger();original.addPropertyChangeListener(e->events.incrementAndGet());
        board(job,"P2⇒nested⇒A").getParent().setLocallyEnabled(false);before=snapshot(job);Map<String,Object> p2=new TreeMap<>();for(Map.Entry<String,Object> e:before.entrySet())if(e.getKey()!=null&&e.getKey().startsWith("P2"))p2.put(e.getKey(),e.getValue());
        JsonObject input=clone("P1⇒nested","A","C");NativePlacementEdits.PanelStructurePatch plan=stage(g,input);JsonObject preview=plan.preview();verify(snapshot(job).equals(before)&&g.reservations==0&&g.callbacks==0&&events.get()==0,"Plan publishes no native changes or reservation");input.addProperty("new_child_id","ALTERED");preview.addProperty("valid",false);Map<String,Object> result=plan.apply();g.complete(result);verify(plan.preview().get("valid").getAsBoolean(),"Preview/input immutability");verify(board(job,"P1⇒nested⇒C").getBoard().getPlacements().get("R1").getPart()==part,"New instance uses configured Part identity");verify(board(job,"P1⇒nested⇒C").getBoard()!=board(job,"P1⇒nested⇒A").getBoard(),"Expanded boards are distinct native objects");verify(g.callbacks==1,"Publication called once");reject("PLAN_CONSUMED",plan::apply);reject("STRUCTURE_PUBLICATION_PROTOCOL",g.retained::publish);
        apply(g,remove("P1⇒nested","B"));Map<String,Object> after=snapshot(job);verify(!after.containsKey("P1⇒nested⇒B")&&after.containsKey("P1⇒nested⇒C"),"Desired child sequence clones then removes exact instance");for(Map.Entry<String,Object> e:p2.entrySet())verify(e.getValue().equals(after.get(e.getKey())),"P2 repeated panel unchanged");verify(library(original).equals(originalHash)&&snapshot(otherJob).equals(outside)&&events.get()==0,"External definition/listeners/job unchanged");verify(library(part).equals(partHash)&&library(part.getPackage()).equals(packageHash),"Part/package native library bytes unchanged");verify(job.getPlacedStatusSnapshot().isEmpty(),"No native history synthesized");
        Map<String,Object> shape=snapshot(job);Job loaded=g.roundTripOwned();verify(shape.equals(snapshot(loaded)),"Actual native save/load retains membership flags and pseudos");reject("STRUCTURE_ID_REUSED",()->stage(g,clone("P1⇒nested","A","B")));verify(g.replay().snapshot(g.jobId).reservedLogicalIds.equals(g.ledger.snapshot(g.jobId).reservedLogicalIds),"Actual forced journal replay and document alias preserve holder/record reservations");
        apply(g,remove("P1⇒nested","C"));reject("STRUCTURE_ID_REUSED",()->stage(g,clone("P1⇒nested","A","C")));groups.add("shared-isolation-clone-remove-native-document-and-durable-retirement");
    }
    static Job flat(String panelId,boolean empty){Board b=empty?new Board():board();Panel p=new Panel();p.setDimensions(pose(50,50,0,0));p.addChild(boardLocation(b,"A",Side.Top,pose(0,0,0,0)));p.addChild(boardLocation(b,"B",Side.Top,pose(20,0,0,0)));Job j=new Job();j.addBoardOrPanelLocation(panelLocation(p,panelId,Side.Top,pose(0,0,0,0)));PanelLocation.setParentsOfAllDescendants(j.getRootPanelLocation());return j;}
    static void unicodeEmpty()throws Exception{
        Guard g=new Guard(flat("面板😀",true),"unicode-empty");JsonObject row=clone("面板😀","A","C");row.add("location",object("frame","holder","units","in","x",0.5,"y",0.25,"z",0.1,"rotation",-90));row.addProperty("side","Bottom");row.addProperty("enabled",false);row.addProperty("check_fiducials",true);apply(g,row);BoardLocation c=board(g.owned,"面板😀⇒C");verify(c.getLocation().getX()==12.7&&c.getLocation().getRotation()==-90&&c.getSide()==Side.Bottom&&!c.isLocallyEnabled()&&c.isCheckFiducials(),"Explicit inch pose/side/flags on empty board");Set<String> keys=g.ledger.snapshot(g.jobId).reservedLogicalIds;verify(keys.size()==1&&keys.iterator().next().startsWith("holder-v1:")&&!keys.iterator().next().contains("⇒"),"Empty board receives disjoint holder tombstone");String expected="holder-v1:"+Base64.getUrlEncoder().withoutPadding().encodeToString("面板😀⇒C".getBytes(java.nio.charset.StandardCharsets.UTF_8));verify(keys.contains(expected),"Exact case-sensitive UTF-8 key encoding");verify(snapshot(g.owned).equals(snapshot(g.roundTripOwned())),"Empty and Unicode boards round-trip natively");apply(g,remove("面板😀","C"));reject("STRUCTURE_ID_REUSED",()->stage(g,clone("面板😀","A","C")));
        Guard controls=new Guard(flat("bad\u0085",true),"controls");reject("PANEL_HOLDER_ID",()->stage(controls,clone("bad\u0085","A","C")));
        Guard malformed=new Guard(flat("bad\ud800",true),"malformed");reject("PANEL_HOLDER_ID",()->stage(malformed,clone("bad\ud800","A","C")));groups.add("unicode-empty-holder-retirement-inch-and-malformed-paths");
    }
    static void refusalsAndFences()throws Exception{
        Guard g=new Guard(fixture(true),"refusals");reject("STRUCTURE_ID_REUSED",()->stage(g,clone("P1⇒nested","A","B")));reject("HOLDER_NOT_FOUND",()->stage(g,remove("P1⇒nested","MISSING")));reject("STRUCTURE_PSEUDO_DEPENDENCY",()->stage(g,remove("P1⇒nested","A")));reject("STRUCTURE_BOARD_ONLY",()->stage(g,clone("P1","nested","C")));JsonObject extra=clone("P1⇒nested","A","C");extra.addProperty("unknown",1);reject("UNKNOWN_FIELD",()->stage(g,extra));JsonObject missing=clone("P1⇒nested","A","C");missing.remove("side");reject("INVALID_FIELD",()->stage(g,missing));JsonObject wrong=clone("P1⇒nested","A","C");wrong.addProperty("enabled","true");reject("INVALID_FIELD",()->stage(g,wrong));JsonObject bad=clone("P1⇒nested","A","C⇒D");reject("INVALID_ID",()->stage(g,bad));
        Job last=flat("P",false);Guard single=new Guard(last,"last");apply(single,remove("P","B"));reject("STRUCTURE_EMPTY_PANEL",()->stage(single,remove("P","A")));
        g.owned.storePlacedStatus(board(g.owned,"solo"),"ORPHAN",false);reject("STRUCTURE_HISTORY_PRESENT",()->stage(g,clone("P1⇒nested","A","C")));g.owned.removePlacedStatus(board(g.owned,"solo"),"ORPHAN");NativePlacementEdits.PanelStructurePatch stale=stage(g,clone("P1⇒nested","A","C"));String oldName=part.getName();part.setName("changed-after-plan");reject("PART_IDENTITY",stale::apply);part.setName(oldName);
        for(String mode:List.of("noop","repeat","revoke","change","thread")){Guard f=new Guard(fixture(false),"fence-"+mode);f.mode=mode;Map<String,Object> before=snapshot(f.owned);reject("STRUCTURE_PUBLICATION_FAILED",()->stage(f,clone("P1⇒nested","A","C")).apply());verify(f.ledger.snapshot(f.jobId).pendingTransaction!=null&&f.callbacks==1,"Uncertain callback retains reservation");verify(f.replay().snapshot(f.jobId).pendingTransaction!=null,"Uncertain callback pending survives real forced replay");if(!mode.equals("repeat")&&!mode.equals("change"))verify(before.equals(snapshot(f.owned)),"No-op/offthread/revoked callback publishes no root");}
        Guard admitted=new Guard(fixture(false),"admitted-fixture");Map<String,Object> admission=Bridge.map("operation_id",UUID.randomUUID().toString(),"request_id",UUID.randomUUID().toString(),"request_digest",String.join("",Collections.nCopies(64,"a")),"job_id",admitted.jobId,"job_revision",admitted.loads.jobRevision(),"board_load_revision",admitted.loads.revision(),"config_revision","cfg-1","method","openpnp_start_job","state","accepted","job_lineage",admitted.ledger.admissionFacts(admitted.jobId));admitted.record("operation",admission);admitted.ledger.observe("operation",admission);reject("LINEAGE_EXECUTED",()->stage(admitted,clone("P1⇒nested","A","C")));verify(admitted.reservations==0&&admitted.replay().snapshot(admitted.jobId).admitted,"Seeded admission receipt retains the no-structure rule; no processor invoked");
        groups.add("closed-fields-history-stale-library-and-publication-protocol");
    }
    static Job prefix(boolean ambiguous)throws Exception{
        Board b=board();Panel inside=new Panel();inside.setDimensions(pose(50,50,0,0));inside.addChild(boardLocation(b,"S",Side.Top,pose(0,0,0,0)));if(ambiguous)inside.addChild(boardLocation(b,"B",Side.Top,pose(0,0,0,0)));
        Panel outer=new Panel();outer.setDimensions(pose(80,80,0,0));outer.addChild(panelLocation(inside,"A",Side.Top,pose(0,0,0,0)));outer.addChild(boardLocation(b,"AB",Side.Top,pose(0,0,0,0)));outer.addPseudoPlacement(outer.createPseudoPlacement("AB⇒FID"));Job j=new Job();j.addBoardOrPanelLocation(panelLocation(outer,"P",Side.Top,pose(0,0,0,0)));PanelLocation.setParentsOfAllDescendants(j.getRootPanelLocation());return j;
    }
    static void pseudoReferences()throws Exception{
        Guard g=new Guard(prefix(false),"prefix-prospective");Map<String,Object> before=snapshot(g.owned);NativePlacementEdits.PanelStructurePatch plan=stage(g,clone("P⇒A","S","B"));reject("STRUCTURE_PSEUDO_REFERENCE",plan::apply);verify(g.reservations==0&&before.equals(snapshot(g.owned)),"Prospective prefix resolver retarget refuses before reservation/root publication");
        Guard bad=new Guard(prefix(true),"prefix-existing");reject("STRUCTURE_PSEUDO_REFERENCE",()->stage(bad,clone("P⇒A","S","C")));verify(bad.reservations==0,"Ambiguous existing pseudo graph refuses before reservation");
        Guard unrelated=new Guard(prefix(false),"prefix-safe");apply(unrelated,clone("P⇒A","S","C"));verify(snapshot(unrelated.owned).equals(snapshot(unrelated.roundTripOwned())),"Unchanged exact ancestor pseudo survives valid clone and native documents");groups.add("prefix-pseudo-retarget-preexisting-ambiguity-and-exact-roundtrip");
    }
    static Job longPath(){Board b=new Board();Panel leaf=new Panel();leaf.addChild(boardLocation(b,"A",Side.Top,pose(0,0,0,0)));leaf.addChild(boardLocation(b,"B",Side.Top,pose(0,0,0,0)));Panel mid=new Panel();mid.addChild(panelLocation(leaf,String.join("",Collections.nCopies(128,"M")),Side.Top,pose(0,0,0,0)));Panel top=new Panel();top.addChild(panelLocation(mid,String.join("",Collections.nCopies(128,"N")),Side.Top,pose(0,0,0,0)));Job j=new Job();j.addBoardOrPanelLocation(panelLocation(top,String.join("",Collections.nCopies(128,"P")),Side.Top,pose(0,0,0,0)));PanelLocation.setParentsOfAllDescendants(j.getRootPanelLocation());return j;}
    static Job manyHolders(int count){Board empty=new Board();Panel panel=new Panel();for(int i=0;i<count;i++)panel.addChild(boardLocation(empty,"B"+i,Side.Top,pose(0,0,0,0)));Job j=new Job();j.addBoardOrPanelLocation(panelLocation(panel,"P",Side.Top,pose(0,0,0,0)));PanelLocation.setParentsOfAllDescendants(j.getRootPanelLocation());return j;}
    static void boundsAndIdentity()throws Exception{
        Guard g=new Guard(longPath(),"path-bound");String parent=board(g.owned,g.owned.getBoardLocations().get(0).getUniqueId()).getUniqueId();parent=parent.substring(0,parent.lastIndexOf("⇒"));final String selected=parent;String id=String.join("",Collections.nCopies(125,"C"));verify((parent+"⇒"+id).length()==512,"Fixture exact native512 path boundary");reject("PANEL_HOLDER_ID",()->stage(g,clone(selected,"A",id+"D")));apply(g,clone(parent,"A",id));verify(snapshot(g.owned).equals(snapshot(g.roundTripOwned())),"Exact512 holder path survives native save/load");
        Guard capacity=new Guard(manyHolders(999),"holders-over");reject("PANEL_GRAPH_LIMIT",()->stage(capacity,clone("P","B0","EXTRA")));verify(capacity.reservations==0&&capacity.owned.getBoardAndPanelLocations().size()==1001,"All-holder bound counts panel plus999 boards, excluding inline root");
        Guard exact=new Guard(manyHolders(998),"holders-exact");apply(exact,clone("P","B0","EXTRA"));verify(exact.owned.getBoardAndPanelLocations().size()==1001,"Exactly1000 non-inline native holders supported");
        Guard identity=new Guard(fixture(false),"identity");NativePlacementEdits.PanelStructurePatch plan=stage(identity,clone("P1⇒nested","A","C"));Part old=part;Part replacement=new Part(part.getId());replacement.setPackage(part.getPackage());config.addPart(replacement);try{reject("PART_IDENTITY",plan::apply);}finally{config.addPart(old);}verify(identity.reservations==0,"Late native Part replacement rejects before durable reservation");
        Guard hugeLibrary=new Guard(fixture(false),"library-byte-bound");String savedName=part.getName();try{part.setName(String.join("",Collections.nCopies(8*1024*1024,"x")));reject("STRUCTURE_LIMIT",()->stage(hugeLibrary,clone("P1⇒nested","A","C")));}finally{part.setName(savedName);}verify(hugeLibrary.reservations==0,"Oversized native library serialization refuses before reservation");
        Guard gaps=new Guard(fixture(false),"geometry");JsonObject nan=clone("P1⇒nested","A","C");nan.getAsJsonObject("location").addProperty("x",Double.NaN);reject("INVALID_FIELD",()->stage(gaps,nan));JsonObject oversized=clone("P1⇒nested","A","C");oversized.getAsJsonObject("location").addProperty("z",1001);reject("GEOMETRY_RANGE",()->stage(gaps,oversized));JsonObject omitted=clone("P1⇒nested","A","C");omitted.getAsJsonObject("location").remove("y");reject("INVALID_FIELD",()->stage(gaps,omitted));JsonObject wrongScope=clone("P1⇒nested","A","C");wrongScope.addProperty("scope","job_shared_definition");reject("EDIT_SCOPE",()->stage(gaps,wrongScope));reject("HOLDER_NOT_FOUND",()->stage(gaps,clone("P1⇒nested","a","C")));groups.add("native-holder512-all-holder1000-boundaries-and-late-reference-identity");
    }
    static void failuresAndHistory()throws Exception{
        for(String mode:List.of("before","after","invalidation")){Guard g=new Guard(fixture(false),"storage-"+mode);g.failBefore=mode.equals("before");g.failAfter=mode.equals("after");g.failFence=mode.equals("invalidation");Map<String,Object> before=snapshot(g.owned);reject(mode.equals("invalidation")?"STRUCTURE_FENCE_FAILED":"STRUCTURE_RESERVATION_UNCERTAIN",()->stage(g,clone("P1⇒nested","A","C")).apply());verify(before.equals(snapshot(g.owned))&&g.callbacks==0,"Storage/fence failure cannot publish a root");verify((g.replay().snapshot(g.jobId).pendingTransaction!=null)==!mode.equals("before"),"Replay preserves actual pre/post-force boundary");}
        Guard rollback=new Guard(fixture(false),"listener-failure");Map<String,Object> before=snapshot(rollback.owned);java.util.concurrent.atomic.AtomicBoolean first=new java.util.concurrent.atomic.AtomicBoolean(true);rollback.owned.getRootPanelLocation().getPanel().addPropertyChangeListener(e->{if(e.getPropertyName().equals("children")&&first.getAndSet(false))throw new IllegalStateException("actual root listener failure");});reject("STRUCTURE_PUBLICATION_FAILED",()->stage(rollback,clone("P1⇒nested","A","C")).apply());verify(before.equals(snapshot(rollback.owned))&&rollback.ledger.snapshot(rollback.jobId).pendingTransaction!=null,"Root rollback retains durable uncertainty and old tree");
        for(String kind:List.of("flags","library","history","root-swap","root-name","root-file","root-dimensions","root-units")){
            Guard mutated=new Guard(fixture(false),"listener-mutation-"+kind);AtomicInteger mutations=new AtomicInteger();String partName=part.getName();
            mutated.owned.getRootPanelLocation().getPanel().addPropertyChangeListener(e->{if(e.getPropertyName().equals("children")&&mutations.getAndIncrement()==0){if(kind.equals("flags"))board(mutated.owned,"P1⇒nested⇒C").setLocallyEnabled(false);else if(kind.equals("library"))part.setName("changed inside native publication");else if(kind.equals("history"))mutated.owned.storePlacedStatus(board(mutated.owned,"solo"),"AFTER_SETTER_ORPHAN",false);
                else if(kind.equals("root-swap")){Panel replacement=new Panel();org.openpnp.util.IdentifiableList<PlacementsHolderLocation<?>> children=new org.openpnp.util.IdentifiableList<>();children.addAll(mutated.owned.getRootPanelLocation().getChildren());replacement.setChildren(children);mutated.owned.getRootPanelLocation().setPanel(replacement);}
                else if(kind.equals("root-name"))mutated.owned.getRootPanelLocation().getPanel().setName("changed inside root publication");
                else if(kind.equals("root-file"))mutated.owned.getRootPanelLocation().getPanel().setFile(temp.resolve("unexpected-root.panel.xml").toFile());
                else if(kind.equals("root-dimensions"))mutated.owned.getRootPanelLocation().getPanel().setDimensions(new Location(LengthUnit.Millimeters,42,19,0,0));
                else mutated.owned.getRootPanelLocation().getPanel().setDimensions(mutated.owned.getRootPanelLocation().getPanel().getDimensions().convertToUnits(LengthUnit.Inches));}});
            try{reject("STRUCTURE_PUBLICATION_FAILED",()->stage(mutated,clone("P1⇒nested","A","C")).apply());}finally{part.setName(partName);}
            verify(mutations.get()==1&&mutated.callbacks==1&&mutated.ledger.snapshot(mutated.jobId).pendingTransaction!=null,"Synchronous native listener mutation cannot produce publication success");
            verify(mutated.replay().snapshot(mutated.jobId).pendingTransaction!=null,"Listener mutation preserves durable uncertain publication after replay");
        }
        Guard history=new Guard(fixture(false),"retired-history");history.owned.storePlacedStatus(board(history.owned,"solo"),"RETIRED_ORPHAN",false);history.loads.checkpoint(history.owned);Map<?,?> root=(Map<?,?>)((List<?>)history.loads.snapshot().get("roots")).get(0);history.loads.change(history.owned,"solo","replace","bottom",(String)root.get("load_id"),history.loads.revision(),false);verify(history.owned.getPlacedStatusSnapshot().isEmpty(),"Native replacement removes current keys but keeps retained ledger");reject("LINEAGE_HISTORY_PRESENT",()->stage(history,clone("P1⇒nested","A","C")));groups.add("before-after-force-invalidation-listener-rollback-and-retired-native-history");
    }
    public static void main(String[] args)throws Exception{
        evidence=Files.createTempDirectory("native-panel-structure-");temp=evidence.resolve("configuration");Files.createDirectories(temp);Configuration.initialize(temp.toFile());config=Configuration.get();config.load();part=config.getParts().get(0);other=config.getParts().get(1);Machine machine=config.getMachine();machine.addListener(new MachineListener.Adapter(){public void machineEnabled(Machine m){enabledEvents++;}public void machineHomed(Machine m,boolean h){if(h)homeEvents++;}public void machineHeadActivity(Machine m,Head h){headEvents++;}});int exit=0;
        try{positive();unicodeEmpty();refusalsAndFences();pseudoReferences();boundsAndIdentity();failuresAndHistory();verify(!machine.isEnabled()&&!machine.isHomed()&&enabledEvents==0&&homeEvents==0&&headEvents==0,"No native enable/home/head activity");System.out.println("OPENPNP_NATIVE_PANEL_STRUCTURE_RESULT "+JSON.toJson(Bridge.map("passed",true,"assertions",assertions,"refusals",refusals,"groups",groups,"evidence_directory",evidence.toString(),"native_enable_events",enabledEvents,"native_home_events",homeEvents,"native_head_events",headEvents,"native_model_qualification",true,"model_override_qualification",!NativePlacementEdits.class.getProtectionDomain().getCodeSource().getLocation().equals(Bridge.class.getProtectionDomain().getCodeSource().getLocation()),"packaged_bridge_qualification",false,"job_processor_called",false,"class_origins",Bridge.map("NativePlacementEdits",NativePlacementEdits.class.getProtectionDomain().getCodeSource().getLocation().toString(),"NativeBoardLoads",NativeBoardLoads.class.getProtectionDomain().getCodeSource().getLocation().toString(),"NativeJobDocuments",NativeJobDocuments.class.getProtectionDomain().getCodeSource().getLocation().toString(),"Bridge",Bridge.class.getProtectionDomain().getCodeSource().getLocation().toString(),"Panel",Panel.class.getProtectionDomain().getCodeSource().getLocation().toString()))));}catch(Throwable failure){failure.printStackTrace();exit=1;}finally{machine.close();}System.exit(exit);
    }
}
