/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import static org.openpnp.codex.NativeReplacementContinuationTest.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import org.openpnp.model.*;

/** Actual native models, exact common reducers and FileChannel.force. Initial fault/action and
 * coordinator authority are explicitly synthetic fixtures; no Bridge, jobs, feeds or placements. */
public final class NativeReplacementAtomicAdmissionTest {
    static int assertions,refused;static final List<Map<String,Object>> groups=new ArrayList<>();
    static void check(boolean value,String why){assertions++;if(!value)throw new AssertionError(why);}
    interface Checked{void run()throws Exception;}
    static void reject(String why,Checked action)throws Exception{try{action.run();throw new AssertionError("Accepted: "+why);}catch(IOException|Bridge.Fault|NativeJobLineage.Fault expected){refused++;check(true,why);}}
    static final class Decision {
        final Env e;final NativeSensingReconciliation.Permit sensing;final String operation=id();
        Decision(Env e)throws Exception{
            this.e=e;e.vacuum=new NativeVacuumJournal();e.coordinator=new NativeSensingReconciliation(e.vacuum,(op,instance,replay)->false,e.replacement::verified);
            Map<String,Object> context=NativeSensingReconciliationTest.context(),job=m("job_id",e.jobId,"job_revision",e.oldBoard.get("job_revision"),"board_load_revision",e.oldBoard.get("revision"),"material_setup_revision",e.oldMaterial.get("revision"),"lineage_id",e.oldLineage.get("lineage_id"),"lineage_revision",e.oldLineage.get("lineage_revision"));context.put("operation_id",e.opId);context.put("scope","job");context.put("job_context",job);
            e.append("vacuum_observation_intent",NativeSensingReconciliationTest.event("read.before",100,null,context,NativeSensingReconciliationTest.SOURCE));Map<String,Object> scope=NativeSensingReconciliationTest.scope(NativeSensingReconciliationTest.INSTANCE,NativeSensingReconciliationTest.SOURCE);scope.put("job_context",job);scope.put("dependencies",e.capture.dependencies());e.faultCapture=e.vacuum.captureFaultSet(scope);e.taskId=id();
            Map<String,Object> record=e.coordinator.taskRecord(e.taskId,id(),id(),e.faultCapture,"replace-faulted-job-attempt",1,"2030-01-01T00:00:00Z");e.append("sensing_reconciliation_task",record);e.append("sensing_reconciliation_intent",e.coordinator.intentRecord(e.taskId,operation,id(),"2026-09-14T00:00:00Z",1,"synthetic-atomic-admission-test"));sensing=e.coordinator.issuePermit(e.taskId,operation,e.faultCapture.digest,e.localOwner);
            e.append("operation",m("operation_id",operation,"request_id",id(),"reconciliation_request_id",record.get("request_id"),"request_digest",e.faultCapture.digest,"method","local_native_sensing_reconciliation","task_id",e.taskId,"bridge_instance_id",NativeSensingReconciliationTest.INSTANCE,"config_revision","cfg-2","state","running"));
        }
        NativeFaultedJobReplacement.Permit begin(NativeReplacementJob.Candidate candidate)throws Exception{return e.replacement.begin(e.capture,candidate,e.coordinator,sensing,e.localOwner);}
    }
    static List<Map<String,Object>> intents(Env e){List<Map<String,Object>> out=new ArrayList<>();for(Map<String,Object> row:e.events)if("faulted_job_replacement_intent".equals(row.get("type")))out.add(row);return out;}
    static void write(String name,Object data)throws Exception{Files.writeString(root.resolve(name),JSON.toJson(data)+"\n",StandardOpenOption.CREATE_NEW);}
    static void noEffects(Env e,Map<String,Integer> counters,Map<String,String> files,Map<String,Boolean> history)throws Exception{check(counters.equals(counters()),"Admission/replay leaves actual native feeder counters unchanged");check(files.equals(configurationFiles()),"Admission/replay performs no native configuration save");check(history.equals(e.oldJob.getPlacedStatusSnapshot()),"Admission/replay preserves actual original complete history");}
    static void pureRefusals()throws Exception{
        try(Env e=new Env("foreign-original",false)){Decision d=task(()->new Decision(e));Map<String,Integer> before=counters();Map<String,String> files=configurationFiles();Map<String,Boolean> history=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());long bytes=Files.size(e.file);
            task(()->{Map<String,Object> bundle=NativeReplacementDocuments.captureReconstruction(config,e.oldJob,e.candidate);try(NativeReplacementDocuments.Reconstructed foreign=NativeReplacementDocuments.reconstruct(config,bundle)){
                check(foreign.original()!=e.oldJob&&NativeFaultedJobReplacement.same(foreign.candidate().mapping(),e.candidate.mapping()),"Foreign source has equal full graph/history mapping but a distinct actual native Job identity");reject("equal-content candidate with foreign exact original",()->d.begin(foreign.candidate()));}return null;});
            check(intents(e).isEmpty()&&bytes==Files.size(e.file),"Foreign exact-source rejection precedes intent force");noEffects(e,before,files,history);groups.add(m("name","foreign-original-identity","passed",true));}
        try(Env e=new Env("stale-history",false)){Decision d=task(()->new Decision(e));task(()->{e.oldJob.storePlacedStatus(e.oldJob.getBoardLocations().get(0),"removed-false-key",false);try(NativeReplacementJob.Candidate current=NativeReplacementJob.build(config,e.oldJob)){current.requireCurrent();long bytes=Files.size(e.file);reject("captured full native history became stale",()->d.begin(current));check(bytes==Files.size(e.file)&&intents(e).isEmpty(),"Stale false/orphan history refuses before admission");}return null;});groups.add(m("name","stale-complete-history","passed",true));}
        try(Env e=new Env("enabled-admission",false)){Decision d=task(()->new Decision(e));task(()->{config.getMachine().setEnabled(true);try{long bytes=Files.size(e.file);reject("enabled native machine cannot admit reconstruction",()->d.begin(e.candidate));check(bytes==Files.size(e.file)&&intents(e).isEmpty(),"Disabled guard refuses before intent");}finally{config.getMachine().setEnabled(false);}return null;});groups.add(m("name","disabled-guard","passed",true));}
        try(Env e=new Env("off-executor",false)){Decision d=task(()->new Decision(e));long bytes=Files.size(e.file);reject("atomic begin outside actual native executor",()->d.begin(e.candidate));check(bytes==Files.size(e.file)&&intents(e).isEmpty(),"Off-executor rejection precedes intent force");groups.add(m("name","native-executor-guard","passed",true));}
    }
    static void assertStaging(Env source,String name,Map<String,Object> expectedBundle)throws Exception{
        List<Map<String,Object>> exact=new ArrayList<>();for(String line:Files.readAllLines(source.file))exact.add(NativeJournalJson.parseObject(line));check(NativeFaultedJobReplacement.same(exact,source.events),"Replay consumes the exact actual forced FileChannel records");String attempt=(String)o(intents(source).get(0).get("payload")).get("replacement_attempt_id");Map<String,Integer> before=counters();Map<String,String> files=configurationFiles();Map<String,Boolean> history=new TreeMap<>(source.oldJob.getPlacedStatusSnapshot());
        try(Env replay=new Env(name+"-replay",true)){replay.replay(exact);check(NativeFaultedJobReplacement.same(replay.replacement.reconstructionBundle(attempt),expectedBundle),"Fresh reducer preserves exact atomically forced reconstruction");
            check(((Number)replay.replacement.status().get("retained_candidate_count")).intValue()==0,"Journal replay restores no native candidate authority");
            task(()->{reject("replay cannot capture live continuation",()->replay.replacement.captureContinuationForHost(attempt));try(NativeFaultedJobReplacement.RestartStage stage=replay.replacement.stageRestart(attempt)){
                stage.requireCurrent();check(stage.original()!=source.oldJob&&stage.candidate().job()!=source.candidate.job(),"Restart stage creates distinct actual native original and candidate objects");check(NativeFaultedJobReplacement.same(stage.original().getPlacedStatusSnapshot(),expectedBundle.get("original_history")),"Inert stage restores every exact original history key");check(NativeFaultedJobReplacement.same(stage.candidate().mapping(),expectedBundle.get("source_mapping")),"Inert stage rebuilds the original mapping exactly");check(stage.candidate().job().getPlacedStatusSnapshot().isEmpty(),"Staged replacement remains unexecuted");check(((Number)replay.replacement.status().get("retained_candidate_count")).intValue()==0,"Staging creates no live root candidate binding");reject("inert stage cannot become a continuation permit",()->replay.replacement.captureContinuationForHost(attempt));reject("only one current inert stage",()->replay.replacement.stageRestart(attempt));reject("replayed material is not ready",()->replay.material.requireReady());reject("replayed candidate boards are not ready",()->replay.boards.requireReady(stage.candidate().job()));}
                try(NativeFaultedJobReplacement.RestartStage retry=replay.replacement.stageRestart(attempt)){retry.requireCurrent();check(true,"Closed inert stage can be reconstructed again without old native effects");}return null;});
            check(Files.size(replay.file)==0&&replay.events.isEmpty(),"Fresh reducer replay and inert stages write no receipt or native event");noEffects(source,before,files,history);write(name+"-replayed-progress.json",replay.replacement.progress(attempt));}
    }
    static void postForceDrift()throws Exception{
        try(Env e=new Env("post-force-candidate-drift",false)){Decision d=task(()->new Decision(e));Map<String,Integer> before=counters();Map<String,String> files=configurationFiles();Map<String,Boolean> history=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());
            e.permit=task(()->d.begin(e.candidate));check(intents(e).size()==1,"Atomic native begin forces exactly one reconstruction intent");Map<String,Object> intent=o(intents(e).get(0).get("payload")),bundle=o(intent.get("reconstruction_bundle"));check(((Number)intent.get("schema_version")).intValue()==2&&NativeFaultedJobReplacement.digest(bundle).equals(intent.get("reconstruction_sha256")),"Schema2 forced intent binds complete native bundle");write("post-force-original-intent.json",intent);long bytes=Files.size(e.file);
            task(()->{Placement p=e.candidate.job().getBoardLocations().get(0).getBoard().getPlacements().get(0);p.setLocation(p.getLocation().derive(p.getLocation().getX()+1,null,null,null));reject("candidate drift after actual force refuses definition retention",()->e.replacement.retainCandidate(e.permit,e.candidate));return null;});
            check(bytes==Files.size(e.file)&&!e.replacement.ownsCandidate(e.candidate),"Candidate drift adds no definition and grants no retained native ownership");check(NativeFaultedJobReplacement.same(bundle,e.replacement.reconstructionBundle(e.permit.attemptId())),"Immutable forced bundle survives post-admission native drift");check("untouched".equals(o(e.replacement.progress(e.permit.attemptId()).get("definition")).get("phase")),"Drift cannot report a completed definition");noEffects(e,before,files,history);assertStaging(e,"post-force-drift",bundle);groups.add(m("name","post-force-candidate-drift","passed",true,"forced_intent_count",intents(e).size()));}
    }
    static void forceFailure(boolean after)throws Exception{
        String name="atomic-intent-"+(after?"after":"before")+"-force";try(Env e=new Env(name,false)){Decision d=task(()->new Decision(e));Map<String,Integer> before=counters();Map<String,String> files=configurationFiles();Map<String,Boolean> history=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());long bytes=Files.size(e.file);
            e.failType="faulted_job_replacement_intent";e.failAfterForce=after;task(()->{reject("controlled intent force failure",()->d.begin(e.candidate));return null;});e.failType=null;check(Boolean.TRUE.equals(e.replacement.status().get("publication_fault")),"Uncertain root force fences the live reducer");check(o(e.replacement.status().get("intents")).isEmpty()&&((Number)e.replacement.status().get("retained_candidate_count")).intValue()==0,"Unknown append return grants neither committed live intent nor candidate binding");task(()->{reject("faulted live reducer cannot retry intent",()->d.begin(e.candidate));return null;});
            check(intents(e).size()==(after?1:0)&&((Files.size(e.file)>bytes)==after),"FileChannel prefix matches before/after actual force boundary");noEffects(e,before,files,history);
            if(after){Map<String,Object> intent=o(intents(e).get(0).get("payload"));write(name+"-actual-forced-intent.json",intent);assertStaging(e,name,o(intent.get("reconstruction_bundle")));}
            else try(Env replay=new Env(name+"-replay",true)){replay.replay(e.events);check(o(replay.replacement.status().get("intents")).isEmpty(),"Before-force replay contains no invented replacement transaction");check(Files.size(replay.file)==0,"Before-force replay has no write");}
            groups.add(m("name",name,"passed",true,"forced_intents",intents(e).size()));}
    }
    public static void main(String[]args)throws Exception{
        if(args.length!=1)throw new IllegalArgumentException("Expected exclusive state directory");initialize(Path.of(args[0]));int exit=0;Throwable failure=null;
        try{pureRefusals();postForceDrift();forceFailure(false);forceFailure(true);}catch(Throwable error){error.printStackTrace();failure=error;exit=1;}
        finally{config.getMachine().close();Map<String,Object> proof=m("passed",exit==0,"assertions",assertions,"refusals",refused,"helper_assertions",checks,"groups",groups,"error",failure==null?null:failure.toString(),"pid",ProcessHandle.current().pid(),"actual_native_job_initializations",0,"actual_native_feeds",0,"actual_native_placements",0,"scope","Actual native models and FileChannel.force; explicitly synthetic initial action/sensing fault and local coordinator authority; root atomic admission and inert reconstruction only","bridge_integration_qualified",false,"restart_continuation_qualified",false,"hardware_qualified",false);write("proof.json",proof);System.out.println("NATIVE_REPLACEMENT_ATOMIC_ADMISSION_RESULT "+JSON.toJson(proof));}System.exit(exit);
    }
}
