/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import java.nio.*;
import java.nio.channels.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import static org.openpnp.codex.NativeReplacementContinuationTest.*;

/** Regression: completing the original callback must not hide the new restart callback.
 * Native graphs, component reducers and FileChannel forces are real; initial faults and the
 * explicitly scoped original-only terminal-wrapper authority are synthetic test fixtures. */
public final class NativeRestartContinuationScopeTest {
    static int checks;static void check(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}
    static final class RootEnv implements AutoCloseable {
        final NativeMaterialLoads material;final NativeBoardLoads boards;final NativeJobLineage lineage;final NativeFaultedJobReplacement replacement;
        final FileChannel channel;final Path file;final List<Map<String,Object>> events=new ArrayList<>();final Set<String> completed=new HashSet<>(),checked=new HashSet<>();long sequence;
        RootEnv(String name,List<Map<String,Object>> original,String completedOriginal)throws Exception{
            file=root.resolve(name+"-restarted-root.jsonl");channel=FileChannel.open(file,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE);completed.add(completedOriginal);lineage=new NativeJobLineage(this::append);boards=new NativeBoardLoads(this::append);material=new NativeMaterialLoads(config,this::append);replacement=new NativeFaultedJobReplacement(config,material,boards,lineage,this::append,operation->{checked.add(operation);return completed.contains(operation);});
            for(Map<String,Object> event:original){String type=(String)event.get("type");Map<String,Object> p=o(event.get("payload"));Runnable common=replacement.prepareContinuationObservation(type,p);material.recoverEvent(type,p);boards.recoverEvent(type,p);boards.observeNativeEvent(type,p);lineage.observe(type,p);replacement.observe(type,p);if(type.startsWith("faulted_job_replacement_"))replacement.recover(type,p);common.run();events.add(event);}sequence=events.size();material.finishRecovery();boards.finishRecovery();
        }
        void append(String type,Map<String,Object> p)throws Exception{
            Runnable mat=material==null?()->{}:material.prepareEvent(type,p),lin=lineage==null||type.startsWith("job_lineage_")?()->{}:lineage.prepareObservation(type,p),common=replacement==null?()->{}:replacement.prepareContinuationObservation(type,p);
            Map<String,Object> event=NativeFaultedJobReplacement.frozen(m("sequence",++sequence,"type",type,"payload",p));ByteBuffer buffer=ByteBuffer.wrap((JSON.toJson(event)+"\n").getBytes(StandardCharsets.UTF_8));while(buffer.hasRemaining())channel.write(buffer);channel.force(true);events.add(event);mat.run();lin.run();common.run();if(boards!=null)boards.observeNativeEvent(type,p);if(replacement!=null)replacement.observe(type,p);
        }
        public void close()throws Exception{try{replacement.close();}finally{channel.close();}}
    }
    static Map<String,Object> operation(String id,String taskId,String digest,String request){return m("operation_id",id,"request_id",NativeReplacementContinuationTest.id(),"request_digest",digest,"bridge_instance_id",NativeRestartSensingTaskTest.INSTANCE,"config_revision","cfg-2","method","local_native_sensing_reconciliation","task_id",taskId,"reconciliation_request_id",request,"state","running");}
    static Map<String,Object> runCase(String name,boolean closeRestart,boolean restartCompleted,boolean originalCompleted)throws Exception{
        try(Env original=new Env(name+"-original-root",false)){
            NativeReplacementAtomicAdmissionTest.Decision first=task(()->new NativeReplacementAtomicAdmissionTest.Decision(original));original.permit=task(()->first.begin(original.candidate));task(()->{original.replacement.retainCandidate(original.permit,original.candidate);return null;});String attempt=original.permit.attemptId();
            Map<String,Object> terminal=null;for(Map<String,Object> e:original.events)if("operation".equals(e.get("type"))&&first.operation.equals(o(e.get("payload")).get("operation_id")))terminal=NativeFaultedJobReplacement.mutable(o(e.get("payload")));check(terminal!=null,"Original actual admitted operation found");terminal.put("state","outcome_unknown");if(originalCompleted)terminal.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));original.append("operation",terminal);original.permit.close();original.append("sensing_reconciliation_unknown",original.coordinator.unknownRecord(original.taskId,"wrapper_unknown"));
            List<Map<String,Object>> exact=new ArrayList<>();for(String line:Files.readAllLines(original.file))exact.add(NativeJournalJson.parseObject(line));check(NativeFaultedJobReplacement.same(exact,original.events),"Fresh root consumes exact forced original journal");
            try(RootEnv current=new RootEnv(name,exact,originalCompleted?first.operation:null);NativeRestartSensingTaskTest.Journal decision=new NativeRestartSensingTaskTest.Journal(name+"-fresh-restart-decision")){
                var stage=task(()->current.replacement.stageRestart(attempt));var restart=task(()->current.replacement.captureRestart(stage));decision.fault(restart);decision.admit();current.append("operation",operation(decision.operation,decision.taskId,decision.capture.digest,(String)decision.record.get("request_id")));var permit=task(()->current.replacement.beginRestart(restart,decision.coordinator,decision.permit,decision.owner));task(()->{permit.check();return null;});check(!current.completed.contains(decision.operation),"Current restart callback is running and has no terminal wrapper witness");if(closeRestart)permit.close();
                if(restartCompleted){Map<String,Object> restartTerminal=null;for(Map<String,Object> event:current.events)if("operation".equals(event.get("type"))&&decision.operation.equals(o(event.get("payload")).get("operation_id")))restartTerminal=NativeFaultedJobReplacement.mutable(o(event.get("payload")));if(restartTerminal==null)throw new AssertionError("Restart admission missing");restartTerminal.put("state","outcome_unknown");restartTerminal.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));current.append("operation",restartTerminal);current.completed.add(decision.operation);decision.append("sensing_reconciliation_unknown",decision.coordinator.unknownRecord(decision.taskId,"wrapper_unknown"));}
                Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();NativeFaultedJobReplacement.ContinuationCapture continuation=null;Exception refused=null;
                try{continuation=task(()->current.replacement.captureContinuation(attempt,permit.original()));}catch(java.io.IOException|Bridge.Fault|NativeJobLineage.Fault expected){refused=expected;}
                Map<String,Object> result=m("case",name,"restart_permit_closed",closeRestart,"restart_wrapper_completed",restartCompleted,"original_wrapper_completed",originalCompleted,"expected_capture",restartCompleted&&originalCompleted,"capture_refused",refused!=null,"refusal",refused==null?null:refused.toString(),"original_completed_operation",first.operation,"running_restart_operation",decision.operation,"terminal_authority_consulted",new TreeSet<>(current.checked),"continuation_permit_issued",false,"restart_operation_captured",null);
                if(continuation!=null){
                    result.put("continuation_capture",continuation.payload);result.put("restart_operation_captured",((List<?>)continuation.dependencies().get("operation_ids")).contains(decision.operation));
                    var captured=continuation;Map<String,Object> scope=NativeSensingReconciliationTest.scope(decision.instanceId,NativeSensingReconciliationTest.SOURCE);scope.put("dependencies",captured.dependencies());scope.put("job_context",captured.jobContext());var sensing=decision.vacuum.captureFaultSet(scope);String taskId=id(),newOperation=id();Object newOwner=new Object();Map<String,Object> row=decision.coordinator.taskRecordForContinuation(taskId,id(),id(),sensing,captured,3,"2030-01-01T00:00:00Z");decision.append("sensing_reconciliation_task",row);decision.append("sensing_reconciliation_intent",decision.coordinator.intentRecord(taskId,newOperation,id(),"2026-09-14T00:00:00Z",3,"synthetic-independent-continuation"));var recovery=decision.coordinator.issuePermit(taskId,newOperation,sensing.digest,newOwner);current.append("operation",operation(newOperation,taskId,sensing.digest,(String)row.get("request_id")));
                    try{var live=task(()->current.replacement.beginContinuation(captured,decision.coordinator,recovery,newOwner));task(()->{live.check();return null;});result.put("continuation_permit_issued",true);live.close();}catch(java.io.IOException|Bridge.Fault|NativeJobLineage.Fault expected){result.put("begin_refusal",expected.toString());}
                }
                check(counts.equals(counters())&&files.equals(configurationFiles()),"Review probe performs no native inventory or configuration mutation");result.put("root_status",current.replacement.status());return result;
            }
        }
    }
    public static void main(String[] args)throws Exception{
        initialize(Path.of(args[0]));List<Map<String,Object>> observation=new ArrayList<>();Throwable error=null;int exit=0;try{observation.add(runCase("live-restart",false,false,true));observation.add(runCase("closed-restart",true,false,true));observation.add(runCase("completed-restart",true,true,true));observation.add(runCase("original-wrapper-missing",true,true,false));for(Map<String,Object> result:observation){if(Boolean.TRUE.equals(result.get("expected_capture"))){if(Boolean.TRUE.equals(result.get("capture_refused"))||!Boolean.TRUE.equals(result.get("continuation_permit_issued"))||!Boolean.TRUE.equals(result.get("restart_operation_captured")))exit=1;}else if(!Boolean.TRUE.equals(result.get("capture_refused")))exit=1;}}catch(Throwable failure){failure.printStackTrace();error=failure;exit=1;}finally{config.getMachine().close();Map<String,Object> proof=m("passed",exit==0,"checks",checks,"observation",observation,"error",error==null?null:error.toString(),"pid",ProcessHandle.current().pid(),"native_job_initializations",0,"native_feeds",0,"native_placements",0,"scope","Actual native reconstruction, root restart/continuation permits and forced journals; synthetic initial fault and explicit original-only terminal authority; no Bridge execution");Files.writeString(root.resolve("proof.json"),JSON.toJson(proof)+"\n");System.out.println("NATIVE_RESTART_CONTINUATION_SCOPE "+JSON.toJson(proof));}System.exit(exit);
    }
}
