/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import com.google.gson.*;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import org.openpnp.model.*;
import org.openpnp.spi.*;
import static org.openpnp.codex.NativePlacementEditsTest.*;

/** Owned fresh native models and real fsynced reservation files. The test caller owns lineage
 * because it creates these Jobs and never dispatches native processing. This is NOT a proof
 * supplied by the current Bridge and is NOT a public authority or replay implementation. */
public final class NativePlacementStructureTest {
    static final Gson JSON=new Gson();static int assertions,enabledEvents,homeEvents,headEvents;static Path evidence;
    static final List<String> groups=new ArrayList<>();
    static void verify(boolean b,String m){assertions++;if(!b)throw new AssertionError(m);}
    interface Checked{void run()throws Exception;}
    static void fault(String code,Checked f)throws Exception{try{f.run();throw new AssertionError("Expected "+code);}catch(NativePlacementEdits.Fault e){verify(code.equals(e.code),code+" != "+e.code+": "+e.getMessage());}}
    static String hash(Path p)throws Exception{return Hex.sha(Files.readAllBytes(p));}
    static final class Hex {static String sha(byte[] bytes)throws Exception{StringBuilder b=new StringBuilder();for(byte x:java.security.MessageDigest.getInstance("SHA-256").digest(bytes))b.append(String.format("%02x",x));return b.toString();}}
    static JsonObject added(String scope,String holder,String id){return object("action","add","scope",scope,"holder_instance_id",holder,"placement_id",id,"placement",object("location",local(4,6,0.3,-30),"side","Bottom","type","Placement","part_id",part.getId(),"enabled",false,"error_handling","Defer","comments","created native record","rank",9));}
    static JsonObject removed(String scope,String holder,String id){return object("action","remove","scope",scope,"holder_instance_id",holder,"placement_id",id);}

    /** Minimal trusted CALLER fixture, not production integration. Native load state is real;
     * admission-history/lineage ownership is known only from this closed test's lifecycle. */
    static final class Guard implements NativePlacementEdits.StructureAuthority,NativePlacementEdits.StructurePublicationFence {
        final Configuration ownedConfig=config;Job ownedJob;final Path file;final String lineage;long revision=1;final Set<String> ids=new TreeSet<>();String pending;
        final NativeBoardLoads loads;boolean observedAdmission,revoked,faulted,failAfterForce,failBeforeForce,failFence,alterDuringFence;int forceCount,fenceCount;final List<String> order=new ArrayList<>();
        Guard(Job job,String label)throws Exception{ownedJob=job;file=evidence.resolve(label+"-reservations.jsonl");lineage="lineage-"+label;Path journal=evidence.resolve(label+"-loads.jsonl");loads=new NativeBoardLoads((type,payload)->force(journal,JSON.toJson(Bridge.map("type",type,"payload",payload))));loads.bindJob(job,lineage,true);}
        NativePlacementEdits.StructureState state()throws Exception{return new NativePlacementEdits.StructureState(lineage,revision,ids);}
        public NativePlacementEdits.StructureState requireUnexecuted(Configuration c,Job job)throws Exception{return checked(c,job,null);}
        NativePlacementEdits.StructureState checked(Configuration c,Job job,String ownPending)throws Exception{
            if(c!=ownedConfig||job!=ownedJob||observedAdmission||revoked||faulted||(pending!=null&&!Objects.equals(pending,ownPending)))throw new NativePlacementEdits.Fault("STRUCTURE_LINEAGE_UNPROVEN","Caller cannot prove exact unexecuted lineage");
            Map<String,Object> snapshot=loads.snapshot();if(!Objects.equals(snapshot.get("job_id"),lineage)||((Number)snapshot.get("pending_changes")).intValue()!=0)throw new NativePlacementEdits.Fault("STRUCTURE_LINEAGE_UNPROVEN","Native load evidence absent or unknown");
            for(Object raw:(List<?>)snapshot.get("loads")){Map<?,?> load=(Map<?,?>)raw;if(((Number)load.get("native_history_entries")).intValue()!=0||"loading_unknown".equals(load.get("state")))throw new NativePlacementEdits.Fault("STRUCTURE_LINEAGE_UNPROVEN","Current or retired load contains history");}
            return state();
        }
        public void reserveAndForce(NativePlacementEdits.StructureState expected,JsonObject reservation)throws Exception{
            verify(state().same(expected),"Reservation uses exact expected lineage revision");
            if(failBeforeForce){faulted=true;throw new java.io.IOException("injected storage refusal before force");}
            force(file,reservation.toString());forceCount++;pending=reservation.get("transaction_id").getAsString();order.add("forced");for(JsonElement id:reservation.getAsJsonArray("logical_ids"))ids.add(id.getAsString());revision++;
            if(failAfterForce){faulted=true;throw new java.io.IOException("injected lost receipt after actual force");}
        }
        public void invalidateBeforePublication(Job job,List<String> roots)throws Exception{
            verify(forceCount>0&&order.get(order.size()-1).equals("forced"),"Forced reservation precedes invalidation");fenceCount++;order.add("invalidated");
            if(failFence){faulted=true;throw new java.io.IOException("injected validation-fence failure");}
            loads.invalidateRegistration("cfg-1","private-structure-edit");NativeBoardLoads.invalidateTransforms(job);if(alterDuringFence)placement(job,"solo","R1").getDefinition().setComments("unexpected listener mutation");
        }
        NativePlacementEdits.StructureAuthority adapter(){return new NativePlacementEdits.StructureAuthority(){String token;public NativePlacementEdits.StructureState requireUnexecuted(Configuration c,Job j)throws Exception{return checked(c,j,token);}public void reserveAndForce(NativePlacementEdits.StructureState expected,JsonObject reservation)throws Exception{token=reservation.get("transaction_id").getAsString();Guard.this.reserveAndForce(expected,reservation);}};}
        void changed()throws Exception{loads.jobChanged(ownedJob,lineage);verify(pending!=null,"Caller records success only for an outstanding publication");force(file,JSON.toJson(Bridge.map("kind","placement-structure-outcome-v1","transaction_id",pending,"lineage_id",lineage,"result_fingerprint",NativePlacementEdits.inspect(config,ownedJob,0,1).get("source_fingerprint"))));order.add("completed");pending=null;}
        void adoptReload(Job reloaded)throws Exception{ownedJob=reloaded;loads.jobChanged(reloaded,lineage);}
        void verifyDisk()throws Exception{Set<String> disk=new TreeSet<>();long rev=1;String diskPending=null;for(String line:Files.readAllLines(file)){JsonObject row=new JsonParser().parse(line).getAsJsonObject();verify(row.get("lineage_id").getAsString().equals(lineage),"Durable stable lineage ID");if(row.get("kind").getAsString().equals("placement-structure-reservation-v1")){verify(diskPending==null,"No new reservation can bypass unresolved prior publication");verify(row.get("expected_lineage_revision").getAsLong()==rev++,"Durable monotonic revision");diskPending=row.get("transaction_id").getAsString();for(JsonElement id:row.getAsJsonArray("logical_ids"))disk.add(id.getAsString());}else{verify(Objects.equals(diskPending,row.get("transaction_id").getAsString()),"Publication outcome binds the outstanding reservation");verify(row.get("result_fingerprint").getAsString().matches("[a-f0-9]{64}"),"Publication outcome binds resulting native graph");diskPending=null;}}verify(ids.equals(disk)&&revision==rev&&Objects.equals(diskPending,pending),"Reserved IDs and pending disposition survive independent file reconstruction");}
    }
    static void force(Path p,String data)throws Exception{try(FileChannel channel=FileChannel.open(p,StandardOpenOption.CREATE,StandardOpenOption.WRITE,StandardOpenOption.APPEND)){ByteBuffer b=StandardCharsets.UTF_8.encode(data+"\n");while(b.hasRemaining())channel.write(b);channel.force(true);}}
    static NativePlacementEdits.StructurePatch stage(Job job,Guard guard,JsonObject...changes)throws Exception{return NativePlacementEdits.stageStructure(config,job,rows(changes),guard.adapter(),guard);}
    static void shared()throws Exception {
        Job job=fixture(true);Guard g=new Guard(job,"shared");Board source=board(job,"solo").getBoard().getDefinition();Path sourceFile=evidence.resolve("source-board.xml");Configuration.createSerializer().write(source,sourceFile.toFile());source.setFile(sourceFile.toFile());String sourceHash=hash(sourceFile);
        Job otherJob=new Job();otherJob.addBoardOrPanelLocation(boardLocation(source,"outside",org.openpnp.model.Abstract2DLocatable.Side.Top,pose(0,0,0,0)));Map<String,Object> outside=snapshot(otherJob),before=snapshot(job);List<BoardLocation> originals=new ArrayList<>(job.getBoardLocations());AtomicInteger originalEvents=new AtomicInteger();source.addPropertyChangeListener(e->originalEvents.incrementAndGet());
        NativePlacementEdits.StructurePatch p=stage(job,g,added("job_shared_definition","solo","NEW1"));verify(snapshot(job).equals(before)&&g.forceCount==0&&originalEvents.get()==0,"Staging has no source model/journal effects");verify(p.preview().getAsJsonArray("changes").get(0).getAsJsonObject().getAsJsonArray("affected").size()==5,"All shared native occurrences previewed");
        Map<String,Object> loadsBefore=g.loads.snapshot();p.apply();g.changed();for(BoardLocation b:job.getBoardLocations()){Placement n=b.getBoard().getPlacements().get("NEW1");verify(n!=null&&n.getPart()==part&&!n.isEnabled()&&n.getRank()==9&&n.getErrorHandling()==Placement.ErrorHandling.Defer,"Complete created scalar fields on every shared instance");near(n.getLocation().getX(),4,"created X");verify(n.getSide()==org.openpnp.model.Abstract2DLocatable.Side.Bottom,"Explicit opposite side preserved");}
        verify(source.getPlacements().get("NEW1")==null&&snapshot(otherJob).equals(outside)&&hash(sourceFile).equals(sourceHash)&&originalEvents.get()==0,"Source definition/file/outside job untouched");
        for(BoardLocation b:originals){Placement old=b.getBoard().getPlacements().get("R1");verify(!old.getDefinition().isListener(old)&&!old.isListener(job),"Old placement definition/job subscriptions retired after commit");}
        verify(job.getPlacedStatusSnapshot().isEmpty(),"No placed-status entries synthesized");verify(((List<?>)loadsBefore.get("loads")).size()==((List<?>)g.loads.snapshot().get("loads")).size(),"Prior native load inventory retained");
        List<?> oldLoads=(List<?>)loadsBefore.get("loads"),newLoads=(List<?>)g.loads.snapshot().get("loads");for(int i=0;i<oldLoads.size();i++)verify(((Map<?,?>)oldLoads.get(i)).get("load_id").equals(((Map<?,?>)newLoads.get(i)).get("load_id")),"Existing native load IDs preserved");
        Job reloaded=roundTrip(job);verify(snapshot(job).equals(snapshot(reloaded)),"Created shared records round-trip through actual native job documents");g.adoptReload(reloaded);g.verifyDisk();fault("STRUCTURE_ID_REUSED",()->stage(reloaded,g,added("job_instance","solo","NEW1")));groups.add("shared-create-native-documents-source-and-load-preservation");
    }
    static void instanceAndRetirement()throws Exception {
        Job job=fixture(true);board(job,"P2⇒nested⇒A").getParent().setLocallyEnabled(false);Guard g=new Guard(job,"instance");Placement source=placement(job,"P1⇒nested⇒A","R2");Map<String,Object> before=snapshot(job);
        stage(job,g,removed("job_instance","P1⇒nested⇒A","R2"),added("job_instance","P1⇒nested⇒A","R3")).apply();g.changed();verify(placement(job,"P1⇒nested⇒A","R2")==null&&placement(job,"P1⇒nested⇒A","R3")!=null,"One exact nested instance gains/loses membership");verify(placement(job,"P2⇒nested⇒A","R2")!=null&&placement(job,"solo","R2")!=null,"Shared siblings retain removed reference");verify(!board(job,"P2⇒nested⇒A").isEnabled(),"Unrelated X-out retained");verify(board(job,"P1⇒nested⇒A").getBoard().getDefinition()!=board(job,"P2⇒nested⇒A").getBoard().getDefinition(),"Required native branch specializes definitions");
        Panel p1=(Panel)board(job,"P1⇒nested⇒A").getParent().getPlacementsHolder();near(p1.getPseudoPlacement(0).getLocation().getX(),11,"Unmodified native pseudo golden X");near(p1.getPseudoPlacement(0).getLocation().getY(),1,"Unmodified native pseudo golden Y");verify(source.getDefinition()!=null&&!source.getDefinition().isListener(source),"Removed old instance subscription retired");
        fault("STRUCTURE_ID_REUSED",()->stage(job,g,added("job_instance","P1⇒nested⇒A","R2")));stage(job,g,removed("job_instance","P1⇒nested⇒A","R3")).apply();g.changed();fault("STRUCTURE_ID_REUSED",()->stage(job,g,added("job_instance","P1⇒nested⇒A","R3")));g.verifyDisk();Job loaded=roundTrip(job);verify(snapshot(job).equals(snapshot(loaded)),"Instance membership/pseudo/X-out survives native round-trip");g.adoptReload(loaded);fault("STRUCTURE_ID_REUSED",()->stage(loaded,g,added("job_instance","P1⇒nested⇒A","R3")));groups.add("instance-removal-specialization-pseudo-and-retired-id-refusal");
    }
    static void extraMembership()throws Exception {
        Job job=fixture(false);Guard g=new Guard(job,"shared-remove");stage(job,g,removed("job_shared_definition","solo","R2")).apply();g.changed();for(BoardLocation b:job.getBoardLocations())verify(b.getBoard().getPlacements().get("R2")==null,"Shared removal reaches every native instance");verify(snapshot(job).equals(snapshot(roundTrip(job))),"Shared removal survives native documents");
        Board empty=new Board();empty.setDimensions(pose(10,10,0,0));Job e=new Job();e.addBoardOrPanelLocation(boardLocation(empty,"empty",org.openpnp.model.Abstract2DLocatable.Side.Top,pose(0,0,0,0)));Guard eg=new Guard(e,"empty-fiducial");JsonObject fid=added("job_instance","empty","FRESHFID");fid.getAsJsonObject("placement").addProperty("type","Fiducial");stage(e,eg,fid).apply();eg.changed();verify(placement(e,"empty","FRESHFID").getType()==Placement.Type.Fiducial,"Empty-board creation preserves explicit native Fiducial type");verify(snapshot(e).equals(snapshot(roundTrip(e))),"Fresh fiducial membership persists");groups.add("shared-remove-and-empty-board-fiducial-create");
    }
    static void historyAndScopes()throws Exception {
        Job job=fixture(true);Guard g=new Guard(job,"history");fault("STRUCTURE_PSEUDO_DEPENDENCY",()->stage(job,g,removed("job_instance","P1⇒nested⇒A","FID")));fault("STRUCTURE_PSEUDO_DEPENDENCY",()->stage(job,g,removed("job_shared_definition","solo","FID")));fault("STRUCTURE_BOARD_ONLY",()->stage(job,g,added("job_instance","P1","PANELFID")));JsonObject rename=removed("job_instance","solo","R1");rename.addProperty("action","rename");fault("STRUCTURE_ACTION",()->stage(job,g,rename));
        job.storePlacedStatus(board(job,"solo"),"OLD_ORPHAN",false);fault("STRUCTURE_HISTORY_PRESENT",()->stage(job,g,added("job_instance","solo","A1")));job.removePlacedStatus(board(job,"solo"),"OLD_ORPHAN");
        NativePlacementEdits.StructurePatch stale=stage(job,g,added("job_instance","solo","A1"));job.storePlacedStatus(board(job,"solo"),"OLD_ORPHAN",true);fault("STRUCTURE_HISTORY_PRESENT",stale::apply);verify(g.forceCount==0,"Late opaque native history rejects before reservation/publication");job.removePlacedStatus(board(job,"solo"),"OLD_ORPHAN");
        g.observedAdmission=true;fault("STRUCTURE_LINEAGE_UNPROVEN",()->stage(job,g,added("job_instance","solo","A1")));g.observedAdmission=false;fault("STRUCTURE_LINEAGE_REQUIRED",()->NativePlacementEdits.stageStructure(config,job,rows(added("job_instance","solo","A1")),null,g));
        job.storePlacedStatus(board(job,"solo"),"OPAQUE_RETIRED",true);g.loads.checkpoint(job);Map<?,?> root=(Map<?,?>)((List<?>)g.loads.snapshot().get("roots")).get(0);g.loads.change(job,"solo","replace","bottom",(String)root.get("load_id"),g.loads.revision(),false);verify(job.getPlacedStatusSnapshot().isEmpty(),"Actual simulator replacement cleared current opaque history");fault("STRUCTURE_LINEAGE_UNPROVEN",()->stage(job,g,added("job_instance","solo","A1")));verify(((List<?>)g.loads.snapshot().get("loads")).size()==4,"Retired historical load remains present");groups.add("no-current-false-orphan-retired-or-unproven-history-and-no-pseudo-removal");
    }
    static void staleAndLimits()throws Exception {
        Job job=fixture(false);Guard g=new Guard(job,"stale");NativePlacementEdits.StructurePatch p=stage(job,g,added("job_instance","solo","R9"));placement(job,"solo","R1").getDefinition().setRank(99);fault("STALE_PLACEMENT_PLAN",p::apply);fault("PLAN_CONSUMED",p::apply);verify(g.forceCount==0,"Stale semantic fingerprint consumes attempt without reservation");
        Job job2=fixture(false);Guard g2=new Guard(job2,"stale-authority");NativePlacementEdits.StructurePatch p2=stage(job2,g2,added("job_instance","solo","R9"));g2.revision++;fault("STRUCTURE_LINEAGE_STALE",p2::apply);
        Job job3=fixture(false);Guard g3=new Guard(job3,"stale-part");NativePlacementEdits.StructurePatch p3=stage(job3,g3,added("job_instance","solo","R9"));Part original=part;Part replacement=new Part(part.getId());replacement.setPackage(part.getPackage());config.addPart(replacement);fault("PART_IDENTITY",p3::apply);config.addPart(original);
        fault("OVERLAPPING_EDITS",()->stage(job2,g2,added("job_shared_definition","solo","DUP"),added("job_instance","P1⇒nested⇒A","DUP")));JsonObject bad=added("job_instance","solo","BAD");bad.getAsJsonObject("placement").remove("rank");fault("STRUCTURE_FIELDS",()->stage(job2,g2,bad));fault("INVALID_ID",()->stage(job2,g2,added("job_instance","solo","unsafe⇒id")));
        Board huge=new Board();for(int i=0;i<10000;i++)huge.addPlacement(placement("R"+i,0,0));Job large=new Job();large.addBoardOrPanelLocation(boardLocation(huge,"large",org.openpnp.model.Abstract2DLocatable.Side.Top,pose(0,0,0,0)));Guard lg=new Guard(large,"limit");fault("GRAPH_LIMIT",()->stage(large,lg,added("job_instance","large","OVER")));verify(lg.forceCount==0,"Expanded limit rejects before native copy or reservation");Board small=new Board();small.addPlacement(placement("R0",0,0));Job budget=new Job();for(int i=0;i<100;i++)budget.addBoardOrPanelLocation(boardLocation(small,"B"+i,org.openpnp.model.Abstract2DLocatable.Side.Top,pose(0,0,0,0)));Guard bg=new Guard(budget,"preview-budget");JsonObject[] additions=new JsonObject[90];for(int i=0;i<90;i++){additions[i]=added("job_shared_definition","B0","NEW"+i);additions[i].getAsJsonObject("placement").addProperty("comments",String.join("",Collections.nCopies(2048,"x")));}fault("STRUCTURE_PREVIEW_LIMIT",()->stage(budget,bg,additions));verify(bg.forceCount==0&&placement(budget,"B0","NEW0")==null,"Oversized complete preview refuses without truncation or publication");groups.add("stale-graph-authority-part-overlap-fields-expanded-and-preview-capacity");
    }
    static void failures()throws Exception {
        Job job=fixture(false);Guard g=new Guard(job,"rollback");List<PlacementsHolderLocation<?>> originals=new ArrayList<>(job.getRootPanelLocation().getChildren());AtomicBoolean first=new AtomicBoolean(true);java.beans.PropertyChangeListener listener=e->{if(e.getPropertyName().equals("children")){verify(g.order.equals(Arrays.asList("forced","invalidated")),"Native root publication follows durable reservation and fence");if(first.getAndSet(false))throw new IllegalStateException("injected native listener failure");}};job.getRootPanelLocation().getPanel().addPropertyChangeListener(listener);
        NativePlacementEdits.StructurePatch plan=stage(job,g,added("job_instance","solo","FAIL"));fault("PLACEMENT_COMMIT_FAILED",plan::apply);verify(job.getRootPanelLocation().getChildren().equals(originals),"Actual native root restored after setter listener throws");Placement old=placement(job,"solo","R1");verify(old.getDefinition().isListener(old),"Rollback keeps original definition subscriptions");verify(placement(job,"solo","FAIL")==null&&g.ids.contains("solo⇒FAIL"),"Failed publication retains tombstone without adding record");job.getRootPanelLocation().getPanel().removePropertyChangeListener(listener);fault("STRUCTURE_LINEAGE_UNPROVEN",()->stage(job,g,added("job_instance","solo","FAIL")));g.verifyDisk();
        Job a=fixture(false);Guard ga=new Guard(a,"after-force");ga.failAfterForce=true;fault("STRUCTURE_RESERVATION_UNCERTAIN",()->stage(a,ga,added("job_instance","solo","LATE")).apply());verify(ga.forceCount==1&&ga.fenceCount==0&&placement(a,"solo","LATE")==null,"Lost reservation receipt fences before invalidation/root setter");verify(Files.size(ga.file)>0&&ga.ids.contains("solo⇒LATE"),"Actually forced record retained after uncertain receipt");fault("STRUCTURE_LINEAGE_UNPROVEN",()->stage(a,ga,added("job_instance","solo","LATE")));
        Job b=fixture(false);Guard gb=new Guard(b,"before-force");gb.failBeforeForce=true;fault("STRUCTURE_RESERVATION_UNCERTAIN",()->stage(b,gb,added("job_instance","solo","EARLY")).apply());verify(!Files.exists(gb.file)&&gb.fenceCount==0&&placement(b,"solo","EARLY")==null,"Pre-force storage refusal publishes nothing and invokes no fence");
        Job c=fixture(false);Guard gc=new Guard(c,"fence");gc.failFence=true;fault("STRUCTURE_FENCE_FAILED",()->stage(c,gc,added("job_instance","solo","FENCE")).apply());verify(gc.forceCount==1&&placement(c,"solo","FENCE")==null&&gc.ids.contains("solo⇒FENCE"),"Invalidation failure keeps reservation and no root publication");Job d=fixture(false);Guard gd=new Guard(d,"fence-drift");gd.alterDuringFence=true;fault("STRUCTURE_FENCE_FAILED",()->stage(d,gd,added("job_instance","solo","DRIFT")).apply());verify(placement(d,"solo","DRIFT")==null&&gd.ids.contains("solo⇒DRIFT"),"Unexpected invalidation-time native mutation fences before publication with spent IDs");groups.add("forced-reservation-listener-rollback-and-fence-failure-no-replay");
    }
    public static void main(String[] args)throws Exception {
        evidence=Files.createTempDirectory("native-placement-structure-");Files.createDirectories(evidence);temp=evidence.resolve("configuration");Files.createDirectory(temp);Configuration.initialize(temp.toFile());config=Configuration.get();config.load();part=config.getParts().get(0);other=config.getParts().get(1);Machine machine=config.getMachine();machine.addListener(new MachineListener.Adapter(){public void machineEnabled(Machine m){enabledEvents++;}public void machineHomed(Machine m,boolean h){if(h)homeEvents++;}public void machineHeadActivity(Machine m,Head h){headEvents++;}});
        int exit=0;try{shared();instanceAndRetirement();extraMembership();historyAndScopes();staleAndLimits();failures();verify(!machine.isEnabled()&&!machine.isHomed()&&enabledEvents==0&&homeEvents==0&&headEvents==0,"No enable/home/head activity occurred");System.out.println("PLACEMENT_STRUCTURE_PROTOTYPE "+JSON.toJson(Bridge.map("passed",true,"groups",groups,"assertions",assertions,"native_enable_events",enabledEvents,"native_home_events",homeEvents,"native_head_events",headEvents,"job_processor_called",false,"hardware_qualified",false,"current_bridge_lineage_support",false,"guard_scope","trusted caller fixture only; no public unexecuted flag")));}catch(Throwable failure){failure.printStackTrace();exit=1;}finally{machine.close();}System.exit(exit);
    }
}
