/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.openpnp.model.*;
import static org.openpnp.codex.NativePortableConfiguration.*;

/** Native model/export and pre-deserialization resource admission; never enables a machine. */
public final class NativePortableBoardLibraryTest {
 static int checks;static Path root;static Configuration c;
 interface Task{void run()throws Exception;}
 static void check(boolean v,String s){checks++;if(!v)throw new AssertionError(s);}
 static void rejects(String label,Task t)throws Exception {try{t.run();throw new AssertionError("Accepted "+label);}catch(Bridge.Fault expected){check(true,label+" "+expected.code);}}
 static Board board(String name)throws Exception {Board b=c.getBoard(root.resolve(name+".board.xml").toFile());b.setName("saved board");b.setDimensions(new Location(LengthUnit.Millimeters,20,10,0,0));Placement p=new Placement("R1");p.setPart(c.getParts().get(0));p.setSide(Abstract2DLocatable.Side.Top);p.setLocation(new Location(LengthUnit.Millimeters,2,3,0,90));b.addPlacement(p);Pad.RoundRectangle shape=new Pad.RoundRectangle();shape.setUnits(LengthUnit.Inches);shape.setWidth(0.05);shape.setHeight(0.04);shape.setRoundness(0.375);BoardPad pad=new BoardPad(shape,new Location(LengthUnit.Inches,0.1,0.2,0,25));pad.setName("R1-1");pad.setSide(Abstract2DLocatable.Side.Bottom);pad.setType(BoardPad.Type.Ignore);b.addSolderPastePad(pad);c.saveBoard(b);c.save();return b;}
 static void admissionReject(Map<String,byte[]> entries,String label)throws Exception {
  Map<String,byte[]> copy=new TreeMap<>(entries);JsonObject m=object(copy.get("manifest.json"));Map<String,String> hashes=hashes(copy);hashes.remove("manifest.json");m.add("entry_sha256",JSON.toJsonTree(hashes));for(String name:CONFIG)m.getAsJsonObject("native_xml_semantic_sha256").addProperty(name,semantic(xml(copy.get("config/"+name))));copy.put("manifest.json",JSON.toJson(m).getBytes(StandardCharsets.UTF_8));byte[] bytes=zip(copy);Path archive=root.resolve("bad-"+UUID.randomUUID()+".zip"),destination=root.resolve("refused-"+UUID.randomUUID());Files.write(archive,bytes);rejects(label,()->prepare(archive,sha(bytes),destination));check(!Files.exists(destination),label+" refused before reservation/native initialization");
 }
 static void rawAdmissionReject(Map<String,byte[]> entries,byte[] manifest,String label)throws Exception {
  Map<String,byte[]> copy=new TreeMap<>(entries);copy.put("manifest.json",manifest);byte[] bytes=zip(copy);Path archive=root.resolve("bad-raw-"+UUID.randomUUID()+".zip"),destination=root.resolve("refused-raw-"+UUID.randomUUID());Files.write(archive,bytes);boolean refused=false;try{prepare(archive,sha(bytes),destination);}catch(Exception expected){refused=true;}check(refused&&!Files.exists(destination),label+" refused before destination/native initialization");
 }
 public static void main(String[] args)throws Exception {
  if(args.length==2&&args[0].equals("native-roundtrip")){
   Path archive=Path.of(args[1]);Prepared prepared=prepare(archive,sha(read(archive,MAX_BUNDLE)),archive.getParent().resolve("native-roundtrip"));Map<String,Object> result=validateAndPublish(prepared);Configuration loaded=Configuration.get();check(((Number)((Map<?,?>)result.get("board_library")).get("paste_pad_count")).intValue()==2,"native adoption receipt retains both pad definitions");check(loaded.getBoards().size()==2&&loaded.getBoards().get(0)!=loaded.getBoards().get(1),"native adoption retains byte-identical distinct board identities");for(Board board:loaded.getBoards()){BoardPad pad=board.getSolderPastePads().get(0);Pad.RoundRectangle shape=(Pad.RoundRectangle)pad.getPad();check(shape.getUnits()==LengthUnit.Inches&&shape.getRoundness()==0.375&&shape.getWidth()==0.05&&shape.getHeight()==0.04,"native roundtrip retains inch geometry and nonzero roundness exactly");check(pad.getType()==BoardPad.Type.Ignore&&pad.getSide()==Abstract2DLocatable.Side.Bottom&&pad.getName().equals("R1-1")&&pad.getLocation().getUnits()==LengthUnit.Inches&&pad.getLocation().getRotation()==25,"native pad identity/type/side/location preserved");}
   Path config=activeConfiguration(prepared.destination);check(config.equals(prepared.staging.resolve("config")),"closed activation reads valid library");Path board=loaded.getBoards().get(0).getFile().toPath();byte[] original=read(board,MAX_FILE);Files.write(board,new byte[]{'\n'},StandardOpenOption.APPEND);rejects("activated board file mutation",()->activeConfiguration(prepared.destination));Files.write(board,original);check(activeConfiguration(prepared.destination).equals(config),"exact original board bytes restore read-only test fixture validity");check(!loaded.getMachine().isEnabled()&&!loaded.getMachine().isHomed(),"native adoption never enables or homes machine");System.out.println("OPENPNP_PORTABLE_NATIVE_ROUNDTRIP "+JSON.toJson(Bridge.map("checks",checks,"boards",2,"paste_pads",2,"physical_qualification",false)));System.exit(0);return;
  }
  if(args.length==2&&args[0].equals("native-skip")){
   Path stage=Path.of(args[1]);JsonObject manifest=object(read(stage.resolve("manifest.json"),256*1024));String entry=NativePortableBoardLibrary.records(manifest).get(0).get("entry").getAsString();Files.delete(stage.resolve(entry));Configuration.initialize(stage.resolve("config").toFile());Configuration loaded=Configuration.get();try(var constraint=loaded.getScripting().constrainExecution(file->{throw new IllegalStateException("scripts disabled");})){
    loaded.load();check(loaded.getBoards().size()==1,"actual native loader skips missing library resource");rejects("post-native-load completeness",()->NativePortableBoardLibrary.verifyLoaded(loaded,manifest,stage));check(!Files.exists(stage.getParent().resolve("adoption.json")),"skipped native load has no activation");check(!loaded.getMachine().isEnabled()&&!loaded.getMachine().isHomed(),"skipped native load acquires no machine authority");System.out.println("OPENPNP_PORTABLE_NATIVE_SKIP "+JSON.toJson(Bridge.map("checks",checks,"loaded_boards",loaded.getBoards().size())));
   }finally{loaded.getMachine().close();}System.exit(0);return;
  }
  root=Files.createTempDirectory("portable-board-library-");Configuration.initialize(root.resolve("config").toFile());c=Configuration.get();c.load();SimulatorMain.accelerateFixture(c);SimulatorMain.settleFreshFixture(root.resolve("config"));c=Configuration.get();
  try {
   Board a=board("one"),b=board("two");check(Arrays.equals(read(a.getFile().toPath(),MAX_FILE),read(b.getFile().toPath(),MAX_FILE)),"distinct file identities have identical native bytes");
   var captured=NativePortableBoardLibrary.capture(c);check(captured.records.size()==2&&captured.entries.size()==2,"identical bytes retain two manifest/native identities");check(captured.records.get(0).get("sha256").equals(captured.records.get(1).get("sha256")),"content hashes match without merging identities");
   a.setName("dirty");rejects("dirty native board",()->NativePortableBoardLibrary.capture(c));check(a.isDirty(),"refusal retains dirty flag");a.setName("saved board");a.setDirty(false);
   Placement direct=new Placement("bypass");direct.setPart(c.getParts().get(0));a.getPlacements().add(direct);check(!a.isDirty(),"mutable-list bypass leaves native dirty flag false");rejects("dirty flag bypass",()->NativePortableBoardLibrary.capture(c));a.getPlacements().remove(direct);
   a.setProfile(a.getProfile());a.setDirty(false);rejects("explicit default-shaped profile",()->NativePortableBoardLibrary.capture(c));a.setProfile(null);a.setDirty(false);
   java.io.File before=a.getFile();a.setFile(root.resolve("two.board.xml").toFile());rejects("duplicate native file identities",()->NativePortableBoardLibrary.capture(c));a.setFile(before);a.setDirty(false);
   Path moved=root.resolve("moved.board.xml");Files.copy(before.toPath(),moved);a.setFile(moved.toFile());a.setDirty(false);rejects("registry key/file drift after native registry persistence",()->export(c,root.resolve("refused-registry-drift.zip")));check(!Files.exists(root.resolve("refused-registry-drift.zip")),"registry mismatch publishes no archive");a.setFile(before);a.setDirty(false);
   Part original=a.getPlacements().get(0).getPart(),shadow=new Part(original.getId());shadow.setPackage(original.getPackage());a.getPlacements().get(0).setPart(shadow);a.setDirty(false);rejects("shadow part identity",()->NativePortableBoardLibrary.capture(c));a.getPlacements().get(0).setPart(original);a.setDirty(false);
   Panel panel=new Panel();panel.setFile(root.resolve("unsupported.panel.xml").toFile());c.addPanel(panel);rejects("nonempty panels",()->NativePortableBoardLibrary.capture(c));panel.setDirty(false);c.removePanel(panel);c.save();
   byte[] priorRegistry=read(root.resolve("config/boards.xml"),MAX_FILE);Path freshlyLoaded=root.resolve("freshly-loaded.board.xml");Files.copy(a.getFile().toPath(),freshlyLoaded);Board added=c.getBoard(freshlyLoaded.toFile());check(!added.isDirty()&&Arrays.equals(priorRegistry,read(root.resolve("config/boards.xml"),MAX_FILE)),"native saved-board load updates memory without writing registry");Map<String,Object> unsavedRegistry=export(c,root.resolve("native-unsaved-registry.zip"));check(((Number)((Map<?,?>)((Map<?,?>)unsavedRegistry.get("manifest")).get("board_library")).get("board_count")).intValue()==3,"ordinary export persists complete native registry without manual source save");c.removeBoard(added);c.save();
   Map<String,String> source=treeHashes(root.resolve("config"));byte[] boardBefore=read(before.toPath(),MAX_FILE);Path archive=root.resolve("library.zip");Map<String,Object> out=export(c,archive);check(((Number)((Map<?,?>)out.get("manifest")).get("version")).intValue()==2,"nonempty export explicitly version2");check(Arrays.equals(boardBefore,read(before.toPath(),MAX_FILE)),"source board bytes unchanged");
   Map<String,byte[]> entries=unzip(read(archive,MAX_BUNDLE));JsonObject manifest=object(entries.get("manifest.json"));NativePortableBoardLibrary.validateArchive(entries,manifest);check(NativePortableBoardLibrary.records(manifest).size()==2,"closed archive validates complete library");
   Prepared prepared=prepare(archive,(String)out.get("sha256"),root.resolve("prepared"));check(Files.isRegularFile(prepared.staging.resolve((String)captured.records.get(0).get("entry"))),"board resource staged inside fresh generation");
   Set<String> ids=NativePortableBoardLibrary.partIds(entries);String entry=NativePortableBoardLibrary.records(manifest).get(0).get("entry").getAsString();
   Map<String,byte[]> missing=new TreeMap<>(entries);missing.remove(entry);rejects("missing native resource",()->NativePortableBoardLibrary.validateArchive(missing,manifest));
   Map<String,byte[]> extra=new TreeMap<>(entries);extra.put("library/boards/board-003-"+"a".repeat(64)+".board.xml",entries.get(entry));rejects("unreferenced resource",()->NativePortableBoardLibrary.validateArchive(extra,manifest));
   Map<String,byte[]> external=new TreeMap<>(entries);external.put("config/boards.xml",new String(entries.get("config/boards.xml"),StandardCharsets.UTF_8).replace("codex-board:board-001","/tmp/outside.board.xml").getBytes(StandardCharsets.UTF_8));rejects("external native File reference",()->NativePortableBoardLibrary.validateArchive(external,manifest));
   Map<String,byte[]> duplicate=new TreeMap<>(entries);duplicate.put("config/boards.xml",new String(entries.get("config/boards.xml"),StandardCharsets.UTF_8).replace("codex-board:board-002","codex-board:board-001").getBytes(StandardCharsets.UTF_8));rejects("duplicate board reference",()->NativePortableBoardLibrary.validateArchive(duplicate,manifest));
   JsonObject fraction=object(entries.get("manifest.json"));fraction.getAsJsonObject("board_library").addProperty("board_count",2.0000000001);rejects("fractional manifest count",()->NativePortableBoardLibrary.validateArchive(entries,fraction));
   JsonObject large=object(entries.get("manifest.json"));large.getAsJsonObject("board_library").addProperty("board_count",33);rejects("33-board declaration",()->NativePortableBoardLibrary.validateArchive(entries,large));
   String xml=new String(entries.get(entry),StandardCharsets.UTF_8);rejects("dangling native part",()->NativePortableBoardLibrary.validateBoard(xml(xml.replace("part-id=\""+original.getId()+"\"","part-id=\"unknown\"").getBytes(StandardCharsets.UTF_8)),ids,new int[4]));
   rejects("class injection",()->NativePortableBoardLibrary.validateBoard(xml(xml.replace("<placements>","<placements class=\"java.util.ArrayList\">").getBytes(StandardCharsets.UTF_8)),ids,new int[4]));
   rejects("legacy fiducial loss",()->NativePortableBoardLibrary.validateBoard(xml(xml.replace("<fiducials/>","<fiducials><fiducial/></fiducials>").getBytes(StandardCharsets.UTF_8)),ids,new int[4]));
   rejects("unsupported native pad class",()->NativePortableBoardLibrary.validateBoard(xml(xml.replace("org.openpnp.model.Pad$RoundRectangle","org.openpnp.model.Pad$Ellipse").getBytes(StandardCharsets.UTF_8)),ids,new int[4]));
   rejects("out-of-range pad roundness",()->NativePortableBoardLibrary.validateBoard(xml(xml.replace("roundness=\"0.375\"","roundness=\"1.001\"").getBytes(StandardCharsets.UTF_8)),ids,new int[4]));
   rejects("cumulative paste pad bound",()->NativePortableBoardLibrary.validateBoard(xml(entries.get(entry)),ids,new int[]{0,0,0,10000}));
   rejects("cumulative placement bound",()->NativePortableBoardLibrary.validateBoard(xml(entries.get(entry)),ids,new int[]{10000,0,0,0}));
   rejects("cumulative element bound",()->NativePortableBoardLibrary.validateBoard(xml(entries.get(entry)),ids,new int[]{0,50000,0,0}));
   rejects("cumulative text bound",()->NativePortableBoardLibrary.validateBoard(xml(entries.get(entry)),ids,new int[]{0,0,2*1024*1024,0}));
   rejects("duplicate JSON key",()->checkJson("{\"a\":1,\"a\":2}".getBytes(StandardCharsets.UTF_8)));boolean malformed=false;try{checkJson(new byte[]{'{','"','a','"',':','"',(byte)0xc3,'"','}'});}catch(Exception expected){malformed=true;}check(malformed,"invalid UTF8 rejected without replacement");
   admissionReject(missing,"missing resource with recomputed outer inventory");admissionReject(extra,"extra resource with recomputed outer inventory");admissionReject(external,"external File with recomputed semantic/hash metadata");admissionReject(duplicate,"duplicate references with recomputed metadata");
   Map<String,byte[]> stringFlags=new TreeMap<>(entries);JsonObject wrongFlag=object(entries.get("manifest.json"));wrongFlag.addProperty("scripts_activated","false");stringFlags.put("manifest.json",JSON.toJson(wrongFlag).getBytes(StandardCharsets.UTF_8));admissionReject(stringFlags,"nonboolean authority flag");
   Map<String,byte[]> nearInteger=new TreeMap<>(entries);JsonObject wrongCount=object(entries.get("manifest.json"));wrongCount.getAsJsonObject("board_library").addProperty("placement_count",new java.math.BigDecimal("2.0000000000000000001"));nearInteger.put("manifest.json",JSON.toJson(wrongCount).getBytes(StandardCharsets.UTF_8));admissionReject(nearInteger,"exact near-integer count");
   Map<String,byte[]> unknownPackage=new TreeMap<>(entries);unknownPackage.put("config/parts.xml",new String(entries.get("config/parts.xml"),StandardCharsets.UTF_8).replace("package-id=\""+original.getPackage().getId()+"\"","package-id=\"MISSING-PACKAGE\"").getBytes(StandardCharsets.UTF_8));admissionReject(unknownPackage,"unknown canonical package before native load");
   String rawManifest=new String(entries.get("manifest.json"),StandardCharsets.UTF_8);rawAdmissionReject(entries,rawManifest.replaceFirst("\\{","{\"version\":2,").getBytes(StandardCharsets.UTF_8),"duplicate manifest version");byte[] invalidUtf8=rawManifest.replace("fresh-native-simulator-adoption","fresh-native-simulator-adoptioX").getBytes(StandardCharsets.UTF_8);for(int index=0;index<invalidUtf8.length;index++)if(invalidUtf8[index]=='X'){invalidUtf8[index]=(byte)0xff;break;}rawAdmissionReject(entries,invalidUtf8,"invalid UTF8 manifest");
   Prepared changed=prepare(archive,(String)out.get("sha256"),root.resolve("changed-stage"));Files.write(changed.staging.resolve(entry),new byte[]{'\n'},StandardOpenOption.APPEND);rejects("changed staged board before native loading",()->validateAndPublish(changed));check(Configuration.get()==c&&!Files.exists(changed.destination.resolve("adoption.json")),"staging refusal leaves source native singleton and no activation");
   Path interrupted=root.resolve("interrupted");boolean failedWrite=false;try{prepare(archive,(String)out.get("sha256"),interrupted,(count,stage)->{if(Files.exists(stage.resolve(entry)))throw new java.io.IOException("test-only interruption after board staging");});}catch(java.io.IOException expected){failedWrite=true;}check(failedWrite&&!Files.exists(interrupted.resolve("adoption.json")),"interrupted board staging cannot activate");
   List<String> command=new ArrayList<>(List.of(Paths.get(System.getProperty("java.home"),"bin/java").toString(),"-Xmx2g","-XX:+ExitOnOutOfMemoryError","-Djava.awt.headless=true","-Djava.util.prefs.PreferencesFactory=org.openpnp.codex.IsolatedPreferencesFactory","-Duser.home="+root,"-Djava.io.tmpdir="+root,"--add-opens=java.base/java.lang=ALL-UNNAMED","--add-opens=java.desktop/java.awt=ALL-UNNAMED","--add-opens=java.desktop/java.awt.color=ALL-UNNAMED","-cp",System.getProperty("java.class.path"),NativePortableBoardLibraryTest.class.getName(),"native-skip",prepared.staging.toString()));List<String> roundtrip=new ArrayList<>(command);roundtrip.set(roundtrip.size()-2,"native-roundtrip");roundtrip.set(roundtrip.size()-1,archive.toString());Process roundtripChild=new ProcessBuilder(roundtrip).redirectErrorStream(true).redirectOutput(root.resolve("native-roundtrip.log").toFile()).start();if(!roundtripChild.waitFor(60,java.util.concurrent.TimeUnit.SECONDS)){roundtripChild.destroyForcibly();roundtripChild.waitFor();throw new AssertionError("native roundtrip probe timeout");}check(roundtripChild.exitValue()==0,"lossless native roundtrip probe passed: "+Files.readString(root.resolve("native-roundtrip.log")));Process child=new ProcessBuilder(command).redirectErrorStream(true).redirectOutput(root.resolve("native-skip.log").toFile()).start();if(!child.waitFor(60,java.util.concurrent.TimeUnit.SECONDS)){child.destroyForcibly();child.waitFor();throw new AssertionError("native skip probe timeout");}check(child.exitValue()==0,"actual skipped native loader probe passed: "+Files.readString(root.resolve("native-skip.log")));
   check(!c.getMachine().isEnabled()&&!c.getMachine().isHomed(),"all qualification leaves native machine disabled/unhomed");
   System.out.println("OPENPNP_PORTABLE_BOARD_LIBRARY_RESULT "+JSON.toJson(Bridge.map("checks",checks,"boards",2,"native_motion",false,"physical_qualification",false)));
  }finally{c.getMachine().close();}System.exit(0);
 }
}
