/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.io.*;
import java.lang.reflect.*;
import java.nio.*;
import java.nio.channels.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.spi.*;

/** Actual native components and forced journal. Original sensing/action faults and wrapper-completion
 * observations are explicit synthetic contract fixtures. No Bridge, job execution, or reattachment. */
public final class NativeReplacementContinuationPublicationTest {
 static final Gson JSON=new GsonBuilder().serializeNulls().create();static Configuration config;static Path root;
 static ReferenceTrayFeeder tray,otherTray;static int checks,refusals;static final List<Map<String,Object>> cases=new ArrayList<>();
 interface Work{void run()throws Exception;}static void yes(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}
 static void no(String why,Work work)throws Exception{try{work.run();throw new AssertionError("Accepted "+why);}catch(IOException|Bridge.Fault|NativeJobLineage.Fault expected){checks++;refusals++;}}
 static Map<String,Object> m(Object... values){return NativeFaultedJobReplacement.map(values);}static Map<String,Object> o(Object value)throws IOException{return NativeFaultedJobReplacement.object(value);}static String id(){return UUID.randomUUID().toString();}
 static <T>T task(Callable<T> work)throws Exception{try{return config.getMachine().submit(work,null,true).get(30,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Error)throw(Error)e.getCause();throw(Exception)e.getCause();}}
 static void initialize(Path directory)throws Exception{root=directory;Files.createDirectory(root);Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);for(Feeder f:config.getMachine().getFeeders()){if(f.getPart()==config.getPart("R0603-1K"))tray=(ReferenceTrayFeeder)f;if(f.getPart()==config.getPart("R0402-1K"))otherTray=(ReferenceTrayFeeder)f;}tray.setTrayCountX(3);tray.setTrayCountY(2);otherTray.setTrayCountX(3);otherTray.setTrayCountY(2);}
 static final class Env implements AutoCloseable {
  final String jobId=id(),aliasId=id(),opId=id(),requestId=id();final NativeMaterialLoads material;final NativeBoardLoads boards;final NativeJobLineage lineage;final NativeFaultedJobReplacement replacement;final Path file;final FileChannel channel;
  final List<Map<String,Object>> events=new ArrayList<>();Job oldJob,freshJob;Map<String,Object> operation,oldMaterial,oldBoard,oldLineage;NativeFaultedJobReplacement.Capture capture;NativeFaultedJobReplacement.Permit permit;NativeSensingReconciliation.Capture faultCapture;NativeSensingReconciliation coordinator;NativeVacuumJournal vacuum;final Object localOwner=new Object();final Set<String> terminalWrappers=new HashSet<>();int terminalChecks;String failType;boolean failAfterForce;int failOccurrence=1,seenFailures;long seq;NativeReplacementJob.Candidate candidate;String taskId;Job installedJob;String installedAttempt;boolean installationAuthority=true;int installationChecks;
  Env(String name,boolean replay)throws Exception {
   file=root.resolve(name+".jsonl");channel=FileChannel.open(file,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE);lineage=new NativeJobLineage(this::append);boards=new NativeBoardLoads(this::append);material=new NativeMaterialLoads(config,this::append);replacement=new NativeFaultedJobReplacement(config,material,boards,lineage,this::append,op->{terminalChecks++;return terminalWrappers.contains(op);},(job,attempt)->{installationChecks++;return installationAuthority&&installedJob==job&&Objects.equals(installedAttempt,attempt);});
   if(!replay)task(()->{otherTray.setFeedCount(2);material.register(otherTray.getId(),otherTray.getPart().getId(),(String)NativeMaterialLoads.describe(otherTray).get("geometry_sha256"),"bind-existing",null,material.revision());tray.setFeedCount(2);material.register(tray.getId(),tray.getPart().getId(),(String)NativeMaterialLoads.describe(tray).get("geometry_sha256"),"bind-existing",null,material.revision());oldJob=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(tray.getPart()));lineage.createFresh(jobId,"canonical-simulator");Map<String,Object> lineageFacts=lineage.admissionFacts(jobId);lineage.bindDocument(jobId,"b".repeat(64));lineage.bindReload(aliasId,"b".repeat(64),(String)lineageFacts.get("lineage_id"),((Number)lineageFacts.get("lineage_revision")).longValue());boards.bindJob(oldJob,jobId,true);BoardLocation board=oldJob.getBoardLocations().get(0);oldJob.storePlacedStatus(board,"R1",true);boards.checkpoint(oldJob);
     operation=m("operation_id",opId,"job_id",jobId,"job_revision",boards.jobRevision(),"board_load_revision",boards.revision(),"request_id",requestId,"request_digest","a".repeat(64),"config_revision","cfg-2","method","openpnp_start_job","job_lineage",lineage.admissionFacts(jobId),"state","accepted");append("operation",operation);
     Map<String,Object> loadScope=boards.ledgerScope(oldJob);NativeActionLedger ledger=new NativeActionLedger(this::append,opId,jobId,"cfg-2",(String)loadScope.get("scope_id"),oldJob,loadScope).withMaterialObserver(material);
     try(NativeActionLedger.StepScope step=ledger.openStep(1)){config.getScripting().on("Feeder.BeforeFeed",m("nozzle",config.getMachine().getDefaultHead().getDefaultNozzle(),"feeder",tray,"part",tray.getPart()));tray.setFeedCount(3);}catch(NativeActionLedger.UnresolvedActionFence expected){}
     operation.put("state","outcome_unknown");append("operation",operation);oldMaterial=material.captureReplacementState();oldBoard=boards.captureReplacementState(jobId);oldLineage=lineage.captureReplacementState(jobId);capture=replacement.capture(oldJob,jobId,opId);candidate=NativeReplacementJob.build(config,oldJob);freshJob=candidate.job();return null;});
  }
  void append(String type,Map<String,Object> p)throws Exception {
   Runnable mat=material==null?()->{}:material.prepareEvent(type,p);Runnable lin=lineage==null||type.startsWith("job_lineage_")?()->{}:lineage.prepareObservation(type,p);
   Runnable continuation=replacement==null?()->{}:replacement.prepareContinuationObservation(type,p);Runnable sensing=coordinator!=null&&NativeSensingReconciliation.matches(type)?coordinator.prepare(type,p,NativeSensingReconciliationTest.INSTANCE):()->{};Runnable observation=vacuum!=null&&NativeVacuumJournal.matches(type)?vacuum.prepare(type,p,NativeSensingReconciliationTest.INSTANCE):()->{};
   boolean fail=type.equals(failType)&&++seenFailures==failOccurrence;
   if(fail&&!failAfterForce)throw new IOException("injected before force: "+type);Map<String,Object> event=NativeFaultedJobReplacement.frozen(m("sequence",++seq,"type",type,"payload",p));byte[] bytes=(JSON.toJson(event)+"\n").getBytes(java.nio.charset.StandardCharsets.UTF_8);ByteBuffer buffer=ByteBuffer.wrap(bytes);while(buffer.hasRemaining())channel.write(buffer);channel.force(true);events.add(event);if(fail&&failAfterForce)throw new IOException("injected uncertain return after actual force: "+type);mat.run();lin.run();continuation.run();sensing.run();observation.run();if(boards!=null)boards.observeNativeEvent(type,p);if(replacement!=null)replacement.observe(type,p);
  }
  void admit()throws Exception {
   vacuum=new NativeVacuumJournal();coordinator=new NativeSensingReconciliation(vacuum,(op,instance,replay)->false,replacement::verified);
   String instance=NativeSensingReconciliationTest.INSTANCE,source=NativeSensingReconciliationTest.SOURCE,machine=NativeSensingReconciliationTest.MACHINE;
   Map<String,Object> jobContext=m("job_id",jobId,"job_revision",oldBoard.get("job_revision"),"board_load_revision",oldBoard.get("revision"),"material_setup_revision",oldMaterial.get("revision"),"lineage_id",oldLineage.get("lineage_id"),"lineage_revision",oldLineage.get("lineage_revision"));
   Map<String,Object> context=NativeSensingReconciliationTest.context();context.put("operation_id",opId);context.put("scope","job");context.put("job_context",jobContext);
   Map<String,Object> event=NativeSensingReconciliationTest.event("read.before",100,null,context,source);append("vacuum_observation_intent",event);Map<String,Object> scope=NativeSensingReconciliationTest.scope(instance,source);scope.put("job_context",jobContext);scope.put("dependencies",capture.dependencies());faultCapture=vacuum.captureFaultSet(scope);
   String task=id(),requestOperation=id(),recovery=id();taskId=task;Map<String,Object> taskRecord=coordinator.taskRecord(task,requestOperation,id(),faultCapture,"replace-faulted-job-attempt",1,"2030-01-01T00:00:00Z");append("sensing_reconciliation_task",taskRecord);append("sensing_reconciliation_intent",coordinator.intentRecord(task,recovery,id(),"2026-09-14T00:00:00Z",1,"synthetic-local-test"));NativeSensingReconciliation.Permit recoveryPermit=coordinator.issuePermit(task,recovery,faultCapture.digest,localOwner);
   permit=replacement.begin(capture,freshJob,coordinator,recoveryPermit,localOwner);
  }
  void replay(List<Map<String,Object>> source)throws Exception {
   for(Map<String,Object> event:source){String type=(String)event.get("type");Map<String,Object> p=o(event.get("payload"));Runnable common=replacement.prepareContinuationObservation(type,p);material.recoverEvent(type,p);boards.recoverEvent(type,p);boards.observeNativeEvent(type,p);lineage.observe(type,p);replacement.observe(type,p);if(type.startsWith("faulted_job_replacement_"))replacement.recover(type,p);common.run();}
   material.finishRecovery();boards.finishRecovery();
  }
  public void close()throws Exception{try{replacement.close();}finally{if(candidate!=null&&!replacement.ownsCandidate(candidate))candidate.close();channel.close();}}
 }
 static final class Fixture implements AutoCloseable {
  final Env e;final String attempt,oldRecovery;final Map<String,Boolean> oldHistory;
  Fixture(String name,String prefix)throws Exception {
   e=new Env(name,false);task(()->{e.admit();if(!prefix.equals("unretained"))e.replacement.retainCandidate(e.permit,e.candidate);return null;});attempt=e.permit.attemptId();oldRecovery=(String)e.coordinator.snapshot(e.taskId).get("recovery_operation_id");oldHistory=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());
   if(Set.of("lineage","completed","mixed-board","pending-material").contains(prefix))task(()->{e.lineage.createReplacement(e.permit,attempt);return null;});
   if(prefix.equals("pending-material"))task(()->{e.failType="material_replacement_outcome";try{no("controlled pending material boundary",()->e.material.replaceRetiredLoad(e.permit,(String)((List<?>)e.capture.dependencies().get("material_load_ids")).get(0)));}finally{e.failType=null;}return null;});
   if(Set.of("completed","mixed-board").contains(prefix))task(()->{for(Object old:(List<?>)e.capture.dependencies().get("material_load_ids"))e.material.replaceRetiredLoad(e.permit,(String)old);if(prefix.equals("mixed-board")){e.failType="board_replacement_outcome";e.failOccurrence=2;try{no("controlled second board pending boundary",()->e.boards.quarantineAndBindReplacement(e.permit,e.oldJob,e.freshJob,attempt));}finally{e.failType=null;}}else e.boards.quarantineAndBindReplacement(e.permit,e.oldJob,e.freshJob,attempt);return null;});
  }
  Map<String,Object> localOperation(String operation,String task,String digest,String state,boolean terminal){Map<String,Object> row=m("operation_id",operation,"request_id",id(),"request_digest",digest,"bridge_instance_id",NativeSensingReconciliationTest.INSTANCE,"config_revision","cfg-2","method","local_native_sensing_reconciliation","task_id",task,"state",state);if(terminal)row.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",state.equals("succeeded"),"physical_outcome_verified",false));return row;}
  void observeOld(String state,boolean observedWrapper)throws Exception {
   Map<String,Object> previous=null;for(Map<String,Object> event:e.events)if(event.get("type").equals("operation")&&oldRecovery.equals(o(event.get("payload")).get("operation_id")))previous=o(event.get("payload"));
   Map<String,Object> row=previous==null?localOperation(oldRecovery,e.taskId,e.faultCapture.digest,state,!Set.of("accepted","running").contains(state)):NativeFaultedJobReplacement.mutable(previous);row.put("state",state);
   if(!Set.of("accepted","running").contains(state))row.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",state.equals("succeeded"),"physical_outcome_verified",false));
   e.append("operation",row);if(observedWrapper)e.terminalWrappers.add(oldRecovery);
  }
  void closeOriginal(String state)throws Exception {observeOld(state,true);e.permit.close();e.append("sensing_reconciliation_unknown",e.coordinator.unknownRecord(e.taskId,"wrapper_unknown"));}
  NativeFaultedJobReplacement.ContinuationCapture capture()throws Exception{return task(()->e.replacement.captureContinuation(attempt,e.oldJob));}
  Fresh fresh(NativeFaultedJobReplacement.ContinuationCapture captured,String kind)throws Exception{return new Fresh(this,captured,kind);}
  public void close()throws Exception{e.close();}
 }
 static final class Fresh {
  final Fixture fixture;final NativeFaultedJobReplacement.ContinuationCapture capture;final NativeSensingReconciliation coordinator;
  final NativeSensingReconciliation.Capture faultCapture;final NativeSensingReconciliation.Permit permit;final Object owner=new Object();final String taskId=id(),operation=id();
  Fresh(Fixture fixture,NativeFaultedJobReplacement.ContinuationCapture capture,String kind)throws Exception {this(fixture,capture,kind,true);}
  Fresh(Fixture fixture,NativeFaultedJobReplacement.ContinuationCapture capture,String kind,boolean observeActive)throws Exception {
   this.fixture=fixture;this.capture=capture;Env e=fixture.e;coordinator=e.coordinator;
   Map<String,Object> scope=NativeSensingReconciliationTest.scope(NativeSensingReconciliationTest.INSTANCE,NativeSensingReconciliationTest.SOURCE);scope.put("job_context",capture.jobContext());scope.put("dependencies",capture.dependencies());faultCapture=e.vacuum.captureFaultSet(scope);
   Map<String,Object> record=kind.equals("continue-faulted-job-replacement")?coordinator.taskRecordForContinuation(taskId,id(),id(),faultCapture,capture,2,"2030-01-01T00:00:00Z"):coordinator.taskRecord(taskId,id(),id(),faultCapture,kind,2,"2030-01-01T00:00:00Z");
   e.append("sensing_reconciliation_task",record);e.append("sensing_reconciliation_intent",coordinator.intentRecord(taskId,operation,id(),"2026-09-14T00:00:00Z",2,"synthetic-fresh-local-test"));permit=coordinator.issuePermit(taskId,operation,faultCapture.digest,owner);
   if(observeActive){Map<String,Object> admitted=fixture.localOperation(operation,taskId,faultCapture.digest,"running",false);admitted.put("reconciliation_request_id",record.get("request_id"));e.append("operation",admitted);}
  }
  NativeFaultedJobReplacement.ContinuationPermit begin()throws Exception{return task(()->fixture.e.replacement.beginContinuation(capture,coordinator,permit,owner));}
  void revoke()throws Exception{fixture.e.append("sensing_reconciliation_unknown",coordinator.unknownRecord(taskId,"ownership_changed"));}
 }
 static Map<String,Integer> counters(){return Map.of(tray.getId(),tray.getFeedCount(),otherTray.getId(),otherTray.getFeedCount());}
 static Map<String,String> configurationFiles()throws Exception{Map<String,String> result=new TreeMap<>();try(var stream=Files.walk(root.resolve("config"))){for(Path file:stream.filter(Files::isRegularFile).toList()){byte[] hash=MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(file));result.put(root.resolve("config").relativize(file).toString(),HexFormat.of().formatHex(hash)+":"+Files.getLastModifiedTime(file));}}return result;}
 static Map<String,Object> immutableOriginal(Env e)throws Exception {Map<String,Object> result=new LinkedHashMap<>();for(Map<String,Object> event:e.events){String type=(String)event.get("type");Map<String,Object> row=o(event.get("payload"));if((type.equals("operation")||NativeActionLedger.isLedgerEventType(type))&&e.opId.equals(row.get("operation_id")))result.put(type+":"+event.get("sequence"),row);}return NativeFaultedJobReplacement.frozen(result);}
 static void ensurePreserved(Fixture f,Map<String,Object> original)throws Exception {yes(f.oldHistory.equals(f.e.oldJob.getPlacedStatusSnapshot()),"Original native placed history remains exact");yes(NativeFaultedJobReplacement.same(original,immutableOriginal(f.e)),"Original operation and native action records remain immutable");yes(Boolean.FALSE.equals(f.e.replacement.progress(f.attempt).get("execution_authority_restored")),"Progress and continuation receipts grant no execution readiness");}

 static Map<String,Object> state(Env e)throws Exception{Map<String,Object> board=NativeFaultedJobReplacement.mutable(e.boards.snapshot());board.remove("continuation_adoptions");board.remove("continuation_publication_fault");Field binding=NativeBoardLoads.class.getDeclaredField("boundNativeJob"),confirmed=NativeBoardLoads.class.getDeclaredField("confirmed");binding.setAccessible(true);confirmed.setAccessible(true);return m("material",e.material.captureReplacementState(),"boards",board,"board_native_binding_identity",System.identityHashCode(binding.get(e.boards)),"board_confirmations",new TreeSet<>((Set<String>)confirmed.get(e.boards)),"old_lineage",e.lineage.describe(e.jobId),"fresh_lineage",e.lineage.describe(e.permit.attemptId()));}
 static Map<String,Object> freshOperation(Fresh fresh)throws Exception{Map<String,Object> result=null;for(Map<String,Object> event:fresh.fixture.e.events)if("operation".equals(event.get("type"))&&fresh.operation.equals(o(event.get("payload")).get("operation_id")))result=o(event.get("payload"));if(result==null)throw new AssertionError("Fresh active operation absent");return NativeFaultedJobReplacement.mutable(result);}

 static void saveDocument(Fixture f,String name)throws Exception {
  Path owned=root.resolve(name+"-owned");Files.createDirectory(owned);NativeReplacementDocuments docs=new NativeReplacementDocuments(config,owned.resolve("documents"),owned);
  task(()->{var context=new NativeReplacementDocuments.Context(f.e.jobId,f.attempt,f.oldRecovery,f.e.faultCapture.digest);var saved=docs.save(context,f.e.candidate);f.e.replacement.recordDocument(f.e.permit,saved);yes(Files.isRegularFile(owned.resolve("documents").resolve(saved.documentId+".zip")),"Actual saved candidate document exists before publication continuation");return null;});
 }
 static final class Ready implements AutoCloseable {
  final Fixture fixture;final Fresh fresh;final NativeFaultedJobReplacement.ContinuationPermit permit;final Map<String,Object> aggregate;final Map<String,Object> original;final Map<String,Boolean> history;
  Ready(String name,String prefix)throws Exception {fixture=new Fixture(name,prefix);saveDocument(fixture,name);fixture.closeOriginal("outcome_unknown");original=immutableOriginal(fixture.e);history=new TreeMap<>(fixture.e.oldJob.getPlacedStatusSnapshot());fresh=fixture.fresh(fixture.capture(),"continue-faulted-job-replacement");permit=fresh.begin();aggregate=task(()->fixture.e.replacement.continueReplacement(permit));}
  void install(Job actual)throws Exception {yes(actual==fixture.e.freshJob,"Synthetic host callback selects the exact actual retained native Job");fixture.e.installedJob=actual;fixture.e.installedAttempt=fixture.attempt;}
  void preserved()throws Exception {yes(history.equals(fixture.e.oldJob.getPlacedStatusSnapshot()),"Original native placed history remains exact");yes(NativeFaultedJobReplacement.same(original,immutableOriginal(fixture.e)),"Original forced operation/action outcomes remain immutable");yes(NativeFaultedJobReplacement.same(aggregate,fixture.e.replacement.continuationReceipt(permit.continuationId())),"Publication preserves the exact earlier continuation aggregate");}
  public void close()throws Exception {permit.close();fixture.close();}
 }
 static void terminalize(Ready ready)throws Exception {var f=ready.fixture;var fresh=ready.fresh;Map<String,Object> terminal=freshOperation(fresh);terminal.put("state","outcome_unknown");terminal.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));f.e.append("operation",terminal);f.e.terminalWrappers.add(fresh.operation);fresh.revoke();ready.permit.close();}
 static final String PUB_INTENT="faulted_job_replacement_continuation_publication_intent",PUB_OUTCOME="faulted_job_replacement_continuation_publication_outcome";
 static NativeFaultedJobReplacement.Publication begin(Ready r)throws Exception{return task(()->r.fixture.e.replacement.beginContinuationPublication(r.permit));}
 static Job stage(Ready r,NativeFaultedJobReplacement.Publication publication)throws Exception{return task(()->{var f=r.fixture;Job selected=f.e.replacement.replacementJobForPublication(publication);yes(selected==f.e.freshJob,"Publication returns the exact retained native candidate");f.e.boards.bindContinuedReplacement(publication,f.e.oldJob,selected,f.attempt);f.e.boards.requireContinuationBinding(publication,selected,f.attempt);return selected;});}
 static Map<String,Object> finish(Ready r,NativeFaultedJobReplacement.Publication publication)throws Exception{return task(()->{r.fixture.e.replacement.finishContinuationPublication(publication);return r.fixture.e.replacement.publicationReceipt(publication.publicationId());});}
 static void ready(Ready r)throws Exception{task(()->{r.fixture.e.boards.requireReady(r.fixture.e.freshJob);return null;});}
 static void notReady(Ready r,String why)throws Exception{no(why,()->ready(r));}
 static void replay(Ready r,String name,String publicationId,boolean complete)throws Exception {
  Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();
  try(Env reduced=new Env(name+"-replay",true)){reduced.replay(r.fixture.e.events);yes((reduced.replacement.publicationReceipt(publicationId)!=null)==complete,"Replay retains exactly the publication outcome actually forced");Map<String,Object> last=freshOperation(r.fresh);boolean succeeded="succeeded".equals(last.get("state"));if(complete){Map<String,Object> dispositions=reduced.replacement.continuationDispositions(publicationId,"none-present");yes(reduced.replacement.verifiedContinuation(r.fresh.faultCapture.payload,dispositions,true)==succeeded,"Historical disposition needs exact forced outcome and succeeded native wrapper history");yes(!reduced.replacement.verifiedContinuation(r.fresh.faultCapture.payload,dispositions,false),"Historical record never supplies a live publication witness");}yes(reduced.installedJob==null&&reduced.installationChecks==0,"Replay invokes no synthetic installation callback or selected native host job");yes(!reduced.replacement.ownsCandidate(r.fixture.e.candidate),"Replay acquires no native candidate graph");no("Publication replay cannot restore board readiness",()->task(()->{reduced.boards.requireReady(r.fixture.e.freshJob);return null;}));no("Publication replay cannot mint a continuation permit",()->task(()->reduced.replacement.captureContinuation(r.fixture.attempt,r.fixture.e.oldJob)));yes(Boolean.FALSE.equals(reduced.replacement.status().get("execution_authority_restored")),"Historical publication does not restore execution authority");for(Object raw:(List<?>)reduced.material.snapshot().get("loads"))yes(Boolean.FALSE.equals(o(raw).get("native_authority")),"Replayed publication grants no material binding");yes(Files.size(reduced.file)==0&&counts.equals(counters())&&files.equals(configurationFiles()),"Publication replay performs no native counter/save/append effects");}
 }
 static void positive(String prefix)throws Exception {
  int start=checks;String name="publication-positive-"+prefix;
  try(Ready r=new Ready(name,prefix)){var f=r.fixture;Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();var publication=begin(r);yes(publication.attemptId().equals(f.attempt),"Publication token binds the exact replacement attempt");long admitted=Files.size(f.e.file);no("duplicate publication admission for this continuation",()->begin(r));yes(admitted==Files.size(f.e.file),"Duplicate begin forces no second intent");Job actual=stage(r,publication);notReady(r,"Native staged binding is not ready before installed authority and forced outcome");task(()->{r.install(actual);return null;});notReady(r,"Actual installed-host identity alone does not make staged boards ready");Map<String,Object> receipt=finish(r,publication);yes(NativeFaultedJobReplacement.same(receipt,f.e.replacement.publicationReceipt(publication.publicationId())),"Final publication reads back its exact forced receipt");yes(f.e.installationChecks>=2,"Real callback identity is checked around publication force");ready(r);r.preserved();yes(counts.equals(counters())&&files.equals(configurationFiles()),"Publication repeats no tray reset or native configuration save");
   Map<String,Object> dispositions=task(()->f.e.replacement.continuationDispositions(publication.publicationId(),"none-present"));yes(publication.publicationId().equals(dispositions.get("publication_id")),"Dispositions identify exact published attempt");yes(NativeFaultedJobReplacement.digest(receipt).equals(dispositions.get("publication_receipt_sha256")),"Dispositions bind exact final publication digest");yes(!f.e.replacement.verifiedContinuation(r.fresh.faultCapture.payload,dispositions,false),"Publication alone cannot verify before terminal wrapper observation");Map<String,Object> terminal=freshOperation(r.fresh);terminal.put("state","succeeded");terminal.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",true,"physical_outcome_verified",false));f.e.append("operation",terminal);f.e.terminalWrappers.add(r.fresh.operation);yes(f.e.replacement.verifiedContinuation(r.fresh.faultCapture.payload,dispositions,false),"Exact continuation disposition verifies only with explicit synthetic successful terminal wrapper history");Map<String,Object> changed=NativeFaultedJobReplacement.mutable(dispositions);changed.put("publication_id",id());yes(!f.e.replacement.verifiedContinuation(r.fresh.faultCapture.payload,changed,false),"Foreign publication ID cannot resolve dependencies");
   long bytes=Files.size(f.e.file);no("duplicate publication finish",()->finish(r,publication));yes(bytes==Files.size(f.e.file),"Duplicate finish forces no new outcome");publication.close();r.permit.close();ready(r);yes(f.e.installedJob==actual,"Successful token/permit close preserves actual installed host identity");r.preserved();
   f.e.installedJob=f.e.oldJob;notReady(r,"Foreign selected native host Job cannot use the published binding");f.e.installedJob=actual;
   replay(r,name,publication.publicationId(),true);if(prefix.equals("definition"))replayNegatives(r,publication.publicationId());Files.writeString(root.resolve(name+"-receipt.json"),JSON.toJson(receipt)+"\n");cases.add(m("name",name,"assertions",checks-start));
  }
 }
 static void replayNegatives(Ready r,String publicationId)throws Exception {
  for(String kind:List.of("digest","duplicate","missing-intent")){
   List<Map<String,Object>> events=new ArrayList<>();for(Map<String,Object> original:r.fixture.e.events){Map<String,Object> event=NativeFaultedJobReplacement.mutable(original);String type=(String)event.get("type");if(kind.equals("missing-intent")&&PUB_INTENT.equals(type))continue;if(PUB_OUTCOME.equals(type)){if(kind.equals("digest")){Map<String,Object> payload=NativeFaultedJobReplacement.mutable(o(event.get("payload")));payload.put("continuation_outcome_sha256","0".repeat(64));event.put("payload",payload);}if(kind.equals("duplicate"))events.add(NativeFaultedJobReplacement.frozen(event));}events.add(NativeFaultedJobReplacement.frozen(event));}
   Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();try(Env reduced=new Env("publication-corrupt-"+kind,true)){no("publication replay refuses "+kind+" receipt history",()->reduced.replay(events));yes(Files.size(reduced.file)==0&&counts.equals(counters())&&files.equals(configurationFiles()),"Malformed replay cannot repeat native effects or write a receipt");}
  }
  for(String state:List.of("failed","outcome_unknown")){
   List<Map<String,Object>> events=new ArrayList<>();for(Map<String,Object> original:r.fixture.e.events){Map<String,Object> event=NativeFaultedJobReplacement.mutable(original);Map<String,Object> payload=o(event.get("payload"));if("operation".equals(event.get("type"))&&r.fresh.operation.equals(payload.get("operation_id"))&&"succeeded".equals(payload.get("state"))){payload=NativeFaultedJobReplacement.mutable(payload);payload.put("state",state);payload.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));event.put("payload",payload);}events.add(NativeFaultedJobReplacement.frozen(event));}
   try(Env reduced=new Env("publication-terminal-"+state,true)){reduced.replay(events);Map<String,Object> dispositions=reduced.replacement.continuationDispositions(publicationId,"none-present");yes(!reduced.replacement.verifiedContinuation(r.fresh.faultCapture.payload,dispositions,true),"A "+state+" wrapper cannot resolve historical disposition despite a durable publication outcome");no("failed wrapper replay restores no board readiness",()->task(()->{reduced.boards.requireReady(r.fixture.e.freshJob);return null;}));yes(Files.size(reduced.file)==0&&reduced.installedJob==null,"Terminal-failure replay performs no publication effects");}
  }
 }
 static void tokenRefusals()throws Exception {
  int start=checks;
  try(Ready r=new Ready("publication-token-refusals","definition")){var f=r.fixture;var p=begin(r);Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();long bytes=Files.size(f.e.file);
   no("omitted publication token cannot expose candidate",()->task(()->f.e.replacement.replacementJobForPublication(null)));no("omitted publication token cannot finish",()->task(()->{f.e.replacement.finishContinuationPublication(null);return null;}));no("publication use off native executor",p::check);
   task(()->{no("foreign native candidate graph",()->f.e.boards.bindContinuedReplacement(p,f.e.oldJob,f.e.oldJob,f.attempt));no("foreign attempt ID",()->f.e.boards.bindContinuedReplacement(p,f.e.oldJob,f.e.freshJob,id()));return null;});
   yes(bytes==Files.size(f.e.file)&&counts.equals(counters())&&files.equals(configurationFiles()),"Missing/foreign token refusals precede all effects");p.close();task(()->{no("closed publication token",p::check);return null;});no("closed publication cannot bind",()->stage(r,p));no("same decision cannot reuse an abandoned publication",()->begin(r));notReady(r,"Abandoned token grants no board readiness");terminalize(r);
  }cases.add(m("name","token-refusals","assertions",checks-start));
 }
 static void failedInstallation()throws Exception {
  int start=checks;String name="publication-failed-installation";
  try(Ready r=new Ready(name,"mixed-board")){var f=r.fixture;var p=begin(r);stage(r,p);long bytes=Files.size(f.e.file);no("false exact host installation authority",()->finish(r,p));yes(bytes==Files.size(f.e.file)&&f.e.replacement.publicationReceipt(p.publicationId())==null,"False host authority produces no success outcome");task(()->{no("failed installation closes token",p::check);no("failed installation closes parent permit",r.permit::check);return null;});r.install(f.e.freshJob);no("same failed token cannot finish after host selection changes",()->finish(r,p));notReady(r,"Failed publication stays unready after subsequent host selection");r.preserved();terminalize(r);
   Fresh next=f.fresh(f.capture(),"continue-faulted-job-replacement");var permit=next.begin();Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();task(()->f.e.replacement.continueReplacement(permit));var nextPub=task(()->f.e.replacement.beginContinuationPublication(permit));task(()->{Job candidate=f.e.replacement.replacementJobForPublication(nextPub);f.e.boards.bindContinuedReplacement(nextPub,f.e.oldJob,candidate,f.attempt);f.e.installedJob=candidate;f.e.installedAttempt=f.attempt;f.e.replacement.finishContinuationPublication(nextPub);return null;});ready(r);yes(f.e.replacement.publicationReceipt(p.publicationId())==null,"Fresh decision preserves earlier failed publication without upgrading it");yes(!p.publicationId().equals(nextPub.publicationId()),"Fresh decision has a distinct publication identity");yes(counts.equals(counters())&&files.equals(configurationFiles()),"Fresh publication adopts completed components without repeated native reset/save");nextPub.close();permit.close();ready(r);cases.add(m("name",name,"assertions",checks-start));
  }
 }
 static void forceBoundary(String suffix,boolean after)throws Exception {
  int start=checks;String name="publication-force-"+suffix+"-"+(after?"after":"before");
  try(Ready r=new Ready(name,"definition")){var f=r.fixture;NativeFaultedJobReplacement.Publication p=null;String publicationId=null;
   if(suffix.equals("outcome")){p=begin(r);r.install(stage(r,p));publicationId=p.publicationId();}
   long bytes=Files.size(f.e.file);Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();f.e.failType=suffix.equals("intent")?PUB_INTENT:PUB_OUTCOME;f.e.failAfterForce=after;
   if(p==null)no("actual publication intent force interruption",()->begin(r));else{var token=p;no("actual publication outcome force interruption",()->finish(r,token));}f.e.failType=null;
   yes((Files.size(f.e.file)>bytes)==after,"Only actual force retains the targeted publication record");if(publicationId==null)for(Map<String,Object> event:f.e.events)if(PUB_INTENT.equals(event.get("type")))publicationId=(String)o(event.get("payload")).get("publication_id");
   task(()->{no("uncertain publication closes parent permit",r.permit::check);return null;});notReady(r,"Uncertain publication cannot release staged binding");yes(counts.equals(counters())&&files.equals(configurationFiles()),"Publication force failure repeats no tray reset/save");r.preserved();if(publicationId!=null)replay(r,name,publicationId,suffix.equals("outcome")&&after);else try(Env reduced=new Env(name+"-replay",true)){reduced.replay(f.e.events);yes(Files.size(reduced.file)==0&&!reduced.replacement.ownsCandidate(f.e.candidate),"No forced intent replay creates native authority");}
   cases.add(m("name",name,"assertions",checks-start,"target_record_forced",after));
  }
 }
 static int nativeNozzlePicks,nativeNozzleCleanupPlaces;
 static void alterNativeGate(String kind)throws Exception {
  if(kind.equals("enabled"))config.getMachine().setEnabled(true);
  else{var nozzle=config.getMachine().getDefaultHead().getDefaultNozzle();config.getMachine().setEnabled(true);try{nozzle.pick(tray.getPart(),tray);nativeNozzlePicks++;}finally{config.getMachine().setEnabled(false);}yes(nozzle.getPart()==tray.getPart()&&!config.getMachine().isEnabled(),"Actual native pick retains synthetic fixture material while disabled");}
 }
 static void restoreNativeGate(String kind)throws Exception {
  if(kind.equals("enabled"))config.getMachine().setEnabled(false);
  else{var nozzle=config.getMachine().getDefaultHead().getDefaultNozzle();if(nozzle.getPart()!=null){config.getMachine().setEnabled(true);try{nozzle.place();nativeNozzleCleanupPlaces++;}finally{config.getMachine().setEnabled(false);}}yes(nozzle.getPart()==null&&!config.getMachine().isEnabled(),"Actual native place removes only test occupancy during cleanup");}
 }
 static void nativeGate(String kind,boolean afterForce)throws Exception {
  int start=checks;String name="publication-native-"+kind+(afterForce?"-postforce":"-entry");
  try(Ready r=new Ready(name,"definition")){var f=r.fixture;var publication=begin(r);r.install(stage(r,publication));long bytes=Files.size(f.e.file);int[] intercepted={0};
   if(afterForce){Field sinkField=NativeFaultedJobReplacement.class.getDeclaredField("sink");sinkField.setAccessible(true);NativeFaultedJobReplacement.Sink actual=(NativeFaultedJobReplacement.Sink)sinkField.get(f.e.replacement);NativeFaultedJobReplacement.Sink changed=(type,payload)->{actual.appendAndForce(type,payload);if(PUB_OUTCOME.equals(type)){intercepted[0]++;alterNativeGate(kind);}};sinkField.set(f.e.replacement,changed);
    try{no("actual native "+kind+" change after publication outcome force",()->finish(r,publication));}finally{sinkField.set(f.e.replacement,actual);task(()->{restoreNativeGate(kind);return null;});}
    yes(intercepted[0]==1&&Files.size(f.e.file)>bytes,"Known-force native seam runs only after the exact outcome is durable");yes(f.e.replacement.publicationReceipt(publication.publicationId())!=null,"Known forced publication outcome survives postcheck failure");task(()->{no("postforce native gate failure revokes publication",publication::check);no("postforce native gate failure revokes parent",r.permit::check);return null;});notReady(r,"Failed postforce publication cannot release staged native board binding");replay(r,name,publication.publicationId(),true);
   }else{task(()->{alterNativeGate(kind);return null;});try{no("native "+kind+" gate at publication finalization",()->finish(r,publication));}finally{task(()->{restoreNativeGate(kind);return null;});}yes(bytes==Files.size(f.e.file)&&f.e.replacement.publicationReceipt(publication.publicationId())==null,"Native entry gate refuses before publication outcome append");notReady(r,"Unpublished native stage remains unavailable after fixture cleanup");}
   r.preserved();cases.add(m("name",name,"assertions",checks-start,"synthetic_interruption","test-only known-force callback changes actual native state; native restoration is fixture cleanup"));
  }
 }
 static void hostAfterForce()throws Exception {
  int start=checks;String name="publication-host-postforce";
  try(Ready r=new Ready(name,"mixed-board")){var f=r.fixture;var p=begin(r);r.install(stage(r,p));Field field=NativeFaultedJobReplacement.class.getDeclaredField("sink");field.setAccessible(true);NativeFaultedJobReplacement.Sink actual=(NativeFaultedJobReplacement.Sink)field.get(f.e.replacement);int[] calls={0};field.set(f.e.replacement,(NativeFaultedJobReplacement.Sink)(type,payload)->{actual.appendAndForce(type,payload);if(PUB_OUTCOME.equals(type)){calls[0]++;f.e.installedJob=f.e.oldJob;}});
   try{no("selected native Job changes after exact publication force",()->finish(r,p));}finally{field.set(f.e.replacement,actual);}
   yes(calls[0]==1&&f.e.replacement.publicationReceipt(p.publicationId())!=null,"Known forced outcome preserved despite failed exact host postcheck");task(()->{no("failed host postcheck closes publication",p::check);no("failed host postcheck closes continuation",r.permit::check);return null;});f.e.installedJob=f.e.freshJob;notReady(r,"Restoring host selection cannot upgrade previously failed publication");r.preserved();replay(r,name,p.publicationId(),true);cases.add(m("name",name,"assertions",checks-start));
  }
 }
 public static void main(String[] args)throws Exception {
  initialize(Path.of(args[0]));Throwable error=null;
  try{for(Constructor<?> constructor:NativeFaultedJobReplacement.Publication.class.getDeclaredConstructors())yes(Modifier.isPrivate(constructor.getModifiers()),"Publication token constructor is private");for(String prefix:List.of("definition","pending-material","mixed-board"))positive(prefix);tokenRefusals();failedInstallation();for(String suffix:List.of("intent","outcome"))for(boolean after:List.of(false,true))forceBoundary(suffix,after);for(String kind:List.of("enabled","occupied"))for(boolean after:List.of(false,true))nativeGate(kind,after);hostAfterForce();}
  catch(Throwable failure){error=failure;failure.printStackTrace();}
  finally{config.getMachine().close();Map<String,Object> proof=m("passed",error==null,"assertions",checks,"refusals",refusals,"cases",cases,"error",error==null?null:error.toString(),"scope","Actual native candidate/documents/component binding with synthetic initial fault, wrapper-terminal and exact selected-host JobAuthority fixtures; no Bridge/public GUI or job execution","actual_native_job_initializations",0,"actual_native_feeds",0,"actual_native_job_placements",0,"actual_native_synthetic_nozzle_picks",nativeNozzlePicks,"actual_native_synthetic_nozzle_cleanup_places",nativeNozzleCleanupPlaces,"bridge_continuation_qualified",false,"restart_reattachment_qualified",false,"hardware_qualified",false,"public_package_qualified",false);Files.writeString(root.resolve("proof.json"),JSON.toJson(proof)+"\n");System.out.println("NATIVE_REPLACEMENT_CONTINUATION_PUBLICATION_RESULT "+JSON.toJson(proof));}System.exit(error==null?0:1);
 }
}
