/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

/** Closed reducer/permit tests against pinned Gson. No machine, sensor, GUI or physical IO. */
public final class NativeSensingReconciliationTest {
    static int checks,refusals;
    static final String MACHINE=id(1),INSTANCE=id(2),OLDOP=id(3),REQUEST=id(4),TASK=id(5),REQOP=id(6),RECOP=id(7),SOURCE=id(8),NEW_SOURCE=id(9),RECEIPT=id(10);
    @FunctionalInterface interface Work{void run()throws Exception;}
    static String id(int x){return UUID.nameUUIDFromBytes(("reconciliation79-"+x).getBytes(StandardCharsets.UTF_8)).toString();}
    static Map<String,Object>m(Object...v){return NativeSensingReconciliation.map(v);}
    @SuppressWarnings("unchecked")static Map<String,Object>o(Map<String,Object>p,String k){return(Map<String,Object>)p.get(k);}
    static Map<String,Object>copy(Map<String,Object>p){return NativeJournalJson.parseObject(new com.google.gson.GsonBuilder().serializeNulls().create().toJson(p));}
    static void yes(boolean x,String why){checks++;if(!x)throw new AssertionError(why);}
    static void no(String why,Work w)throws Exception {try{w.run();throw new AssertionError("Accepted "+why);}catch(IOException expected){checks++;refusals++;}}
    static void blocked(NativeVacuumJournal j,String why)throws Exception {try{j.requireNoFault();throw new AssertionError("Unfenced "+why);}catch(NativeVacuumJournal.Fault expected){checks++;}}
    static Map<String,Object>source(String id){return m("origin","controlled-simulator","profile","controlled-native-vacuum-v1","source_id",id,"process_id",1234,"simulation_only",true,"hardware_qualified",false,"fixture_id","controlled-reducer","scenario_id","success","units","native-actuator-units");}
    static Map<String,Object>context(){return m("operation_id",OLDOP,"request_id",REQUEST,"machine_id",MACHINE,"bridge_instance_id",INSTANCE,"config_revision","cfg-2","nozzle_id","N1","scope","manual","job_context",null);}
    static Map<String,Object>binding(String instance,String source)throws Exception {return NativeVacuumJournal.binding(MACHINE,instance,"cfg-2","N1","NT1","A1",source(source));}
    static Map<String,Object>scope(String instance,String source)throws Exception {return m("machine_id",MACHINE,"bridge_instance_id",instance,"config_revision","cfg-2","native_graph_sha256","a".repeat(64),"nozzle_bindings",List.of(binding(instance,source)),"job_context",null,"dependencies",m("action_ids",List.of(),"operation_ids",List.of(),"board_load_ids",List.of(),"material_load_ids",List.of(),"job_attempt_ids",List.of(),"unresolved_dependencies",List.of()));}
    static Map<String,Object>latch(){return m("state","empty","original_operation_id",null,"original_action_id",null,"original_part_id",null);}
    static Map<String,Object>event(String event,int n,Integer parent,Map<String,Object>c,String source){
        Map<String,Object>d=m("api_version",1,"observation_id",id(n),"parent_observation_id",parent==null?null:id(parent),"native_stage","direct","check_kind",event.startsWith("read")&&parent==null?null:"part_off","nozzle_tip_id","NT1","sensor_id","A1","source",source(source));
        if(event.startsWith("valve"))d.putAll(m("enabled",true,"reason","part_off_probe","cleanup_attempt",false));
        if(event.equals("read.returned"))d.putAll(m("raw","0","raw_length",1,"value",0));
        if(event.equals("check.returned"))d.put("verdict",true);
        return m("schema_version",1,"profile",NativeVacuumJournal.PROFILE,"context",c,"native_event",event,"data",d);
    }
    static final class Env {
        final NativeVacuumJournal j=new NativeVacuumJournal();final AtomicBoolean completed=new AtomicBoolean(),disposition=new AtomicBoolean(true);
        final NativeSensingReconciliation r=new NativeSensingReconciliation(j,(op,instance,replay)->completed.get()&&op.equals(RECOP)&&instance.equals(INSTANCE),(capture,receipt,replay)->disposition.get());
        final List<Map<String,Object>> records=new ArrayList<>();final Object owner=new Object();NativeSensingReconciliation.Capture capture;NativeSensingReconciliation.Permit permit;Map<String,Object>ctx,verification;
        void append(String type,Map<String,Object>p)throws Exception {append(type,p,(String)p.getOrDefault("bridge_instance_id",INSTANCE));}
        void append(String type,Map<String,Object>p,String instance)throws Exception {if(NativeSensingReconciliation.matches(type))r.prepare(type,p,instance).run();else j.prepare(type,p,instance).run();records.add(m("type",type,"payload",copy(p),"bridge_instance_id",instance));}
        void obs(Map<String,Object>p)throws Exception {append(((String)p.get("native_event")).endsWith(".before")?"vacuum_observation_intent":"vacuum_observation_outcome",p);}
        void fault()throws Exception {obs(event("read.before",100,null,context(),SOURCE));capture=j.captureFaultSet(scope(INSTANCE,SOURCE));}
        void task()throws Exception {append("sensing_reconciliation_task",r.taskRecord(TASK,REQOP,REQUEST,capture,"restore-sensing-readiness",7,"2030-01-01T00:00:00Z"));}
        void admit()throws Exception {append("sensing_reconciliation_intent",r.intentRecord(TASK,RECOP,id(101),"2026-09-14T00:00:00Z",7,"local-test"));permit=r.issuePermit(TASK,RECOP,capture.digest,owner);}
        void repair()throws Exception {append("sensing_reconciliation_intervention",r.interventionRecord(TASK,List.of(binding(INSTANCE,SOURCE)),List.of(binding(INSTANCE,NEW_SOURCE)),List.of(),latch(),latch()));ctx=r.observationContext(permit,"N1");}
        void valve(String phase,int n,boolean enabled)throws Exception {Map<String,Object>p=event("valve."+phase,n,200,ctx,NEW_SOURCE);o(p,"data").putAll(m("enabled",enabled,"cleanup_attempt",!enabled));obs(p);}
        void probe()throws Exception {r.withPermit(permit,owner,()->{obs(event("check.before",200,null,ctx,NEW_SOURCE));valve("before",201,true);valve("returned",201,true);obs(event("read.before",202,200,ctx,NEW_SOURCE));obs(event("read.returned",202,200,ctx,NEW_SOURCE));valve("before",203,false);valve("returned",203,false);obs(event("check.returned",200,null,ctx,NEW_SOURCE));return null;});
            verification=m("native_probe_operation_id",RECOP,"probes",List.of(m("nozzle_id","N1","check_observation_id",id(200),"read_observation_ids",List.of(id(202)),"valve_on_id",id(201),"valve_off_id",id(203),"native_verdict",true,"exact_current_binding",binding(INSTANCE,NEW_SOURCE))));}
        Map<String,Object>result()throws Exception {return r.resolvedRecord(TASK,RECEIPT,m("sensing","fresh-observed-empty","nozzle_material","none-present","feeder_loads",List.of(),"board_loads",List.of(),"replacement_attempt_id",null,"unresolved_dependencies",List.of()),List.of());}
    }
    public static void main(String[]args)throws Exception {
        Map<String,Object> dep=copy(o(scope(INSTANCE,SOURCE),"dependencies"));dep.put("operation_ids",List.of(OLDOP));NativeSensingReconciliation.validateDependencies(dep);yes(!NativeSensingReconciliation.hasWorkpieceDependencies(dep)&&NativeSensingReconciliation.hasDependencies(dep),"standalone operation-only prior recovery closure");
        dep.put("action_ids",List.of(OLDOP+"/native-action-1"));NativeSensingReconciliation.validateDependencies(dep);yes(NativeSensingReconciliation.hasWorkpieceDependencies(dep),"exact native action dependency is workpiece scope");
        for(String bad:List.of(OLDOP,OLDOP+"/native-action-0",OLDOP+"/native-action-01",OLDOP+"/native-action--1",OLDOP+"/native-action-1/trailing")){Map<String,Object> invalid=copy(dep);invalid.put("action_ids",List.of(bad));no("malformed native action ID",()->NativeSensingReconciliation.validateDependencies(invalid));}
        Map<String,Object> foreignAction=copy(dep);foreignAction.put("operation_ids",List.of(id(888)));no("action operation omitted from union",()->NativeSensingReconciliation.validateDependencies(foreignAction));
        for(String key:List.of("board_load_ids","material_load_ids","job_attempt_ids","unresolved_dependencies")){Map<String,Object> work=copy(o(scope(INSTANCE,SOURCE),"dependencies"));work.put(key,List.of(id(888)));yes(NativeSensingReconciliation.hasWorkpieceDependencies(work),"standalone must reject "+key);}

        Env e=new Env();no("no fault capture",()->e.j.captureFaultSet(scope(INSTANCE,SOURCE)));e.fault();blocked(e.j,"original pending");
        String digest=e.capture.digest;Map<String,Object>reordered=copy(e.capture.payload);yes(digest.equals(NativeSensingReconciliation.digest(reordered)),"canonical detached digest");
        Map<String,Object>omitted=copy(e.capture.payload);omitted.put("faults",List.of());no("omitted pending fault",()->e.j.validateCapture(omitted,null));
        Map<String,Object>missing=scope(INSTANCE,SOURCE);missing.put("nozzle_bindings",List.of());no("missing nozzle binding",()->e.j.captureFaultSet(missing));
        yes(!e.r.liveDisposesOperation(OLDOP,INSTANCE),"fault capture does not dispose operation");e.task();no("permit before local intent",()->e.r.issuePermit(TASK,RECOP,digest,e.owner));no("unknown local task",()->e.r.intentRecord(id(99),RECOP,id(101),"2026-09-14T00:00:00Z",7,"test"));
        Map<String,Object>late=e.r.intentRecord(TASK,RECOP,id(101),"2031-01-01T00:00:00Z",7,"test");no("expired action",()->e.r.prepare("sensing_reconciliation_intent",late,INSTANCE));
        e.admit();no("second permit",()->e.r.issuePermit(TASK,RECOP,digest,e.owner));no("wrong local owner",()->e.r.withPermit(e.permit,new Object(),()->null));
        e.repair();no("probe without local permit",()->e.obs(event("check.before",200,null,e.ctx,NEW_SOURCE)));
        Map<String,Object>wrong=event("check.before",200,null,e.ctx,SOURCE);no("old source under local permit",()->e.r.withPermit(e.permit,e.owner,()->{e.obs(wrong);return null;}));
        e.probe();blocked(e.j,"successful recovery probe alone");no("second native probe",()->e.r.withPermit(e.permit,e.owner,()->{e.obs(event("check.before",210,null,e.ctx,NEW_SOURCE));return null;}));
        Map<String,Object>invented=copy(e.verification);o((Map<String,Object>)((List<?>)invented.get("probes")).get(0),"exact_current_binding").put("sensor_id","A2");no("invented probe binding",()->e.r.prepare("sensing_reconciliation_verified",e.r.verifiedRecord(TASK,invented),INSTANCE));
        e.append("sensing_reconciliation_verified",e.r.verifiedRecord(TASK,e.verification));no("resolved before successful wrapper",()->e.r.prepare("sensing_reconciliation_resolved",e.result(),INSTANCE));no("token before successful wrapper",()->e.r.wrapperCompleted(TASK,RECOP));
        e.completed.set(true);e.disposition.set(false);no("unverified load dependency callback",()->e.r.prepare("sensing_reconciliation_resolved",e.result(),INSTANCE));e.disposition.set(true);
        NativeSensingReconciliation.WrapperCompletion token=e.r.wrapperCompleted(TASK,RECOP);no("activation before forced final receipt",()->e.r.activateResolution(TASK,token));
        Map<String,Object>resolved=e.result();Runnable finalCommit=e.r.prepare("sensing_reconciliation_resolved",resolved,INSTANCE);blocked(e.j,"prepared disposition");finalCommit.run();e.records.add(m("type","sensing_reconciliation_resolved","payload",resolved,"bridge_instance_id",INSTANCE));blocked(e.j,"durable disposition without activation");yes(!e.r.liveDisposesOperation(OLDOP,INSTANCE),"durable resolution alone does not admit future operations");
        no("missing completion token",()->e.r.activateResolution(TASK,null));e.r.activateResolution(TASK,token);e.j.requireNoFault();e.j.requireUnoccupied("N1",binding(INSTANCE,NEW_SOURCE));checks+=2;yes(e.r.liveDisposesOperation(OLDOP,INSTANCE),"activated exact original operation disposition");yes(!e.r.liveDisposesOperation(id(888),INSTANCE),"unrelated unknown operation remains fenced");yes(!e.r.liveDisposesOperation(OLDOP,id(777)),"different instance gets no operation authority");yes(e.r.summaries().size()==1,"bounded status summary");
        yes(((List<?>)e.j.snapshot().get("pending")).size()==1,"original pending row retained");Map<String,Object>pending=(Map<String,Object>)((List<?>)e.j.snapshot().get("pending")).get(0);yes(RECEIPT.equals(pending.get("superseded_for_future_readiness_by")),"exact supersession link");
        no("token reuse",()->e.r.activateResolution(TASK,token));no("old unknown becomes returned",()->e.obs(event("read.returned",100,null,context(),SOURCE)));
        Map<String,Object>nextContext=context();nextContext.put("operation_id",id(500));nextContext.put("request_id",id(501));e.obs(event("read.before",502,null,nextContext,NEW_SOURCE));Map<String,Object>nextFailure=event("read.failed",502,null,nextContext,NEW_SOURCE);o(nextFailure,"data").putAll(m("failure_code","SENSOR_VALUE_NONFINITE","failure_type","SensorValueException","raw","NaN","raw_length",3));e.obs(nextFailure);NativeSensingReconciliation.Capture nextCapture=e.j.captureFaultSet(scope(INSTANCE,NEW_SOURCE));yes(((List<?>)nextCapture.payload.get("faults")).size()==1,"later current-instance capture excludes exact previously disposed IDs");e.append("sensing_reconciliation_task",e.r.taskRecord(id(503),id(504),id(505),nextCapture,"restore-sensing-readiness",7,"2030-01-01T00:00:00Z"));
        Env replay=new Env();replay.completed.set(true);for(Map<String,Object>rec:e.records){String type=(String)rec.get("type"),instance=(String)rec.get("bridge_instance_id");Map<String,Object>p=o(rec,"payload");if(NativeSensingReconciliation.matches(type))replay.r.recover(type,p,instance);else replay.j.recover(type,p,instance);}
        blocked(replay.j,"history never activates disposition");yes(!replay.r.liveDisposesOperation(OLDOP,INSTANCE),"history cannot dispose old operation for live work");yes(Boolean.TRUE.equals(replay.r.snapshot(TASK).get("historical")),"historical task marked");no("replay creates no permit",()->replay.r.issuePermit(TASK,RECOP,digest,replay.owner));no("replay creates no completion token",()->replay.r.wrapperCompleted(TASK,RECOP));
        NativeSensingReconciliation.Capture fresh=replay.j.captureFaultSet(scope(id(999),id(998)));yes(((List<?>)fresh.payload.get("faults")).size()==2,"new instance recaptures historical uncertainty");yes(((Number)fresh.payload.get("prior_disposition_generation")).longValue()==1,"disposition generation retained");
        Env partial=new Env();partial.fault();partial.task();partial.admit();partial.repair();partial.r.withPermit(partial.permit,partial.owner,()->{partial.obs(event("check.before",200,null,partial.ctx,NEW_SOURCE));partial.valve("before",201,true);partial.valve("returned",201,true);partial.permit.revoke();partial.valve("before",203,false);partial.valve("returned",203,false);return null;});checks++;blocked(partial.j,"revocation preserves fault after cleanup");
        no("revoked permit denies read",()->partial.r.withPermit(partial.permit,partial.owner,()->null));
        Env failed=new Env();failed.obs(event("check.before",400,null,context(),SOURCE));failed.obs(event("read.before",401,400,context(),SOURCE));Map<String,Object>fail=event("read.failed",401,400,context(),SOURCE);o(fail,"data").putAll(m("failure_code","SENSOR_VALUE_NONFINITE","failure_type","SensorValueException","raw","NaN","raw_length",3));failed.obs(fail);NativeSensingReconciliation.Capture both=failed.j.captureFaultSet(scope(INSTANCE,SOURCE));yes(((List<?>)both.payload.get("faults")).size()==2,"failed child and pending parent both captured");
        Map<String,Object>dropParent=copy(both.payload);List<?>all=(List<?>)dropParent.get("faults");dropParent.put("faults",List.of(all.get(0)));no("cannot omit related pending parent",()->failed.j.validateCapture(dropParent,null));
        Env cancelled=new Env();cancelled.fault();cancelled.task();cancelled.append("sensing_reconciliation_closed",cancelled.r.closedRecord(TASK,"cancelled"));blocked(cancelled.j,"cancelled task");no("cancelled task cannot issue local intent",()->cancelled.admit());
        Env uncertain=new Env();uncertain.fault();uncertain.task();uncertain.admit();uncertain.append("sensing_reconciliation_unknown",uncertain.r.unknownRecord(TASK,"wrapper_unknown"));blocked(uncertain.j,"unknown recovery");no("unknown recovery permit revoked",()->uncertain.r.withPermit(uncertain.permit,uncertain.owner,()->null));
        Env badProbe=new Env();badProbe.fault();badProbe.task();badProbe.admit();badProbe.repair();badProbe.r.withPermit(badProbe.permit,badProbe.owner,()->{badProbe.obs(event("check.before",200,null,badProbe.ctx,NEW_SOURCE));badProbe.valve("before",201,true);badProbe.valve("returned",201,true);badProbe.obs(event("read.before",202,200,badProbe.ctx,NEW_SOURCE));Map<String,Object>bf=event("read.failed",202,200,badProbe.ctx,NEW_SOURCE);o(bf,"data").putAll(m("failure_code","SENSOR_VALUE_NONFINITE","failure_type","SensorValueException","raw","NaN","raw_length",3));badProbe.obs(bf);badProbe.valve("before",203,false);badProbe.valve("returned",203,false);Map<String,Object>cf=event("check.failed",200,null,badProbe.ctx,NEW_SOURCE);o(cf,"data").putAll(m("failure_code","NATIVE_CHECK_FAILED","failure_type","SensorValueException"));badProbe.obs(cf);return null;});blocked(badProbe.j,"failed recovery probe");yes(((List<?>)badProbe.j.captureFaultSet(scope(INSTANCE,NEW_SOURCE)).payload.get("faults")).size()==3,"recovery failure retains old pending and new child/parent faults");
        Env stale=new Env();stale.fault();stale.task();stale.j.invalidate("N1","publication-failure");no("unpublished fault prevents local admission",()->stale.admit());
        Env jobs=new Env();Map<String,Object>jc=context();Map<String,Object>job=m("job_id",id(301),"job_revision","b".repeat(64),"board_load_revision","load-2","material_setup_revision","material-3","lineage_id",id(302),"lineage_revision",4);jc.put("scope","job");jc.put("job_context",job);jobs.obs(event("read.before",300,null,jc,SOURCE));no("job cannot be captured as standalone",()->jobs.j.captureFaultSet(scope(INSTANCE,SOURCE)));
        Map<String,Object>js=scope(INSTANCE,SOURCE);js.put("job_context",job);o(js,"dependencies").put("operation_ids",List.of(OLDOP));NativeSensingReconciliation.Capture cap=jobs.j.captureFaultSet(js);no("standalone request cannot waive job",()->jobs.r.prepare("sensing_reconciliation_task",jobs.r.taskRecord(TASK,REQOP,REQUEST,cap,"restore-sensing-readiness",7,"2030-01-01T00:00:00Z"),INSTANCE));
        Map<String,Object>unknown=e.r.closedRecord(TASK,"cancelled");no("resolved task cannot be cancelled",()->e.r.prepare("sensing_reconciliation_closed",unknown,INSTANCE));
        System.out.println("NATIVE_SENSING_RECONCILIATION_PASS "+checks+" checks "+refusals+" refusals; pinned-Gson reducer and process-local permit only; no native sensor, GUI, job, or physical qualification");
    }
}
