/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.awt.geom.AffineTransform;
import java.beans.PropertyChangeListener;
import java.lang.reflect.Field;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.openpnp.model.*;
import org.openpnp.machine.reference.camera.ReferenceCamera;
import org.openpnp.spi.*;

/** Actual Bridge/executor/model/save test. Registration transforms, validation and placed statuses
 * are explicitly seeded native cache fixtures, not measured fiducials or executed placements.
 * No enable/home/motion/capture/feed/pick/placement operation belongs to this test. */
public final class NativeCameraRegistrationTest {
 static final Gson G=new Gson();static Configuration config;static Machine machine;static Bridge bridge;static Job job;static NativeBoardLoads loads;static String session;static Path root;static int checks,enableEvents,headActivity;
 static final List<PlacementsHolderLocation<?>> locations=new ArrayList<>();
 static final List<Map<String,Object>> observations=new ArrayList<>();static Map<String,Integer> initialCounts;
 static Map<String,Integer> counts(){Map<String,Integer> out=new TreeMap<>();for(Feeder f:machine.getFeeders()){if(f instanceof org.openpnp.machine.reference.feeder.ReferenceStripFeeder)out.put(f.getId(),((org.openpnp.machine.reference.feeder.ReferenceStripFeeder)f).getFeedCount());else if(f instanceof org.openpnp.machine.reference.feeder.ReferenceTrayFeeder)out.put(f.getId(),((org.openpnp.machine.reference.feeder.ReferenceTrayFeeder)f).getFeedCount());}return out;}
 static void check(boolean ok,String label){checks++;if(!ok)throw new AssertionError(label);}
 static JsonObject obj(Object...args){return G.toJsonTree(Bridge.map(args)).getAsJsonObject();}
 static Object field(Object o,String name)throws Exception{Field f=o.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(o);}
 static void set(Object o,String name,Object value)throws Exception{Field f=o.getClass().getDeclaredField(name);f.setAccessible(true);f.set(o,value);}
 @SuppressWarnings("unchecked")static Map<String,Object> call(String n,JsonObject p)throws Exception{return(Map<String,Object>)bridge.call(n,p);}
 static String revision()throws Exception{return(String)call("openpnp_get_status",obj()).get("config_revision");}
 static JsonObject mutation(Object...p)throws Exception{JsonObject j=obj(p);j.addProperty("session_id",session);j.addProperty("request_id",UUID.randomUUID().toString());j.addProperty("expected_config_revision",revision());return j;}
 static void idle()throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(10);while(machine.isBusy()){if(System.nanoTime()>end)throw new AssertionError("native busy deadline");Thread.sleep(5);}}
 static <T>T task(Callable<T> c)throws Exception{T v=machine.submit(c,null,true).get(30,TimeUnit.SECONDS);idle();return v;}
 static Map<String,Object> operation(String n,JsonObject p)throws Exception{Map<String,Object> accepted=call(n,p);String id=(String)accepted.get("operation_id");long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(30);while(true){Map<String,Object> op=call("openpnp_get_operation",obj("operation_id",id));if(Arrays.asList("succeeded","failed","outcome_unknown","cancelled").contains(op.get("state"))){idle();return op;}if(System.nanoTime()>end)throw new AssertionError("operation deadline");Thread.sleep(5);}}
 static Map<?,?> result(Map<String,Object> op){return(Map<?,?>)op.get("result");}
 static JsonObject geometry(Camera camera,double x){return obj("type","set_camera_geometry","camera_id",camera.getId(),"units_per_pixel_x_mm",x,"units_per_pixel_y_mm",0.041,"working_plane_z_mm",0,"head_offsets",obj("x_mm",1,"y_mm",2,"z_mm",0,"rotation_deg",0));}
 static Map<String,Object> plan(JsonObject...cs)throws Exception{JsonArray a=new JsonArray();for(JsonObject c:cs)a.add(c);return call("openpnp_plan_configuration",mutation("changes",a));}
 static Map<String,Object> apply(Map<String,Object> p)throws Exception{return operation("openpnp_apply_configuration",mutation("plan_id",p.get("plan_id")));}
 static JsonObject instance(String id,String kind,String def){return obj("id",id,"kind",kind,"definitionId",def,"x",0,"y",0,"z",0,"rotation",0,"side","top","enabled",true);}
 static JsonObject canonical(){Part p=config.getPart("R0603-1K");double h=p.getHeight().convertToUnits(LengthUnit.Millimeters).getValue();JsonObject x=obj("schemaVersion",1,"id","camera-registration","units","mm","coordinateConvention","openpnp-top-view");JsonArray parts=new JsonArray();parts.add(obj("id",p.getId(),"packageId",p.getPackage().getId(),"heightMm",h));x.add("parts",parts);JsonArray placements=new JsonArray();for(int i=1;i<=2;i++)placements.add(obj("ref","R"+i,"partId",p.getId(),"packageId",p.getPackage().getId(),"heightMm",h,"x",2+i,"y",3,"z",0,"rotation",0,"side","top","enabled",true,"type","placement"));JsonObject b=obj("id","board","widthMm",20,"heightMm",20);b.add("placements",placements);JsonArray boards=new JsonArray();boards.add(b);x.add("boards",boards);JsonArray panels=new JsonArray();JsonArray innerChildren=new JsonArray();innerChildren.add(instance("child","board","board"));JsonObject inner=obj("id","inner","widthMm",20,"heightMm",20);inner.add("children",innerChildren);panels.add(inner);JsonArray outerChildren=new JsonArray();outerChildren.add(instance("nested","panel","inner"));JsonObject outer=obj("id","outer","widthMm",20,"heightMm",20);outer.add("children",outerChildren);panels.add(outer);x.add("panels",panels);JsonArray roots=new JsonArray();roots.add(instance("panel-root","panel","outer"));roots.add(instance("board-root","board","board"));x.add("instances",roots);return x;}
 static void visit(PlacementsHolderLocation<?> l){locations.add(l);if(l instanceof PanelLocation)for(PlacementsHolderLocation<?> c:((PanelLocation)l).getChildren())visit(c);}
 static Map<String,Object> observe(String phase)throws Exception{List<Object> tr=new ArrayList<>();for(PlacementsHolderLocation<?> l:locations)tr.add(Bridge.map("id",l.getUniqueId(),"class",l.getClass().getSimpleName(),"status",l.getPlacementsTransformStatus().name(),"cached_transform_present",rawTransform(l)!=null));return Bridge.map("phase",phase,"config_revision",revision(),"job_state",field(bridge,"jobState"),"validated_board_load_revision",field(bridge,"validatedBoardLoadRevision"),"transforms",tr,"load_snapshot",loads.snapshot());}
 static Object rawTransform(PlacementsHolderLocation<?> l)throws Exception{Field f=PlacementsHolderLocation.class.getDeclaredField("localToParentTransform");f.setAccessible(true);return f.get(l);}
 static void seed()throws Exception{
  task(()->{for(BoardLocation b:job.getBoardLocations()){job.storePlacedStatus(b,"R1",true);job.storePlacedStatus(b,"R2",false);}loads.checkpoint(job);loads.registrationCompleted(job,revision());int i=0;for(PlacementsHolderLocation<?> l:locations){l.setLocalToParentTransform(AffineTransform.getTranslateInstance(10+(++i),20+i));l.setPlacementsTransformStatus(PlacementsHolderLocation.PlacementsTransformStatus.LocallySet);}return null;});
  synchronized(bridge){set(bridge,"jobState","validated");set(bridge,"validatedBoardLoadRevision",loads.revision());}
  check(locations.size()==4&&job.getBoardLocations().size()==2,"two nested panels and two board instances");for(PlacementsHolderLocation<?> l:locations)check(rawTransform(l)!=null&&l.getPlacementsTransformStatus()==PlacementsHolderLocation.PlacementsTransformStatus.LocallySet,"seed actual native transform");
 }
 static boolean revoked(Map<String,Object> observation){if(observation.get("validated_board_load_revision")!=null)return false;for(Object raw:(List<?>)observation.get("transforms")){Map<?,?> t=(Map<?,?>)raw;if(!"NotSet".equals(t.get("status")))return false;}for(Object raw:(List<?>)((Map<?,?>)observation.get("load_snapshot")).get("loads")){Map<?,?> reg=(Map<?,?>)((Map<?,?>)raw).get("registration");if(reg==null||!"invalidated".equals(reg.get("state")))return false;}return true;}
 static void run(String mode,String cameraKind)throws Exception{
  ReferenceCamera camera=(ReferenceCamera)("top".equals(cameraKind)?machine.getDefaultHead().getDefaultCamera():machine.getCameras().get(0));
  String artifact=null;if(mode.startsWith("restore")){Map<String,Object> op=operation("openpnp_backup_configuration",mutation());check("succeeded".equals(op.get("state")),"backup succeeds");artifact=(String)result(op).get("artifact_id");check(artifact!=null,"backup artifact");check("succeeded".equals(apply(plan(geometry(camera,0.052))).get("state")),"intervening camera change succeeds");}
  seed();Map<String,Boolean> history=new TreeMap<>(job.getPlacedStatusSnapshot());String loadRevision=loads.revision();List<Object> ids=new ArrayList<>();for(Object r:(List<?>)loads.snapshot().get("roots"))ids.add(((Map<?,?>)r).get("load_id"));String old=revision();Location before=camera.getUnitsPerPixelPrimary();
  observations.add(observe("before-plan"));
  if("late-invalid".equals(mode)){long bytes=Files.size(root.resolve("journal/operations.jsonl"));try{plan(geometry(camera,0.05),obj("type","set_camera_geometry","camera_id",camera.getId(),"units_per_pixel_x_mm",-1,"units_per_pixel_y_mm",0.04,"working_plane_z_mm",0,"head_offsets",obj("x_mm",0,"y_mm",0,"z_mm",0,"rotation_deg",0)));throw new AssertionError("invalid accepted");}catch(Bridge.Fault e){check("OUT_OF_RANGE".equals(e.code),"late invalid exact code");}check(bytes==Files.size(root.resolve("journal/operations.jsonl")),"rejected preview does not journal");check(old.equals(revision())&&before.equals(camera.getUnitsPerPixelPrimary()),"late rejection unchanged geometry/revision");check(!revoked(observe("rejected")),"late rejection preserves registration");return;}
  Map<String,Object> p=mode.startsWith("restore")?null:plan("settling".equals(mode)?obj("type","set_camera_settling","camera_id",camera.getId(),"settle_time_ms",30):geometry(camera,0.049));
  check(!revoked(observe("after-plan")),"planning preserves registration");
  AtomicInteger setter=new AtomicInteger();PropertyChangeListener monitor=e->{setter.incrementAndGet();try{observations.add(observe("first-camera-setter"));String journal=Files.readString(root.resolve("journal/operations.jsonl"));check(journal.contains("camera-geometry")&&journal.contains("configuration_change_started")&&journal.contains("\"state\":\"invalidated\""),"forced registration/revision/native effect records exist before camera setter");}catch(Exception err){throw new RuntimeException(err);}};
  camera.addPropertyChangeListener("unitsPerPixelPrimary",monitor);
  PropertyChangeListener breaker=e->{if(e.getNewValue()==null){if(mode.endsWith("transform-error"))throw new AssertionError("injected native registration invalidation Error");if(mode.endsWith("transform-exception"))throw new IllegalStateException("injected native registration invalidation exception");}};
  if(mode.contains("transform-"))locations.get(0).addPropertyChangeListener("localToParentTransform",breaker);
  Map<String,Object> op;
  try{op=mode.startsWith("restore")?operation("openpnp_restore_configuration",mutation("artifact_id",artifact)):apply(p);}finally{camera.removePropertyChangeListener("unitsPerPixelPrimary",monitor);if(mode.contains("transform-"))locations.get(0).removePropertyChangeListener("localToParentTransform",breaker);}
  observations.add(observe("after-operation"));Files.writeString(root.resolve("operation.json"),G.toJson(op));Files.writeString(root.resolve("observations.json"),G.toJson(observations));
  check(history.equals(job.getPlacedStatusSnapshot()),"all true and false native history keys preserved");check(loadRevision.equals(loads.revision()),"load revision preserved");List<Object> afterIds=new ArrayList<>();for(Object r:(List<?>)loads.snapshot().get("roots"))afterIds.add(((Map<?,?>)r).get("load_id"));check(ids.equals(afterIds),"existing load IDs preserved");check(!old.equals(revision())&&!"validated".equals(field(bridge,"jobState")),"config revision and job validation invalidated");
  if(mode.contains("transform-")){check(!"succeeded".equals(op.get("state")),"invalidation fault cannot succeed");check(Boolean.TRUE.equals(field(bridge,"configurationFault")),"invalidation fault persistently fences config");check(setter.get()==0&&before.equals(camera.getUnitsPerPixelPrimary()),"first geometry setter not reached after invalidation fault");try{plan(obj("type","set_machine_speed","speed",0.5));throw new AssertionError("fault allowed plan");}catch(Bridge.Fault e){check("CONFIGURATION_FAULT".equals(e.code)||"RECOVERY_REQUIRED".equals(e.code),"new mutation refused after failure");}return;}
  check("succeeded".equals(op.get("state")),"apply success");
  if("settling".equals(mode)){check(!revoked(observations.get(observations.size()-1)),"settling-only control preserves native registration");check(setter.get()==0,"settling does not change geometry");return;}
  check(setter.get()>=1,"actual native camera setter callback");check(revoked(observations.get(observations.size()-1)),"camera geometry must clear all board/panel transforms and registration");
  for(Map<String,Object> o:observations)if("first-camera-setter".equals(o.get("phase"))){check(revoked(o),"registration invalidated before camera setter");for(Object raw:(List<?>)o.get("transforms"))check(Boolean.FALSE.equals(((Map<?,?>)raw).get("cached_transform_present")),"old cached transform removed before camera setter");}
  for(PlacementsHolderLocation<?> l:locations){check(l.getLocalToParentTransform().equals(org.openpnp.util.Utils2D.getDefaultBoardPlacementLocationTransform(l)),"subsequent native lookup uses nominal transform, not old fiducial matrix");check(l.getPlacementsTransformStatus()==PlacementsHolderLocation.PlacementsTransformStatus.NotSet,"nominal lazy reconstruction does not restore fiducial validity");}
  check(Files.readString(root.resolve("config/machine.xml")).contains("<units-per-pixel "),"actual configuration save retained camera geometry");
  Map<String,Object> rejected=call("openpnp_start_job",mutation("job_id",field(bridge,"jobId")));check("failed".equals(rejected.get("state"))&&"JOB_NOT_VALIDATED".equals(result(rejected).get("code")),"old job cannot start after camera geometry change");
 }
 public static void main(String[] args)throws Exception{
  root=Path.of(args[1]);Files.createDirectories(root);Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();machine=config.getMachine();initialCounts=counts();Path token=root.resolve("token");Files.writeString(token,UUID.randomUUID().toString()+UUID.randomUUID());bridge=new Bridge(config,token,root.resolve("journal"),Path.of(args[0]),0,true);int code=0;Throwable error=null;
  try{machine.addListener(new MachineListener.Adapter(){@Override public void machineEnabled(Machine m){enableEvents++;}@Override public void machineHeadActivity(Machine m,Head h){headActivity++;}});session=(String)call("openpnp_request_control_session",obj("request_id",UUID.randomUUID().toString(),"ttl_seconds",300)).get("session_id");check("succeeded".equals(operation("openpnp_prepare_job",mutation("canonical_job",canonical())).get("state")),"native canonical preparation");job=(Job)field(bridge,"job");loads=(NativeBoardLoads)field(bridge,"boardLoads");for(PlacementsHolderLocation<?> l:job.getRootPanelLocation().getChildren())visit(l);run(args[2],args[3]);check(initialCounts.equals(counts()),"all native feeder counters unchanged");check(!Files.readString(root.resolve("journal/operations.jsonl")).contains("native_action_intent"),"no native feed/pick/align/release intents");check(!machine.isEnabled()&&!machine.isHomed()&&enableEvents==0&&headActivity==0,"no enable/home/motion/capture or native processing");}
  catch(Throwable t){error=t;code=1;t.printStackTrace();}
  finally{Map<String,Object> r=Bridge.map("passed",code==0,"checks",checks,"mode",args[2],"camera",args[3],"error",error==null?null:error.toString(),"registration_cache_fixture","seeded native transforms and durable registration; no fiducial measurement","native_enabled_events",enableEvents,"native_head_activity",headActivity,"native_feeds",0,"native_placements",0,"hardware_qualified",false,"observations",observations);Files.writeString(root.resolve("result.json"),G.toJson(r));System.out.println("CAMERA_REGISTRATION_RESULT "+G.toJson(r));try{bridge.close();}catch(Exception close){System.err.println("BRIDGE_CLOSE "+close);}try{machine.close();}catch(Exception close){System.err.println("MACHINE_CLOSE "+close);}}
  System.exit(code);
 }
}
