/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import java.awt.geom.AffineTransform;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;
import org.openpnp.model.Abstract2DLocatable.Side;

/** Native model construction and listener/identity checks only. No job processor initialization,
 * motion, feed, sensor observation, job admission, persistence or physical workpiece claim. */
public final class NativeReplacementJobTest {
 static Configuration config;static Path root;static int checks,refusals;static final List<String> passed=new ArrayList<>();
 interface Work{void run()throws Exception;}
 static void yes(boolean value,String why){checks++;if(!value)throw new AssertionError(why);passed.add(why);}
 static void no(String why,Work work)throws Exception{try{work.run();throw new AssertionError("Accepted "+why);}catch(IOException|Bridge.Fault expected){checks++;refusals++;passed.add("refused "+why);}}
 static <T>T task(Callable<T> c)throws Exception{try{return config.getMachine().submit(c,null,true).get(30,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Error)throw(Error)e.getCause();throw(Exception)e.getCause();}}
 static Job canonical(boolean nested)throws Exception{return CanonicalJobImporter.load(config,nested?NativeBoardLoadsTest.nested(config.getPart("R0603-1K")):NativeBoardLoadsTest.canonical(config.getPart("R0603-1K")));}
 static Location pose(double x,double y){return new Location(LengthUnit.Millimeters,x,y,0,0);}
 static int libraryBoards(){return config.getBoards().size();}
 static Job nativeNested()throws Exception{
  Part part=config.getPart("R0603-1K");Board definition=new Board();definition.setName("Shared native definition");definition.setDimensions(pose(25,20));Placement p=new Placement("F1");p.setPart(part);p.setType(Placement.Type.Fiducial);p.setLocation(pose(5,6));p.setComments("native fiducial");p.setRank(7);definition.addPlacement(p);
  GeometricPath2D profile=definition.getProfile();profile.reset();profile.moveTo(0,0);profile.lineTo(25,0);profile.quadTo(30,10,25,20);profile.lineTo(0,20);profile.closePath();definition.setProfile(profile);
  BoardPad pad=new BoardPad();Pad.RoundRectangle shape=new Pad.RoundRectangle();shape.setUnits(LengthUnit.Millimeters);shape.setWidth(2);shape.setHeight(3);shape.setRoundness(0.2);pad.setPad(shape);pad.setName("paste1");pad.setLocation(pose(4,5));definition.addSolderPastePad(pad);
  Panel inner=new Panel();inner.setName("Inner");inner.setDimensions(pose(70,30));PanelLocation innerLoc=new PanelLocation(inner);innerLoc.setId("I");innerLoc.setLocation(pose(4,5));
  for(String id:List.of("A","B")){Board b=new Board(definition);b.setProfile(profile.convertToUnits(LengthUnit.Millimeters));BoardLocation loc=new BoardLocation(b);loc.setId(id);loc.setLocation(pose(id.equals("A")?10:40,5));innerLoc.addChild(loc);}
  inner.addPseudoPlacement(inner.createPseudoPlacement("A"+PlacementsHolderLocation.ID_DELIMITTER+"F1"));
  Panel outer=new Panel();outer.setName("Outer");outer.setDimensions(pose(90,60));PanelLocation outerLoc=new PanelLocation(outer);outerLoc.setId("P");outerLoc.setLocation(pose(12,15));outerLoc.addChild(innerLoc);outer.addPseudoPlacement(outer.createPseudoPlacement("I"+PlacementsHolderLocation.ID_DELIMITTER+"B"+PlacementsHolderLocation.ID_DELIMITTER+"F1"));
  Job job=new Job();job.addBoardOrPanelLocation(outerLoc);PanelLocation.setParentsOfAllDescendants(job.getRootPanelLocation());return job;
 }
 static void debug(Job old,String name)throws Exception {
  Class<?> snap=Class.forName("org.openpnp.codex.NativeReplacementJob$Snapshot"),builder=Class.forName("org.openpnp.codex.NativeReplacementJob$Builder");java.lang.reflect.Constructor<?> sc=snap.getDeclaredConstructor(Configuration.class,Job.class);sc.setAccessible(true);Object before=sc.newInstance(config,old);java.lang.reflect.Constructor<?> bc=builder.getDeclaredConstructor(snap);bc.setAccessible(true);Object b=bc.newInstance(before);java.lang.reflect.Method build=builder.getDeclaredMethod("build",Job.class);build.setAccessible(true);Job next=(Job)build.invoke(b,old);Object after=sc.newInstance(config,next);java.lang.reflect.Field shape=snap.getDeclaredField("shape");shape.setAccessible(true);com.google.gson.Gson json=new com.google.gson.GsonBuilder().setPrettyPrinting().serializeNulls().create();Files.writeString(root.resolve(name+"-before-shape.json"),json.toJson(shape.get(before)));Files.writeString(root.resolve(name+"-after-shape.json"),json.toJson(shape.get(after)));java.lang.reflect.Method clean=builder.getDeclaredMethod("cleanup");clean.setAccessible(true);clean.invoke(b);
 }
 static Set<Object> objects(Job job)throws Exception {Class<?> snap=Class.forName("org.openpnp.codex.NativeReplacementJob$Snapshot");java.lang.reflect.Constructor<?> c=snap.getDeclaredConstructor(Configuration.class,Job.class);c.setAccessible(true);Object value=c.newInstance(config,job);java.lang.reflect.Field objects=snap.getDeclaredField("objects");objects.setAccessible(true);return(Set<Object>)objects.get(value);}
 static Map<Object,List<Object>> listeners(Set<Object> graph)throws Exception {Map<Object,List<Object>> result=new LinkedHashMap<>();java.lang.reflect.Field f=AbstractModelObject.class.getDeclaredField("propertyChangeSupport");f.setAccessible(true);for(Object value:graph)if(value instanceof AbstractModelObject){java.beans.PropertyChangeSupport support=(java.beans.PropertyChangeSupport)f.get(value);List<Object> rows=new ArrayList<>();for(PropertyChangeListener listener:support.getPropertyChangeListeners())if(listener instanceof java.beans.PropertyChangeListenerProxy){java.beans.PropertyChangeListenerProxy proxy=(java.beans.PropertyChangeListenerProxy)listener;rows.add(List.of(proxy.getPropertyName(),proxy.getListener()));}else rows.add(listener);result.put(value,rows);}return result;}
 static void verify(Job source,String name)throws Exception{
  BoardLocation first=source.getBoardLocations().get(0);Placement original=first.getBoard().getPlacement(0);source.storePlacedStatus(first,original.getId(),true);source.storePlacedStatus(first,"removed-opaque",true);source.storePlacedStatus(first,"failed-opaque",false);source.storeEnabledState(first,original,false);source.storeCheckFiducialsState(first,true);source.storeErrorHandlingState(first,original,Placement.ErrorHandling.Defer);first.setLocalToParentTransform(AffineTransform.getTranslateInstance(0.1,0.2));source.setFile(root.resolve(name+".job.xml").toFile());first.setFileName("source-only.board.xml");
  Map<String,Boolean> history=new TreeMap<>(source.getPlacedStatusSnapshot());int boards=libraryBoards();Part part=original.getPart();int count=part.getPlacementCount();List<Object> nativeSources=new ArrayList<>();for(PlacementsHolderLocation<?> loc:source.getBoardAndPanelLocations()){nativeSources.add(loc);nativeSources.add(loc.getDefinition());nativeSources.add(loc.getPlacementsHolder());nativeSources.add(loc.getPlacementsHolder().getDefinition());for(Placement p:loc.getPlacementsHolder().getPlacements()){nativeSources.add(p);nativeSources.add(p.getDefinition());}}
  PropertyChangeListener sentinel=event->{};original.getDefinition().addPropertyChangeListener(sentinel);Map<Object,List<Object>> beforeListeners=listeners(objects(source));
  NativeReplacementJob.Candidate candidate;try{candidate=NativeReplacementJob.build(config,source);}catch(Exception failure){debug(source,name);throw failure;}Job fresh=candidate.job();Set<Object> freshObjects=objects(fresh);yes(beforeListeners.equals(listeners(objects(source))),name+" preserves every old listener with exact multiplicity after build");Map<Object,List<Object>> freshListeners=listeners(freshObjects);for(Object node:freshObjects)if(node instanceof PropertyChangeListener){long self=freshListeners.get(node).stream().filter(listener->listener==node).count();yes(self==1,name+" exactly one native self listener "+node.getClass().getSimpleName());}BoardLocation next=fresh.getBoardLocations().get(0);Placement copy=next.getBoard().getPlacement(0);
  yes(source!=fresh&&history.equals(source.getPlacedStatusSnapshot())&&fresh.getPlacedStatusSnapshot().isEmpty(),name+" retains opaque true/false old history and creates empty new history");
  yes(first.getUniqueId().equals(next.getUniqueId())&&original.getId().equals(copy.getId()),name+" preserves native logical identities");
  yes(copy.getPart()==part&&libraryBoards()==boards&&part.getPlacementCount()==count,name+" shares only canonical part/package without library insertion");
  yes(!fresh.retrieveEnabledState(next,copy)&&fresh.retrieveCheckFiducialsState(next)&&fresh.retrieveErrorHandlingState(next,copy)==Placement.ErrorHandling.Defer,name+" preserves effective native overrides");
  yes(fresh.getFile()==null&&next.getFileName()==null&&next.getPlacementsTransformStatus()==PlacementsHolderLocation.PlacementsTransformStatus.NotSet,name+" clears only new file and measured registration bindings");
  yes(source.getFile()!=null&&first.getFileName()!=null&&first.getLocalToParentTransform().getTranslateX()==0.1,name+" leaves old files and registration untouched");
  yes(original.getDefinition().isListener(sentinel)&&!original.getDefinition().isListener(copy),name+" removes copied old-definition listener and preserves sentinel");
  Set<Object> old=Collections.newSetFromMap(new IdentityHashMap<>());old.addAll(nativeSources);for(PlacementsHolderLocation<?> loc:fresh.getBoardAndPanelLocations()){yes(!old.contains(loc)&&!old.contains(loc.getDefinition())&&!old.contains(loc.getPlacementsHolder())&&!old.contains(loc.getPlacementsHolder().getDefinition()),name+" detached location and holder "+loc.getUniqueId());for(Placement p:loc.getPlacementsHolder().getPlacements())yes(!old.contains(p)&&!old.contains(p.getDefinition()),name+" detached placement "+loc.getUniqueId()+"/"+p.getId());}
  yes(fresh.getBoardLocations().get(0).getBoard().getDefinition()==fresh.getBoardLocations().get(1).getBoard().getDefinition(),name+" preserves internal shared board definition");candidate.requireCurrent();
  Map<String,Object> mapping=candidate.mapping();yes(mapping.get("source_model_sha256").equals(mapping.get("replacement_model_sha256"))&&((Number)mapping.get("source_history_entries")).intValue()==3,name+" mapping binds source content and complete old history");
  candidate.close();yes(beforeListeners.equals(listeners(objects(source))),name+" cleanup preserves every old listener with exact multiplicity");for(Map.Entry<Object,List<Object>> entry:listeners(freshObjects).entrySet())if(!entry.getValue().isEmpty())System.out.println("REMAINING_SUBSCRIPTION "+entry.getKey().getClass().getSimpleName()+" "+entry.getValue());yes(listeners(freshObjects).values().stream().allMatch(List::isEmpty),name+" unpublished cleanup removes every constructed graph subscription");yes(!copy.isListener(next.getBoard())&&original.getDefinition().isListener(sentinel),name+" unpublished cleanup removes only new subscriptions");no(name+" closed candidate admission",candidate::requireCurrent);original.getDefinition().removePropertyChangeListener(sentinel);
 }
 public static void main(String[] args)throws Exception{
  root=Paths.get(args[1]);Files.createDirectories(root);Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);int exit=0;
  try{
   no("foreign executor",()->NativeReplacementJob.build(config,new Job()));
   task(()->{verify(canonical(false),"repeated-board");verify(canonical(true),"nested-panel");verify(nativeNested(),"native-nested-pseudo-pad-outline");Job definitionJob=nativeNested();Job instanceJob=new Job();instanceJob.addBoardOrPanelLocation(new PanelLocation((PanelLocation)definitionJob.getRootPanelLocation().getChildren().get(0)));PanelLocation.setParentsOfAllDescendants(instanceJob.getRootPanelLocation());verify(instanceJob,"native-panel-instance-pseudo-definitions");return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);Placement p=old.getBoardLocations().get(0).getBoard().getPlacement(0);Placement copy=c.job().getBoardLocations().get(0).getBoard().getPlacement(0);String text=copy.getComments();p.setComments("old changed after capture");yes(Objects.equals(copy.getComments(),text),"source edits cannot propagate into new graph");no("source content drift",c::requireCurrent);c.close();return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);c.job().getBoardLocations().get(0).getBoard().getPlacement(0).setRank(999);no("new content drift",c::requireCurrent);c.close();return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);old.storePlacedStatus(old.getBoardLocations().get(0),"post-capture",true);no("old opaque history drift",c::requireCurrent);c.close();return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);Job fresh=c.job();Placement p=fresh.getBoardLocations().get(0).getBoard().getPlacement(0);Board board=fresh.getBoardLocations().get(0).getBoard();Map<Object,List<Object>> before=listeners(objects(old));c.publish();c.close();yes(before.equals(listeners(objects(old))),"publication preserves exact original listener multiplicity");yes(c.job()==fresh&&p.isListener(board),"published candidate transfers subscription ownership and remains installed-usable");yes(fresh.getPlacedStatusSnapshot().isEmpty(),"ownership transfer does not initialize or execute native job");return null;});
   task(()->{for(String field:List.of("side","enabled","check","pose","registration","root-definition","panel-definition")){Job old=canonical(false);PanelLocation r=old.getRootPanelLocation();switch(field){case "side":r.setSide(Side.Bottom);break;case "enabled":r.setLocallyEnabled(false);break;case "check":r.setCheckFiducials(true);break;case "pose":r.setLocation(pose(1,2));break;case "registration":r.setLocalToParentTransform(AffineTransform.getTranslateInstance(1,2));break;case "root-definition":r.setDefinition(new Job().getRootPanelLocation());break;case "panel-definition":r.getPanel().setDefinition(new Panel());break;}no("nonneutral or externally defined root "+field,()->NativeReplacementJob.build(config,old));}return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);old.getBoardLocations().get(0).setLocalToParentTransform(AffineTransform.getTranslateInstance(5,6));no("old measured registration drift",c::requireCurrent);c.close();return null;});
   task(()->{Job old=nativeNested();NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);Board b=c.job().getBoardLocations().get(0).getBoard();Board original=old.getBoardLocations().get(0).getBoard();yes(b.getProfile()!=original.getProfile()&&b.getSolderPastePads().get(0).getPad()!=original.getSolderPastePads().get(0).getPad(),"custom outline and paste geometry are independently mutable");b.getProfile().lineTo(100,200);no("new custom outline drift",c::requireCurrent);c.close();return null;});
   task(()->{Job old=canonical(true);Panel hidden=new Panel();PanelLocation cycle=new PanelLocation(hidden);cycle.setId("C");hidden.addChild(cycle);PanelLocation source=(PanelLocation)old.getRootPanelLocation().getChildren().get(0);source.getPanel().setDefinition(hidden);no("cyclic hidden definition hierarchy",()->NativeReplacementJob.build(config,old));return null;});
   task(()->{Job old=canonical(false);BoardLocation loc=old.getBoardLocations().get(0);BoardLocation external=new BoardLocation(new Board());PanelLocation cycle=new PanelLocation(new Panel());cycle.setParent(cycle);external.setParent(cycle);loc.setDefinition(external);no("cyclic hidden definition parent chain",()->NativeReplacementJob.build(config,old));return null;});
   task(()->{Job old=nativeNested();Map<Object,List<Object>> before=listeners(objects(old));Part part=config.getPart("R0603-1K");PropertyChangeListener injected=event->{if(event.getPropertyName().equals("placementCount"))throw new IllegalStateException("injected native pseudo part-count listener");};part.addPropertyChangeListener(injected);try{try{NativeReplacementJob.build(config,old);throw new AssertionError("native listener failure was not reached");}catch(IllegalStateException expected){yes(expected.getMessage().contains("injected native pseudo"),"native constructor listener failure is observed");}}finally{part.removePropertyChangeListener(injected);}yes(before.equals(listeners(objects(old))),"failed partial construction preserves every old graph subscription");yes(old.getPlacedStatusSnapshot().isEmpty(),"failed native generation never writes old placed history");return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);Board a=c.job().getBoardLocations().get(0).getBoard(),b=c.job().getBoardLocations().get(1).getBoard();Placement p=a.getPlacement(0);p.setDefinition(p);no("same-content native definition edge substitution",c::requireCurrent);c.close();return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);old.getBoardLocations().get(0).getBoard().getDefinition().setFile(root.resolve("changed-hidden-definition.board.xml").toFile());no("hidden native definition file binding drift",c::requireCurrent);c.close();return null;});
   task(()->{Job old=canonical(false);NativeReplacementJob.Candidate c=NativeReplacementJob.build(config,old);c.job().getBoardLocations().get(0).setLocalToParentTransform(old.getBoardLocations().get(0).getLocalToParentTransform());no("mutable native registration object alias with equal matrix",c::requireCurrent);c.close();return null;});
   System.out.println("NATIVE_REPLACEMENT_JOB_PASS "+checks+" checks "+refusals+" refusals; actual pinned native Job/Panel/Board/PseudoPlacement models; native job initialization 0, feeds 0, placements 0; no integration, GUI, restart or physical qualification");Files.writeString(root.resolve("checks.json"),new com.google.gson.GsonBuilder().setPrettyPrinting().create().toJson(passed));
  }catch(Throwable t){t.printStackTrace();exit=1;}finally{config.getMachine().close();}System.exit(exit);
 }
}
