/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.openpnp.model.*;
import org.openpnp.machine.reference.ReferenceNozzle;
import org.openpnp.machine.reference.camera.AbstractSettlingCamera;

/** Real separate JVM export/CLI adoption/consumed-context workflow. No physical controller. */
public final class NativePortableJourneyTest {
    static Bridge bridge;static String session;static int checks;static final Gson G=new Gson();
    static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    public static void main(String[] args)throws Exception {
        if(args.length==3){child(args[0],Paths.get(args[1]),Paths.get(args[2]));return;}
        Path root=Files.createTempDirectory("native-portable-journey-");String samples=Paths.get(args[0]).toAbsolutePath().toString();
        for(String phase:List.of("export","adopt","first-launch","library-adopt","library-launch","repeat")){
            List<String> command=new ArrayList<>(List.of(Paths.get(System.getProperty("java.home"),"bin/java").toString(),"-Xmx2g","-XX:+ExitOnOutOfMemoryError","-Djava.awt.headless=true","-Djava.util.prefs.PreferencesFactory=org.openpnp.codex.IsolatedPreferencesFactory","-Duser.home="+root,"-Djava.io.tmpdir="+root,"--add-opens=java.base/java.lang=ALL-UNNAMED","--add-opens=java.desktop/java.awt=ALL-UNNAMED","--add-opens=java.desktop/java.awt.color=ALL-UNNAMED","-cp",System.getProperty("java.class.path")));
            if(phase.equals("adopt")||phase.equals("library-adopt"))command.addAll(List.of(NativePortableConfigurationMain.class.getName(),"--bundle",root.resolve(phase.equals("adopt")?"source.zip":"library.zip").toString(),"--sha256",Files.readString(root.resolve(phase.equals("adopt")?"archive-sha":"library-sha")),"--destination",root.resolve(phase.equals("adopt")?"adopted":"library-adopted").toString()));else command.addAll(List.of(NativePortableJourneyTest.class.getName(),phase,root.toString(),samples));
            Process child=new ProcessBuilder(command).redirectErrorStream(true).redirectOutput(root.resolve(phase+".log").toFile()).start();if(!child.waitFor(90,TimeUnit.SECONDS)){child.destroyForcibly();throw new AssertionError("Journey phase timeout "+phase);}check(child.exitValue()==0,"Journey phase "+phase+" failed\n"+Files.readString(root.resolve(phase+".log")));
        }
        System.out.println("OPENPNP_PORTABLE_JOURNEY_RESULT {\"phases\":6,\"native_placements\":32,\"hardware_qualified\":false}");
    }
    static void child(String phase,Path root,Path samples)throws Exception {
        Path token=root.resolve("token");NativePortableLaunch launch=null;Configuration c=null;int exit=0;
        try {
            if(phase.equals("repeat")){try{NativePortableLaunch.claim(root.resolve("adopted"),root.resolve("reused-journal"));throw new AssertionError("Consumed adoption relaunched");}catch(Bridge.Fault e){check("ADOPTION_ALREADY_LAUNCHED".equals(e.code),"spent first launch has explicit disposition");}check(!Files.exists(root.resolve("reused-journal")),"repeat refusal creates no new journal");check(Files.isRegularFile(root.resolve("adopted/first-launch-closed.json")),"closed lifecycle receipt retained");return;}
            if(phase.equals("library-launch")){
                launch=NativePortableLaunch.claim(root.resolve("library-adopted"),root.resolve("library-journal"));c=launch.initialize();
                check(c.getBoards().size()==Integer.parseInt(Files.readString(root.resolve("library-board-count"))),"fresh native launch retains exact nonempty board count");check(!c.getBoards().isEmpty()&&c.getPanels().isEmpty(),"adopted library is bounded flat boards only");check(c.getBoards().stream().mapToInt(b->b.getSolderPastePads().size()).sum()==48,"all48 sample paste pad definitions survive native adoption");check(!c.getMachine().isEnabled()&&!c.getMachine().isHomed(),"used-library first launch restores no native authority");
                bridge=new Bridge(c,token,launch.journalDirectory,samples,0,true,"adopted-simulator",null,launch);Map<String,Object> status=call("openpnp_get_status",new LinkedHashMap<>());check(status.get("job_id")==null&&"absent".equals(((Map<?,?>)status.get("job_progress")).get("state")),"old completed job is not restored");Map<String,Object> loads=call("openpnp_get_board_loads",new LinkedHashMap<>());check(((List<?>)loads.get("roots")).isEmpty()&&((List<?>)loads.get("loads")).isEmpty(),"no source board-load identity or history transfers");c.save();NativePortableBoardLibrary.verifyFirstLaunch(c,c.getConfigurationDirectory().toPath());check(!c.getMachine().isEnabled()&&!c.getMachine().isHomed(),"adopted save/native-readback preserves disabled unhomed state");check(feeds(c)==Long.parseLong(Files.readString(root.resolve("library-source-feeds"))),"source feed counter retained without new feed");
                System.out.println("OPENPNP_PORTABLE_LIBRARY_FIRST_LAUNCH "+G.toJson(Bridge.map("boards",c.getBoards().size(),"checks",checks,"physical_qualification",false)));return;
            }
            if(phase.equals("export")){
                Files.writeString(token,UUID.randomUUID().toString()+UUID.randomUUID());Path config=root.resolve("source-config");Configuration.initialize(config.toFile());c=Configuration.get();c.load();SimulatorMain.accelerateFixture(c);((AbstractSettlingCamera)c.getMachine().getDefaultHead().getDefaultCamera()).setSettleTimeMs(7);((ReferenceNozzle)c.getMachine().getDefaultHead().getDefaultNozzle()).setPickDwellMilliseconds(3);SimulatorMain.settleFreshFixture(config);c=Configuration.get();
                check(!c.getMachine().isEnabled()&&!c.getMachine().isHomed(),"settled source stays disabled/unhomed");check(feeds(c)==0,"fresh source settling performs no feeds");Files.writeString(root.resolve("source-feeds"),Long.toString(feeds(c)));Map<String,String> before=NativePortableConfiguration.canonicalFiles(c);check(before.equals(NativePortableConfiguration.canonicalFiles(c)),"settled repeat-save preserves exact native XML semantics");
                bridge=new Bridge(c,token,root.resolve("source-journal"),samples,0,true);session=(String)call("openpnp_request_control_session",Bridge.map("request_id",UUID.randomUUID().toString(),"ttl_seconds",300)).get("session_id");
                try{call("openpnp_export_portable_configuration",Bridge.map("request_id",UUID.randomUUID().toString(),"session_id",session));throw new AssertionError("Missing revision accepted");}catch(Bridge.Fault expected){check("INVALID_ARGUMENT".equals(expected.code),"export revision required natively");}
                Map<String,Object> op=run("openpnp_export_portable_configuration",new LinkedHashMap<>());Map<String,Object> artifact=(Map<String,Object>)result(op).get("artifact");Map<String,Object> bytes=call("openpnp_get_artifact",Bridge.map("artifact_id",artifact.get("artifact_id")));Files.write(root.resolve("source.zip"),Base64.getDecoder().decode((String)bytes.get("base64")));Files.writeString(root.resolve("archive-sha"),(String)artifact.get("sha256"));Files.writeString(root.resolve("source-machine-id"),(String)call("openpnp_get_status",new LinkedHashMap<>()).get("machine_id"));check(!c.getMachine().isEnabled()&&!c.getMachine().isHomed(),"export does not acquire native motion authority");
            }else {
                launch=NativePortableLaunch.claim(root.resolve("adopted"),root.resolve("new-journal"));c=launch.initialize();bridge=new Bridge(c,token,launch.journalDirectory,samples,0,true,"adopted-simulator",null,launch);session=(String)call("openpnp_request_control_session",Bridge.map("request_id",UUID.randomUUID().toString(),"ttl_seconds",300)).get("session_id");Map<String,Object> cap=call("openpnp_get_capabilities",new LinkedHashMap<>());check("adopted-simulator".equals(cap.get("simulator_profile")),"adopted profile explicit");check(!Files.readString(root.resolve("source-machine-id")).equals(cap.get("machine_id")),"adopted journal has distinct native identity");check(!c.getMachine().isEnabled()&&!c.getMachine().isHomed(),"first launch disabled/unhomed");long feedsBefore=feeds(c);check(feedsBefore==Long.parseLong(Files.readString(root.resolve("source-feeds"))),"captured source material counts retained without native feed");check(((AbstractSettlingCamera)c.getMachine().getDefaultHead().getDefaultCamera()).getSettleTimeMs()==7,"camera timing retained without acceleration");check(((ReferenceNozzle)c.getMachine().getDefaultHead().getDefaultNozzle()).getPickDwellMilliseconds()==3,"native nozzle dwell retained");
                Path injected=c.getScripting().getScriptsDirectory().toPath().resolve("blocked.js");Files.writeString(injected,"throw 'should not evaluate'");try{c.getScripting().execute(injected.toFile());throw new AssertionError("Active script evaluated");}catch(org.openpnp.scripting.Scripting.ExecutionRejected expected){checks++;}finally{Files.delete(injected);}
                run("openpnp_set_machine_enabled",Bridge.map("enabled",true));run("openpnp_home_machine",new LinkedHashMap<>());Map<String,Object> prepared=result(run("openpnp_prepare_job",Bridge.map("sample","pnp-test")));run("openpnp_validate_job",new LinkedHashMap<>());
                // The complete native sample demonstrates imported settings operating; every placement is native.
                Map<String,Object> completed=result(run("openpnp_start_job",Bridge.map("job_id",prepared.get("job_id"))));check(((Number)completed.get("placed")).intValue()==32,"actual native sample completes under adopted settings");check(feeds(c)-feedsBefore==32,"adopted native sample has exactly32 feeds for32 placements");run("openpnp_set_machine_enabled",Bridge.map("enabled",false));int pipelineCount=0;for(String file:List.of("machine.xml","vision-settings.xml")){org.w3c.dom.Document xml=NativePortableConfiguration.xml(Files.readAllBytes(c.getConfigurationDirectory().toPath().resolve(file)));for(String tag:List.of("pipeline","cv-pipeline")){org.w3c.dom.NodeList pipelines=xml.getElementsByTagName(tag);for(int i=0;i<pipelines.getLength();i++){NativePortablePipelines.validate((org.w3c.dom.Element)pipelines.item(i));pipelineCount++;}}}check(pipelineCount>0,"stock-derived pipeline profile retains native parameter-written fields after actual processing");java.lang.reflect.Field jobField=Bridge.class.getDeclaredField("job");jobField.setAccessible(true);Job sourceJob=(Job)jobField.get(bridge);Map<String,Boolean> sourceHistory=new TreeMap<>(sourceJob.getPlacedStatusSnapshot());Map<String,String> sourceBoards=new TreeMap<>();for(Board sourceBoard:c.getBoards())sourceBoards.put(sourceBoard.getFile().toString(),NativePortableConfiguration.sha(Files.readAllBytes(sourceBoard.getFile().toPath())));Map<String,Object> library=NativePortableConfiguration.export(c,root.resolve("library.zip"));check(sourceHistory.equals(sourceJob.getPlacedStatusSnapshot()),"portable export preserves exact source native placed history");for(var boardFile:sourceBoards.entrySet())check(boardFile.getValue().equals(NativePortableConfiguration.sha(Files.readAllBytes(Paths.get(boardFile.getKey())))),"source board bytes retained after used-library export");Files.writeString(root.resolve("library-sha"),(String)library.get("sha256"));Files.writeString(root.resolve("library-board-count"),Integer.toString(c.getBoards().size()));Files.writeString(root.resolve("library-source-feeds"),Long.toString(feeds(c)));check(!c.getBoards().isEmpty(),"used sample board library now exports after native32placements");check(feeds(c)-feedsBefore==32,"post-job profile checks cannot consume material");
            }
            System.out.println("OPENPNP_PORTABLE_JOURNEY_PHASE "+G.toJson(Bridge.map("phase",phase,"checks",checks,"hardware_qualified",false)));
        }catch(Throwable failure){failure.printStackTrace();exit=1;}finally{if(bridge!=null)bridge.close();if(launch!=null)launch.close();else if(c!=null)c.getMachine().close();}System.exit(exit);
    }
    static long feeds(Configuration c){long count=0;for(org.openpnp.spi.Feeder f:c.getMachine().getFeeders()){if(f instanceof org.openpnp.machine.reference.feeder.ReferenceStripFeeder)count+=((org.openpnp.machine.reference.feeder.ReferenceStripFeeder)f).getFeedCount();else if(f instanceof org.openpnp.machine.reference.feeder.ReferenceTrayFeeder)count+=((org.openpnp.machine.reference.feeder.ReferenceTrayFeeder)f).getFeedCount();}return count;}
    static Map<String,Object> call(String method,Map<String,Object> fields)throws Exception{return(Map<String,Object>)bridge.call(method,G.toJsonTree(new LinkedHashMap<>(fields)).getAsJsonObject());}
    static Map<String,Object> run(String method,Map<String,Object> fields)throws Exception{Map<String,Object> args=Bridge.map("request_id",UUID.randomUUID().toString(),"session_id",session,"expected_config_revision",call("openpnp_get_status",new LinkedHashMap<>()).get("config_revision"));args.putAll(fields);Map<String,Object> op=call(method,args);String id=(String)op.get("operation_id");long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(60);while(System.nanoTime()<end){op=call("openpnp_get_operation",Bridge.map("operation_id",id));if("succeeded".equals(op.get("state"))&&!Configuration.get().getMachine().isBusy())return op;if(Set.of("failed","outcome_unknown","aborted").contains(op.get("state")))throw new AssertionError(op);Thread.sleep(10);}throw new AssertionError("Timeout "+op);}
    static Map<String,Object> result(Map<String,Object> op){return(Map<String,Object>)op.get("result");}
}
