/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;
import org.openpnp.model.Abstract2DLocatable.Side;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.spi.*;

/** Real native feed/place hooks establish retained facts; model-only edits then exercise admission.
 * No failed admission executes a processor step, feeder, or board setter. */
public final class NativeBoardHistoryAdmissionTest {
 static final List<String> checks=new ArrayList<>();static NativeBoardLoads loads;static NativeBoardLoadsTest.Recorder recorder;static Job job;static Machine machine;
 interface Checked {void run()throws Exception;}
 static void check(boolean ok,String text){if(!ok)throw new AssertionError(text);checks.add(text);}
 static <T>T task(Callable<T> c)throws Exception {return task(c,false);}
 static <T>T task(Callable<T> c,boolean ignoreEnabled)throws Exception {try{return machine.submit(c,null,ignoreEnabled).get(45,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Exception)throw (Exception)e.getCause();throw e;}}
 static int feeds(){int total=0;for(Feeder f:machine.getFeeders())if(f instanceof ReferenceTrayFeeder)total+=((ReferenceTrayFeeder)f).getFeedCount();return total;}
 static String loadId(String root){for(Object o:(List<?>)loads.snapshot().get("roots")){Map<?,?> row=(Map<?,?>)o;if(root.equals(row.get("root_instance_id")))return(String)row.get("load_id");}throw new AssertionError(root);}
 static Map<?,?> load(String id){for(Object o:(List<?>)loads.snapshot().get("loads")){Map<?,?> row=(Map<?,?>)o;if(id.equals(row.get("load_id")))return row;}throw new AssertionError(id);}
 static void reject(String label,Checked c)throws Exception {byte[] before=Files.readAllBytes(recorder.path);Map<String,Boolean> history=job.getPlacedStatusSnapshot();String revision=loads.revision();int count=feeds();List<Side> sides=new ArrayList<>();for(BoardLocation b:job.getBoardLocations())sides.add(b.getGlobalSide());try{c.run();throw new AssertionError("admitted "+label);}catch(Bridge.Fault expected){check("BOARD_LOAD_HISTORY_MISMATCH".equals(expected.code),label+" explicit history refusal");}check(Arrays.equals(before,Files.readAllBytes(recorder.path))&&feeds()==count&&history.equals(job.getPlacedStatusSnapshot())&&revision.equals(loads.revision()),label+" leaves journal/native history/feed count/revision unchanged");int i=0;for(BoardLocation b:job.getBoardLocations())check(sides.get(i++)==b.getGlobalSide(),label+" does not change native side");}
 static void noEffectReady(String label)throws Exception {byte[] before=Files.readAllBytes(recorder.path);int count=feeds();loads.requireReady(job);loads.ledgerScope(job);check(Arrays.equals(before,Files.readAllBytes(recorder.path))&&feeds()==count,label+" admits without an effect or new journal record");}
 static void runNativeJob()throws Exception {loads.requireReady(job);Map<String,Object> scope=loads.ledgerScope(job);NativeActionLedger ledger=new NativeActionLedger((type,payload)->{recorder.append(type,payload);loads.observeNativeEvent(type,payload);},"history-admission-native-op","history-admission-job","cfg-1",(String)scope.get("scope_id"),job,scope);machine.getPnpJobProcessor().initialize(job);boolean more;long step=0;do{try(NativeActionLedger.StepScope s=ledger.openStep(++step)){more=machine.getPnpJobProcessor().next();s.complete();}}while(more);machine.getMotionPlanner().waitForCompletion(null,MotionPlanner.CompletionType.WaitForStillstand);loads.checkpoint(job);loads.publishSnapshot();}
 public static void main(String[] args)throws Exception {
  Path root=Files.createTempDirectory("native-board-history-admission-");Configuration.initialize(root.resolve("config").toFile());Configuration config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);machine=config.getMachine();int exit=0;
  try(NativeBoardLoadsTest.Recorder r=new NativeBoardLoadsTest.Recorder(root.resolve("loads.jsonl"))){recorder=r;loads=new NativeBoardLoads(r::append);
   task(()->{job=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(config.getPart("R0603-1K")));loads.bindJob(job,"history-admission-job",true);noEffectReady("new empty native boards");machine.setEnabled(true);machine.home();runNativeJob();return null;},true);
   BoardLocation a=job.getBoardLocations().get(0),b=job.getBoardLocations().get(1);String rootA=a.getUniqueId(),oldA=loadId(rootA),oldB=loadId(b.getUniqueId());
   check(feeds()==2&&job.retrievePlacedStatus(a,"R1")&&job.retrievePlacedStatus(b,"R1"),"two real native placements established separate retained completion facts");
   long checkpoints=Files.readAllLines(recorder.path).stream().map(NativeJournalJson::parseObject).filter(e->"native_placement_checkpoint".equals(e.get("type"))).count();long completedHooks=Files.readAllLines(recorder.path).stream().map(NativeJournalJson::parseObject).filter(e->"native_placement_checkpoint".equals(e.get("type"))&&"native-placement-complete-hook".equals(((Map<?,?>)e.get("payload")).get("state"))).count();check(checkpoints==6&&completedHooks==2,"two actual native placements each retain starting, before-assembly, and completion checkpoints");
   task(()->{noEffectReady("unchanged genuine native completion history");
    job.removePlacedStatus(a,"R1");reject("removed completed key requireReady",()->loads.requireReady(job));reject("removed completed key ledgerScope",()->loads.ledgerScope(job));reject("removed completed key same-load",()->loads.change(job,rootA,"same-load","top",oldA,loads.revision(),false));reject("removed completed key flip",()->loads.change(job,rootA,"flip","bottom",oldA,loads.revision(),false));job.storePlacedStatus(a,"R1",true);
    job.storePlacedStatus(a,"R1",false);reject("true-to-false requireReady",()->loads.requireReady(job));reject("true-to-false ledgerScope",()->loads.ledgerScope(job));reject("true-to-false same-load",()->loads.change(job,rootA,"same-load","top",oldA,loads.revision(),false));reject("true-to-false flip",()->loads.change(job,rootA,"flip","bottom",oldA,loads.revision(),false));job.storePlacedStatus(a,"R1",true);
    job.storePlacedStatus(a,"opaque-false-key",false);noEffectReady("new native false history key");loads.checkpoint(job);job.removePlacedStatus(a,"opaque-false-key");reject("removed retained false key",()->loads.requireReady(job));job.storePlacedStatus(a,"opaque-false-key",false);
    job.storePlacedStatus(a,"opaque-false-key",true);noEffectReady("native false-to-true advance");job.storePlacedStatus(a,"opaque-false-key",false); // direct model stimulus was not a placement hook or checkpoint.
    job.storePlacedStatus(b,"new-uncheckpointed-key",false);noEffectReady("new key on other native root");job.removePlacedStatus(b,"new-uncheckpointed-key");
    loads.change(job,rootA,"same-load","top",oldA,loads.revision(),false);noEffectReady("exact same-load after restored facts");loads.change(job,rootA,"flip","bottom",oldA,loads.revision(),false);noEffectReady("flip retains genuine completed top-side history");check(loadId(rootA).equals(oldA)&&loadId(b.getUniqueId()).equals(oldB),"same-load and flip preserve both load identities");
    job.removePlacedStatus(a,"R1");reject("flipped native history regressed",()->loads.requireReady(job));
    loads.change(job,rootA,"replace","bottom",oldA,loads.revision(),false);noEffectReady("explicit replacement has a new empty history");check(!loadId(rootA).equals(oldA)&&loadId(b.getUniqueId()).equals(oldB),"explicit replacement changes only selected load identity");check(((Number)load(oldA).get("placed_history_count")).intValue()==1&&((Number)load(oldA).get("native_history_entries")).intValue()==2,"replacement preserves old true and opaque-false retired facts even when native key was removed");check(job.retrievePlacedStatus(b,"R1")&&!job.retrievePlacedStatus(a,"R1"),"replacement clears only selected new-board scope");check(feeds()==2,"all model mutation and rejection cases perform no additional feed");return null;});
   byte[] journal=Files.readAllBytes(recorder.path);NativeBoardLoads recovered=new NativeBoardLoads((t,p)->{throw new AssertionError("recovery must not append");});for(String line:Files.readAllLines(recorder.path)){Map<String,Object> e=NativeJournalJson.parseObject(line);recovered.recoverEvent((String)e.get("type"),(Map<String,Object>)e.get("payload"));recovered.observeNativeEvent((String)e.get("type"),(Map<String,Object>)e.get("payload"));}recovered.finishRecovery();recovered.bindJob(job,"recovered-no-authority",false);try{recovered.requireReady(job);throw new AssertionError("recovery restored presence");}catch(Bridge.Fault expected){check("BOARD_LOAD_REQUIRED".equals(expected.code),"replay never restores ready authority");}check(Arrays.equals(journal,Files.readAllBytes(recorder.path))&&feeds()==2,"replay does not append or repeat feed");
   System.out.println("NATIVE_BOARD_HISTORY_ADMISSION_RESULT "+new Gson().toJson(Bridge.map("passed",true,"assertions",checks.size(),"checks",checks,"actual_native_placements",2,"actual_native_feeds",feeds(),"actual_completed_placement_hooks",completedHooks,"producer_emitted_checkpoints",checkpoints,"model_only_regression_stimuli",true,"physical_qualification",false,"process_restart_test",false)));
  }catch(Throwable failure){failure.printStackTrace();exit=1;}finally{machine.close();}System.exit(exit);
 }
}
