/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;
import org.openpnp.machine.reference.ReferenceFeeder;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.spi.*;

/** Native models/setters + forced local journal; explicit synthetic hook tests perform no feed. */
public final class NativeMaterialLoadsBoundaryTest {
 static final Gson G=new Gson();static final List<String> checks=new ArrayList<>();static Configuration config;static ReferenceTrayFeeder tray;static Path root;static int serial;
 static class Recorder implements AutoCloseable{final Path file;final FileChannel channel;final NativeMaterialLoads material;String failType;boolean failAfterForce;long seq;
  Recorder(String name)throws Exception{file=root.resolve(name+".jsonl");channel=FileChannel.open(file,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE);material=new NativeMaterialLoads(config,this::append);}
  void append(String type,Map<String,Object> payload)throws Exception{Runnable commit=material.prepareEvent(type,payload);boolean fail=type.equals(failType);if(fail&&!failAfterForce)throw new IOException("injected before force");byte[] bytes=(G.toJson(Bridge.map("sequence",++seq,"type",type,"payload",payload))+"\n").getBytes(StandardCharsets.UTF_8);ByteBuffer b=ByteBuffer.wrap(bytes);while(b.hasRemaining())channel.write(b);channel.force(true);if(fail)throw new IOException("injected force returned uncertain after actual force");commit.run();}
  public void close()throws Exception{channel.close();}
 }
 public static void main(String[] args)throws Exception{root=(args.length>1?Paths.get(args[1]):Files.createTempDirectory("material-load-native-"));int code=0;Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);for(Feeder f:config.getMachine().getFeeders())if(f.getPart()==config.getPart("R0603-1K"))tray=(ReferenceTrayFeeder)f;tray.setTrayCountX(3);tray.setTrayCountY(2);tray.setOffsets(new Location(LengthUnit.Millimeters,2,3,0,0));tray.setFeedCount(2);
 try{
  try(Recorder r=new Recorder("guards")){
   expect("MATERIAL_OWNER_REQUIRED",()->bind(r));check(Files.size(r.file)==0&&tray.getFeedCount()==2,"foreign-thread call fails before write/setter");
   Part canonical=tray.getPart();org.openpnp.model.Package canonicalPackage=canonical.getPackage();
   task(()->{Part unregistered=new Part(canonical.getId());unregistered.setPackage(canonicalPackage);unregistered.setHeight(canonical.getHeight());tray.setPart(unregistered);try{expect("MATERIAL_MODEL_CHANGED",()->bind(r));}finally{tray.setPart(canonical);}canonical.setPackage(new org.openpnp.model.Package(canonicalPackage.getId()));try{expect("MATERIAL_MODEL_CHANGED",()->bind(r));}finally{canonical.setPackage(canonicalPackage);}return null;});
   check(Files.size(r.file)==0&&tray.getFeedCount()==2,"noncanonical part/package identities reject before forced intent or index mutation");
   task(()->{bind(r);return null;});Map<?,?> original=load(r.material,0);String id=(String)original.get("load_id");check(num(original,"initial_index")==2&&num(original,"current_index")==2&&num(original,"observed_advances")==0,"binding a nonzero index records baseline separately from observed consumption");
   Location expected=tray.getLocation().add(tray.getOffsets().multiply(0,1,0,0));check(tray.getPickLocation().equals(expected),"nonzero binding preserves the native current pick-location geometry");
   long bytes=Files.size(r.file);task(()->{expect("MATERIAL_ALREADY_BOUND",()->r.material.register(tray.getId(),tray.getPart().getId(),fp(),"bind-existing",id,r.material.revision()));expect("MATERIAL_REVISION_CONFLICT",()->replace(r,id,"material-0"));expect("MATERIAL_LOAD_CONFLICT",()->replace(r,UUID.randomUUID().toString(),r.material.revision()));return null;});check(Files.size(r.file)==bytes&&tray.getFeedCount()==2,"stale/repeated/wrong-load guards have no journal/index change");
   Location previous=tray.getLocation();task(()->{tray.setLocation(new Location(LengthUnit.Inches,previous.getX(),previous.getY(),previous.getZ(),previous.getRotation()));expect("MATERIAL_MODEL_CHANGED",r.material::requireReady);tray.setLocation(previous);r.material.requireReady();return null;});check(Files.size(r.file)==bytes,"same numeric coordinates with changed native units cannot retain geometry authority");
   task(()->{tray.setFeedOptions(ReferenceFeeder.FeedOptions.SkipNext);expect("MATERIAL_MODEL_CHANGED",r.material::requireReady);tray.setFeedOptions(ReferenceFeeder.FeedOptions.Normal);r.material.requireReady();return null;});
   task(()->{tray.setFeedCount(1);expect("MATERIAL_INDEX_CHANGED",r.material::requireReady);tray.setFeedCount(2);r.material.requireReady();return null;});
   expect(UnsupportedOperationException.class,()->((Map<String,Object>)load(r.material,0)).put("current_index",0));check(Files.size(r.file)==bytes,"public snapshots cannot edit reducer history");
   List<Map<String,Object>> records=records(r.file);NativeMaterialLoads recovered=replay(records);check(Boolean.FALSE.equals(load(recovered,0).get("native_authority")),"replayed loaded record has no native authority");task(()->{expect("MATERIAL_REATTACH_UNSUPPORTED",recovered::requireReady);return null;});
   malformed(records,"extra-field",p->p.put("unrecognized",1));malformed(records,"string-count",p->row(p).put("current_index","2"));malformed(records,"fraction-count",p->row(p).put("initial_index",2.5));malformed(records,"near-integer-count",p->row(p).put("initial_index",new java.math.BigDecimal("2.00000000000000001")));malformed(records,"near-integer-revision",p->p.put("revision",new java.math.BigDecimal("1.00000000000000001")));malformed(records,"wrong-UUID",p->row(p).put("load_id","1-1-1-1-1"));malformed(records,"false-schema",p->p.put("schema_version",true));malformed(records,"negative-before",p->p.put("before_index",-1));malformed(records,"different-geometry",p->row(p).put("geometry_sha256","0".repeat(64))); // apply this one only to outcome
   Map<String,Object> context=Bridge.map("feeder_id",tray.getId(),"part_id",tray.getPart().getId(),"material_load",task(()->r.material.beforeFeed(tray)));
   Map<String,Object> intent=Bridge.map("action_id","offline-native-action-1","operation_id","offline-op","kind","feed","hook","Feeder.BeforeFeed","state","intent","physical_outcome","unknown","context",context);
   List<Map<String,Object>> prefix=G.fromJson(G.toJson(records),List.class);prefix.add(Bridge.map("type","native_action_intent","payload",intent));
   Map<String,Object> outcome=G.fromJson(G.toJson(intent),Map.class);outcome.put("state","native_hook_returned");outcome.put("after_hook","Feeder.AfterFeed");outcome.put("material_after",Bridge.map("after_index",3,"expected_delta_observed",true,"observation","native-feedCount-at-after-hook","physical_inventory_verified",false));prefix.add(Bridge.map("type","native_action_outcome","payload",outcome));
   NativeMaterialLoads valid=replay(G.fromJson(G.toJson(prefix),List.class));check(num(load(valid,0),"observed_advances")==1&&tray.getFeedCount()==2,"offline synthetic DTO sequence validates exactly one observation with no native effect");
   for(String mutation:List.of("intent-state","intent-hook","context-part","outcome-hook","delta-boolean")){List<Map<String,Object>> bad=G.fromJson(G.toJson(prefix),List.class);Map<String,Object> ip=(Map<String,Object>)bad.get(2).get("payload"),op=(Map<String,Object>)bad.get(3).get("payload");if(mutation.equals("intent-state"))ip.put("state","failed");if(mutation.equals("intent-hook"))ip.put("hook","Other.BeforeFeed");if(mutation.equals("context-part"))((Map<String,Object>)ip.get("context")).put("part_id","other");if(mutation.equals("outcome-hook"))op.put("after_hook","Other.AfterFeed");if(mutation.equals("delta-boolean"))((Map<String,Object>)op.get("material_after")).put("expected_delta_observed","true");expect("MATERIAL_RECORD_INVALID",()->replay(bad));check(tray.getFeedCount()==2,"malformed feed "+mutation+" cannot change native index");}
  }
  tray.setFeedCount(2);try(Recorder r=new Recorder("intent-failure")){r.failType="material_load_intent";task(()->{expect(IOException.class,()->bind(r));return null;});check(tray.getFeedCount()==2&&Files.size(r.file)==0&&((List<?>)r.material.snapshot().get("loads")).isEmpty(),"failed intent force precedes every setter and published load");}
  tray.setFeedCount(2);try(Recorder r=new Recorder("setter-failure")){task(()->{bind(r);return null;});String id=(String)load(r.material,0).get("load_id");PropertyChangeListener fail=e->{if("feedCount".equals(e.getPropertyName()))throw new IllegalStateException("injected native setter failure");};tray.addPropertyChangeListener(fail);try{task(()->{expect(IllegalStateException.class,()->replace(r,id,r.material.revision()));return null;});}finally{tray.removePropertyChangeListener(fail);}check(tray.getFeedCount()==0&&((List<?>)r.material.snapshot().get("pending_changes")).size()==1&&num(load(r.material,0),"current_index")==2,"post-setter failure preserves previous index evidence plus unresolved new load");NativeMaterialLoads after=replay(records(r.file));task(()->{expect("MATERIAL_OUTCOME_UNKNOWN",after::requireReady);return null;});check(tray.getFeedCount()==0,"replay after setter failure never repeats reset");}
  tray.setFeedCount(2);try(Recorder r=new Recorder("outcome-failure")){task(()->{bind(r);return null;});String id=(String)load(r.material,0).get("load_id");r.failType="material_load_outcome";task(()->{expect(IOException.class,()->replace(r,id,r.material.revision()));return null;});check(tray.getFeedCount()==0&&((List<?>)r.material.snapshot().get("pending_changes")).size()==1,"failed outcome publication retains uncertain changed native index");check(((List<?>)replay(records(r.file)).snapshot().get("pending_changes")).size()==1,"outcome failure replay preserves unmatched intent");}
  tray.setFeedCount(2);try(Recorder r=new Recorder("forced-then-thrown")){r.failType="material_load_intent";r.failAfterForce=true;task(()->{expect(IOException.class,()->bind(r));return null;});check(tray.getFeedCount()==2&&((List<?>)r.material.snapshot().get("loads")).isEmpty(),"force-return uncertainty leaves old in-memory state and no setter");check(((List<?>)replay(records(r.file)).snapshot().get("pending_changes")).size()==1,"actual forced intent remains discoverable after force-return uncertainty");}
  tray.setFeedCount(2);try(Recorder r=new Recorder("missing-hook-outcome")){task(()->{bind(r);Job job=new Job();NativeActionLedger ledger=new NativeActionLedger(r::append,"synthetic-hook-op","synthetic-job","cfg-1","synthetic-board",job).withMaterialObserver(r.material);Map<String,Object> argsMap=Bridge.map("nozzle",config.getMachine().getDefaultHead().getDefaultNozzle(),"feeder",tray,"part",tray.getPart());expect(NativeActionLedger.UnresolvedActionFence.class,()->{try(NativeActionLedger.StepScope scope=ledger.openStep(1)){config.getScripting().on("Feeder.BeforeFeed",argsMap);}});expect(NativeActionLedger.UnresolvedActionFence.class,()->ledger.openStep(2));expect("MATERIAL_OUTCOME_UNKNOWN",r.material::requireReady);expect("MATERIAL_OUTCOME_UNKNOWN",()->replace(r,(String)load(r.material,0).get("load_id"),r.material.revision()));return null;});check(tray.getFeedCount()==2&&((List<?>)r.material.snapshot().get("pending_feeds")).size()==1,"explicit synthetic before-hook without after-hook is unknown and cannot authorize a retry/reset");NativeMaterialLoads replay=replay(records(r.file));check(((List<?>)replay.snapshot().get("pending_feeds")).size()==1,"missing feed outcome survives replay without inventing consumption");}
  System.out.println("MATERIAL_LOAD_BOUNDARY_RESULT "+G.toJson(Bridge.map("passed",true,"assertions",checks.size(),"checks",checks,"native_feed_calls",0,"native_placements",0,"synthetic_hook_contract_case",true,"native_tray_index_setter_fault",true,"real_FileChannel_force",true,"physical_inventory_verified",false,"simulation_only",true)));
 }catch(Throwable t){t.printStackTrace();code=1;}finally{try{config.getMachine().close();}catch(Throwable t){t.printStackTrace();code=1;}}System.exit(code);}
 static Map<String,Object> bind(Recorder r)throws Exception{return r.material.register(tray.getId(),tray.getPart().getId(),fp(),"bind-existing",null,r.material.revision());}
 static Map<String,Object> replace(Recorder r,String id,String revision)throws Exception{return r.material.register(tray.getId(),tray.getPart().getId(),fp(),"replace-full-tray",id,revision);}
 static String fp()throws Exception{return (String)NativeMaterialLoads.describe(tray).get("geometry_sha256");}
 static <T>T task(Callable<T> c)throws Exception{try{return config.getMachine().submit(c,null,true).get(15,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Error)throw (Error)e.getCause();if(e.getCause() instanceof Exception)throw (Exception)e.getCause();throw e;}}
 static Map<String,Object> load(NativeMaterialLoads m,int i){return (Map<String,Object>)((List<?>)m.snapshot().get("loads")).get(i);}static int num(Map<?,?> m,String k){return ((Number)m.get(k)).intValue();}
 static List<Map<String,Object>> records(Path p)throws Exception{List<Map<String,Object>> rows=new ArrayList<>();for(String line:Files.readAllLines(p))rows.add(NativeJournalJson.parseObject(line));return rows;}
 static NativeMaterialLoads replay(List<Map<String,Object>> rows)throws Exception{NativeMaterialLoads n=new NativeMaterialLoads(config,(t,p)->{throw new AssertionError("Replay must not append");});for(Map<String,Object> e:rows)n.recoverEvent((String)e.get("type"),(Map<String,Object>)e.get("payload"));n.finishRecovery();return n;}
 static Map<String,Object> row(Map<String,Object> p){return (Map<String,Object>)p.get("record");}interface Edit{void edit(Map<String,Object> p)throws Exception;}
 static void malformed(List<Map<String,Object>> rows,String name,Edit edit)throws Exception{List<Map<String,Object>> copy=G.fromJson(G.toJson(rows),List.class);edit.edit((Map<String,Object>)copy.get(name.equals("different-geometry")?1:0).get("payload"));expect("MATERIAL_RECORD_INVALID",()->replay(copy));check(tray.getFeedCount()==2,"malformed "+name+" rejects with no native index effect");}
 interface Checked{void run()throws Exception;}static void expect(String code,Checked action)throws Exception{try{action.run();throw new AssertionError("Expected "+code);}catch(Bridge.Fault f){check(code.equals(f.code),"reject "+code);}}static void expect(Class<? extends Throwable> kind,Checked action)throws Exception{try{action.run();throw new AssertionError("Expected "+kind);}catch(Throwable t){if(!kind.isInstance(t))throw t;check(true,"reject "+kind.getSimpleName());}}static void check(boolean ok,String text){if(!ok)throw new AssertionError(text);checks.add(text);}
}
