/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.io.*;
import java.lang.reflect.*;
import java.nio.*;
import java.nio.channels.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
import org.openpnp.spi.*;

/** Actual native components and forced journal. Original sensing/action faults and wrapper-completion
 * observations are explicit synthetic contract fixtures. No Bridge, job execution, or reattachment. */
public final class NativeReplacementContinuationTest {
 static final Gson JSON=new GsonBuilder().serializeNulls().create();static Configuration config;static Path root;
 static ReferenceTrayFeeder tray,otherTray;static int checks,refusals;static final List<Map<String,Object>> cases=new ArrayList<>();
 interface Work{void run()throws Exception;}static void yes(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}
 static void no(String why,Work work)throws Exception{try{work.run();throw new AssertionError("Accepted "+why);}catch(IOException|Bridge.Fault|NativeJobLineage.Fault expected){checks++;refusals++;}}
 static Map<String,Object> m(Object... values){return NativeFaultedJobReplacement.map(values);}static Map<String,Object> o(Object value)throws IOException{return NativeFaultedJobReplacement.object(value);}static String id(){return UUID.randomUUID().toString();}
 static <T>T task(Callable<T> work)throws Exception{try{return config.getMachine().submit(work,null,true).get(30,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Error)throw(Error)e.getCause();throw(Exception)e.getCause();}}
 static void initialize(Path directory)throws Exception{root=directory;Files.createDirectory(root);Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);for(Feeder f:config.getMachine().getFeeders()){if(f.getPart()==config.getPart("R0603-1K"))tray=(ReferenceTrayFeeder)f;if(f.getPart()==config.getPart("R0402-1K"))otherTray=(ReferenceTrayFeeder)f;}tray.setTrayCountX(3);tray.setTrayCountY(2);otherTray.setTrayCountX(3);otherTray.setTrayCountY(2);}
 static final class Env implements AutoCloseable {
  final String jobId=id(),aliasId=id(),opId=id(),requestId=id();final NativeMaterialLoads material;final NativeBoardLoads boards;final NativeJobLineage lineage;final NativeFaultedJobReplacement replacement;final Path file;final FileChannel channel;
  final List<Map<String,Object>> events=new ArrayList<>();Job oldJob,freshJob;Map<String,Object> operation,oldMaterial,oldBoard,oldLineage;NativeFaultedJobReplacement.Capture capture;NativeFaultedJobReplacement.Permit permit;NativeSensingReconciliation.Capture faultCapture;NativeSensingReconciliation coordinator;NativeVacuumJournal vacuum;final Object localOwner=new Object();final Set<String> terminalWrappers=new HashSet<>();int terminalChecks;String failType;boolean failAfterForce;int failOccurrence=1,seenFailures;long seq;NativeReplacementJob.Candidate candidate;String taskId;
  Env(String name,boolean replay)throws Exception {
   file=root.resolve(name+".jsonl");channel=FileChannel.open(file,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE);lineage=new NativeJobLineage(this::append);boards=new NativeBoardLoads(this::append);material=new NativeMaterialLoads(config,this::append);replacement=new NativeFaultedJobReplacement(config,material,boards,lineage,this::append,op->{terminalChecks++;return terminalWrappers.contains(op);});
   if(!replay)task(()->{otherTray.setFeedCount(2);material.register(otherTray.getId(),otherTray.getPart().getId(),(String)NativeMaterialLoads.describe(otherTray).get("geometry_sha256"),"bind-existing",null,material.revision());tray.setFeedCount(2);material.register(tray.getId(),tray.getPart().getId(),(String)NativeMaterialLoads.describe(tray).get("geometry_sha256"),"bind-existing",null,material.revision());oldJob=CanonicalJobImporter.load(config,NativeBoardLoadsTest.canonical(tray.getPart()));lineage.createFresh(jobId,"canonical-simulator");Map<String,Object> lineageFacts=lineage.admissionFacts(jobId);lineage.bindDocument(jobId,"b".repeat(64));lineage.bindReload(aliasId,"b".repeat(64),(String)lineageFacts.get("lineage_id"),((Number)lineageFacts.get("lineage_revision")).longValue());boards.bindJob(oldJob,jobId,true);BoardLocation board=oldJob.getBoardLocations().get(0);oldJob.storePlacedStatus(board,"R1",true);boards.checkpoint(oldJob);
     operation=m("operation_id",opId,"job_id",jobId,"job_revision",boards.jobRevision(),"board_load_revision",boards.revision(),"request_id",requestId,"request_digest","a".repeat(64),"config_revision","cfg-2","method","openpnp_start_job","job_lineage",lineage.admissionFacts(jobId),"state","accepted");append("operation",operation);
     Map<String,Object> loadScope=boards.ledgerScope(oldJob);NativeActionLedger ledger=new NativeActionLedger(this::append,opId,jobId,"cfg-2",(String)loadScope.get("scope_id"),oldJob,loadScope).withMaterialObserver(material);
     try(NativeActionLedger.StepScope step=ledger.openStep(1)){config.getScripting().on("Feeder.BeforeFeed",m("nozzle",config.getMachine().getDefaultHead().getDefaultNozzle(),"feeder",tray,"part",tray.getPart()));tray.setFeedCount(3);}catch(NativeActionLedger.UnresolvedActionFence expected){}
     operation.put("state","outcome_unknown");append("operation",operation);oldMaterial=material.captureReplacementState();oldBoard=boards.captureReplacementState(jobId);oldLineage=lineage.captureReplacementState(jobId);capture=replacement.capture(oldJob,jobId,opId);candidate=NativeReplacementJob.build(config,oldJob);freshJob=candidate.job();return null;});
  }
  void append(String type,Map<String,Object> p)throws Exception {
   Runnable mat=material==null?()->{}:material.prepareEvent(type,p);Runnable lin=lineage==null||type.startsWith("job_lineage_")?()->{}:lineage.prepareObservation(type,p);
   Runnable continuation=replacement==null?()->{}:replacement.prepareContinuationObservation(type,p);Runnable sensing=coordinator!=null&&NativeSensingReconciliation.matches(type)?coordinator.prepare(type,p,NativeSensingReconciliationTest.INSTANCE):()->{};Runnable observation=vacuum!=null&&NativeVacuumJournal.matches(type)?vacuum.prepare(type,p,NativeSensingReconciliationTest.INSTANCE):()->{};
   boolean fail=type.equals(failType)&&++seenFailures==failOccurrence;
   if(fail&&!failAfterForce)throw new IOException("injected before force: "+type);Map<String,Object> event=NativeFaultedJobReplacement.frozen(m("sequence",++seq,"type",type,"payload",p));byte[] bytes=(JSON.toJson(event)+"\n").getBytes(java.nio.charset.StandardCharsets.UTF_8);ByteBuffer buffer=ByteBuffer.wrap(bytes);while(buffer.hasRemaining())channel.write(buffer);channel.force(true);events.add(event);if(fail&&failAfterForce)throw new IOException("injected uncertain return after actual force: "+type);mat.run();lin.run();continuation.run();sensing.run();observation.run();if(boards!=null)boards.observeNativeEvent(type,p);if(replacement!=null)replacement.observe(type,p);
  }
  void admit()throws Exception {
   vacuum=new NativeVacuumJournal();coordinator=new NativeSensingReconciliation(vacuum,(op,instance,replay)->false,replacement::verified);
   String instance=NativeSensingReconciliationTest.INSTANCE,source=NativeSensingReconciliationTest.SOURCE,machine=NativeSensingReconciliationTest.MACHINE;
   Map<String,Object> jobContext=m("job_id",jobId,"job_revision",oldBoard.get("job_revision"),"board_load_revision",oldBoard.get("revision"),"material_setup_revision",oldMaterial.get("revision"),"lineage_id",oldLineage.get("lineage_id"),"lineage_revision",oldLineage.get("lineage_revision"));
   Map<String,Object> context=NativeSensingReconciliationTest.context();context.put("operation_id",opId);context.put("scope","job");context.put("job_context",jobContext);
   Map<String,Object> event=NativeSensingReconciliationTest.event("read.before",100,null,context,source);append("vacuum_observation_intent",event);Map<String,Object> scope=NativeSensingReconciliationTest.scope(instance,source);scope.put("job_context",jobContext);scope.put("dependencies",capture.dependencies());faultCapture=vacuum.captureFaultSet(scope);
   String task=id(),requestOperation=id(),recovery=id();taskId=task;Map<String,Object> taskRecord=coordinator.taskRecord(task,requestOperation,id(),faultCapture,"replace-faulted-job-attempt",1,"2030-01-01T00:00:00Z");append("sensing_reconciliation_task",taskRecord);append("sensing_reconciliation_intent",coordinator.intentRecord(task,recovery,id(),"2026-09-14T00:00:00Z",1,"synthetic-local-test"));NativeSensingReconciliation.Permit recoveryPermit=coordinator.issuePermit(task,recovery,faultCapture.digest,localOwner);
   permit=replacement.begin(capture,freshJob,coordinator,recoveryPermit,localOwner);
  }
  void replay(List<Map<String,Object>> source)throws Exception {for(Map<String,Object> event:source){String t=(String)event.get("type");Map<String,Object> p=o(event.get("payload"));material.recoverEvent(t,p);boards.recoverEvent(t,p);boards.observeNativeEvent(t,p);lineage.observe(t,p);replacement.observe(t,p);if(t.startsWith("faulted_job_replacement_"))replacement.recover(t,p);replacement.prepareContinuationObservation(t,p).run();}material.finishRecovery();boards.finishRecovery();}
  public void close()throws Exception{try{replacement.close();}finally{if(candidate!=null&&!replacement.ownsCandidate(candidate))candidate.close();channel.close();}}
 }
 static final class Fixture implements AutoCloseable {
  final Env e;final String attempt,oldRecovery;final Map<String,Boolean> oldHistory;
  Fixture(String name,String prefix)throws Exception {
   e=new Env(name,false);task(()->{e.admit();if(!prefix.equals("unretained"))e.replacement.retainCandidate(e.permit,e.candidate);return null;});attempt=e.permit.attemptId();oldRecovery=(String)e.coordinator.snapshot(e.taskId).get("recovery_operation_id");oldHistory=new TreeMap<>(e.oldJob.getPlacedStatusSnapshot());
   if(Set.of("lineage","completed","mixed-board","pending-material").contains(prefix))task(()->{e.lineage.createReplacement(e.permit,attempt);return null;});
   if(prefix.equals("pending-material"))task(()->{e.failType="material_replacement_outcome";try{no("controlled pending material boundary",()->e.material.replaceRetiredLoad(e.permit,(String)((List<?>)e.capture.dependencies().get("material_load_ids")).get(0)));}finally{e.failType=null;}return null;});
   if(Set.of("completed","mixed-board").contains(prefix))task(()->{for(Object old:(List<?>)e.capture.dependencies().get("material_load_ids"))e.material.replaceRetiredLoad(e.permit,(String)old);if(prefix.equals("mixed-board")){e.failType="board_replacement_outcome";e.failOccurrence=2;try{no("controlled second board pending boundary",()->e.boards.quarantineAndBindReplacement(e.permit,e.oldJob,e.freshJob,attempt));}finally{e.failType=null;}}else e.boards.quarantineAndBindReplacement(e.permit,e.oldJob,e.freshJob,attempt);return null;});
  }
  Map<String,Object> localOperation(String operation,String task,String digest,String state,boolean terminal){Map<String,Object> row=m("operation_id",operation,"request_id",id(),"request_digest",digest,"bridge_instance_id",NativeSensingReconciliationTest.INSTANCE,"config_revision","cfg-2","method","local_native_sensing_reconciliation","task_id",task,"state",state);if(terminal)row.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",state.equals("succeeded"),"physical_outcome_verified",false));return row;}
  void observeOld(String state,boolean observedWrapper)throws Exception {
   Map<String,Object> previous=null;for(Map<String,Object> event:e.events)if(event.get("type").equals("operation")&&oldRecovery.equals(o(event.get("payload")).get("operation_id")))previous=o(event.get("payload"));
   Map<String,Object> row=previous==null?localOperation(oldRecovery,e.taskId,e.faultCapture.digest,state,!Set.of("accepted","running").contains(state)):NativeFaultedJobReplacement.mutable(previous);row.put("state",state);
   if(!Set.of("accepted","running").contains(state))row.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",state.equals("succeeded"),"physical_outcome_verified",false));
   e.append("operation",row);if(observedWrapper)e.terminalWrappers.add(oldRecovery);
  }
  void closeOriginal(String state)throws Exception {observeOld(state,true);e.permit.close();e.append("sensing_reconciliation_unknown",e.coordinator.unknownRecord(e.taskId,"wrapper_unknown"));}
  NativeFaultedJobReplacement.ContinuationCapture capture()throws Exception{return task(()->e.replacement.captureContinuation(attempt,e.oldJob));}
  Fresh fresh(NativeFaultedJobReplacement.ContinuationCapture captured,String kind)throws Exception{return new Fresh(this,captured,kind);}
  public void close()throws Exception{e.close();}
 }
 static final class Fresh {
  final Fixture fixture;final NativeFaultedJobReplacement.ContinuationCapture capture;final NativeSensingReconciliation coordinator;
  final NativeSensingReconciliation.Capture faultCapture;final NativeSensingReconciliation.Permit permit;final Object owner=new Object();final String taskId=id(),operation=id();
  Fresh(Fixture fixture,NativeFaultedJobReplacement.ContinuationCapture capture,String kind)throws Exception {this(fixture,capture,kind,true);}
  Fresh(Fixture fixture,NativeFaultedJobReplacement.ContinuationCapture capture,String kind,boolean observeActive)throws Exception {
   this.fixture=fixture;this.capture=capture;Env e=fixture.e;coordinator=e.coordinator;
   Map<String,Object> scope=NativeSensingReconciliationTest.scope(NativeSensingReconciliationTest.INSTANCE,NativeSensingReconciliationTest.SOURCE);scope.put("job_context",capture.jobContext());scope.put("dependencies",capture.dependencies());faultCapture=e.vacuum.captureFaultSet(scope);
   Map<String,Object> record=kind.equals("continue-faulted-job-replacement")?coordinator.taskRecordForContinuation(taskId,id(),id(),faultCapture,capture,2,"2030-01-01T00:00:00Z"):coordinator.taskRecord(taskId,id(),id(),faultCapture,kind,2,"2030-01-01T00:00:00Z");
   e.append("sensing_reconciliation_task",record);e.append("sensing_reconciliation_intent",coordinator.intentRecord(taskId,operation,id(),"2026-09-14T00:00:00Z",2,"synthetic-fresh-local-test"));permit=coordinator.issuePermit(taskId,operation,faultCapture.digest,owner);
   if(observeActive){Map<String,Object> admitted=fixture.localOperation(operation,taskId,faultCapture.digest,"running",false);admitted.put("reconciliation_request_id",record.get("request_id"));e.append("operation",admitted);}
  }
  NativeFaultedJobReplacement.ContinuationPermit begin()throws Exception{return task(()->fixture.e.replacement.beginContinuation(capture,coordinator,permit,owner));}
  void revoke()throws Exception{fixture.e.append("sensing_reconciliation_unknown",coordinator.unknownRecord(taskId,"ownership_changed"));}
 }
 static Map<String,Integer> counters(){return Map.of(tray.getId(),tray.getFeedCount(),otherTray.getId(),otherTray.getFeedCount());}
 static Map<String,String> configurationFiles()throws Exception{Map<String,String> result=new TreeMap<>();try(var stream=Files.walk(root.resolve("config"))){for(Path file:stream.filter(Files::isRegularFile).toList()){byte[] hash=MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(file));result.put(root.resolve("config").relativize(file).toString(),HexFormat.of().formatHex(hash)+":"+Files.getLastModifiedTime(file));}}return result;}
 static Map<String,Object> immutableOriginal(Env e)throws Exception {Map<String,Object> result=new LinkedHashMap<>();for(Map<String,Object> event:e.events){String type=(String)event.get("type");Map<String,Object> row=o(event.get("payload"));if((type.equals("operation")||NativeActionLedger.isLedgerEventType(type))&&e.opId.equals(row.get("operation_id")))result.put(type+":"+event.get("sequence"),row);}return NativeFaultedJobReplacement.frozen(result);}
 static void ensurePreserved(Fixture f,Map<String,Object> original)throws Exception {yes(f.oldHistory.equals(f.e.oldJob.getPlacedStatusSnapshot()),"Original native placed history remains exact");yes(NativeFaultedJobReplacement.same(original,immutableOriginal(f.e)),"Original operation and native action records remain immutable");yes(Boolean.FALSE.equals(f.e.replacement.progress(f.attempt).get("execution_authority_restored")),"Progress and continuation receipts grant no execution readiness");}

 static Map<String,Object> state(Env e)throws Exception{Map<String,Object> board=NativeFaultedJobReplacement.mutable(e.boards.snapshot());board.remove("continuation_adoptions");board.remove("continuation_publication_fault");Field binding=NativeBoardLoads.class.getDeclaredField("boundNativeJob"),confirmed=NativeBoardLoads.class.getDeclaredField("confirmed");binding.setAccessible(true);confirmed.setAccessible(true);return m("material",e.material.captureReplacementState(),"boards",board,"board_native_binding_identity",System.identityHashCode(binding.get(e.boards)),"board_confirmations",new TreeSet<>((Set<String>)confirmed.get(e.boards)),"old_lineage",e.lineage.describe(e.jobId),"fresh_lineage",e.lineage.describe(e.permit.attemptId()));}
 static Map<String,Object> freshOperation(Fresh fresh)throws Exception{Map<String,Object> result=null;for(Map<String,Object> event:fresh.fixture.e.events)if("operation".equals(event.get("type"))&&fresh.operation.equals(o(event.get("payload")).get("operation_id")))result=o(event.get("payload"));if(result==null)throw new AssertionError("Fresh active operation absent");return NativeFaultedJobReplacement.mutable(result);}
 static void admissionRefusals()throws Exception {
  try(Fixture f=new Fixture("missing-old-terminal","definition")){f.e.permit.close();Map<String,Integer> before=counters();long bytes=Files.size(f.e.file);no("missing prior local recovery record",f::capture);f.observeOld("running",false);no("prior local recovery is still running",f::capture);f.observeOld("outcome_unknown",false);no("terminal DTO without independently observed wrapper completion",f::capture);yes(before.equals(counters()),"all incomplete original-wrapper refusals preserve counters");yes(Files.size(f.e.file)>bytes,"only explicit synthetic operation records were appended");}
  try(Fixture f=new Fixture("live-old-permit","definition")){f.observeOld("outcome_unknown",true);long bytes=Files.size(f.e.file);no("still-live old replacement permit",f::capture);yes(bytes==Files.size(f.e.file),"live-old-permit refusal appends no record");}
  try(Fixture f=new Fixture("no-retained-candidate","unretained")){f.closeOriginal("failed");no("no retained native candidate",f::capture);}
  try(Fixture f=new Fixture("wrong-native-original","definition")){f.closeOriginal("outcome_unknown");no("foreign attempt",()->task(()->f.e.replacement.captureContinuation(id(),f.e.oldJob)));no("wrong original native Job",()->task(()->f.e.replacement.captureContinuation(f.attempt,f.e.freshJob)));no("capture off native executor",()->f.e.replacement.captureContinuation(f.attempt,f.e.oldJob));}
  try(Fixture f=new Fixture("old-history-drift","definition")){f.closeOriginal("outcome_unknown");task(()->{f.e.oldJob.storePlacedStatus(f.e.oldJob.getBoardLocations().get(0),"R2",true);return null;});no("old native history drift",f::capture);}
  try(Fixture f=new Fixture("candidate-drift","definition")){f.closeOriginal("outcome_unknown");task(()->{f.e.freshJob.getBoardLocations().get(0).getBoard().getPlacement(0).setRank(91);return null;});no("retained candidate native drift",f::capture);}
  try(Fixture f=new Fixture("fresh-authority-negatives","definition")){f.closeOriginal("outcome_unknown");var captured=f.capture();Fresh fresh=f.fresh(captured,"continue-faulted-job-replacement");long bytes=Files.size(f.e.file);Map<String,Integer> before=counters();
   no("wrong process-local owner",()->task(()->f.e.replacement.beginContinuation(captured,fresh.coordinator,fresh.permit,new Object())));
   NativeSensingReconciliation foreign=new NativeSensingReconciliation(new NativeVacuumJournal(),(op,instance,replay)->false,f.e.replacement::verified);
   no("foreign coordinator",()->task(()->f.e.replacement.beginContinuation(captured,foreign,fresh.permit,fresh.owner)));
   no("missing continuation capture",()->task(()->f.e.replacement.beginContinuation(null,fresh.coordinator,fresh.permit,fresh.owner)));
   no("generic continuation task lacks an exact replacement binding",()->fresh.coordinator.prepare("sensing_reconciliation_task",fresh.coordinator.taskRecord(id(),id(),id(),fresh.faultCapture,"continue-faulted-job-replacement",2,"2030-01-01T00:00:00Z"),NativeSensingReconciliationTest.INSTANCE));
   no("begin outside native executor",()->f.e.replacement.beginContinuation(captured,fresh.coordinator,fresh.permit,fresh.owner));
   yes(bytes==Files.size(f.e.file)&&before.equals(counters()),"foreign/missing/off-executor permit attempts have zero effects");
   fresh.revoke();no("revoked new local permit",fresh::begin);
  }
  try(Fixture f=new Fixture("missing-fresh-operation","definition")){f.closeOriginal("outcome_unknown");Fresh fresh=new Fresh(f,f.capture(),"continue-faulted-job-replacement",false);no("new task lacks observed active operation",fresh::begin);}
  try(Fixture f=new Fixture("wrong-fresh-kind","definition")){f.closeOriginal("outcome_unknown");Fresh fresh=f.fresh(f.capture(),"replace-faulted-job-attempt");no("old recovery kind cannot authorize continuation",fresh::begin);}
  try(Fixture f=new Fixture("stale-capture","definition")){f.closeOriginal("outcome_unknown");Fresh fresh=f.fresh(f.capture(),"continue-faulted-job-replacement");f.observeOld("failed",true);no("captured previous local outcome changed",fresh::begin);}
  for(String key:List.of("task_id","bridge_instance_id","config_revision","request_digest","reconciliation_request_id"))try(Fixture f=new Fixture("fresh-admission-drift-"+key,"definition")){f.closeOriginal("outcome_unknown");Fresh fresh=new Fresh(f,f.capture(),"continue-faulted-job-replacement",false);Map<String,Object> changed=f.localOperation(fresh.operation,fresh.taskId,fresh.faultCapture.digest,"running",false);changed.put("reconciliation_request_id",o(fresh.coordinator.snapshot(fresh.taskId).get("task")).get("request_id"));changed.put(key,key.equals("request_digest")?"f".repeat(64):key.equals("config_revision")?"cfg-999":id());f.e.append("operation",changed);long bytes=Files.size(f.e.file);no("fresh admitted "+key+" differs from coordinator scope",fresh::begin);yes(bytes==Files.size(f.e.file),"mismatched admission is refused before new intent");}
  try(Fixture f=new Fixture("fresh-active-operation-terminal","completed")){f.closeOriginal("outcome_unknown");Fresh fresh=f.fresh(f.capture(),"continue-faulted-job-replacement");var permit=fresh.begin();Map<String,Object> terminal=freshOperation(fresh);terminal.put("state","outcome_unknown");terminal.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));f.e.append("operation",terminal);long bytes=Files.size(f.e.file);Map<String,Integer> before=counters();task(()->{no("terminal fresh operation invalidates continuation permit without coordinator revocation",permit::check);no("terminal fresh operation cannot adopt completed lineage",()->f.e.lineage.adoptCompletedReplacement(permit,f.attempt));for(Object old:(List<?>)f.e.capture.dependencies().get("material_load_ids"))no("terminal fresh operation cannot adopt material",()->f.e.material.adoptCompletedReplacement(permit,(String)old));for(Object old:(List<?>)f.e.capture.dependencies().get("board_load_ids"))no("terminal fresh operation cannot adopt board",()->f.e.boards.adoptCompletedReplacement(permit,f.e.oldJob,f.e.freshJob,f.attempt,(String)old));return null;});yes(bytes==Files.size(f.e.file)&&before.equals(counters()),"terminalized local operation cannot cause any adoption/native effect");permit.close();}
  cases.add(m("name","admission-refusals","no_native_execution",true));
 }
 static void positive(String prefix)throws Exception {
  int start=checks;try(Fixture f=new Fixture("positive-"+prefix,prefix)){
   f.closeOriginal("outcome_unknown");Map<String,Object> original=immutableOriginal(f.e);var captured=f.capture();
   yes(((List<?>)captured.dependencies().get("operation_ids")).containsAll(List.of(f.e.opId,f.oldRecovery)),"Continuation captures original and prior local operation IDs");
   yes(((List<?>)captured.dependencies().get("job_attempt_ids")).containsAll(List.of(f.e.jobId,f.e.aliasId,f.attempt)),"Continuation captures every original alias and replacement attempt");
   for(String kind:List.of("material","boards")){String key=kind.equals("material")?"material_load_ids":"board_load_ids";for(Object raw:(List<?>)o(o(captured.payload.get("progress")).get(kind)).get("rows")){Map<String,Object> row=o(raw);yes(((List<?>)captured.dependencies().get(key)).contains(row.get("old_load_id")),"Dependency union preserves original "+kind+" load");if(row.get("new_load")!=null)yes(((List<?>)captured.dependencies().get(key)).contains(o(row.get("new_load")).get("load_id")),"Dependency union includes replacement "+kind+" load");}}
   Fresh fresh=f.fresh(captured,"continue-faulted-job-replacement");Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();Map<String,Object> before=state(f.e);long bytes=Files.size(f.e.file);
   var permit=fresh.begin();yes(permit.attemptId().equals(f.attempt)&&!permit.continuationId().equals(f.attempt),"Fresh unforgeable permit binds existing attempt with a new continuation identity");task(()->{permit.check();return null;});
   yes(Files.size(f.e.file)>bytes&&f.e.terminalChecks>0,"Continuation admission is forced and consults independent synthetic wrapper authority");
   long admitted=Files.size(f.e.file);no("duplicate new permit",fresh::begin);no("recapture while continuation is live",f::capture);yes(admitted==Files.size(f.e.file),"duplicate permit and live recapture add no record");
   List<Map<String,Object>> adopted=new ArrayList<>();task(()->{
    Map<String,Object> progress=f.e.replacement.progress(f.attempt);
    if("completed".equals(o(progress.get("lineage")).get("phase"))){Map<String,Object> receipt=f.e.lineage.adoptCompletedReplacement(permit,f.attempt);adopted.add(m("type","job_lineage_continuation_adoption","payload",receipt));yes(NativeFaultedJobReplacement.same(receipt,f.e.lineage.continuationAdoptionReceipt((String)receipt.get("receipt_id"))),"Lineage adoption reads back its exact receipt");no("duplicate lineage adoption",()->f.e.lineage.adoptCompletedReplacement(permit,f.attempt));}else no("untouched lineage adoption",()->f.e.lineage.adoptCompletedReplacement(permit,f.attempt));
    for(Object raw:(List<?>)o(progress.get("material")).get("rows")){Map<String,Object> row=o(raw);String old=(String)row.get("old_load_id");if("completed".equals(row.get("phase"))){Map<String,Object> receipt=f.e.material.adoptCompletedReplacement(permit,old);adopted.add(m("type","material_continuation_adoption","payload",receipt));yes(NativeFaultedJobReplacement.same(receipt,f.e.material.continuationAdoptionReceipt((String)receipt.get("receipt_id"))),"Material adoption reads back its exact receipt");no("duplicate material adoption",()->f.e.material.adoptCompletedReplacement(permit,old));}else no("pending or untouched material adoption",()->f.e.material.adoptCompletedReplacement(permit,old));}
    for(Object raw:(List<?>)o(progress.get("boards")).get("rows")){Map<String,Object> row=o(raw);String old=(String)row.get("old_load_id");if("completed".equals(row.get("phase"))){Map<String,Object> receipt=f.e.boards.adoptCompletedReplacement(permit,f.e.oldJob,f.e.freshJob,f.attempt,old);adopted.add(m("type","board_continuation_adoption","payload",receipt));yes(NativeFaultedJobReplacement.same(receipt,f.e.boards.continuationAdoptionReceipt((String)receipt.get("receipt_id"))),"Board adoption reads back its exact receipt");no("duplicate board adoption",()->f.e.boards.adoptCompletedReplacement(permit,f.e.oldJob,f.e.freshJob,f.attempt,old));}else no("pending or untouched board adoption",()->f.e.boards.adoptCompletedReplacement(permit,f.e.oldJob,f.e.freshJob,f.attempt,old));}
    return null;
   });
   yes(counts.equals(counters())&&files.equals(configurationFiles()),"Adoption changes no native tray counter or configuration file bytes/timestamps");yes(NativeFaultedJobReplacement.same(before,state(f.e)),"Adoption creates no load, lineage, revision, or native binding state");ensurePreserved(f,original);
   yes(adopted.size()==(prefix.equals("completed")?5:prefix.equals("mixed-board")?4:prefix.equals("definition")?0:1),"Only exact completed phases receive adoption receipts");
   for(Map<String,Object> record:adopted){Map<String,Object> payload=o(record.get("payload")),bad=NativeFaultedJobReplacement.mutable(payload);bad.put("receipt_id",id());bad.put("phase_row_sha256","f".repeat(64));no("altered phase digest cannot enter forced continuation history",()->f.e.replacement.prepareContinuationObservation((String)record.get("type"),bad));no("reused continuation adoption receipt",()->f.e.replacement.prepareContinuationObservation((String)record.get("type"),payload));}
   if(!prefix.equals("completed"))no("partial adoption does not grant board readiness",()->task(()->{f.e.boards.requireReady(f.e.freshJob);return null;}));
   fresh.revoke();task(()->{no("revoked current coordinator permit",permit::check);return null;});permit.close();task(()->{no("closed continuation permit",permit::check);return null;});
   Map<String,Object> terminal=freshOperation(fresh);terminal.put("state","outcome_unknown");terminal.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));f.e.append("operation",terminal);f.e.terminalWrappers.add(fresh.operation);
   if(!adopted.isEmpty())try(Env reordered=new Env("positive-"+prefix+"-reordered-replay",true)){List<Map<String,Object>> records=new ArrayList<>(),late=new ArrayList<>();for(Map<String,Object> event:f.e.events){if(NativeFaultedJobReplacement.isContinuationAdoption((String)event.get("type")))late.add(event);else records.add(event);}records.addAll(late);Map<String,Integer> beforeReplay=counters();no("adoption moved after its fresh local operation terminated",()->reordered.replay(records));yes(beforeReplay.equals(counters())&&Files.size(reordered.file)==0,"rejected post-terminal adoption replay has no native/journal effects");}

   // Fresh reducer replay must retain receipts without reconstructing any native candidate or permit.
   try(Env replay=new Env("positive-"+prefix+"-replay",true)){Map<String,Integer> beforeReplay=counters();replay.replay(f.e.events);yes(beforeReplay.equals(counters())&&Files.size(replay.file)==0,"Continuation replay performs no counter reset or journal append");yes(!replay.replacement.ownsCandidate(f.e.candidate),"Replay cannot acquire native candidate ownership");no("replay cannot mint a continuation from historical receipts",()->task(()->replay.replacement.captureContinuation(f.attempt,f.e.oldJob)));for(Object raw:(List<?>)replay.material.snapshot().get("loads"))yes(Boolean.FALSE.equals(o(raw).get("native_authority")),"Replayed material lacks native authority");no("replayed new board binding remains unconfirmed",()->task(()->{replay.boards.requireReady(f.e.freshJob);return null;}));yes(Boolean.FALSE.equals(replay.replacement.progress(f.attempt).get("execution_authority_restored")),"Replayed continuation progress has no execution authority");}
   Files.writeString(root.resolve("positive-"+prefix+"-progress.json"),JSON.toJson(f.e.replacement.progress(f.attempt))+"\n");cases.add(m("name","positive-"+prefix,"assertions",checks-start,"adoption_receipts",adopted.size(),"replacement_attempt_id",f.attempt));
  }
 }

 static void chainedDecision()throws Exception {
  int start=checks;try(Fixture f=new Fixture("chained-decision","completed")){
   f.closeOriginal("outcome_unknown");Map<String,Object> original=immutableOriginal(f.e);Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();Map<String,Object> before=state(f.e);
   var initial=f.capture();Fresh one=f.fresh(initial,"continue-faulted-job-replacement");var permitOne=one.begin();List<?> loads=(List<?>)f.e.capture.dependencies().get("material_load_ids");
   Map<String,Object> first=task(()->f.e.material.adoptCompletedReplacement(permitOne,(String)loads.get(0)));one.revoke();permitOne.close();
   no("second decision lacks first continuation terminal record",f::capture);
   Map<String,Object> terminal=freshOperation(one);terminal.put("state","outcome_unknown");terminal.put("native_completion",m("native_wrapper_completed",true,"native_wrapper_succeeded",false,"physical_outcome_verified",false));f.e.append("operation",terminal);
   no("second decision lacks independent first continuation wrapper completion",f::capture);f.e.terminalWrappers.add(one.operation);
   var captured=f.capture();Map<String,Object> prior=o(captured.payload.get("prior_operations"));yes(prior.keySet().equals(Set.of(f.oldRecovery,one.operation)),"Second continuation captures every earlier local operation exactly");
   yes(((List<?>)captured.dependencies().get("operation_ids")).containsAll(List.of(f.e.opId,f.oldRecovery,one.operation)),"Second continuation dependency union preserves original and both prior local operations");
   yes(o(captured.payload.get("prior_adoptions")).size()==1,"Second continuation carries the exact previously forced adoption");
   Fresh two=f.fresh(captured,"continue-faulted-job-replacement");var permitTwo=two.begin();yes(!permitTwo.continuationId().equals(permitOne.continuationId())&&permitTwo.attemptId().equals(f.attempt),"Second fresh local decision has a new permit for the same attempt");
   task(()->{no("first decision permit cannot resume",permitOne::check);f.e.material.adoptCompletedReplacement(permitTwo,(String)loads.get(1));return null;});
   yes(NativeFaultedJobReplacement.same(first,f.e.material.continuationAdoptionReceipt((String)first.get("receipt_id"))),"Earlier adoption receipt remains byte-equivalent after the next decision");
   yes(counts.equals(counters())&&files.equals(configurationFiles())&&NativeFaultedJobReplacement.same(before,state(f.e)),"Chained decisions repeat no reset/save/load/lineage/binding effects");ensurePreserved(f,original);two.revoke();permitTwo.close();
   cases.add(m("name","chained-decision","assertions",checks-start,"prior_local_operations",prior.size()));
  }
 }
 static void intentForceBoundary(boolean afterForce)throws Exception {
  int start=checks;String name=afterForce?"intent-force-uncertain":"intent-before-force";try(Fixture f=new Fixture(name,"completed")){
   f.closeOriginal("outcome_unknown");Fresh fresh=f.fresh(f.capture(),"continue-faulted-job-replacement");Map<String,Object> original=immutableOriginal(f.e),before=state(f.e);Map<String,Integer> counts=counters();Map<String,String> files=configurationFiles();long bytes=Files.size(f.e.file);
   f.e.failType="faulted_job_replacement_continuation_intent";f.e.failAfterForce=afterForce;
   no("controlled continuation intent force boundary",fresh::begin);f.e.failType=null;
   yes((Files.size(f.e.file)>bytes)==afterForce,"Only force-then-throw retains the new continuation record");
   yes(Boolean.TRUE.equals(f.e.replacement.status().get("publication_fault")),"Ambiguous continuation admission permanently fences the current component owner");
   yes(o(f.e.replacement.status().get("continuation_intents")).isEmpty(),"Failed current-process admission publishes no known continuation intent");
   long failedSize=Files.size(f.e.file);no("uncertain owner cannot recapture",f::capture);no("uncertain owner cannot retry admission",fresh::begin);yes(failedSize==Files.size(f.e.file),"Fenced retries never force another intent");
   yes(counts.equals(counters())&&files.equals(configurationFiles())&&NativeFaultedJobReplacement.same(before,state(f.e)),"Intent force failure repeats no native reset/save/load/lineage/binding effects");ensurePreserved(f,original);
   try(Env replay=new Env(name+"-replay",true)){replay.replay(f.e.events);Map<String,Object> status=replay.replacement.status();yes(o(status.get("continuation_intents")).size()==(afterForce?1:0),"Fresh reducer classifies exactly zero or one actually forced pending continuation");yes(((Number)status.get("retained_candidate_count")).intValue()==0&&Boolean.FALSE.equals(status.get("execution_authority_restored")),"Forced pending history creates neither native candidate nor authority");no("replayed uncertain intent cannot mint a continuation",()->task(()->replay.replacement.captureContinuation(f.attempt,f.e.oldJob)));yes(Files.size(replay.file)==0&&counts.equals(counters()),"Verified replay does not repeat the effect or append a new decision");for(Object raw:(List<?>)replay.material.snapshot().get("loads"))yes(Boolean.FALSE.equals(o(raw).get("native_authority")),"Replayed material still lacks process-local authority");}
   cases.add(m("name",name,"assertions",checks-start,"record_actually_forced",afterForce));
  }
 }
 public static void main(String[] args)throws Exception {
  initialize(Path.of(args[0]));int exit=0;Throwable error=null;
  try{for(Constructor<?> c:NativeFaultedJobReplacement.ContinuationPermit.class.getDeclaredConstructors())yes(Modifier.isPrivate(c.getModifiers()),"Continuation capability constructor is private");admissionRefusals();for(String prefix:List.of("definition","lineage","pending-material","mixed-board","completed"))positive(prefix);chainedDecision();intentForceBoundary(false);intentForceBoundary(true);}
  catch(Throwable failure){failure.printStackTrace();error=failure;exit=1;}finally{config.getMachine().close();Map<String,Object> proof=m("passed",exit==0,"assertions",checks,"refusals",refusals,"cases",cases,"error",error==null?null:error.toString(),"initial_fault_fixture","synthetic sensing/action hooks and explicit synthetic TerminalAuthority; actual native models/setters and FileChannel.force","actual_native_job_initializations",0,"actual_native_feeds",0,"actual_native_placements",0,"bridge_integration_qualified",false,"full_continuation_qualified",false,"restart_reattachment_qualified",false,"hardware_qualified",false);Files.writeString(root.resolve("proof.json"),JSON.toJson(proof)+"\n");System.out.println("NATIVE_REPLACEMENT_CONTINUATION_RESULT "+JSON.toJson(proof));}System.exit(exit);
 }

}
