/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import org.openpnp.model.*;

/** Each invocation is a distinct JVM. Actual native model -> owned forced document -> new native
 * model reconstruction; no Configuration.loadJob arbitrary XML path and no native job execution. */
public final class NativeReplacementDocumentsTest {
 static Configuration config;static Path root;static int checks,refusals;static final com.google.gson.Gson JSON=new com.google.gson.GsonBuilder().setPrettyPrinting().serializeNulls().create();
 interface Work{void run()throws Exception;}static void yes(boolean value,String why){checks++;if(!value)throw new AssertionError(why);}static void no(String why,Work w)throws Exception{try{w.run();throw new AssertionError("Accepted "+why);}catch(IOException|Bridge.Fault expected){checks++;refusals++;}}
 static String id(String value){return UUID.nameUUIDFromBytes(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)).toString();}static String sha(byte[] b)throws Exception{StringBuilder s=new StringBuilder();for(byte v:java.security.MessageDigest.getInstance("SHA-256").digest(b))s.append(String.format("%02x",v&255));return s.toString();}
 static Map<String,Object> obj(Object v)throws Exception{return NativeFaultedJobReplacement.object(v);}static <T>T task(Callable<T> c)throws Exception{try{return config.getMachine().submit(c,null,true).get(30,TimeUnit.SECONDS);}catch(ExecutionException e){if(e.getCause() instanceof Error)throw(Error)e.getCause();throw(Exception)e.getCause();}}
 static NativeReplacementDocuments.Context context(String name)throws Exception{return new NativeReplacementDocuments.Context(id(name+"-old"),id(name+"-new"),id(name+"-recovery"),"a".repeat(64));}
 static NativeReplacementDocuments docs(Path owned)throws Exception{return new NativeReplacementDocuments(config,owned.resolve("documents"),owned);}
 static List<Map<String,Object>> catalog()throws Exception{return(List<Map<String,Object>>)JSON.fromJson(Files.readString(root.resolve("catalog.json")),List.class);}
 static Job fixture(String name)throws Exception{if(name.equals("canonical"))return NativeReplacementJobTest.canonical(false);if(name.equals("nested"))return NativeReplacementJobTest.canonical(true);Job old=NativeReplacementJobTest.nativeNested();if(name.equals("instances")){Job copy=new Job();copy.addBoardOrPanelLocation(new PanelLocation((PanelLocation)old.getRootPanelLocation().getChildren().get(0)));PanelLocation.setParentsOfAllDescendants(copy.getRootPanelLocation());old=copy;}BoardLocation first=old.getBoardLocations().get(0);first.getBoard().getPlacement(0).setLocation(new Location(LengthUnit.Millimeters,7,9,0,13));first.getBoard().getPlacement(0).setComments("instance-only content");first.getBoard().getPlacement(0).setRank(23);GeometricPath2D rootOutline=old.getRootPanelLocation().getPanel().getProfile();rootOutline.reset();rootOutline.moveTo(0,0);rootOutline.curveTo(10,1,20,1,30,0);rootOutline.lineTo(20,40);rootOutline.closePath();old.getRootPanelLocation().getPanel().setProfile(rootOutline);return old;}
 static void write()throws Exception{Files.createDirectories(root.resolve("owned"));NativeReplacementDocuments documents=docs(root.resolve("owned"));List<Object> catalog=new ArrayList<>();int boards=config.getBoards().size(),panels=config.getPanels().size();
  for(String name:List.of("canonical","nested","native","instances")){Job original=fixture(name);BoardLocation loc=original.getBoardLocations().get(0);Placement p=loc.getBoard().getPlacement(0);original.storePlacedStatus(loc,p.getId(),true);original.storePlacedStatus(loc,"opaque-unknown",false);original.storeEnabledState(loc,p,false);original.storeErrorHandlingState(loc,p,Placement.ErrorHandling.Defer);original.storeCheckFiducialsState(loc,true);Map<String,Boolean> history=new TreeMap<>(original.getPlacedStatusSnapshot());
   try(NativeReplacementJob.Candidate candidate=NativeReplacementJob.build(config,original)){Map<Object,List<Object>> listeners=NativeReplacementJobTest.listeners(NativeReplacementJobTest.objects(original));NativeReplacementDocuments.Saved saved=documents.save(context(name),candidate);yes(history.equals(original.getPlacedStatusSnapshot()),name+" save leaves old complete history unchanged");yes(listeners.equals(NativeReplacementJobTest.listeners(NativeReplacementJobTest.objects(original))),name+" save preserves old subscriptions");yes(candidate.job().getPlacedStatusSnapshot().isEmpty(),name+" save never sets candidate placed state");yes(documents.save(context(name),candidate).documentId.equals(saved.documentId),name+" repeated unchanged save is content-addressed and idempotent");candidate.requireCurrent();
    catalog.add(NativeFaultedJobReplacement.map("name",name,"document_id",saved.documentId,"graph_sha256",saved.manifest.get("candidate_graph_sha256"),"model_sha256",candidate.mapping().get("replacement_model_sha256"),"mapping_sha256",saved.manifest.get("source_mapping_sha256"),"placements",candidate.job().getBoardLocations().stream().mapToInt(l->l.getBoard().getPlacements().size()).sum(),"boards",candidate.job().getBoardLocations().size()));
    try(NativeReplacementDocuments.Reloaded fresh=documents.reload(saved.documentId,context(name))){yes(fresh.job()!=candidate.job(),name+" same-process native objects are newly constructed");NativeBoardLoads.requireDetachedReplacement(candidate.job(),fresh.job());fresh.requireCurrent();yes(fresh.mapping().equals(candidate.mapping()),name+" exact original source mapping survives");}
   }}
  yes(config.getBoards().size()==boards&&config.getPanels().size()==panels,"candidate document operations do not insert definitions into configured libraries");Files.writeString(root.resolve("catalog.json"),JSON.toJson(catalog));
 }
 static void read()throws Exception{NativeReplacementDocuments documents=docs(root.resolve("owned"));int boardLibrary=config.getBoards().size(),panelLibrary=config.getPanels().size();for(Map<String,Object> record:catalog()){String name=(String)record.get("name");try(NativeReplacementDocuments.Reloaded candidate=documents.reload((String)record.get("document_id"),context(name))){Job job=candidate.job();BoardLocation first=job.getBoardLocations().get(0);Placement p=first.getBoard().getPlacement(0);yes(job.getPlacedStatusSnapshot().isEmpty(),name+" fresh JVM has empty candidate history without resetting old work");yes(job.getBoardLocations().size()==((Number)record.get("boards")).intValue(),name+" all native board instances reconstructed");yes(p.getPart()==config.getPart(p.getPart().getId())&&p.getPart().getPackage()==config.getPackage(p.getPart().getPackage().getId()),name+" canonical Part/Package rebound to fresh-JVM library");yes(job.getBoardLocations().get(0).getBoard().getDefinition()==job.getBoardLocations().get(1).getBoard().getDefinition(),name+" shared definition preserved");yes(!job.retrieveEnabledState(first,p)&&job.retrieveErrorHandlingState(first,p)==Placement.ErrorHandling.Defer&&job.retrieveCheckFiducialsState(first),name+" stored native overrides preserved");yes(candidate.manifest().get("candidate_graph_sha256").equals(record.get("graph_sha256"))&&candidate.manifest().get("source_mapping_sha256").equals(record.get("mapping_sha256")),name+" exact graph and mapping integrity bound");yes(job.getFile()==null&&first.getFileName()==null&&first.getPlacementsTransformStatus()==PlacementsHolderLocation.PlacementsTransformStatus.NotSet,name+" no old file/registration authority imported");
   if(name.equals("native")||name.equals("instances")){yes(first.getBoard().getSolderPastePads().size()==1&&((Pad.RoundRectangle)first.getBoard().getSolderPastePads().get(0).getPad()).getRoundness()==0.2,name+" rounded paste-pad metadata round-trips");yes(job.getPanelLocations().stream().filter(l->!l.getPanel().getPseudoPlacements().isEmpty()).count()==2,name+" both nested pseudo lists reconstructed");yes(job.getRootPanelLocation().getPanel().getProfile()==job.getRootPanelLocation().getPanel().getProfile(),name+" explicit root outline preserved");yes(first.getBoard().getPlacement(0).getLocation().getX()==7&&first.getBoard().getPlacement(0).getRank()==23,name+" instance-only geometry metadata preserved");}
   candidate.requireCurrent();Set<Object> graph=NativeReplacementJobTest.objects(job);candidate.close();yes(NativeReplacementJobTest.listeners(graph).values().stream().allMatch(List::isEmpty),name+" closing unpublished reconstructed graph cleans every new subscription");
  }}yes(boardLibrary==config.getBoards().size()&&panelLibrary==config.getPanels().size(),"fresh-JVM reconstruction does not populate native definition libraries");}
 static void failures(String mode)throws Exception{Map<String,Object> record=catalog().get(0);String document=(String)record.get("document_id");NativeReplacementDocuments documents=docs(root.resolve("owned"));
  if(mode.equals("part-change")){Part part=config.getPart("R0603-1K");part.setHeight(new Length(1.25,LengthUnit.Millimeters));for(Map<String,Object> row:catalog())no("changed Part definition for "+row.get("name"),()->documents.reload((String)row.get("document_id"),context((String)row.get("name"))));}
  else if(mode.equals("package-change")){config.getPart("R0603-1K").getPackage().setDescription("changed canonical dependency");for(Map<String,Object> row:catalog())no("changed Package definition for "+row.get("name"),()->documents.reload((String)row.get("document_id"),context((String)row.get("name"))));}
  else if(mode.equals("part-identity")){for(Map<String,Object> row:catalog())try(NativeReplacementDocuments.Reloaded candidate=documents.reload((String)row.get("document_id"),context((String)row.get("name")))){Part original=config.getPart("R0603-1K");ByteArrayOutputStream bytes=new ByteArrayOutputStream();Configuration.createSerializer().write(original,bytes);Part replacement=Configuration.createSerializer().read(Part.class,new ByteArrayInputStream(bytes.toByteArray()));replacement.setPackage(original.getPackage());ByteArrayOutputStream copyBytes=new ByteArrayOutputStream();Configuration.createSerializer().write(replacement,copyBytes);yes(Arrays.equals(bytes.toByteArray(),copyBytes.toByteArray()),row.get("name")+" Part identity replacement has identical serialized dependency fields");config.addPart(replacement);try{no("same-value canonical Part identity changed for "+row.get("name"),candidate::publish);}finally{config.addPart(original);}}}
  else if(mode.equals("package-identity")){for(Map<String,Object> row:catalog())try(NativeReplacementDocuments.Reloaded candidate=documents.reload((String)row.get("document_id"),context((String)row.get("name")))){org.openpnp.model.Package original=config.getPart("R0603-1K").getPackage();ByteArrayOutputStream bytes=new ByteArrayOutputStream();Configuration.createSerializer().write(original,bytes);org.openpnp.model.Package replacement=Configuration.createSerializer().read(org.openpnp.model.Package.class,new ByteArrayInputStream(bytes.toByteArray()));ByteArrayOutputStream copyBytes=new ByteArrayOutputStream();Configuration.createSerializer().write(replacement,copyBytes);yes(Arrays.equals(bytes.toByteArray(),copyBytes.toByteArray()),row.get("name")+" Package identity replacement has identical serialized dependency fields");config.addPackage(replacement);try{no("same-value canonical Package identity changed for "+row.get("name"),candidate::publish);}finally{config.addPackage(original);}}}
  else if(mode.equals("wrong-context")){no("foreign original/replacement IDs",()->documents.reload(document,context("foreign")));no("external path document import",()->documents.reload(root.resolve("external.job.xml").toString(),context("canonical")));no("unknown content address",()->documents.reload("f".repeat(64),context("canonical")));no("outside owned document root",()->new NativeReplacementDocuments(config,root.resolve("outside"),root.resolve("owned")));}
  else if(mode.equals("tamper-archive")){Path archive=root.resolve("owned/documents").resolve(document+".zip");byte[] bytes=Files.readAllBytes(archive);bytes[bytes.length/2]^=1;Files.write(archive,bytes);no("corrupted retained archive",()->documents.reload(document,context("canonical")));}
  else if(mode.equals("tamper-receipt")){Path receipt=root.resolve("owned/documents").resolve(document+".receipt.json");String bytes=Files.readString(receipt);Files.writeString(receipt,bytes.replaceFirst("hmac_sha256", "hmac_sha257"));no("corrupted private receipt",()->documents.reload(document,context("canonical")));}
  else if(mode.equals("same-content-alias")){try(NativeReplacementDocuments.Reloaded candidate=documents.reload(document,context("canonical"))){BoardLocation location=candidate.job().getBoardLocations().get(0);Board replacement=new Board(location.getBoard());location.setBoard(replacement);try{no("equal-content foreign native object replacement",candidate::publish);}finally{replacement.dispose();}}}
  else if(mode.equals("tamper-key")){Files.delete(root.resolve("owned/documents/receipt-key"));no("missing committed document key in reopened store",()->docs(root.resolve("owned")));}
  else if(mode.equals("tamper-symlink")){Path archive=root.resolve("owned/documents").resolve(document+".zip"),elsewhere=root.resolve("external-copy.zip");Files.copy(archive,elsewhere);Files.delete(archive);Files.createSymbolicLink(archive,elsewhere);no("retained archive changed into symlink",()->documents.reload(document,context("canonical")));}
  else if(mode.equals("candidate-drift")){try(NativeReplacementDocuments.Reloaded candidate=documents.reload(document,context("canonical"))){candidate.job().getBoardLocations().get(0).getBoard().getPlacement(0).setRank(999);no("reconstructed graph modified before transfer",candidate::publish);}}
  else if(mode.equals("publish")){for(Map<String,Object> row:catalog()){String name=(String)row.get("name");NativeReplacementDocuments.Reloaded candidate=documents.reload((String)row.get("document_id"),context(name));Job job=candidate.job();Set<Object> graph=NativeReplacementJobTest.objects(job);Map<Object,List<Object>> decodedListeners=NativeReplacementJobTest.listeners(graph);java.lang.reflect.Field field=NativeReplacementDocuments.Reloaded.class.getDeclaredField("witness");field.setAccessible(true);NativeReplacementJob.Candidate witness=(NativeReplacementJob.Candidate)field.get(candidate);Set<Object> witnessGraph=NativeReplacementJobTest.objects(witness.job());yes(Collections.disjoint(graph,witnessGraph),name+" identity witness graph is separate from decoded graph");yes(NativeReplacementJobTest.listeners(witnessGraph).values().stream().anyMatch(v->!v.isEmpty()),name+" identity witness owns actual native subscriptions before publication");Map<String,Object> mapping=candidate.mapping(),manifest=candidate.manifest();candidate.publish();yes(NativeReplacementJobTest.listeners(witnessGraph).values().stream().allMatch(List::isEmpty),name+" publication releases unused witness subscriptions");yes(decodedListeners.equals(NativeReplacementJobTest.listeners(graph)),name+" publication preserves exact decoded graph subscriptions");no(name+" second publication after ownership transfer",candidate::publish);no(name+" current-identity authority after ownership transfer",candidate::requireCurrent);candidate.close();yes(candidate.job()==job&&candidate.mapping().equals(mapping)&&candidate.manifest().equals(manifest),name+" published job and historical manifest/mapping stay readable");yes(decodedListeners.equals(NativeReplacementJobTest.listeners(graph)),name+" repeat publication refusal and close preserve published subscriptions");NativeBoardLoads.validateCandidate(job);try(NativeReplacementJob.Candidate validation=NativeReplacementJob.build(config,job)){validation.requireCurrent();yes(Objects.equals(mapping.get("replacement_model_sha256"),validation.mapping().get("replacement_model_sha256")),name+" published native graph remains valid and identity-bound");}yes(job.getPlacedStatusSnapshot().isEmpty()&&Boolean.FALSE.equals(candidate.manifest().get("execution_authority_restored")),name+" publication does not initialize job or grant execution");}}
  else throw new AssertionError(mode);
 }
 static void killed(String mode)throws Exception{Files.createDirectories(root.resolve("owned"));boolean after=mode.endsWith("after");NativeReplacementDocuments documents=new NativeReplacementDocuments(config,root.resolve("owned/documents"),root.resolve("owned"),(target,renamed)->{if(target.getFileName().toString().endsWith(".receipt.json")&&renamed==after){String document=target.getFileName().toString().substring(0,64);Path evidence=root.resolve("killed-document-id.txt");byte[] bytes=document.getBytes(java.nio.charset.StandardCharsets.US_ASCII);try(java.nio.channels.FileChannel channel=java.nio.channels.FileChannel.open(evidence,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){channel.write(java.nio.ByteBuffer.wrap(bytes));channel.force(true);}Runtime.getRuntime().halt(47);}});Job old=fixture("native");try(NativeReplacementJob.Candidate candidate=NativeReplacementJob.build(config,old)){documents.save(context("killed"),candidate);}throw new AssertionError("native store crash seam not reached");}
 static void inspectKilled(String mode)throws Exception{NativeReplacementDocuments documents=docs(root.resolve("owned"));String document=Files.readString(root.resolve("killed-document-id.txt"));if(mode.endsWith("before")){no("killed uncommitted receipt cannot create authority",()->documents.reload(document,context("killed")));}else try(NativeReplacementDocuments.Reloaded loaded=documents.reload(document,context("killed"))){yes(loaded.job().getPlacedStatusSnapshot().isEmpty(),"fresh JVM reconstructs exactly committed candidate after lost save response");yes(Boolean.FALSE.equals(loaded.manifest().get("execution_authority_restored")),"forced document never restores machine/recovery authority");loaded.requireCurrent();}}
 public static void main(String[] args)throws Exception{String mode=args[0];root=Paths.get(args[1]);Files.createDirectories(root);Configuration.initialize(root.resolve("config").toFile());config=Configuration.get();config.load();SimulatorMain.accelerateFixture(config);SimulatorMain.configureSustainedWorkload(config);NativeReplacementJobTest.config=config;NativeReplacementJobTest.root=root;int exit=0;try{task(()->{if(mode.startsWith("kill-"))killed(mode);else if(mode.startsWith("inspect-kill-"))inspectKilled(mode);else if(mode.equals("write"))write();else if(mode.equals("read"))read();else failures(mode);return null;});System.out.println("NATIVE_REPLACEMENT_DOCUMENTS_PASS mode="+mode+" checks="+checks+" refusals="+refusals+" pid="+ProcessHandle.current().pid()+" native_initialize=0 feeds=0 placements=0; owned graph-document native reconstruction, no XML import/execution authority");}catch(Throwable t){t.printStackTrace();exit=1;}finally{config.getMachine().close();}System.exit(exit);}
}
