/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import com.google.gson.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import org.openpnp.model.Configuration;
import org.openpnp.spi.Camera;
import org.openpnp.machine.reference.camera.*;

/** Actual leased Bridge native executor, both default simulator cameras and retained PNG integrity. */
public final class NativeCameraSettlingBridgeTest {
    static final Gson GSON=new Gson();static int checks,captures;static Bridge bridge;static Configuration config;static String session;
    static void check(boolean c,String message){checks++;if(!c)throw new AssertionError(message);}
    static JsonObject obj(Object...pairs){return GSON.toJsonTree(Bridge.map(pairs)).getAsJsonObject();}
    static Map<String,Object> call(String name,Object...pairs)throws Exception{return (Map<String,Object>)bridge.call(name,obj(pairs));}
    static Map<String,Object> waitFor(Map<String,Object> op)throws Exception{long until=System.nanoTime()+java.util.concurrent.TimeUnit.SECONDS.toNanos(30);while(Arrays.asList("accepted","running").contains(op.get("state"))){if(System.nanoTime()>until)throw new AssertionError("native operation timeout; no replay");Thread.sleep(5);op=call("openpnp_get_operation","operation_id",op.get("operation_id"));}while(Boolean.TRUE.equals(call("openpnp_get_status").get("native_busy"))){if(System.nanoTime()>until)throw new AssertionError("native wrapper idle timeout");Thread.sleep(5);}return op;}
    static JsonObject mutation(Object...pairs)throws Exception{JsonObject p=obj(pairs);p.addProperty("request_id",UUID.randomUUID().toString());p.addProperty("session_id",session);p.addProperty("expected_config_revision",(String)call("openpnp_get_status").get("config_revision"));return p;}
    static Map<String,Object> operation(String name,Object...pairs)throws Exception{return waitFor((Map<String,Object>)bridge.call(name,mutation(pairs)));}
    static Map<String,Object> mutate(String name,Object...pairs)throws Exception{Map<String,Object> op=operation(name,pairs);if(!"succeeded".equals(op.get("state")))throw new AssertionError(name+": "+GSON.toJson(op));return (Map<String,Object>)op.get("result");}
    static void settings(JsonObject...changes)throws Exception{JsonArray rows=new JsonArray();for(JsonObject row:changes)rows.add(row);String before=(String)call("openpnp_get_configuration").get("config_revision");Map<String,Object> plan=(Map<String,Object>)bridge.call("openpnp_plan_configuration",mutation("changes",rows));mutate("openpnp_apply_configuration","plan_id",plan.get("plan_id"));check(!before.equals(call("openpnp_get_configuration").get("config_revision")),"native configuration revision advances");}
    static JsonObject dynamic(Camera c,String method,boolean full){return obj("type",NativeCameraSettling.TYPE,"camera_id",c.getId(),"method",method,"timeout_ms",40,"debounce",1,"threshold_percent",0.5,"full_color",full);}
    static String hex(byte[] bytes){StringBuilder s=new StringBuilder();for(byte b:bytes)s.append(String.format("%02x",b&255));return s.toString();}
    static Map<?,?> capture(Camera camera,String mode)throws Exception {
        Map<String,Object> artifact=mutate("openpnp_capture_camera","camera_id",camera.getId(),"mode",mode);captures++;Map<?,?> meta=(Map<?,?>)artifact.get("metadata");
        check("image/png".equals(artifact.get("mime_type"))&&artifact.get("artifact_id") instanceof String,"existing native image artifact fields retained");
        check(camera.getId().equals(meta.get("camera_id"))&&mode.equals(meta.get("capture_mode")),"capture metadata bound to actual camera/mode");
        check("capture-returned".equals(meta.get("capture_status"))&&("raw".equals(mode)?"not-requested":"not-reported-by-native-api").equals(meta.get("settling_outcome")),"capture return has truthful unreported settling outcome");
        check("not-established-by-capture-return".equals(meta.get("image_validity"))&&"not-assessed".equals(meta.get("physical_calibration_validity"))&&Boolean.FALSE.equals(meta.get("hardware_qualified"))&&Boolean.FALSE.equals(meta.get("native_timeout_is_hard_io_deadline")),"no image-validity/calibration/hard-deadline claim");
        ReferenceCamera c=(ReferenceCamera)camera;boolean dynamic=c.getSettleMethod()!=null&&NativeCameraSettling.METHODS.contains(c.getSettleMethod().name());check(meta.containsKey("native_recorded_settle_ms")==("settled".equals(mode)&&dynamic),"raw/fixed results exclude previous native dynamic timer");
        Map<?,?> stored=(Map<?,?>)((Map<?,?>)meta.get("admission")).get("settling_settings");check(c.getSettleMethod().name().equals(stored.get("method"))&&((Number)stored.get("timeout_ms")).longValue()==c.getSettleTimeoutMs()&&((Number)stored.get("debounce")).intValue()==c.getSettleDebounce()&&((Number)stored.get("threshold_percent")).doubleValue()==c.getSettleThreshold()&&((Boolean)stored.get("full_color"))==c.isSettleFullColor(),"receipt stores all five exact native settings");
        Map<String,Object> retained=call("openpnp_get_artifact","artifact_id",artifact.get("artifact_id"));byte[] bytes=Base64.getDecoder().decode((String)retained.get("base64"));check(hex(MessageDigest.getInstance("SHA-256").digest(bytes)).equals(artifact.get("sha256")),"retained PNG bytes match declared hash");java.awt.image.BufferedImage image=javax.imageio.ImageIO.read(new java.io.ByteArrayInputStream(bytes));check(image.getWidth()==((Number)meta.get("width")).intValue()&&image.getHeight()==((Number)meta.get("height")).intValue(),"actual PNG dimensions match metadata");return meta;
    }
    public static void main(String[] args)throws Exception {
        Path root=Files.createTempDirectory("openpnp-camera-settling-bridge-");Path home=root.resolve("config");Configuration.initialize(home.toFile());Configuration.get().load();SimulatorMain.accelerateFixture(Configuration.get());SimulatorMain.settleFreshFixture(home);config=Configuration.get();Path token=root.resolve("token");Files.writeString(token,UUID.randomUUID().toString()+UUID.randomUUID());int exit=0;
        try{bridge=new Bridge(config,token,root.resolve("journal"),Paths.get(args[0]),0,true);Map<?,?> caps=call("openpnp_get_capabilities");check(((List<?>)caps.get("configuration_changes")).contains(NativeCameraSettling.TYPE)&&((Map<?,?>)caps.get("camera_settling")).get("methods").equals(NativeCameraSettling.METHODS),"native capability publishes exact additive method/bound scope");session=(String)call("openpnp_request_control_session","request_id",UUID.randomUUID().toString(),"ttl_seconds",300).get("session_id");Camera top=config.getMachine().getDefaultHead().getDefaultCamera(),bottom=config.getMachine().getCameras().get(0);
            int[] callbacks={0};((ReferenceCamera)top).startCalibration((found,goal,complete)->callbacks[0]++);Map<?,?> activeCalibration=operation("openpnp_capture_camera","camera_id",top.getId(),"mode","raw");check("failed".equals(activeCalibration.get("state"))&&"CAMERA_CALIBRATION_ACTIVE".equals(((Map<?,?>)activeCalibration.get("result")).get("code")),"Bridge refuses raw acquisition while native calibration is active");check(((ReferenceCamera)top).isCalibrating()&&callbacks[0]==0,"Bridge refusal does not advance or cancel native calibration");((ReferenceCamera)top).cancelCalibration();
            check(!config.getMachine().isEnabled(),"default raw capture starts with disabled simulator");capture(top,"raw");check(!config.getMachine().isEnabled()&&!config.getMachine().isHomed(),"raw admission/capture does not enable or home");Map<?,?> disabled=operation("openpnp_capture_camera","camera_id",top.getId(),"mode","settled");check("failed".equals(disabled.get("state"))&&"MACHINE_DISABLED".equals(((Map<?,?>)disabled.get("result")).get("code")),"settled capture keeps existing enable requirement");
            mutate("openpnp_set_machine_enabled","enabled",true);mutate("openpnp_home_machine");
            for(String method:NativeCameraSettling.METHODS){settings(dynamic(top,method,false),dynamic(bottom,method,true));for(Camera c:Arrays.asList(top,bottom)){capture(c,"raw");capture(c,"settled");}}
            settings(NativeCameraSettlingTest.fixed((ReferenceCamera)top,0),NativeCameraSettlingTest.fixed((ReferenceCamera)bottom,0));capture(top,"settled");
            // Stop the native preview worker before inserting an oversized admission-only fixture.
            ((ImageCamera)top).close();((ImageCamera)top).setViewWidth(Integer.MAX_VALUE);Map<?,?> oversized=operation("openpnp_capture_camera","camera_id",top.getId(),"mode","raw");check("failed".equals(oversized.get("state"))&&"CAMERA_FRAME_LIMIT".equals(((Map<?,?>)oversized.get("result")).get("code")),"oversized native frame refuses before allocation");((ImageCamera)top).setViewWidth(640);
            JsonObject request=mutation("camera_id",top.getId(),"mode","raw");Map<String,Object> first=waitFor((Map<String,Object>)bridge.call("openpnp_capture_camera",request));Map<String,Object> duplicate=(Map<String,Object>)bridge.call("openpnp_capture_camera",request);check(first.get("operation_id").equals(duplicate.get("operation_id"))&&((Map<?,?>)first.get("result")).get("artifact_id").equals(((Map<?,?>)duplicate.get("result")).get("artifact_id")),"repeated request returns retained capture operation/artifact without reacquisition");
            mutate("openpnp_set_machine_enabled","enabled",false);check("absent".equals(call("openpnp_get_status").get("job_state")),"camera operations create no native job");for(org.openpnp.spi.Feeder f:config.getMachine().getFeeders())if(f instanceof org.openpnp.machine.reference.feeder.ReferenceStripFeeder)check(((org.openpnp.machine.reference.feeder.ReferenceStripFeeder)f).getFeedCount()==0,"camera settings/captures feed no parts");call("openpnp_release_control_session","session_id",session);
            System.out.println("OPENPNP_CAMERA_SETTLING_BRIDGE_RESULT "+GSON.toJson(Bridge.map("checks",checks,"captures_with_verified_png",captures,"additional_deduplicated_raw_capture",1,"native_camera_classes",Arrays.asList(top.getClass().getName(),bottom.getClass().getName()),"upstream_commit",Bridge.UPSTREAM,"native_feeds",0,"native_placements",0,"hardware_qualified",false)));
        }catch(Throwable failure){failure.printStackTrace();exit=1;}finally{if(bridge!=null)bridge.close();config.getMachine().close();}System.exit(exit);
    }
}
