/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.lang.management.ManagementFactory;
import org.openpnp.model.*;
import org.openpnp.spi.*;
import org.openpnp.machine.reference.*;

/** Actual process death after durable intent/native insertion, same-journal restart and fresh adoption. */
public final class NativeNozzleAssemblyCrashTest {
 static final Gson G=new Gson();static int checks;static Configuration c;static Machine m;static Bridge bridge;
 static void check(boolean v,String why){checks++;if(!v)throw new AssertionError(why);}
 static JsonObject obj(Object...v){return G.toJsonTree(Bridge.map(v)).getAsJsonObject();}
 @SuppressWarnings("unchecked")static Map<String,Object> call(String name,JsonObject j)throws Exception{return(Map<String,Object>)bridge.call("openpnp_"+name,j);}
 static void boot(Path root,String samples,boolean seed)throws Exception{Path dir=root.resolve("config");Configuration.initialize(dir.toFile());c=Configuration.get();c.load();if(seed){SimulatorMain.accelerateFixture(c);SimulatorMain.settleFreshFixture(dir);c=Configuration.get();Files.writeString(root.resolve("token"),UUID.randomUUID().toString()+UUID.randomUUID());}m=c.getMachine();bridge=new Bridge(c,root.resolve("token"),root.resolve("journal"),Path.of(samples),0,true);}
 static void crash(Path root,String samples)throws Exception{Files.createDirectories(root);boot(root,samples,true);String session=(String)call("request_control_session",obj("request_id","topology-crash-grant","ttl_seconds",300)).get("session_id");JsonObject p=NativeNozzleAssemblyTest.proposal(c);Map<String,Object> plan=call("plan_configuration",obj("session_id",session,"expected_config_revision",call("get_status",obj()).get("config_revision"),"changes",NativeNozzleAssemblyTest.rows(p)));
  CountDownLatch admitted=new CountDownLatch(1);((ReferenceMachine)m).addPropertyChangeListener(e->{if("axes".equals(e.getPropertyName())){try{if(!admitted.await(10,TimeUnit.SECONDS))throw new AssertionError("admission barrier");}catch(InterruptedException x){throw new AssertionError(x);}Runtime.getRuntime().halt(61);}});
  Map<String,Object> op=call("apply_configuration",obj("session_id",session,"request_id","topology-crash-request","plan_id",plan.get("plan_id")));Files.writeString(root.resolve("admitted.json"),G.toJson(op));admitted.countDown();Thread.sleep(20000);throw new AssertionError("Native insertion crash was not reached");
 }
 static void restart(Path root,String samples)throws Exception{boot(root,samples,false);Map<String,Object> admitted=G.fromJson(Files.readString(root.resolve("admitted.json")),Map.class),op=call("get_operation",obj("operation_id",admitted.get("operation_id")));check("outcome_unknown".equals(op.get("state")),"actual interrupted operation recovers as unknown");check(Boolean.TRUE.equals(call("get_status",obj()).get("configuration_fault")),"same journal remains topology-fenced after JVM restart");check(!m.isEnabled()&&!m.isHomed(),"restart transfers no enable/home state");
  try{call("request_control_session",obj("request_id","unsafe-regrant","ttl_seconds",300));throw new AssertionError("partial creation allowed regrant");}catch(Bridge.Fault expected){check(expected.code.equals("CONFIGURATION_FAULT")&&expected.getMessage().contains("topology_recovery_available")&&expected.getMessage().contains("fresh simulator generation")&&expected.getMessage().contains("Restarting this state does not clear"),"configuration fault directs retained preimage into fresh adoption");}
  List<Map<?,?>> events=(List<Map<?,?>>)call("get_events",obj("after_sequence",0,"limit",500)).get("events");Map<?,?> recovery=null;for(Map<?,?> e:events)if("topology_recovery_available".equals(e.get("type")))recovery=(Map<?,?>)e.get("payload");check(recovery!=null&&op.get("operation_id").equals(recovery.get("operation_id")),"recovery event survives all native journal reducers");Map<?,?> artifact=(Map<?,?>)recovery.get("artifact");Map<String,Object> bytes=call("get_artifact",obj("artifact_id",artifact.get("artifact_id")));byte[] archive=Base64.getDecoder().decode((String)bytes.get("base64"));check(NativePortableConfiguration.sha(archive).equals(artifact.get("sha256")),"read-only artifact retrieval remains available after failure/restart");Files.write(root.resolve("recovery.zip"),archive);Files.writeString(root.resolve("recovery.json"),G.toJson(recovery));bridge.close();m.close();
 }
 static void saveFailure(Path root,String samples)throws Exception{
  Files.createDirectories(root);boot(root,samples,true);String session=(String)call("request_control_session",obj("request_id","save-failure-grant","ttl_seconds",300)).get("session_id");Map<String,Object> plan=call("plan_configuration",obj("session_id",session,"expected_config_revision",call("get_status",obj()).get("config_revision"),"changes",NativeNozzleAssemblyTest.rows(NativeNozzleAssemblyTest.proposal(c))));
  java.beans.PropertyChangeListener blocker=e->{if("nozzles".equals(e.getPropertyName()))try{Path file=root.resolve("config/machine.xml");Files.move(file,root.resolve("machine-before-blocker.xml"));Files.createDirectory(file);Files.writeString(file.resolve("save-blocker"),"Test-only native save path collision");}catch(Exception x){throw new AssertionError(x);}};((ReferenceHead)m.getDefaultHead()).addPropertyChangeListener(blocker);
  Map<String,Object> op=call("apply_configuration",obj("session_id",session,"request_id","topology-save-failure","plan_id",plan.get("plan_id")));long deadline=System.nanoTime()+TimeUnit.SECONDS.toNanos(60);while(List.of("accepted","running").contains(op.get("state"))){check(System.nanoTime()<deadline,"save failure deadline");Thread.sleep(10);op=call("get_operation",obj("operation_id",op.get("operation_id")));}while(m.isBusy())Thread.sleep(5);((ReferenceHead)m.getDefaultHead()).removePropertyChangeListener(blocker);
  check("outcome_unknown".equals(op.get("state"))&&Boolean.TRUE.equals(call("get_status",obj()).get("configuration_fault")),"actual native post-assembly save failure is fenced unknown");check(m.getDefaultHead().getNozzles().size()==2,"failure retains newly created native graph without removal");check(((Map<?,?>)op.get("result")).get("message").toString().contains("saving machine.xml"),"failure originates in native Configuration.save");
  List<Map<?,?>> events=(List<Map<?,?>>)call("get_events",obj("after_sequence",0,"limit",500)).get("events");Map<?,?> recovery=null;for(Map<?,?> e:events)if("topology_recovery_available".equals(e.get("type")))recovery=(Map<?,?>)e.get("payload");Map<?,?> artifact=(Map<?,?>)recovery.get("artifact");Map<String,Object> bytes=call("get_artifact",obj("artifact_id",artifact.get("artifact_id")));byte[] archive=Base64.getDecoder().decode((String)bytes.get("base64"));check(NativePortableConfiguration.sha(archive).equals(artifact.get("sha256")),"save failure preserves preimage bytes");Files.write(root.resolve("recovery.zip"),archive);Files.writeString(root.resolve("save-failure.json"),G.toJson(op));bridge.close();m.close();
 }
 static void adopt(Path root)throws Exception{Path zip=root.resolve("recovery.zip");NativePortableConfiguration.Prepared p=NativePortableConfiguration.prepare(zip,NativePortableConfiguration.sha(Files.readAllBytes(zip)),root.resolve("recovered"));NativePortableConfiguration.validateAndPublish(p);}
 static void verify(Path root,String samples)throws Exception{Path destination=root.resolve("recovered"),state=root.resolve("fresh-state");Files.createDirectory(state);NativePortableLaunch launch=NativePortableLaunch.claim(destination,state.resolve("journal"));launch.initialize();c=Configuration.get();m=c.getMachine();Path token=state.resolve("token");Files.writeString(token,UUID.randomUUID().toString()+UUID.randomUUID());bridge=new Bridge(c,token,state.resolve("journal"),Path.of(samples),0,true,"adopted-simulator",null,launch);check(!m.isHomed()&&!m.isEnabled()&&m.getDefaultHead().getNozzles().size()==1,"fresh recovered generation has original graph and no execution authority");check(!Boolean.TRUE.equals(call("get_status",obj()).get("configuration_fault")),"fresh adopted configuration is usable");check(Boolean.FALSE.equals(call("get_request_status",obj("request_id","topology-crash-request")).get("found")),"failed operation is not transplanted");check(call("request_control_session",obj("request_id","fresh-control","ttl_seconds",300)).get("session_id")!=null,"new generation can receive a fresh lease");bridge.close();m.close();}
 public static void main(String[] args)throws Exception{if(args.length==1){Path root=Files.createTempDirectory("native-topology-crash61-");for(String phase:List.of("crash","restart","adopt","verify","save-failure","save-adopt","save-verify")){List<String> command=new ArrayList<>();command.add(Path.of(System.getProperty("java.home"),"bin/java").toString());command.addAll(ManagementFactory.getRuntimeMXBean().getInputArguments());command.addAll(List.of("-cp",System.getProperty("java.class.path"),NativeNozzleAssemblyCrashTest.class.getName(),phase,root.toString(),args[0]));Path log=root.resolve(phase+".log");Process child=new ProcessBuilder(command).redirectErrorStream(true).redirectOutput(log.toFile()).start();check(child.waitFor(75,TimeUnit.SECONDS)&&child.exitValue()==(phase.equals("crash")?61:0),phase+": "+Files.readString(log));}System.out.println("OPENPNP_NATIVE_TOPOLOGY_CRASH_RESULT "+G.toJson(Bridge.map("phases",7,"actual_process_halt",61,"root",root.toString(),"fresh_recovery",true,"physical_qualification",false)));return;}try{Path root=Path.of(args[1]);if(args[0].equals("crash"))crash(root,args[2]);else if(args[0].equals("restart"))restart(root,args[2]);else if(args[0].equals("save-failure"))saveFailure(root.resolve("save-case"),args[2]);else if(args[0].equals("save-adopt"))adopt(root.resolve("save-case"));else if(args[0].equals("save-verify"))verify(root.resolve("save-case"),args[2]);else if(args[0].equals("adopt"))adopt(root);else if(args[0].equals("verify"))verify(root,args[2]);else throw new AssertionError(args[0]);System.out.println("OPENPNP_TOPOLOGY_CRASH_PHASE "+G.toJson(Bridge.map("phase",args[0],"checks",checks)));System.exit(0);}catch(Throwable e){e.printStackTrace();System.exit(1);}}
}
