/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import javax.swing.*;
import org.openpnp.model.*;
import org.openpnp.spi.*;
import org.openpnp.machine.reference.ReferenceMachine;
import org.openpnp.machine.reference.feeder.ReferenceTrayFeeder;
/** Private deterministic gates around actual native executor/planner, never replacement completion. */
public final class NativeJobSteppingRaceTest {
 static final List<String> checks=new ArrayList<>();static Machine machine;static Bridge bridge;static Part part;static ReferenceTrayFeeder feeder;
 static void check(boolean v,String s){if(!v)throw new AssertionError(s);checks.add(s);System.out.println("PASS "+s);}
 static Map<String,Object> read(String name,Object...p)throws Exception{return NativeJobSteppingTest.read(name,p);}
 static JsonObject request(Object...p)throws Exception{return NativeJobSteppingTest.mutation(p);}
 static Map<String,Object> call(String name,JsonObject p)throws Exception{return NativeJobSteppingTest.call(name,p);}
 static Map<String,Object> waitOp(Map<String,Object> op)throws Exception{return NativeJobSteppingTest.await(op);}
 static long steps(Map<String,Object> op){return NativeJobSteppingTest.steps(op);}
 static Map<String,Object> result(Map<String,Object> op){return NativeJobSteppingTest.result(op);}
 static Map<String,Object> success(String name,Object...p)throws Exception{Map<String,Object> op=waitOp(call(name,request(p)));check("succeeded".equals(op.get("state")),name+" succeeds");return result(op);}
 static boolean held(){return machine.getHeads().stream().flatMap(h->h.getNozzles().stream()).anyMatch(n->n.getPart()!=null);}
 static Map<String,Object> pauseWithPart()throws Exception {
  String job=(String)success("prepare_job","canonical_job",NativeJobSteppingTest.canonical(part)).get("job_id");success("validate_job");Map<String,Object> op=waitOp(call("step_job",request("job_id",job)));int limit=0;
  while(!held()){check("paused".equals(op.get("state"))&&limit++<50,"bounded actual stepping until native nozzle holds part");op=waitOp(call("step_job",request("operation_id",op.get("operation_id"))));}
  check("paused".equals(op.get("state"))&&held(),"native held part is at a paused step boundary");return op;
 }
 /** Delegates every native method; gate occurs only AFTER actual standstill completion. */
 static final class CompletionGate implements MotionPlanner {
  final MotionPlanner delegate;final CountDownLatch reached=new CountDownLatch(1),release=new CountDownLatch(1);final AtomicBoolean armed=new AtomicBoolean();final AtomicInteger hits=new AtomicInteger();
  CompletionGate(MotionPlanner d){delegate=d;}
  public void waitForCompletion(HeadMountable h,CompletionType type)throws Exception{delegate.waitForCompletion(h,type);boolean bridgeFrame=false,processorFrame=false;for(StackTraceElement f:Thread.currentThread().getStackTrace()){bridgeFrame|=f.getClassName().equals(Bridge.class.getName());processorFrame|=f.getClassName().startsWith("org.openpnp.machine.reference.ReferencePnpJobProcessor");}if(type==CompletionType.WaitForStillstand&&machine.isTask(Thread.currentThread())&&bridgeFrame&&!processorFrame&&armed.compareAndSet(true,false)){hits.incrementAndGet();reached.countDown();if(!release.await(10,TimeUnit.SECONDS))throw new AssertionError("Owned completion gate timed out");}}
  public void home()throws Exception{delegate.home();}public void delay(int ms,HeadMountable...h)throws Exception{delegate.delay(ms,h);}public void unhome(){delegate.unhome();}public boolean isHomed(){return delegate.isHomed();}public void setGlobalOffsets(AxesLocation l)throws Exception{delegate.setGlobalOffsets(l);}public void moveTo(HeadMountable h,AxesLocation l,double s,Motion.MotionOption...o)throws Exception{delegate.moveTo(h,l,s,o);}public Motion getMomentaryMotion(double t){return delegate.getMomentaryMotion(t);}public Motion getLastMotion(){return delegate.getLastMotion();}public void clearMotionPlanOlderThan(double t){delegate.clearMotionPlanOlderThan(t);}public boolean isValidLocation(HeadMountable h,AxesLocation l){return delegate.isValidLocation(h,l);}public double getMinimumSpeed(){return delegate.getMinimumSpeed();}
  public String getPropertySheetHolderTitle(){return delegate.getPropertySheetHolderTitle();}public PropertySheetHolder[] getChildPropertySheetHolders(){return delegate.getChildPropertySheetHolders();}public PropertySheet[] getPropertySheets(){return delegate.getPropertySheets();}public Action[] getPropertySheetHolderActions(){return delegate.getPropertySheetHolderActions();}public Icon getPropertySheetHolderIcon(){return delegate.getPropertySheetHolderIcon();}public void findIssues(Solutions s){delegate.findIssues(s);}
 }
 static void abortDuringBarrier()throws Exception {
  Map<String,Object> prior=pauseWithPart();String id=(String)prior.get("operation_id");long before=steps(prior);int feeds=feeder.getFeedCount();MotionPlanner nativePlanner=machine.getMotionPlanner();CompletionGate gate=new CompletionGate(nativePlanner);((ReferenceMachine)machine).setMotionPlanner(gate);
  try{gate.armed.set(true);Map<String,Object> submitted=call("step_job",request("operation_id",id));check(gate.reached.await(10,TimeUnit.SECONDS),"actual native standstill completed before deterministic abort gate");check("running".equals(read("get_operation","operation_id",id).get("state")),"abort delivered while step wrapper still running");JsonObject abort=request("operation_id",id);call("abort_job",abort);gate.release.countDown();Map<String,Object> done=waitOp(submitted);System.out.println("JOB_STEPPING_RACE_OBSERVED "+new Gson().toJson(Bridge.map("case","abort-during-barrier","state",done.get("state"),"held",held(),"feeds",feeder.getFeedCount(),"steps",steps(done))));check("aborted".equals(done.get("state")),"abort during post-step barrier reaches terminal aborted without another command");check(gate.hits.get()==1&&steps(done)==before+1,"only the admitted native next call runs before abort cleanup");check(!held()&&feeder.getFeedCount()==feeds&&((Number)result(done).get("placed")).intValue()==0,"native cleanup clears held part without extra feed or placement");check("aborted".equals(call("abort_job",abort).get("state"))&&feeder.getFeedCount()==feeds,"lost abort reply replay does not repeat native cleanup");}
  finally{gate.release.countDown();((ReferenceMachine)machine).setMotionPlanner(nativePlanner);}
 }
 static void revokedBeforeDispatch()throws Exception {
  Map<String,Object> prior=pauseWithPart();String id=(String)prior.get("operation_id");long before=steps(prior);int feeds=feeder.getFeedCount();CountDownLatch entered=new CountDownLatch(1),release=new CountDownLatch(1);Future<Void> blocker=machine.submit(()->{entered.countDown();if(!release.await(10,TimeUnit.SECONDS))throw new AssertionError("Owned executor gate timed out");return null;},null,true);
  try{check(entered.await(5,TimeUnit.SECONDS),"owned native executor gate entered before queued step");JsonObject request=request("operation_id",id);Map<String,Object> submitted=call("step_job",request);read("release_control_session","session_id",NativeJobSteppingTest.session);release.countDown();blocker.get(5,TimeUnit.SECONDS);Map<String,Object> paused=waitOp(submitted);System.out.println("JOB_STEPPING_RACE_OBSERVED "+new Gson().toJson(Bridge.map("case","revoked-before-dispatch","state",paused.get("state"),"held",held(),"feeds",feeder.getFeedCount(),"steps",steps(paused),"active_operation_id",read("get_status").get("active_operation_id"))));check("paused".equals(paused.get("state")),"pre-dispatch ownership revocation preserves paused operation");check(steps(paused)==before&&held()&&feeder.getFeedCount()==feeds,"revoked queued step performs no next call, feed, discard or release");Map<String,Object> status=read("get_status");check("paused".equals(status.get("job_state"))&&id.equals(status.get("active_operation_id")),"paused native job remains active and owns held work");NativeJobSteppingTest.session=(String)read("request_control_session","request_id",UUID.randomUUID().toString(),"ttl_seconds",300).get("session_id");try{call("prepare_job",request("canonical_job",NativeJobSteppingTest.canonical(part)));throw new AssertionError("Expected BUSY");}catch(Bridge.Fault f){check("BUSY".equals(f.code),"new owner cannot overlap a replacement job with held paused work");}Map<String,Object> receipt=read("get_request_status","request_id",request.get("request_id").getAsString());check(Boolean.TRUE.equals(receipt.get("found")),"revoked queued request remains durably discoverable");Map<String,Object> done=waitOp(call("abort_job",request("operation_id",id)));check("aborted".equals(done.get("state"))&&!held()&&feeder.getFeedCount()==feeds,"new owner may explicitly clean up preserved paused job once");}
  finally{release.countDown();blocker.get(5,TimeUnit.SECONDS);}
 }
 public static void main(String[]args)throws Exception{
  String phase=args.length>2?args[2]:"all";if(!Arrays.asList("all","abort","revoke").contains(phase))throw new IllegalArgumentException("Expected all, abort or revoke phase");
  Path root=args.length>1?Paths.get(args[1]):Files.createTempDirectory("openpnp-native-job-stepping-");Files.createDirectories(root.resolve("config"));Path token=root.resolve("token");Files.writeString(token,UUID.randomUUID().toString()+UUID.randomUUID());Configuration.initialize(root.resolve("config").toFile());Configuration c=Configuration.get();c.load();SimulatorMain.accelerateFixture(c);SimulatorMain.configureSustainedWorkload(c);machine=c.getMachine();int exit=0;
  try{bridge=new Bridge(c,token,root.resolve("journal"),Paths.get(args[0]),0,true,"sustained-workload");NativeJobSteppingTest.bridge=bridge;NativeJobSteppingTest.machine=machine;NativeJobSteppingTest.session=(String)read("request_control_session","request_id",UUID.randomUUID().toString(),"ttl_seconds",300).get("session_id");part=c.getPart("R0603-1K");feeder=(ReferenceTrayFeeder)machine.getFeeders().stream().filter(f->f.isEnabled()&&f.getPart()==part).findFirst().orElseThrow();success("set_machine_enabled","enabled",true);success("home_machine");if(!phase.equals("revoke"))abortDuringBarrier();if(!phase.equals("abort"))revokedBeforeDispatch();check(feeder.getFeedCount()==(phase.equals("all")?2:1),"each selected adversarial fixture consumed exactly one native feed");success("set_machine_enabled","enabled",false);System.out.println("JOB_STEPPING_RACE_RESULT "+new Gson().toJson(Bridge.map("passed",true,"assertions",checks.size(),"checks",checks,"native_feeds",feeder.getFeedCount(),"native_placements",0,"phase",phase,"test_gates","owned executor admission and post-real-completion planner wrapper","hardware_qualified",false)));}catch(Throwable failure){failure.printStackTrace();exit=1;}finally{if(bridge!=null)bridge.close();machine.close();}System.exit(exit);
 }
}
