/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import com.google.gson.*;
import java.awt.geom.AffineTransform;
import java.beans.PropertyChangeListener;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.openpnp.model.*;
import org.openpnp.model.Abstract2DLocatable.Side;
import org.openpnp.util.Utils2D;

/** Actual native Job/Board/Panel graphs and serializer round trips; no motion or fake processor. */
public final class NativePlacementEditsTest {
    static Configuration config;static Part part,other;static Path temp;
    static final List<String> passed=new ArrayList<>();static final Gson GSON=new Gson();
    interface Action {void run()throws Exception;}
    static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
    static void near(double actual,double expected,String label){check(Math.abs(actual-expected)<1e-8,label+": "+actual+" != "+expected);}
    static void expect(String code,Action action)throws Exception {try{action.run();throw new AssertionError("Expected "+code);}catch(NativePlacementEdits.Fault e){check(e.code.equals(code),"Expected "+code+", got "+e.code+": "+e.getMessage());}}
    static JsonObject object(Object...pairs){JsonObject o=new JsonObject();for(int i=0;i<pairs.length;i+=2){Object v=pairs[i+1];if(v instanceof JsonElement)o.add((String)pairs[i],(JsonElement)v);else if(v instanceof String)o.addProperty((String)pairs[i],(String)v);else if(v instanceof Number)o.addProperty((String)pairs[i],(Number)v);else if(v instanceof Boolean)o.addProperty((String)pairs[i],(Boolean)v);else throw new IllegalArgumentException();}return o;}
    static JsonArray rows(JsonObject... rows){JsonArray a=new JsonArray();for(JsonObject r:rows)a.add(r);return a;}
    static JsonObject edit(String scope,String holder,String ref,JsonObject value){return object("scope",scope,"holder_instance_id",holder,"placement_id",ref,"set",value);}
    static JsonObject local(double x,double y,double z,double r){return object("frame","holder","units","mm","x",x,"y",y,"z",z,"rotation",r);}
    static Location pose(double x,double y,double z,double r){return new Location(LengthUnit.Millimeters,x,y,z,r);}
    static Placement placement(String id,double x,double y){Placement p=new Placement(id);p.setPart(part);p.setLocation(pose(x,y,0,15));p.setComments("original metadata");p.setRank(7);return p;}
    static Board board(){Board b=new Board();b.setName("shared-board");b.setDimensions(pose(20,10,0,0));b.addPlacement(placement("R1",2,3));b.addPlacement(placement("R2",7,8));Placement f=placement("FID",1,1);f.setType(Placement.Type.Fiducial);b.addPlacement(f);return b;}
    static BoardLocation boardLocation(Board d,String id,Side side,Location pose){BoardLocation b=new BoardLocation(new Board(d));b.setId(id);b.setSide(side);b.setLocation(pose);return b;}
    static PanelLocation panelLocation(Panel d,String id,Side side,Location pose){PanelLocation p=new PanelLocation(new Panel(d));p.setId(id);p.setSide(side);p.setLocation(pose);return p;}
    static Job fixture(boolean pseudo){
        try{Board b=board();Panel inner=new Panel();inner.setName("inner");inner.setDimensions(pose(50,30,0,0));inner.addChild(boardLocation(b,"A",Side.Top,pose(10,0,0,0)));inner.addChild(boardLocation(b,"B",Side.Top,pose(30,0,0,0)));if(pseudo)inner.addPseudoPlacement(inner.createPseudoPlacement("A⇒FID"));
            Panel outer=new Panel();outer.setName("outer");outer.setDimensions(pose(70,50,0,0));outer.addChild(panelLocation(inner,"nested",Side.Top,pose(0,0,0,0)));
            Job job=new Job();job.addBoardOrPanelLocation(boardLocation(b,"solo",Side.Bottom,pose(100,200,3,0)));job.addBoardOrPanelLocation(panelLocation(outer,"P1",Side.Top,pose(100,200,3,90)));job.addBoardOrPanelLocation(panelLocation(outer,"P2",Side.Top,pose(300,200,3,0)));PanelLocation.setParentsOfAllDescendants(job.getRootPanelLocation());return job;
        }catch(Exception e){throw new RuntimeException(e);}
    }
    static BoardLocation board(Job job,String id){for(BoardLocation b:job.getBoardLocations())if(b.getUniqueId().equals(id))return b;throw new AssertionError(id);}
    static Placement placement(Job j,String board,String ref){return board(j,board).getBoard().getPlacements().get(ref);}
    static Map<String,Object> snapshot(Job job){Map<String,Object> all=new LinkedHashMap<>();for(PlacementsHolderLocation<?> l:job.getBoardAndPanelLocations()){List<Object> ps=new ArrayList<>();for(Placement p:l.getPlacementsHolder().getPlacements())ps.add(Arrays.asList(p.getId(),p.getLocation().toString(),p.getSide(),p.getPart()==null?null:p.getPart().getId(),p.getType(),p.isEnabled(),p.getErrorHandling(),p.getComments(),p.getRank(),job.retrievePlacedStatus(l,p.getId())));List<Object> pseudo=new ArrayList<>();if(l instanceof PanelLocation)for(Placement p:((PanelLocation)l).getPanel().getPseudoPlacements())pseudo.add(Arrays.asList(p.getId(),p.getLocation().toString(),p.getSide(),p.getPart().getId(),p.getType(),p.isEnabled(),p.getComments(),p.getRank()));all.put(l.getUniqueId(),Arrays.asList(l.getLocation().toString(),l.getSide(),l.isLocallyEnabled(),l.isCheckFiducials(),ps,pseudo));}return all;}
    static Job roundTrip(Job j)throws Exception {NativeJobDocuments docs=new NativeJobDocuments(config,Files.createTempDirectory(temp,"documents-"));return docs.reload(docs.save(j).sha256);}
    public static void main(String[] args)throws Exception {
        temp=Files.createTempDirectory("openpnp-placement-edits-");Configuration.initialize(temp.toFile());config=Configuration.get();config.load();part=config.getParts().get(0);other=config.getParts().get(1);int exit=0;
        try{previewAndReject();sharedAndHistory();instanceAndNested();pseudoAndPanels();staleNoopsAndLimits();rollback();graphRejections();inspection();configurationReplacement();check(!config.getMachine().isEnabled()&&!config.getMachine().isHomed(),"No placement-edit test enabled or homed the machine");System.out.println("OPENPNP_NATIVE_PLACEMENT_EDITS_RESULT "+GSON.toJson(Bridge.map("passed",passed,"count",passed.size(),"native_machine_enabled",config.getMachine().isEnabled(),"native_machine_homed",config.getMachine().isHomed(),"motion_or_feed_methods_called_by_test",false,"physical_qualification",false)));}
        catch(Throwable e){e.printStackTrace();exit=1;}finally{config.getMachine().close();}System.exit(exit);
    }
    static void previewAndReject()throws Exception {
        Job j=fixture(false);Map<String,Object> before=snapshot(j);BoardLocation b=board(j,"solo");boolean dirty=j.isDirty();AtomicInteger events=new AtomicInteger();PropertyChangeListener observer=e->events.incrementAndGet();b.getBoard().getDefinition().addPropertyChangeListener(observer);
        JsonObject pose=object("frame","holder","units","in","x",0.5,"y",0.25,"z",0,"rotation",-90);JsonObject set=object("location",pose,"side","Bottom","part_id",other.getId());
        NativePlacementEdits.Patch plan=NativePlacementEdits.stage(config,j,rows(edit("job_instance","solo","R1",set)));
        check(before.equals(snapshot(j))&&dirty==j.isDirty()&&events.get()==0,"Preview leaves native graph, flags, definitions and history unchanged");
        JsonObject returned=plan.preview();returned.addProperty("valid",false);set.addProperty("side","Top");check(plan.preview().get("valid").getAsBoolean(),"Preview cannot mutate private plan data");
        plan.apply();Placement actual=placement(j,"solo","R1");near(actual.getLocation().getX(),12.7,"inches convert to mm");near(actual.getLocation().getY(),6.35,"inches Y");check(actual.getSide()==Side.Bottom&&actual.getPart()==other,"Mutable caller JSON cannot change staged side/part");
        expect("PLAN_CONSUMED",plan::apply);passed.add("read-only immutable preview, explicit inch/mm conversion, exact native part identity and single-use plan");
        Job invalid=fixture(false);Map<String,Object> untouched=snapshot(invalid);expect("PART_NOT_FOUND",()->NativePlacementEdits.stage(config,invalid,rows(edit("job_instance","solo","R1",object("enabled",false)),edit("job_instance","P1⇒nested⇒A","R2",object("part_id","missing-part")))));check(untouched.equals(snapshot(invalid)),"Late invalid row cannot publish early valid row");
        expect("OVERLAPPING_EDITS",()->NativePlacementEdits.stage(config,invalid,rows(edit("job_shared_definition","solo","R1",object("enabled",false)),edit("job_instance","P1⇒nested⇒A","R1",object("enabled",true)))));
        expect("COORDINATE_FRAME",()->NativePlacementEdits.stage(config,invalid,rows(edit("job_instance","solo","R1",object("location",object("frame","machine","units","mm","x",0,"y",0,"z",0,"rotation",0))))));
        passed.add("whole-batch rejection of late invalid parts, overlapping instance/shared edits and implicit machine coordinates");
    }
    static void sharedAndHistory()throws Exception {
        Job j=fixture(false);Board original=board(j,"solo").getBoard().getDefinition();Job outside=new Job();outside.addBoardOrPanelLocation(boardLocation(original,"external",Side.Top,pose(0,0,0,0)));Map<String,Object> outsideBefore=snapshot(outside);
        j.storePlacedStatus(board(j,"solo"),"R2",true);BoardLocation orphan=new BoardLocation();orphan.setId("removed-board");j.storePlacedStatus(orphan,"removed-reference",true);j.storePlacedStatus(orphan,"explicit-false",false);
        NativePlacementEdits.Patch patch=NativePlacementEdits.stage(config,j,rows(edit("job_shared_definition","solo","R1",object("location",local(4,5,1,30),"side","Bottom","rank",11))));
        check(patch.preview().getAsJsonArray("changes").get(0).getAsJsonObject().getAsJsonArray("affected").size()==5,"Preview enumerates all five same-definition instances");
        patch.apply();for(BoardLocation b:j.getBoardLocations()){Placement p=b.getBoard().getPlacements().get("R1");near(p.getLocation().getX(),4,"shared X");check(p.getSide()==Side.Bottom&&p.getRank()==11,"shared content applies across panel occurrences");}
        check(j.retrievePlacedStatus(board(j,"solo"),"R2")&&j.retrievePlacedStatus(orphan,"removed-reference")&&!j.retrievePlacedStatus(orphan,"explicit-false"),"Current and orphan native history maps survive intact");check(outsideBefore.equals(snapshot(outside))&&original.getPlacements().get("R1").getLocation().getX()==2,"Other job and original shared definition remain unchanged");
        Board clone=board(j,"solo").getBoard().getDefinition();for(BoardLocation b:j.getBoardLocations())check(b.getBoard().getDefinition()==clone,"Unsplit job definitions retain shared identity");
        Location global=Utils2D.calculateBoardPlacementLocation(board(j,"solo"),placement(j,"solo","R1"));near(global.getX(),116,"native bottom-width mirror X");near(global.getY(),205,"native bottom mirror Y");near(global.getZ(),4,"native board plus placement Z");near(global.getRotation(),30,"native side-specific rotation");
        Job loaded=roundTrip(j);check(snapshot(j).equals(snapshot(loaded))&&loaded.retrievePlacedStatus(orphan,"removed-reference"),"Native documents preserve changed shared data and orphan history");passed.add("job-local shared edits preserve sharing, bottom transforms, current/orphan history, outside jobs and native save/reload");
        Job placed=fixture(false);placed.storePlacedStatus(board(placed,"P2⇒nested⇒B"),"R1",true);Map<String,Object> unchanged=snapshot(placed);expect("PLACED_HISTORY_CONFLICT",()->NativePlacementEdits.stage(config,placed,rows(edit("job_shared_definition","solo","R1",object("enabled",false)))));check(unchanged.equals(snapshot(placed)),"Shared edit rejects a placed descendant before mutation");passed.add("placed descendant blocks ambiguous shared history changes even when the anchor itself is pending");
    }
    static void instanceAndNested()throws Exception {
        Job j=fixture(false);board(j,"P2⇒nested⇒A").getParent().setLocallyEnabled(false);board(j,"P1⇒nested⇒B").getBoard().getPlacements().get("R2").setEnabled(false);
        for(BoardLocation b:j.getBoardLocations())b.setLocalToGlobalTransform(AffineTransform.getTranslateInstance(99,98));
        Map<String,Object> result=NativePlacementEdits.stage(config,j,rows(edit("job_instance","P1⇒nested⇒A","R1",object("location",local(4,5,1,-30),"part_id",other.getId())),edit("job_instance","P1⇒nested⇒B","R2",object("error_handling","Defer")))).apply();
        check(((Number)result.get("private_instance_definition_count")).intValue()==3,"Nested board edit clones its board, inner panel and outer panel definitions");
        near(placement(j,"P1⇒nested⇒A","R1").getLocation().getX(),4,"selected nested placement");near(placement(j,"P2⇒nested⇒A","R1").getLocation().getX(),2,"sibling repeated panel unchanged");near(placement(j,"P1⇒nested⇒B","R1").getLocation().getX(),2,"neighbor board unchanged");
        check(placement(j,"P1⇒nested⇒B","R2").getErrorHandling()==Placement.ErrorHandling.Defer&&!placement(j,"P1⇒nested⇒B","R2").isEnabled(),"Instance error edit preserves existing per-instance disable");check(!board(j,"P2⇒nested⇒A").isEnabled(),"Ancestor X-out preserved");
        for(PlacementsHolderLocation<?> l:j.getBoardAndPanelLocations())if(l!=j.getRootPanelLocation())check(l.getPlacementsTransformStatus()==PlacementsHolderLocation.PlacementsTransformStatus.NotSet,"Every copied registration invalidated");
        Location global=Utils2D.calculateBoardPlacementLocation(board(j,"P1⇒nested⇒A"),placement(j,"P1⇒nested⇒A","R1"));near(global.getX(),95,"nested rotated X");near(global.getY(),214,"nested rotated Y");near(global.getZ(),4,"nested Z");near(global.getRotation(),60,"nested rotation");
        Job loaded=roundTrip(j);check(snapshot(j).equals(snapshot(loaded)),"Nested instance geometry and all X-outs/error overrides survive native documents");check(board(loaded,"P1⇒nested⇒A").getBoard().getDefinition()!=board(loaded,"P2⇒nested⇒A").getBoard().getDefinition(),"Edited physical copy retains private native definition after reload");passed.add("nested instance geometry clones only required ancestor definitions and survives native reload with X-outs, overrides and fresh registration");
        Job enabled=fixture(false);NativePlacementEdits.stage(config,enabled,rows(edit("job_instance","P1⇒nested⇒A","R1",object("enabled",false)))).apply();check(!placement(enabled,"P1⇒nested⇒A","R1").isEnabled()&&placement(enabled,"P2⇒nested⇒A","R1").isEnabled(),"Same ref on another repeated panel remains enabled");check(board(enabled,"P1⇒nested⇒A").getBoard().getDefinition()==board(enabled,"P2⇒nested⇒A").getBoard().getDefinition(),"Simple job override does not split shared board definitions");check(snapshot(enabled).equals(snapshot(roundTrip(enabled))),"Simple native per-instance override persists");passed.add("instance-only enable override uses native persistence without changing repeated sibling or shared geometry");
        Job defaults=fixture(false);for(BoardLocation b:defaults.getBoardLocations())b.getBoard().getPlacements().get("R1").setEnabled(false);
        NativePlacementEdits.Patch defaultPatch=NativePlacementEdits.stage(config,defaults,rows(edit("job_shared_definition","solo","R1",object("enabled",false))));check(defaultPatch.preview().get("changed").getAsBoolean(),"Changed shared default is not hidden by equal current instance overrides");defaultPatch.apply();check(!board(defaults,"solo").getBoard().getDefinition().getPlacements().get("R1").isEnabled(),"Requested shared default changes even when all instances were already disabled");passed.add("shared default update remains a real edit when every current instance already overrides that value");
    }
    static void pseudoAndPanels()throws Exception {
        Job j=fixture(true);Panel source=((PanelLocation)j.getRootPanelLocation().getChildren().get(1)).getPanel().getChild(0).getPlacementsHolder().getDefinition() instanceof Panel?(Panel)((PanelLocation)j.getRootPanelLocation().getChildren().get(1)).getPanel().getChild(0).getPlacementsHolder().getDefinition():null;
        Location before=source.getPseudoPlacement(0).getLocation();
        expect("PSEUDO_PLACEMENT_DERIVED",()->NativePlacementEdits.stage(config,j,rows(edit("job_instance","P1⇒nested","A⇒FID",object("enabled",false)))));
        NativePlacementEdits.stage(config,j,rows(edit("job_instance","P1⇒nested⇒A","FID",object("location",local(4,6,0,0))))).apply();
        Panel p1=((PanelLocation)((PanelLocation)j.getRootPanelLocation().getChildren().get(1)).getChildren().get(0)).getPanel();Panel p2=((PanelLocation)((PanelLocation)j.getRootPanelLocation().getChildren().get(2)).getChildren().get(0)).getPanel();
        near(p1.getPseudoPlacement(0).getLocation().getX(),14,"cloned panel pseudo X derives from edited child");near(p1.getPseudoPlacement(0).getLocation().getY(),6,"cloned pseudo Y");check(p2.getPseudoPlacement(0).getLocation().equals(before)&&source.getPseudoPlacement(0).getLocation().equals(before),"Sibling and original native pseudo remain unchanged");check(snapshot(j).equals(snapshot(roundTrip(j))),"Derived pseudo geometry persists native save/reload");passed.add("derived native pseudo-fiducials regenerate after nested leaf edit, preserve siblings and persist; direct pseudo edit rejected");
        Job panelJob=fixture(false);Panel outer=(Panel)panelJob.getRootPanelLocation().getChildren().get(1).getPlacementsHolder().getDefinition();Placement f=placement("PANEL-FID",3,4);f.setType(Placement.Type.Fiducial);outer.addPlacement(f);
        NativePlacementEdits.stage(config,panelJob,rows(edit("job_instance","P1","PANEL-FID",object("location",local(6,7,0,0))))).apply();check(panelJob.getRootPanelLocation().getChildren().get(1).getPlacementsHolder().getPlacements().get("PANEL-FID").getLocation().getX()==6,"Real panel fiducial edits supported");check(snapshot(panelJob).equals(snapshot(roundTrip(panelJob))),"Real panel fiducial edit persists");passed.add("real panel fiducial edits remain distinct from derived pseudo records and round-trip natively");
        Board nestedBoard=board();Panel inner=new Panel();inner.setDimensions(pose(30,20,0,0));inner.addChild(boardLocation(nestedBoard,"A",Side.Top,pose(3,0,0,90)));
        Panel parent=new Panel();parent.setDimensions(pose(50,50,0,0));PanelLocation nested=panelLocation(inner,"N",Side.Top,pose(10,20,0,90));PanelLocation.setParentsOfAllDescendants(nested);parent.addChild(nested);parent.addPseudoPlacement(parent.createPseudoPlacement("N⇒A⇒FID"));
        near(parent.getPseudoPlacement(0).getLocation().getX(),9,"Original multilevel pseudo independent golden X");near(parent.getPseudoPlacement(0).getLocation().getY(),22,"Original multilevel pseudo independent golden Y");
        Job multilevel=new Job();multilevel.addBoardOrPanelLocation(panelLocation(parent,"P",Side.Top,pose(100,200,0,0)));PanelLocation.setParentsOfAllDescendants(multilevel.getRootPanelLocation());
        NativePlacementEdits.stage(config,multilevel,rows(edit("job_instance","P⇒N⇒A","FID",object("location",local(4,6,0,0))))).apply();Panel edited=((PanelLocation)multilevel.getRootPanelLocation().getChildren().get(0)).getPanel();
        near(edited.getPseudoPlacement(0).getLocation().getX(),6,"Edited multilevel pseudo independent golden X");near(edited.getPseudoPlacement(0).getLocation().getY(),17,"Edited multilevel pseudo independent golden Y");
        check(snapshot(multilevel).equals(snapshot(roundTrip(multilevel))),"Multilevel rotated pseudo dependency survives native serialization");passed.add("multilevel rotated pseudo derivation uses cloned parent relationships with independent golden coordinates and native round-trip");
    }
    static void staleNoopsAndLimits()throws Exception {
        Job j=fixture(false);NativePlacementEdits.Patch p=NativePlacementEdits.stage(config,j,rows(edit("job_instance","solo","R1",object("enabled",false))));j.storePlacedStatus(board(j,"solo"),"R1",true);expect("STALE_PLACEMENT_PLAN",p::apply);check(placement(j,"solo","R1").isEnabled(),"History changed after preview blocks apply");
        Job changed=fixture(false);NativePlacementEdits.Patch stale=NativePlacementEdits.stage(config,changed,rows(edit("job_instance","solo","R1",object("enabled",false))));board(changed,"solo").setLocation(pose(9,9,0,0));expect("STALE_PLACEMENT_PLAN",stale::apply);passed.add("stale plan detects changed placed status and native load geometry before publication");
        Job noop=fixture(false);BoardLocation b=board(noop,"solo");noop.storePlacedStatus(b,"R1",true);b.setLocalToGlobalTransform(AffineTransform.getTranslateInstance(10,20));AffineTransform tx=b.getLocalToParentTransform();Map<String,Object> r=NativePlacementEdits.stage(config,noop,rows(edit("job_instance","solo","R1",object("enabled",true)))).apply();check(Boolean.FALSE.equals(r.get("changed"))&&board(noop,"solo")==b&&b.getLocalToParentTransform()==tx,"No-op on placed record preserves object identity and registration");passed.add("no-op edits preserve placed history, existing native object identity and registration");
        Job invalid=fixture(false);JsonArray tooMany=new JsonArray();for(int i=0;i<1001;i++)tooMany.add(edit("job_instance","solo","R1",object("enabled",false)));expect("EDIT_LIMIT",()->NativePlacementEdits.stage(config,invalid,tooMany));
        JsonObject bad=local(1,2,0,0);bad.addProperty("x",Double.NaN);expect("INVALID_FIELD",()->NativePlacementEdits.stage(config,invalid,rows(edit("job_instance","solo","R1",object("location",bad)))));
        expect("UNKNOWN_FIELD",()->NativePlacementEdits.stage(config,invalid,rows(edit("job_instance","solo","R1",object("script","anything")))));
        expect("GEOMETRY_RANGE",()->NativePlacementEdits.stage(config,invalid,rows(edit("job_instance","solo","R1",object("location",local(10001,0,0,0))))));
        placement(invalid,"solo","R1").setLocation(pose(999,999,0,0));expect("UNSUPPORTED_INSTANCE_DRIFT",()->NativePlacementEdits.stage(config,invalid,rows(edit("job_instance","solo","R1",object("enabled",false)))));
        passed.add("bounded typed edits reject nonfinite/out-of-range geometry, extra fields, oversized batches and preexisting unpersistable drift");
    }
    static void rollback()throws Exception {
        Job j=fixture(false);Map<String,Object> before=snapshot(j);List<PlacementsHolderLocation<?>> originals=new ArrayList<>(j.getRootPanelLocation().getChildren());j.setDirty(false);j.getRootPanelLocation().getPanel().setDirty(false);
        NativePlacementEdits.Patch p=NativePlacementEdits.stage(config,j,rows(edit("job_instance","solo","R1",object("location",local(8,9,0,0)))));
        AtomicInteger calls=new AtomicInteger();PropertyChangeListener failure=e->{if(e.getPropertyName().equals("children")&&calls.getAndIncrement()==0)throw new IllegalStateException("Injected native publication observer failure");};j.getRootPanelLocation().getPanel().addPropertyChangeListener(failure);
        expect("PLACEMENT_COMMIT_FAILED",p::apply);j.getRootPanelLocation().getPanel().removePropertyChangeListener(failure);
        check(before.equals(snapshot(j))&&j.getRootPanelLocation().getChildren().equals(originals)&&!j.isDirty()&&!j.getRootPanelLocation().getPanel().isDirty(),"Single-setter failure restores original objects, intent, history and dirty flags");
        for(BoardLocation b:j.getBoardLocations())check(b.getBoard().getDefinition().isListener(b.getBoard()),"Rollback retains original native definition subscriptions");
        passed.add("injected native setter/listener failure rolls back the original child tree, listeners and dirty flags and requires Bridge fencing");
        Job retire=fixture(false);List<BoardLocation> oldBoards=new ArrayList<>(retire.getBoardLocations());Board originalDefinition=oldBoards.get(0).getBoard().getDefinition();BoardLocation outside=boardLocation(originalDefinition,"outside",Side.Top,pose(0,0,0,0));
        for(BoardLocation b:oldBoards)check(originalDefinition.isListener(b.getBoard()),"Fixture copied board listens to original definition");
        NativePlacementEdits.stage(config,retire,rows(edit("job_instance","solo","R1",object("enabled",false)))).apply();
        for(BoardLocation b:oldBoards){check(!originalDefinition.isListener(b.getBoard()),"Retired board no longer retained by shared definition listener");for(Placement placement:b.getBoard().getPlacements())check(!placement.getDefinition().isListener(placement),"Retired placement no longer retained by source placement definition");}
        check(originalDefinition.isListener(outside.getBoard()),"Outside-job instance subscription is retained");originalDefinition.getPlacements().get("R1").setLocation(pose(88,77,0,0));near(outside.getBoard().getPlacements().get("R1").getLocation().getX(),88,"Outside instance still follows shared definition");near(oldBoards.get(0).getBoard().getPlacements().get("R1").getLocation().getX(),2,"Retired snapshot stops following shared edits");
        passed.add("successful replacement retires obsolete native instance listeners while preserving outside-job subscriptions and rollback subscriptions");
    }
    static void graphRejections()throws Exception {
        Job duplicate=fixture(false);board(duplicate,"solo").getBoard().getDefinition().addPlacement(placement("R1",4,5));expect("DUPLICATE_REFERENCE",()->NativePlacementEdits.stage(config,duplicate,rows(edit("job_instance","solo","R1",object("enabled",false)))));
        Job rootPose=fixture(false);rootPose.getRootPanelLocation().setLocation(pose(8,9,0,0));expect("UNSUPPORTED_JOB_ROOT",()->NativePlacementEdits.stage(config,rootPose,rows(edit("job_instance","solo","R1",object("enabled",false)))));
        Board custom=board();custom.setProfile(custom.getProfile());Job outline=new Job();outline.addBoardOrPanelLocation(boardLocation(custom,"solo",Side.Top,pose(0,0,0,0)));expect("UNSUPPORTED_OUTLINE",()->NativePlacementEdits.stage(config,outline,rows(edit("job_instance","solo","R1",object("enabled",false)))));
        Job pending=fixture(false);NativePlacementEdits.Patch p=NativePlacementEdits.stage(config,pending,rows(edit("job_instance","solo","R1",object("enabled",false))));BoardLocation original=board(pending,"solo");original.getBoard().getDefinition().getPlacements().get("R1").setComments("shared changed after stage");expect("STALE_PLACEMENT_PLAN",p::apply);check(board(pending,"solo")==original,"Shared-content stale rejection preserves original tree");passed.add("native duplicate references, custom root poses/outlines and post-preview shared-content changes reject before publication");
    }
    static void configurationReplacement()throws Exception {
        Job j=fixture(false);NativePlacementEdits.Patch plan=NativePlacementEdits.stage(config,j,rows(edit("job_instance","solo","R1",object("enabled",false))));Configuration previous=config;
        Configuration.initialize(Files.createTempDirectory("openpnp-placement-edits-replacement-").toFile());config=Configuration.get();config.load();expect("STALE_PLACEMENT_PLAN",plan::apply);check(placement(j,"solo","R1").isEnabled(),"Global Configuration replacement invalidates retained plan");previous.getMachine().close();passed.add("native Configuration replacement invalidates an otherwise unchanged retained placement plan");
    }
    @SuppressWarnings("unchecked")
    static void inspection()throws Exception {
        Job j=fixture(true);Board shared=board(j,"solo").getBoard().getDefinition();shared.getPlacements().get("R1").setLocation(new Location(LengthUnit.Inches,1,0.5,0,-90));
        placement(j,"P1⇒nested⇒B","R2").setEnabled(false);board(j,"P2⇒nested⇒A").getParent().setLocallyEnabled(false);j.storePlacedStatus(board(j,"P1⇒nested⇒A"),"R1",true);
        Map<String,Object> before=snapshot(j);boolean dirty=j.isDirty();AtomicInteger events=new AtomicInteger();PropertyChangeListener listener=e->events.incrementAndGet();shared.addPropertyChangeListener(listener);
        List<Map<String,Object>> rows=new ArrayList<>();String fingerprint=null;int offset=0;
        do{Map<String,Object> page=NativePlacementEdits.inspect(config,j,offset,3);check(((Number)page.get("total_records")).intValue()==17,"Includes15 real and2 pseudo expanded records");check(((Number)page.get("offset")).intValue()==offset&&((Number)page.get("limit")).intValue()==3,"Page echoes exact bounds");if(fingerprint==null)fingerprint=(String)page.get("source_fingerprint");check(fingerprint.equals(page.get("source_fingerprint")),"Stable native graph has stable page fingerprint");List<Map<String,Object>> records=(List<Map<String,Object>>)page.get("records");check(records.size()<=3&&records.size()==((Number)page.get("count")).intValue(),"Count matches bounded rows");rows.addAll(records);offset=((Number)page.get("next_offset")).intValue();if(Boolean.TRUE.equals(page.get("eof")))break;}while(true);
        check(rows.size()==17&&offset==17,"Pagination is complete and lossless");Set<String> keys=new LinkedHashSet<>();for(Map<String,Object> row:rows)check(keys.add(row.get("holder_instance_id")+"/"+row.get("placement_id")),"Every native placement identity appears once");
        Map<String,Object> solo=rows.get(0);check(solo.get("holder_instance_id").equals("solo")&&solo.get("placement_id").equals("R1")&&solo.get("holder_global_side")==Side.Bottom&&Boolean.FALSE.equals(solo.get("ordinary_active_side_placement")),"Opposite-side record remains inspectable");Map<String,Object> pose=(Map<String,Object>)solo.get("location");check(pose.get("frame").equals("holder")&&pose.get("units").equals("mm"),"Readback uses explicit usable local mm");near(((Number)pose.get("x")).doubleValue(),25.4,"Inspection converts inches exactly");near(((Number)pose.get("y")).doubleValue(),12.7,"Inspection converts inches Y");
        int pseudos=0;boolean disabled=false,xout=false,placed=false;
        for(Map<String,Object> row:rows){if(Boolean.TRUE.equals(row.get("derived"))){pseudos++;check(Boolean.TRUE.equals(row.get("read_only"))&&row.get("holder_kind").equals("panel")&&row.get("placement_id").equals("A⇒FID"),"Derived panel record read-only and exact native ID");}if(row.get("holder_instance_id").equals("P1⇒nested⇒B")&&row.get("placement_id").equals("R2"))disabled=Boolean.FALSE.equals(row.get("enabled"));if(row.get("holder_instance_id").equals("P2⇒nested⇒A"))xout|=Boolean.TRUE.equals(row.get("holder_locally_enabled"))&&Boolean.FALSE.equals(row.get("holder_effectively_enabled"));if(row.get("holder_instance_id").equals("P1⇒nested⇒A")&&row.get("placement_id").equals("R1"))placed=Boolean.TRUE.equals(row.get("placed"));}
        check(pseudos==2&&disabled&&xout&&placed,"Inspection includes derived, disabled, ancestor-X-out and actually placed records");
        solo.put("part_id","tampered-return");pose.put("x",999);check(before.equals(snapshot(j))&&j.isDirty()==dirty&&events.get()==0,"Inspection and caller DTO edits cause no native mutation or notifications");
        for(PlacementsHolderLocation<?> loc:j.getBoardAndPanelLocations())check(loc.getPlacementsTransformStatus()==PlacementsHolderLocation.PlacementsTransformStatus.NotSet,"Inspection does not synthesize or cache registration");shared.removePropertyChangeListener(listener);
        j.storePlacedStatus(board(j,"solo"),"R1",true);String afterReal=(String)NativePlacementEdits.inspect(config,j,0,1).get("source_fingerprint");check(!fingerprint.equals(afterReal),"Page fingerprint changes with actual native placed history");
        PanelLocation pseudoHolder=(PanelLocation)board(j,"P1⇒nested⇒A").getParent();j.storePlacedStatus(pseudoHolder,"A⇒FID",true);Map<String,Object> afterPseudo=NativePlacementEdits.inspect(config,j,0,200);check(!afterReal.equals(afterPseudo.get("source_fingerprint")),"Pseudo native placed status participates in the exact inspection fingerprint");boolean pseudoPlaced=false;for(Map<String,Object> row:(List<Map<String,Object>>)afterPseudo.get("records"))if(row.get("holder_instance_id").equals("P1⇒nested")&&row.get("placement_id").equals("A⇒FID"))pseudoPlaced=Boolean.TRUE.equals(row.get("placed"));check(pseudoPlaced,"Fingerprint change corresponds to the published pseudo placed row");passed.add("read-only native inspection pages every enabled/disabled/opposite-side/X-out/pseudo record with usable holder coordinates and complete history fingerprint");
        for(int[] bounds:new int[][]{{-1,1},{0,0},{0,201},{10001,1},{18,1}})expect("INSPECTION_PAGE_RANGE",()->NativePlacementEdits.inspect(config,j,bounds[0],bounds[1]));
        Map<String,Object> end=NativePlacementEdits.inspect(config,j,17,200);check(Boolean.TRUE.equals(end.get("eof"))&&((Number)end.get("count")).intValue()==0&&((Number)end.get("next_offset")).intValue()==17,"Exact end offset returns explicit empty EOF");
        Job empty=new Job();Map<String,Object> none=NativePlacementEdits.inspect(config,empty,0,100);check(Boolean.TRUE.equals(none.get("eof"))&&((Number)none.get("total_records")).intValue()==0,"Empty native job has finite empty inspection");passed.add("inspection rejects invalid page ranges and returns explicit terminal pages without mutation");
    }
}
