import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TOOL_DEFINITIONS, publicDefinition } from './contracts.mjs';
const source = path.dirname(fileURLToPath(import.meta.url));
const destination = path.resolve(source, '../../../plugins/openpnp/mcp');
await mkdir(destination, { recursive: true });
const result = await build({
  absWorkingDir: source, entryPoints: ['server.mjs'], outfile: path.join(destination, 'server.mjs'),
  bundle: true, platform: 'node', format: 'esm', target: 'node22',
  external: ['./domain/index.mjs'], sourcemap: false, metafile: true, legalComments: 'external',
  banner: { js: '/* Generated by src/openpnp/node/build.mjs. See THIRD_PARTY_NOTICES.md for dependency licenses. */\nimport { createRequire as __openpnpCreateRequire } from "node:module"; const require = __openpnpCreateRequire(import.meta.url);' },
});
await writeFile(path.join(source, 'build-inputs.json'), JSON.stringify(Object.keys(result.metafile.inputs).sort(), null, 2) + '\n');
await writeFile(path.join(destination, 'tool-inputs.json'), JSON.stringify({
  schema_version: 1,
  bridge_protocol_version: '1.0',
  upstream_commit: '5bd404cfc70f34103a3ca0fbb6b50c2b465f407c',
  scope: 'Public MCP input schemas. Tool discovery and runtime validation use the same source definitions.',
  tools: TOOL_DEFINITIONS.map(publicDefinition),
}, null, 2) + '\n');
console.log(`Built ${path.relative(process.cwd(), destination)}/server.mjs`);
