import { NATIVE_CHANGE_SCHEMAS } from './settings-contracts.mjs';
const string = (maxLength = 128) => ({ type: 'string', minLength: 1, maxLength });
const id = string();
const number = { type: 'number' };
const bool = { type: 'boolean' };
const readView = { enum: ['full', 'progress'], default: 'full', description: 'Use progress for repeated polls: bounded native state, IDs, counters, faults and supplied freshness, without retaining a full snapshot. Full (default) returns complete details with exact retained pagination when large. Read full once at pause/terminal for evidence; that read is a new observation.' };
const object = (properties = {}, required = []) => ({ type: 'object', properties, required, additionalProperties: false });
const revision = { type: 'string', pattern: '^cfg-[0-9]+$', maxLength: 64 };
const loadRevision = { type: 'string', pattern: '^load-[0-9]+$', maxLength: 64 };
const jobRevision = { type: 'string', pattern: '^[a-f0-9]{64}$' };
const uuid = { type: 'string', pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$' };
const nativeId = { ...string(), pattern: '^[^⇒\\u0000]+$' };
const holderId = { ...string(2048), pattern: '^[^\\u0000]+$' };
const mutation = { request_id: id, session_id: id, expected_config_revision: revision };
const tools = [];
function add(name, description, schema, { mutating = false, offline = false } = {}) {
  tools.push({ name: `openpnp_${name}`, description, inputSchema: schema, annotations: {
    title: name.replaceAll('_', ' '), readOnlyHint: !mutating, destructiveHint: mutating,
    idempotentHint: !mutating, openWorldHint: false,
  }, mutating, offline });
}
const command = (properties = {}, required = []) => object({ ...mutation, ...properties }, ['request_id', 'session_id', ...required]);

add('run_controller_diagnostic', 'Run the fixed bind/connect(G21,G90)/identify(M115)/close recipe once in a fresh owned loopback controller simulator. Requires the observed controller identity, configuration revision and control session. No motion, raw commands, endpoint selection or hardware qualification. Returns an operation; unknown admission/completion consumes the generation and must be observed by its original request ID without replay.', command({ request_id: { type: 'string', pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' }, controller_instance_id: { type: 'string', pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' } }, ['expected_config_revision', 'controller_instance_id']), { mutating: true });

add('get_capabilities', 'Discover this bridge build, genuine simulator attestation, supported tools, and qualification limits before choosing a workflow.', object());
add('get_status', 'Observe machine and job state without enabling, moving, feeding, or probing the machine. Use view:progress for repeated polls and full for selected detailed snapshots. Native timestamps and unknown observations remain unchanged; progress does not archive full snapshots.', object({ view: readView }));
add('get_configuration', 'Read a native configuration snapshot and its revision; this does not save or modify configuration.', object());
add('request_control_session', 'Acquire a bounded native ownership lease. Automatic grant is limited to the native simulator; physical control requires the bridge local grant workflow.', object({ request_id: id, ttl_seconds: { type: 'integer', minimum: 10, maximum: 600 } }, ['request_id']), { mutating: true });
add('get_control_session', 'Read the native ownership lease and epoch without acquiring control.', object());
add('get_request_status', 'Reconcile a request by its original request ID after a lost response. Never generate a new ID to retry an unknown action. Use view:progress while polling, then full once when paused or terminal to retain complete evidence.', object({ request_id: id, view: readView }, ['request_id']));
for (const verb of ['renew', 'release']) add(`${verb}_control_session`, `${verb === 'renew' ? 'Renew' : 'Release'} the existing native ownership lease.`, object({ session_id: id, ...(verb === 'renew' ? { ttl_seconds: { type: 'integer', minimum: 10, maximum: 600 } } : {}) }, ['session_id']), { mutating: true });
add('set_machine_enabled', 'Request machine enable or disable under native ownership. Disabling is not a hardware emergency stop.', command({ enabled: bool }, ['enabled']), { mutating: true });
add('home_machine', 'Run the qualified native homing sequence, which can move axes. Returns an operation to observe.', command(), { mutating: true });
add('plan_motion', 'Validate and preview an absolute pose in the native machine frame under an existing session. Does not move. Execution rechecks state and ownership.', object({ session_id: id, expected_config_revision: revision, tool_id: id, x: number, y: number, z: number, rotation: number, units: { const: 'mm' }, speed: { type: 'number', exclusiveMinimum: 0, maximum: 1 } }, ['session_id', 'x', 'y', 'z', 'units']));
add('execute_motion', 'Execute a native validated motion plan using its plan ID. Never reconstruct or retry a lost physical action.', command({ plan_id: id }, ['plan_id']), { mutating: true });
add('capture_camera', 'Capture a native raw or settled camera frame with camera and capture provenance through the native executor. Returns an operation and artifact.', command({ camera_id: id, mode: { enum: ['raw', 'settled'], default: 'raw' } }), { mutating: true });
const sensingRequestId = { type: 'string', pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' };
const sensingNozzleId = { type: 'string', pattern: '^[A-Za-z0-9_.:+-]{1,128}$' };
const recoveryJobFields = ['job_id', 'expected_job_revision', 'expected_board_load_revision', 'expected_material_revision', 'original_operation_id'];
const recoveryRequest = command({
  request_id: sensingRequestId,
  recovery_kind: { enum: ['restore-sensing-readiness', 'replace-faulted-job-attempt', 'continue-faulted-job-replacement', 'restart-faulted-job-replacement'] },
  job_id: sensingRequestId, expected_job_revision: jobRevision, expected_board_load_revision: loadRevision,
  expected_material_revision: { type: 'string', pattern: '^material-[0-9]+$', maxLength: 64 },
  original_operation_id: sensingRequestId,
  replacement_attempt_id: sensingRequestId,
}, ['expected_config_revision', 'recovery_kind']);
recoveryRequest.allOf = [{
  if: { properties: { recovery_kind: { const: 'replace-faulted-job-attempt' } }, required: ['recovery_kind'] },
  then: { properties: Object.fromEntries(recoveryJobFields.map(field => [field, recoveryRequest.properties[field]])), required: recoveryJobFields },
  else: { not: { anyOf: recoveryJobFields.map(field => ({ properties: { [field]: recoveryRequest.properties[field] }, required: [field] })) } },
}, {
  if: { properties: { recovery_kind: { enum: ['continue-faulted-job-replacement', 'restart-faulted-job-replacement'] } }, required: ['recovery_kind'] },
  then: { properties: { replacement_attempt_id: sensingRequestId }, required: ['replacement_attempt_id'] },
  else: { not: { properties: { replacement_attempt_id: sensingRequestId }, required: ['replacement_attempt_id'] } },
}];
add('request_sensing_reconciliation', 'Request an expiring, one-use local simulator recovery form for the complete sensing fault set. Requires the disabled GUI simulator and exact configuration revision. Standalone recovery repairs the synthetic source and performs fresh native probes. Replacing a faulted job requires its exact job/load/material revisions and original operation; the local action disposes nozzle material, retires captured trays and boards, and creates a separately validated replacement attempt. Continuing a replacement requires its canonical replacement_attempt_id and a same-process retained candidate. Restarting a replacement requires its canonical replacement_attempt_id, explicit GUI restart mode with no live sensing source, and restart_request_available. That local decision reconstructs inactive job graphs and records fresh source, tray and board observations; its completion preserves sensing faults and grants no execution readiness. A separate continuation decision performs the remaining repair, disposal, probes and replacement work. The Bridge captures its current complete transaction, faults and source scope for a new local one-use decision. Completed replacement/load effects are not replayed; fresh repair, disposal and probes follow the locally reviewed proposed effects. Original failed or unknown outcomes remain unchanged. No remote observation submission or physical qualification.', recoveryRequest, { mutating: true });
add('get_sensing_reconciliation', 'Read a sensing recovery task, local operation, native probe evidence and durable disposition. Historical records never recreate a local grant, controlled source or current nozzle readiness.', object({ task_id: sensingRequestId }, ['task_id']));
add('measure_sensor', 'Collect 1–32 immediate native vacuum readings for the selected nozzle under a current control session and configuration revision. Requires the advertised controlled simulator sensing profile. Returns an operation with source and units provenance; measurements alone do not verify occupancy. Samples are count-bounded, not a hardware I/O deadline. Reconcile a lost response by the original request ID without replay.', command({ request_id: sensingRequestId, nozzle_id: sensingNozzleId, samples: { type: 'integer', minimum: 1, maximum: 32, default: 1 } }, ['expected_config_revision', 'nozzle_id']), { mutating: true });
add('verify_part_state', 'Execute a native part-on or part-off check using the selected nozzle’s configured Absolute thresholds and controlled simulator source. Returns an operation and durable observation. Part-off actively pulses the bound vacuum valve and requires an enabled, homed nozzle at Safe Z with no model-held part. Read the actual effect order from events. Retained or uncertain occupancy blocks further action; an ordinary check cannot clear a fault. Synthetic signals do not qualify physical presence or pressure.', command({ request_id: sensingRequestId, nozzle_id: sensingNozzleId, state: { enum: ['part_on', 'part_off'] } }, ['expected_config_revision', 'nozzle_id', 'state']), { mutating: true });
add('get_operation', 'Observe an admitted operation through completion, failure, or outcome-unknown. Use view:progress for polling, then full once when paused or terminal for complete evidence. While running, an earlier result can remain from a prior pause; get_status.job_progress provides separately timestamped counts. Client cancellation does not stop physical motion.', object({ operation_id: id, view: readView }, ['operation_id']));
add('get_events', 'Read sequenced native events. On resync_required, reread authoritative snapshots instead of inferring missing state.', object({ after_sequence: { type: 'integer', minimum: 0 }, limit: { type: 'integer', minimum: 1, maximum: 500 } }));
add('prepare_job', 'Prepare a native OpenPnP job from the bundled pnp-test fixture or a previously imported canonical artifact. With part_bindings, resolve source IDs to existing configured parts for this import; all unbound IDs must also exist and package/height must match. This optional branch requires the advertised existing-parts-v1 profile, a canonical request UUID and current revision, and creates no parts. The legacy branch retains its import behavior. Preparation does not establish electrical equivalence or start production.', {
  type: 'object', properties: { ...mutation, sample: { const: 'pnp-test' }, artifact_id: { type: 'string', pattern: '^[a-f0-9]{64}$' }, part_bindings: { type: 'array', minItems: 1, maxItems: 1000, items: object({ source_part_id: { ...id, pattern: '^[A-Za-z0-9_.:+-]{1,128}$' }, native_part_id: { ...id, pattern: '^[A-Za-z0-9_.:+-]{1,128}$' } }, ['source_part_id', 'native_part_id']) } },
  required: ['request_id', 'session_id'], additionalProperties: false,
  oneOf: [{ properties: { sample: { const: 'pnp-test' } }, required: ['sample'] }, { properties: { artifact_id: { type: 'string' } }, required: ['artifact_id'] }],
  allOf: [{ if: { properties: { part_bindings: { type: 'array' } }, required: ['part_bindings'] }, then: { required: ['artifact_id', 'expected_config_revision'], properties: { artifact_id: { type: 'string' }, expected_config_revision: revision, request_id: { type: 'string', pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' } } } }],
}, { mutating: true });
add('validate_job', 'Check the currently loaded native job model and return an operation with prerequisites. The native processor performs its own preflight when the job starts; model validation does not prove placement quality.', command(), { mutating: true });
add('save_job', 'Save the current job and its referenced native board/panel definitions as a hash-verified document bundle. Preserves placed history and static transforms. This does not create a portable machine backup.', command(), { mutating: true });
add('load_job', 'Reload a native document bundle saved in this installation’s owned document store, including after a bridge restart. Verifies its private receipt and component dependencies, preserves recorded placement history, and requires fresh job validation and alignment. Accepts an artifact ID, never a path or arbitrary XML.', command({ artifact_id: id }, ['artifact_id']), { mutating: true });
add('get_board_loads', 'Read native root and descendant board-load identities, job and load revisions, facing sides, retained history, and required presence confirmations. Simulator records do not verify a physical board or underside clearance.', object());
const materialUuid = { type: 'string', pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' };
const materialRevision = { type: 'string', pattern: '^material-[0-9]+$', maxLength: 64 };
add('get_material_loads', 'Read cached virtual tray-load identities, retained native index observations, setup revision, available tray geometry digests with observation timestamps, and unresolved feed/change records. Supported by the finite-tray sustained or attested sensing simulator profiles. Reads do not refresh hardware or verify physical stock. Full retained response paging remains available when large.', object());
const materialCommand = command({ request_id: materialUuid, expected_material_revision: materialRevision, feeder_id: id, part_id: id, expected_geometry_sha256: jobRevision, action: { enum: ['bind-existing', 'replace-full-tray'] }, expected_load_id: materialUuid }, ['expected_config_revision', 'expected_material_revision', 'feeder_id', 'part_id', 'expected_geometry_sha256', 'action']);
materialCommand.allOf = [{ if: { properties: { action: { const: 'replace-full-tray' } }, required: ['action'] }, then: { properties: { expected_load_id: materialUuid }, required: ['expected_load_id'] }, else: { not: { properties: { expected_load_id: materialUuid }, required: ['expected_load_id'] } } }];
add('register_material_load', 'Bind an existing virtual tray index or explicitly replace a full tray with the same native part and geometry. Use the observed material revision/digest and exact previous load ID for replacement; initial binding omits it. Requires a disabled, idle finite-tray sustained or attested sensing simulator and empty nozzles. Returns an operation, preserves retired load history, and requires job revalidation. Enrolled loads block generic settings/restores and manual feeder tests. No physical refill, powered feeder, paused-job refill, or restart reattachment; unknown outcomes cannot be replayed.', materialCommand, { mutating: true });
const loadCommand = command({ expected_board_load_revision: loadRevision, job_id: id, root_instance_id: nativeId, action: { enum: ['replace', 'flip', 'same-load'] }, side: { enum: ['top', 'bottom'] }, expected_load_id: uuid }, ['expected_config_revision', 'expected_board_load_revision', 'job_id', 'root_instance_id', 'action', 'side']);
loadCommand.allOf = [{ if: { properties: { action: { enum: ['flip', 'same-load'] } }, required: ['action'] }, then: { properties: { expected_load_id: uuid }, required: ['expected_load_id'] } }];
add('register_board_load', 'Record an explicit simulator board replacement, flip, or same-load confirmation for an exact current native root. Requires the current load revision and, for any existing binding or flip/same-load, its expected_load_id. Returns an operation; invalidates registration and production validation. This records operator intent without verifying physical presence, clearance, or undoing placed material.', loadCommand, { mutating: true });

const bounded = maximum => ({ type: 'number', minimum: -maximum, maximum });
const placementPose = { oneOf: ['mm', 'in'].map(units => {
  const scale = units === 'mm' ? 1 : 25.4;
  return object({ frame: { const: 'holder' }, units: { const: units }, x: bounded(10000 / scale), y: bounded(10000 / scale), z: bounded(1000 / scale), rotation: bounded(360) }, ['frame', 'units', 'x', 'y', 'z', 'rotation']);
}) };
const placementSet = { ...object({ location: placementPose, side: { enum: ['Top', 'Bottom'] }, type: { enum: ['Placement', 'Fiducial'] }, part_id: { ...id, pattern: '^[^\\u0000]+$' }, enabled: bool, error_handling: { enum: ['Default', 'Alert', 'Defer'] }, comments: { type: 'string', maxLength: 2048, pattern: '^[^\\u0000]*$' }, rank: { type: 'integer', minimum: -100000, maximum: 100000 } }), minProperties: 1 };
const placementEnvelope = { job_id: id, expected_job_revision: jobRevision, expected_board_load_revision: loadRevision };
const placementRequired = ['expected_config_revision', 'job_id', 'expected_job_revision', 'expected_board_load_revision'];
add('request_board_inspection', 'Request a five-minute local inspection form for one completed native loaded board with at most 200 required placements. Requires the local GUI simulator, disabled machine, empty nozzles and exact current job/configuration/load revisions. Returns a short operation and task_id; observations are submitted only in the local form. Native identities and history are rechecked before a durable receipt. Operator reports and simulator placement history do not authenticate measurements or grant production authority.', command({ ...placementEnvelope, request_id: materialUuid, loaded_board_id: string(512) }, [...placementRequired, 'loaded_board_id']), { mutating: true });
add('get_board_inspection', 'Read a retained native loaded-board inspection task, local submission operation and receipt by task_id. Historical requests never restore local submission authority. Reported measurements remain operator-supplied; no physical qualification or production authority is granted.', object({ task_id: materialUuid }, ['task_id']));
add('inspect_job', 'Read a native executor-owned page of all real and derived placement records, including disabled holders, opposite sides, panel fiducials, X-outs and placed history. Returns an operation with exact native IDs and holder-local mm/degrees. Use current job/configuration/load revisions and the first page’s source_fingerprint as expected_source_fingerprint on later pages. Derived pseudo records are read-only. Does not change native job fields, move, or feed; the request receipt is retained.', command({ ...placementEnvelope, expected_source_fingerprint: jobRevision, offset: { type: 'integer', minimum: 0, maximum: 10000, default: 0 }, limit: { type: 'integer', minimum: 1, maximum: 200, default: 100 } }, placementRequired), { mutating: true });
add('plan_placement_edits', 'Admit an executor-owned preview of typed edits to existing native placements. Returns an operation whose completed result contains plan_id and every affected instance. Bind exact current job/configuration/load revisions. job_instance affects one expanded holder; job_shared_definition affects its shared definition within this job. Coordinates are explicit local holder mm/in and degrees. No placement fields, machine position, feeds, or files change during planning; the request and plan receipt are retained.', command({ ...placementEnvelope, changes: { type: 'array', minItems: 1, maxItems: 1000, items: object({ scope: { enum: ['job_instance', 'job_shared_definition'] }, holder_instance_id: holderId, placement_id: nativeId, set: placementSet }, ['scope', 'holder_instance_id', 'placement_id', 'set']) } }, [...placementRequired, 'changes']), { mutating: true });
add('apply_placement_edits', 'Apply a reviewed native placement plan once under the same job, configuration, load revision and owner. Returns an operation. Changed placed records are rejected; unchanged history is preserved. Copies required shared definitions within this job, invalidates registration/validation and board-load bindings, and requires explicit load confirmation or replacement before production. Save the document separately. Does not move or feed the machine.', command({ ...placementEnvelope, plan_id: id }, [...placementRequired, 'plan_id']), { mutating: true });
const structurePlacement = { ...placementSet, required: Object.keys(placementSet.properties) };
const structureScope = { scope: { enum: ['job_instance', 'job_shared_definition'] }, holder_instance_id: holderId };
const structureChange = { oneOf: [
  object({ action: { const: 'add' }, ...structureScope, placement_id: { ...id, pattern: '^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$' }, placement: structurePlacement }, ['action', 'scope', 'holder_instance_id', 'placement_id', 'placement']),
  object({ action: { const: 'remove' }, ...structureScope, placement_id: nativeId }, ['action', 'scope', 'holder_instance_id', 'placement_id']),
] };
// New panel selectors preserve native identity, including well-formed Unicode.
const panelParentId = { ...string(512), pattern: '^[^\\u0000-\\u001f\\u007f-\\u009f\\ud800-\\udfff]+$' };
const panelChildId = { ...string(128), pattern: '^[^⇒\\u0000-\\u001f\\u007f-\\u009f\\ud800-\\udfff]+$' };
const panelScope = { scope: { const: 'job_instance' }, parent_instance_id: panelParentId };
const panelBoardChange = { oneOf: [
  object({ action: { const: 'clone_board_child' }, ...panelScope, source_child_id: panelChildId, new_child_id: { ...id, pattern: '^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$' }, location: placementPose, side: { enum: ['Top', 'Bottom'] }, enabled: bool, check_fiducials: bool }, ['action', 'scope', 'parent_instance_id', 'source_child_id', 'new_child_id', 'location', 'side', 'enabled', 'check_fiducials']),
  object({ action: { const: 'remove_board_child' }, ...panelScope, child_id: panelChildId }, ['action', 'scope', 'parent_instance_id', 'child_id']),
] };
const structureChanges = { oneOf: [
  { type: 'array', minItems: 1, maxItems: 100, items: structureChange },
  { type: 'array', minItems: 1, maxItems: 1, items: panelBoardChange },
] };
add('plan_placement_structure', 'Preview adding or removing real placements/fiducials on existing boards in a trusted unused simulator job. Returns an operation whose completed result binds a plan, exact lineage/revision and every affected instance. Requires disabled machine, empty nozzles, complete empty current/retired native history and no prior processor admission. New records require every placement field and an existing part/package. Native coordinates are local holder mm/in and degrees. The separately advertised panel-board-membership-v1 profile permits exactly one direct board-child clone or removal in one panel instance, with explicit local pose/side/flags for cloning. It cannot mix panel and placement actions. Pseudo-dependent removal, shared-panel or subtree edits, renaming and reused logical IDs are refused. Planning retains a receipt without publishing the job tree; dimensions and poses do not establish physical clearance.', command({ ...placementEnvelope, changes: structureChanges }, [...placementRequired, 'changes']), { mutating: true });
add('apply_placement_structure', 'Apply a reviewed structure plan once under the same native job/configuration/load/lineage and owner. Durably reserves touched logical IDs before publishing a detached job tree; invalidates job validation, cached plans, registration and load bindings. Pending or uncertain publication retains its reservation and cannot be retried. Save separately and explicitly rebind loads before revalidation. Does not move, feed, reset placed history or qualify hardware. Old documents and jobs without trusted unused lineage are refused.', command({ ...placementEnvelope, plan_id: id }, [...placementRequired, 'plan_id']), { mutating: true });
add('start_job', 'Start the selected validated native job under the existing control lease, returning an operation ID.', command({ job_id: id }, ['job_id']), { mutating: true });
const stepJob = command({ job_id: id, operation_id: id }, ['expected_config_revision']);
stepJob.oneOf = [{ properties: { job_id: id }, required: ['job_id'] }, { properties: { operation_id: id }, required: ['operation_id'] }];
add('step_job', 'Advance exactly one native processor next() call in the simulator, then wait for native standstill and return a paused or completed operation. A native step can include multiple motions/actions or no placement. Supply job_id to begin a validated job, or operation_id to advance its paused operation; choose exactly one and bind the current configuration revision. Reuse the original operation throughout the job. Repeated request IDs return its receipt without advancing again. Unknown outcomes require reconciliation.', stepJob, { mutating: true });
for (const verb of ['pause', 'resume', 'abort']) add(`${verb}_job`, `${verb === 'abort' ? 'Abort the native job; cleanup can move axes and discard parts. This is not an emergency stop.' : `${verb} the native job at its supported cooperative boundary; observe the returned state.`}`, command({ operation_id: id }, ['operation_id']), { mutating: true });

add('plan_configuration', 'Stage a revision-bound patch of supported native settings and shared-reference effects. Changes use explicit mm/degrees and replace the named setting group. Vision settings require a separate vision-only patch. Mapped-axis geometry requires a separate plan containing exactly one change; supported existing native links and transformed limits are revalidated before application. Native validation checks the whole patch before applying anything. No settings are applied by planning.', object({ session_id: id, expected_config_revision: revision, changes: { type: 'array', minItems: 1, maxItems: 50, items: { oneOf: NATIVE_CHANGE_SCHEMAS } } }, ['session_id', 'changes']));
add('apply_configuration', 'Apply and persist the selected typed native configuration plan under its current revision and lease.', command({ plan_id: id }, ['plan_id']), { mutating: true });
add('test_feeder', 'Advance one native feeder using the selected nozzle. A feed can consume material; this operation is not a passive check.', command({ feeder_id: id, nozzle_id: id }, ['feeder_id']), { mutating: true });
add('control_actuator', 'Command one allowlisted native actuator. Returned command state is not independent physical feedback.', command({ actuator_id: id, enabled: bool }, ['actuator_id', 'enabled']), { mutating: true });
add('change_nozzle_tip', 'Use the native nozzle-tip change sequence. Omit nozzle_tip_id to unload. This can move axes.', command({ nozzle_id: id, nozzle_tip_id: id }, ['nozzle_id']), { mutating: true });
add('backup_configuration', 'Save and snapshot the supported native configuration files into a bridge artifact. The result declares whether it is a complete portable backup.', command(), { mutating: true });
add('export_portable_configuration', 'Export the disabled, idle supported native simulator configuration as a portable ZIP artifact for fresh-instance adoption. Preserves seven native XML documents and inventoried images; scripts are quarantined. Supports advertised saved flat-board and saved-board-child-panel-library-v1 profiles. The panel profile uses archive version 3 for clean saved panels with direct board children, exact board references and supported fiducials; inspect its advertised bounds. Refuses dirty or changed definitions, nested panels, custom outlines and unsupported pad shapes. Transfers no operational history, physical authority or calibration qualification; source feeder counters remain unqualified simulator data.', command({}, ['expected_config_revision']), { mutating: true });
add('export_run_report', 'Export a native run report with operation provenance and stated inspection limits through the native executor.', command(), { mutating: true });
add('get_native_artifact', 'Read a camera frame, backup, or report artifact from the connected native bridge by its native artifact ID.', object({ artifact_id: id }, ['artifact_id']));
const runoutCalibration = command({ recipe_id: { const: 'nozzle-tip-runout' }, nozzle_id: id, enable: bool }, ['recipe_id', 'nozzle_id']);
const cameraScaleCalibration = command({
  request_id: { type: 'string', pattern: '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' },
  recipe_id: { const: 'camera-planar-scale' }, camera_id: id,
  displacement_mm: { type: 'number', minimum: 0.5, maximum: 2 },
  expected_feature_diameter_px: { type: 'integer', minimum: 12, maximum: 96 },
}, ['expected_config_revision', 'recipe_id', 'camera_id', 'displacement_mm', 'expected_feature_diameter_px']);
const calibrationCommand = {
  type: 'object', properties: { ...runoutCalibration.properties, ...cameraScaleCalibration.properties,
    request_id: id, recipe_id: { enum: ['nozzle-tip-runout', 'camera-planar-scale'] } },
  additionalProperties: false, oneOf: [runoutCalibration, cameraScaleCalibration],
};
add('run_calibration', 'Run native nozzle-tip runout, or measure planar camera scale from eight native simulator frames and a fixed bounded XY sequence. Camera scale requires a current revision, an approximately calibrated head ImageCamera and one isolated circular feature; returns an unapplied proposal with separate image-prediction checks. Neither native fitted offsets nor simulator image predictions establish physical accuracy. Observe the original operation; no automatic retry after unknown effects.', calibrationCommand, { mutating: true });
add('validate_calibration', 'Read the native nozzle-tip calibration model through the executor. Report validity and fitted offsets with their limits; this does not independently qualify hardware.', command({ nozzle_id: id }, ['nozzle_id']), { mutating: true });
add('locate_fiducials', 'Use OpenPnP native vision to locate fiducials for the current job and update board alignment. This may move the camera and change job coordinates.', command(), { mutating: true });
add('list_issues', 'Run a fresh native Issues & Solutions scan through the executor. Scanning updates native issue bookkeeping; returned issues are advisory and unsupported solutions cannot be auto-applied.', command(), { mutating: true });
add('restore_configuration', 'Restore the supported typed setting subset from a native backup made by this bridge instance. The result declares the restore scope; this does not restore physical position, material, or placement history.', command({ artifact_id: id }, ['artifact_id']), { mutating: true });
add('reconcile_operation', 'Explicitly abandon an unknown operation from a prior native simulator instance after a fresh simulator reset. Retains the unknown historical outcome and never replays it.', command({ operation_id: id, disposition: { const: 'abandon-after-simulator-reset' } }, ['operation_id', 'disposition']), { mutating: true });

add('import_job', 'Parse supplied KiCad position, reference CSV, or canonical JSON content into a deterministic local job artifact. Reports source rows, units, and unresolved data; does not touch the machine.', object({
  format: { enum: ['kicad-pos', 'reference-csv', 'canonical-json'] }, content: string(4 * 1024 * 1024), bomContent: string(4 * 1024 * 1024),
  units: { enum: ['mm', 'in', 'mil'] }, mapping: { type: 'object', additionalProperties: string(128), maxProperties: 30 },
  boardId: id, jobId: id, widthMm: { type: 'number', exclusiveMinimum: 0 }, heightMm: { type: 'number', exclusiveMinimum: 0 }, variant: id,
  kicadBottomConvention: { enum: ['negated-x', 'top-view'] },
}, ['format', 'content']), { mutating: true, offline: true });
add('validate_imported_job', 'Validate a local canonical job artifact and report unresolved heights, identities, side transforms, and placement requirements. No physical qualification is implied.', object({ artifact_id: { type: 'string', pattern: '^[a-f0-9]{64}$' }, mode: { enum: ['offline', 'production'], default: 'offline' } }, ['artifact_id']), { offline: true });
add('get_artifact', 'Read an immutable local imported job artifact by SHA-256 identifier.', object({ artifact_id: { type: 'string', pattern: '^[a-f0-9]{64}$' } }, ['artifact_id']), { offline: true });

const sha = { type: 'string', pattern: '^[a-f0-9]{64}$' };
add('read_response_page', 'Read a page from an exact locally retained large MCP response, without contacting the machine. JSON mode pages array items or object entries; bytes mode returns serialized JSON bytes (exact retained bytes at pointer ""); decoded-base64 mode returns original binary bytes from a selected base64 string. Follow count, next_offset and eof; oversized JSON items require child pointers or bytes mode. No arbitrary paths or prototype access.', object({
  response_id: sha, pointer: { type: 'string', maxLength: 4096 }, offset: { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER },
  limit: { type: 'integer', minimum: 1, maximum: 16384, description: 'At most 500 values in JSON mode or 16384 bytes in either byte mode. The inline byte budget may return fewer JSON values.' }, format: { enum: ['json', 'bytes', 'decoded-base64'] },
}, ['response_id']), { offline: true });
add('record_inspection', 'Evaluate explicitly supplied independent inspection measurements against supplied tolerances and persist an immutable receipt. Do not invent measurements or evidence. External evidence references are recorded, not independently authenticated; this tool never grants production or hardware qualification.', object({
  job_artifact_id: sha, configuration_revision: sha, board_load_id: id, placement_key: string(1024),
  method: { enum: ['operator-metrology', 'calibrated-vision', 'external-metrology'] }, actor: id,
  observed_at: { type: 'string', pattern: '^\\d{4}-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d(?:\\.\\d{3})?Z$' },
  presence: { enum: ['present', 'missing', 'unknown'] }, polarity: { enum: ['correct', 'incorrect', 'not-applicable', 'unknown'] },
  measurements: object({ dxMm: number, dyMm: number, rotationErrorDeg: number, uncertaintyMm: { type: 'number', minimum: 0 }, uncertaintyDeg: { type: 'number', minimum: 0 } }, ['dxMm', 'dyMm', 'rotationErrorDeg', 'uncertaintyMm', 'uncertaintyDeg']),
  tolerances: object({ xyMm: { type: 'number', exclusiveMinimum: 0 }, rotationDeg: { type: 'number', exclusiveMinimum: 0 } }, ['xyMm', 'rotationDeg']),
  evidence: { type: 'array', minItems: 1, maxItems: 32, items: object({ id, sha256: sha, kind: { enum: ['image', 'measurement-file', 'operator-note'] } }, ['id', 'sha256', 'kind']) },
}, ['job_artifact_id', 'configuration_revision', 'board_load_id', 'placement_key', 'method', 'actor', 'observed_at', 'presence', 'polarity', 'measurements', 'tolerances', 'evidence']), { mutating: true, offline: true });
add('assess_inspection_coverage', 'Check passing inspection coverage for the exact canonical job revision, supplied configuration revision, and physical board-load identity. Missing, stale, or uncertain evidence blocks coverage; coverage is distinct from native production authorization.', object({
  job_artifact_id: sha, configuration_revision: sha, board_load_id: id, inspection_artifact_ids: { type: 'array', maxItems: 10000, uniqueItems: true, items: sha },
}, ['job_artifact_id', 'configuration_revision', 'board_load_id', 'inspection_artifact_ids']), { offline: true });

export const TOOL_DEFINITIONS = Object.freeze(tools);
export const TOOL_BY_NAME = new Map(tools.map(tool => [tool.name, tool]));
export function publicDefinition({ mutating, offline, ...definition }) { return definition; }
