/* SPDX-License-Identifier: GPL-3.0-or-later */
package org.openpnp.codex;

import java.awt.geom.*;
import java.beans.PropertyChangeListener;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.nio.file.attribute.PosixFilePermissions;
import java.security.MessageDigest;
import java.util.*;
import java.util.zip.*;
import org.openpnp.model.*;
import org.openpnp.model.Abstract2DLocatable.Side;
import org.openpnp.util.IdentifiableList;
import org.openpnp.util.Pair;

/** Owned, HMAC-verified generated candidate documents. The Bridge must hold its exclusive storage
 * lock. The closed graph manifest is the reconstruction format; native Job XML is supplementary
 * generated evidence, not an external XML import path. This avoids the pinned native outline
 * decoder and copy-constructor losses without narrowing NativeReplacementJob's model support.
 * Reload only constructs unpublished native objects. It never installs, initializes, feeds,
 * clears placed history, restores sensing grants, or confirms any physical/simulator load. */
final class NativeReplacementDocuments {
    static final String FORMAT="openpnp-replacement-candidate-v1";
    private static final int MAX_BYTES=NativeDocumentStore.MAX_ARCHIVE_BYTES,MAX_NODES=100000,MAX_RELOADS=32;
    private final Configuration config;private final NativeDocumentStore store;private int reloads;
    static final class Context {
        final Map<String,Object> payload;
        Context(String originalJobId,String replacementAttemptId,String recoveryOperationId,String faultSetSha256)throws Exception {
            uuid(originalJobId);uuid(replacementAttemptId);uuid(recoveryOperationId);hash(faultSetSha256);
            if(originalJobId.equals(replacementAttemptId)||originalJobId.equals(recoveryOperationId)||replacementAttemptId.equals(recoveryOperationId))throw bad("Candidate identities must be distinct");
            payload=frozen(map("original_job_id",originalJobId,"replacement_attempt_id",replacementAttemptId,"recovery_operation_id",recoveryOperationId,"fault_set_sha256",faultSetSha256));
        }
    }
    static final class Saved {final String documentId;final Map<String,Object> manifest;private Saved(String id,Map<String,Object> manifest){documentId=id;this.manifest=manifest;}}
    final class Reloaded implements AutoCloseable {
        private final Decoder decoder;private final NativeReplacementJob.Candidate witness;private final Job job;private final Map<String,Object> manifest,graph;private boolean closed,published;
        private Reloaded(Decoder decoder,NativeReplacementJob.Candidate witness,Job job,Map<String,Object> manifest,Map<String,Object> graph){this.decoder=decoder;this.witness=witness;this.job=job;this.manifest=manifest;this.graph=graph;}
        Job job(){if(closed)throw new IllegalStateException("Candidate document is closed");return job;}
        Map<String,Object> mapping()throws Exception{return object(manifest.get("source_mapping"));}
        Map<String,Object> manifest(){return manifest;}
        void requireCurrent()throws Exception {owner();if(closed)throw bad("Reconstructed candidate is closed");if(published)throw bad("Reconstructed candidate ownership was transferred");witness.requireCurrent();if(!same(graph,new Encoder(config,job,false).payload()))throw bad("Reconstructed candidate changed");verifyDependencies(object(manifest.get("required_parts")),object(manifest.get("required_packages")));}
        /** Cleanup ownership transfer only; no installation or execution authority. */
        void publish()throws Exception{requireCurrent();witness.close();published=true;}
        public void close(){if(!closed&&!published){witness.close();decoder.cleanup();closed=true;}}
    }
    NativeReplacementDocuments(Configuration config,Path generatedRoot,Path allowedOwnedRoot)throws Exception {this(config,generatedRoot,allowedOwnedRoot,(path,renamed)->{});}
    /** Deterministic private crash seam; never selected by request data or environment. */
    NativeReplacementDocuments(Configuration config,Path generatedRoot,Path allowedOwnedRoot,NativeDocumentStore.PublicationProbe probe)throws Exception {
        this.config=Objects.requireNonNull(config);Path configured=allowedOwnedRoot.toAbsolutePath().normalize(),allowed=configured.toRealPath(),candidate=generatedRoot.toAbsolutePath().normalize();
        if(candidate.startsWith(configured))candidate=allowed.resolve(configured.relativize(candidate));
        if(candidate.equals(allowed)||!candidate.startsWith(allowed))throw bad("Generated document store must be inside its owned root");
        for(Path path=candidate;path!=null&&path.startsWith(allowed);path=path.getParent())if(Files.isSymbolicLink(path))throw bad("Document store does not follow symbolic links");
        Files.createDirectories(candidate,PosixFilePermissions.asFileAttribute(PosixFilePermissions.fromString("rwx------")));store=new NativeDocumentStore(candidate.toRealPath(),probe);
    }
    Saved save(Context context,NativeReplacementJob.Candidate candidate)throws Exception {
        owner();Objects.requireNonNull(context);candidate.requireCurrent();Encoder encoder=new Encoder(config,candidate.job(),false);Map<String,Object> graph=encoder.payload(),mapping=frozen(candidate.mapping());
        LinkedHashMap<String,String> parts=new LinkedHashMap<>(),packages=new LinkedHashMap<>();for(Part part:encoder.parts){canonical(part);parts.put(part.getId(),fingerprint(part));packages.put(part.getPackage().getId(),fingerprint(part.getPackage()));}
        byte[] xml;try(NativeReplacementJob.Candidate copy=NativeReplacementJob.build(config,candidate.job())){ByteArrayOutputStream out=new ByteArrayOutputStream();Configuration.createSerializer().write(copy.job(),out);xml=out.toByteArray();if(xml.length>MAX_BYTES)throw bad("Supplementary native Job XML exceeds document bound");}
        Map<String,Object> manifest=frozen(map("format",FORMAT,"schema_version",1,"upstream_commit",Bridge.UPSTREAM,"context",context.payload,"candidate_graph",graph,"candidate_graph_sha256",digest(graph),"source_mapping",mapping,"source_mapping_sha256",digest(mapping),"required_parts",parts,"required_packages",packages,"native_job_xml_sha256",sha(xml),"native_xml_role","supplementary-native-serialization; closed-graph-is-reconstruction-format","candidate_history_entries",0,"job_installed",false,"native_job_initialized",false,"execution_authority_restored",false,"load_presence_verified",false));
        LinkedHashMap<String,byte[]> entries=new LinkedHashMap<>();entries.put("job.job.xml",xml);entries.put("manifest.json",json(manifest));LinkedHashMap<String,String> hashes=new LinkedHashMap<>();for(Map.Entry<String,byte[]> entry:entries.entrySet())hashes.put(entry.getKey(),sha(entry.getValue()));byte[] archive=zip(entries);String id=sha(archive);
        candidate.requireCurrent();verifyDependencies(object(manifest.get("required_parts")),object(manifest.get("required_packages")));store.save(id,archive,hashes,parts,packages);store.verify(id);candidate.requireCurrent();return new Saved(id,manifest);
    }
    /** Verify the exact previously recorded archive without reconstructing native objects or
     * restoring any runtime authority. The caller separately guards its current local decision. */
    void verifySaved(String documentId,Context expected,Map<String,Object> expectedManifest)throws Exception {
        owner();hash(documentId);validateManifest(expectedManifest,expected);
        NativeDocumentStore.Record receipt=store.verify(documentId);byte[] bytes=read(receipt.file,MAX_BYTES);
        if(!sha(bytes).equals(documentId))throw bad("Candidate archive digest mismatch");
        Map<String,byte[]> entries=unzip(bytes,receipt.hashes);Map<String,Object> manifest=NativeJournalJson.parseObject(new String(entries.get("manifest.json"),StandardCharsets.UTF_8));
        if(!same(expectedManifest,manifest)||!sha(entries.get("job.job.xml")).equals(hash(manifest.get("native_job_xml_sha256")))||!same(receipt.parts,manifest.get("required_parts"))||!same(receipt.packages,manifest.get("required_packages")))throw bad("Recorded candidate archive no longer matches its exact manifest and receipt");
    }
    /** Pure closed-schema validation shared by forced journal replay and archive consumers. */
    static void validateManifest(Map<String,Object> manifest,Context expected)throws Exception {
        keys(manifest,"format","schema_version","upstream_commit","context","candidate_graph","candidate_graph_sha256","source_mapping","source_mapping_sha256","required_parts","required_packages","native_job_xml_sha256","native_xml_role","candidate_history_entries","job_installed","native_job_initialized","execution_authority_restored","load_presence_verified");
        if(!FORMAT.equals(manifest.get("format"))||number(manifest.get("schema_version"))!=1||!Bridge.UPSTREAM.equals(manifest.get("upstream_commit"))||!same(expected.payload,manifest.get("context"))||number(manifest.get("candidate_history_entries"))!=0)throw bad("Candidate document context/version differs");
        for(String key:List.of("job_installed","native_job_initialized","execution_authority_restored","load_presence_verified"))if(!Boolean.FALSE.equals(manifest.get(key)))throw bad("Candidate document cannot restore authority");
        if(!"supplementary-native-serialization; closed-graph-is-reconstruction-format".equals(manifest.get("native_xml_role")))throw bad("Candidate native XML role differs");hash(manifest.get("native_job_xml_sha256"));
        if(!digest(object(manifest.get("candidate_graph"))).equals(hash(manifest.get("candidate_graph_sha256")))||!digest(object(manifest.get("source_mapping"))).equals(hash(manifest.get("source_mapping_sha256"))))throw bad("Candidate content/mapping digest mismatch");
        for(String key:List.of("required_parts","required_packages"))for(Object value:object(manifest.get(key)).values())hash(value);
    }
    Reloaded reload(String documentId,Context expected)throws Exception {
        owner();hash(documentId);if(reloads>=MAX_RELOADS)throw bad("Candidate reconstruction limit reached");NativeDocumentStore.Record receipt=store.verify(documentId);byte[] bytes=read(receipt.file,MAX_BYTES);if(!sha(bytes).equals(documentId))throw bad("Candidate archive digest mismatch");Map<String,byte[]> entries=unzip(bytes,receipt.hashes);Map<String,Object> manifest=NativeJournalJson.parseObject(new String(entries.get("manifest.json"),StandardCharsets.UTF_8));
        validateManifest(manifest,expected);
        if(!"supplementary-native-serialization; closed-graph-is-reconstruction-format".equals(manifest.get("native_xml_role"))||!sha(entries.get("job.job.xml")).equals(hash(manifest.get("native_job_xml_sha256"))))throw bad("Supplementary native XML binding differs");
        Map<String,Object> graph=object(manifest.get("candidate_graph")),mapping=object(manifest.get("source_mapping"));if(!digest(graph).equals(hash(manifest.get("candidate_graph_sha256")))||!digest(mapping).equals(hash(manifest.get("source_mapping_sha256"))))throw bad("Candidate content/mapping digest mismatch");
        if(!same(receipt.parts,manifest.get("required_parts"))||!same(receipt.packages,manifest.get("required_packages")))throw bad("Signed candidate dependencies differ");verifyDependencies(object(manifest.get("required_parts")),object(manifest.get("required_packages")));reloads++;
        Decoder decoder=new Decoder(config,graph);NativeReplacementJob.Candidate witness=null;try{Job job=decoder.build();if(!same(graph,new Encoder(config,job,false).payload()))throw bad("Native candidate graph round-trip differs");witness=NativeReplacementJob.build(config,job);if(!Objects.equals(witness.mapping().get("replacement_model_sha256"),mapping.get("replacement_model_sha256")))throw bad("Native model differs from original candidate mapping");
            verifyDependencies(object(manifest.get("required_parts")),object(manifest.get("required_packages")));return new Reloaded(decoder,witness,job,frozen(manifest),frozen(graph));
        }catch(Exception|Error failure){if(witness!=null)witness.close();decoder.cleanup();throw failure;}
    }
    private void owner()throws Exception{owner(config);}
    private static void owner(Configuration config)throws Exception{if(config==null||Configuration.get()!=config||config.getMachine()==null||!config.getMachine().isTask(Thread.currentThread()))throw bad("Current configuration and native executor required");}
    private void canonical(Part part)throws Exception{canonical(config,part);}
    private static void canonical(Configuration config,Part part)throws Exception{if(part==null||config.getPart(part.getId())!=part||part.getPackage()==null||config.getPackage(part.getPackage().getId())!=part.getPackage())throw bad("Canonical native Part/Package required");}
    private void verifyDependencies(Map<String,Object> parts,Map<String,Object> packages)throws Exception{verifyDependencies(config,parts,packages);}
    private static void verifyDependencies(Configuration config,Map<String,Object> parts,Map<String,Object> packages)throws Exception{Set<String> requiredPackages=new TreeSet<>();for(Map.Entry<String,Object> entry:parts.entrySet()){Part value=config.getPart(entry.getKey());canonical(config,value);requiredPackages.add(value.getPackage().getId());if(!fingerprint(value).equals(hash(entry.getValue())))throw bad("Candidate Part dependency changed: "+entry.getKey());}if(!requiredPackages.equals(packages.keySet()))throw bad("Candidate Package dependency set differs from its canonical Parts");for(Map.Entry<String,Object> entry:packages.entrySet()){org.openpnp.model.Package value=config.getPackage(entry.getKey());if(value==null||!fingerprint(value).equals(hash(entry.getValue())))throw bad("Candidate Package dependency changed: "+entry.getKey());}}

    private static final class Encoder {
        final Configuration config;
        final Job job;final IdentityHashMap<Object,Integer> ids=new IdentityHashMap<>();final List<Object> objects=new ArrayList<>();final IdentityHashMap<Placement,Panel> pseudoOwners=new IdentityHashMap<>();final Set<Part> parts=new LinkedHashSet<>();
        Encoder(Configuration config,Job job,boolean historical)throws Exception{this.config=config;this.job=job;NativeBoardLoads.validateCandidate(job);if(!historical&&!job.getPlacedStatusSnapshot().isEmpty())throw bad("Only unexecuted candidate documents can be saved");ref(job.getRootPanelLocation());for(int i=0;i<objects.size();i++)discover(objects.get(i));}
        Map<String,Object> provenance()throws Exception{
            List<Object> nodes=new ArrayList<>();for(int i=0;i<objects.size();i++){Object value=objects.get(i);Map<String,Object> row=map("index",i,"type",value.getClass().getSimpleName());
                if(value instanceof PlacementsHolderLocation){PlacementsHolderLocation<?> l=(PlacementsHolderLocation<?>)value;AffineTransform t=l.getLocalToParentTransform();List<Object> matrix=null;if(t!=null){double[] a=new double[6];t.getMatrix(a);matrix=new ArrayList<>();for(double d:a)matrix.add(finite(d));}row.putAll(map("file",l.getFileName(),"dirty",l.isDirty(),"registration",matrix,"registration_status",l.getPlacementsTransformStatus().name()));}
                else if(value instanceof PlacementsHolder){PlacementsHolder<?> h=(PlacementsHolder<?>)value;row.putAll(map("file",h.getFile()==null?null:h.getFile().toString(),"dirty",h.isDirty()));}
                else if(value instanceof Placement)row.put("dirty",((Placement)value).isDirty());nodes.add(row);
            }return frozen(map("role","inert-only; never opened or applied","job_file",job.getFile()==null?null:job.getFile().toString(),"job_dirty",job.isDirty(),"nodes",nodes));
        }
        Integer ref(Object value)throws Exception{if(value==null)return null;Integer id=ids.get(value);if(id==null){if(objects.size()>=MAX_NODES)throw bad("Candidate graph exceeds node bound");id=objects.size();ids.put(value,id);objects.add(value);}return id;}
        List<Object> refs(Collection<?> values)throws Exception{List<Object> out=new ArrayList<>();for(Object value:values)out.add(ref(value));return out;}
        void discover(Object value)throws Exception{
            if(value instanceof PlacementsHolderLocation){PlacementsHolderLocation<?> l=(PlacementsHolderLocation<?>)value;ref(l.getDefinition());ref(l.getParent());ref(l.getPlacementsHolder());}
            else if(value instanceof PlacementsHolder){PlacementsHolder<?> h=(PlacementsHolder<?>)value;ref(h.getDefinition());refs(h.getPlacements());if(h instanceof Panel){Panel p=(Panel)h;for(Placement placement:p.getPseudoPlacements())if(placement instanceof PseudoPlacement)pseudoOwners.putIfAbsent(placement,p);refs(p.getChildren());refs(p.getPseudoPlacements());}else refs(((Board)h).getSolderPastePads());}
            else if(value instanceof Placement){Placement p=(Placement)value;ref(p.getDefinition());if(p.getPart()!=null){canonical(config,p.getPart());parts.add(p.getPart());}}
            else if(!(value instanceof BoardPad))throw bad("Unsupported candidate native node");
        }
        Map<String,Object> payload()throws Exception{
            List<Object> nodes=new ArrayList<>();for(Object value:objects){Map<String,Object> row;
                if(value instanceof PlacementsHolderLocation){PlacementsHolderLocation<?> l=(PlacementsHolderLocation<?>)value;if(l.getClass()!=BoardLocation.class&&l.getClass()!=PanelLocation.class)throw bad("Unsupported location subclass");row=map("type",l.getClass().getSimpleName(),"definition",ref(l.getDefinition()),"parent",ref(l.getParent()),"holder",ref(l.getPlacementsHolder()),"id",l.getId(),"location",pose(l.getLocation()),"side",l.getSide().name(),"enabled",l.isLocallyEnabled(),"check_fiducials",l.isCheckFiducials());}
                else if(value instanceof PlacementsHolder){PlacementsHolder<?> h=(PlacementsHolder<?>)value;if(h.getClass()!=Board.class&&h.getClass()!=Panel.class)throw bad("Unsupported holder subclass");GeometricPath2D path=h.getProfile();row=map("type",h.getClass().getSimpleName(),"definition",ref(h.getDefinition()),"name",h.getName(),"dimensions",pose(h.getDimensions()),"profile",path==h.getProfile()?path(path):null,"placements",refs(h.getPlacements()),"children",h instanceof Panel?refs(((Panel)h).getChildren()):List.of(),"pseudo",h instanceof Panel?refs(((Panel)h).getPseudoPlacements()):List.of(),"pads",h instanceof Board?refs(((Board)h).getSolderPastePads()):List.of());}
                else if(value instanceof Placement){Placement p=(Placement)value;if(p.getClass()!=Placement.class&&p.getClass()!=PseudoPlacement.class)throw bad("Unsupported placement subclass");row=map("type",p.getClass().getSimpleName(),"definition",ref(p.getDefinition()),"pseudo_owner",p instanceof PseudoPlacement?ref(pseudoOwners.get(p)):null,"id",p.getId(),"location",pose(p.getLocation()),"side",p.getSide().name(),"part",p.getPart()==null?null:p.getPart().getId(),"kind",p.getType().name(),"enabled",p.isEnabled(),"error",p.getErrorHandling().name(),"comments",p.getComments(),"rank",p.getRank());}
                else {BoardPad p=(BoardPad)value;row=map("type","BoardPad","name",p.getName(),"location",pose(p.getLocation()),"side",p.getSide().name(),"kind",p.getType().name(),"shape",pad(p.getPad()));}nodes.add(row);
            }
            List<Object> overrides=new ArrayList<>();for(PlacementsHolderLocation<?> l:job.getBoardAndPanelLocations()){List<Object> placements=new ArrayList<>();for(Placement p:l.getPlacementsHolder().getPlacements())placements.add(map("placement",ref(p),"enabled",job.retrieveEnabledState(l,p),"error",job.retrieveErrorHandlingState(l,p).name()));overrides.add(map("location",ref(l),"enabled",job.retrieveEnabledState(l,null),"check_fiducials",job.retrieveCheckFiducialsState(l),"placements",placements));}
            return frozen(map("schema_version",1,"root",ref(job.getRootPanelLocation()),"error_handling",job.getErrorHandling().name(),"nodes",nodes,"overrides",overrides));
        }
    }
    private static final class Edge {final AbstractModelObject source;final PropertyChangeListener listener;final String property;Edge(AbstractModelObject s,PropertyChangeListener l,String p){source=s;listener=l;property=p;}void remove(){if(property==null){while(source.isListener(listener))source.removePropertyChangeListener(listener);}else while(source.isListener(property,listener))source.removePropertyChangeListener(property,listener);}}
    private static final class Decoder {
        final Configuration config;
        final Map<String,Object> graph;final List<Map<String,Object>> rows=new ArrayList<>();final List<Object> objects=new ArrayList<>();final List<Edge> edges=new ArrayList<>();final Set<Integer> constructingPseudo=new HashSet<>();final List<Runnable> restoreListeners=new ArrayList<>();Job job;
        Decoder(Configuration config,Map<String,Object> graph)throws Exception{this.config=config;this.graph=graph;keys(graph,"schema_version","root","error_handling","nodes","overrides");if(number(graph.get("schema_version"))!=1)throw bad("Candidate graph schema");for(Object value:list(graph.get("nodes"),MAX_NODES))rows.add(object(value));if(rows.isEmpty())throw bad("Empty candidate graph");}
        <T>T own(T value){if(value instanceof AbstractModelObject&&value instanceof PropertyChangeListener)edge((AbstractModelObject)value,value,null);return value;}
        void edge(AbstractModelObject from,Object to,String property){if(to instanceof PropertyChangeListener)edges.add(new Edge(from,(PropertyChangeListener)to,property));}
        Object at(Object raw)throws Exception{int id=index(raw,rows.size());Object value=objects.get(id);if(value==null)value=pseudo(id);return value;}
        <T>T at(Object raw,Class<T> type)throws Exception{Object value=at(raw);if(!type.isInstance(value))throw bad("Candidate reference type mismatch");return type.cast(value);}
        Job build()throws Exception{
            int root=index(graph.get("root"),rows.size());Map<String,Object> rr=rows.get(root);if(!"PanelLocation".equals(rr.get("type")))throw bad("Candidate root is not a panel location");int rootHolder=index(rr.get("holder"),rows.size());job=own(new Job());
            for(int i=0;i<rows.size();i++){Map<String,Object> r=rows.get(i);String type=text(r.get("type"));Object value;switch(type){case "Board":value=own(new Board());break;case "Panel":value=i==rootHolder?own(job.getRootPanelLocation().getPanel()):own(new Panel());break;case "BoardLocation":value=own(new BoardLocation());break;case "PanelLocation":value=i==root?own(job.getRootPanelLocation()):own(new PanelLocation());break;case "Placement":value=own(new Placement(nullableText(r.get("id"))));break;case "PseudoPlacement":value=null;break;case "BoardPad":value=new BoardPad();break;default:throw bad("Unknown generated native node type");}objects.add(value);}
            for(int i=0;i<rows.size();i++)metadata(i);
            // Populate each actual native instance independently before definition listeners can
            // create implicit extra instance copies in response to indexed native events.
            for(int i=0;i<rows.size();i++)topology(i);
            for(int i=0;i<rows.size();i++)if(objects.get(i) instanceof PlacementsHolderLocation)locationDefinition(i);
            for(int i=0;i<rows.size();i++)if(objects.get(i) instanceof PlacementsHolder)holderDefinition(i);
            for(int i=0;i<rows.size();i++)if(objects.get(i) instanceof Placement&&"Placement".equals(rows.get(index(rows.get(i).get("definition"),rows.size())).get("type")))placementDefinition(i);
            for(int i=0;i<rows.size();i++)if(objects.get(i) instanceof Placement&&!"Placement".equals(rows.get(index(rows.get(i).get("definition"),rows.size())).get("type")))placementDefinition(i);
            for(int i=0;i<rows.size();i++)if("PseudoPlacement".equals(rows.get(i).get("type")))pseudo(i);
            for(int i=0;i<rows.size();i++)if(objects.get(i) instanceof Panel){Panel panel=(Panel)objects.get(i);IdentifiableList<Placement> list=new IdentifiableList<>();for(Object id:list(rows.get(i).get("pseudo"),10000)){Placement p=at(id,Placement.class);list.add(p);p.addPropertyChangeListener(panel);edge(p,panel,null);}panel.setPseudoPlacements(list);}
            for(Runnable restore:restoreListeners)restore.run();for(Object value:objects)if(value instanceof AbstractModelObject&&value instanceof PropertyChangeListener){AbstractModelObject m=(AbstractModelObject)value;PropertyChangeListener self=(PropertyChangeListener)value;while(m.isListener(self))m.removePropertyChangeListener(self);m.addPropertyChangeListener(self);}
            job.setErrorHandling(Job.ErrorHandling.valueOf(text(graph.get("error_handling"))));for(Object value:list(graph.get("overrides"),1000)){Map<String,Object> r=object(value);keys(r,"location","enabled","check_fiducials","placements");PlacementsHolderLocation<?> l=at(r.get("location"),PlacementsHolderLocation.class);job.storeEnabledState(l,null,bool(r.get("enabled")));job.storeCheckFiducialsState(l,bool(r.get("check_fiducials")));for(Object pv:list(r.get("placements"),10000)){Map<String,Object> pr=object(pv);keys(pr,"placement","enabled","error");Placement p=at(pr.get("placement"),Placement.class);job.storeEnabledState(l,p,bool(pr.get("enabled")));job.storeErrorHandlingState(l,p,Placement.ErrorHandling.valueOf(text(pr.get("error"))));}}
            return job;
        }
        @SuppressWarnings({"unchecked","rawtypes"})void metadata(int i)throws Exception{Map<String,Object> r=rows.get(i);Object v=objects.get(i);
            if(v instanceof PlacementsHolderLocation){keys(r,"type","definition","parent","holder","id","location","side","enabled","check_fiducials");PlacementsHolderLocation l=(PlacementsHolderLocation)v;l.setId(nullableText(r.get("id")));l.setLocation(location(r.get("location")));l.setSide(Side.valueOf(text(r.get("side"))));l.setLocallyEnabled(bool(r.get("enabled")));l.setCheckFiducials(bool(r.get("check_fiducials")));l.setPlacementsHolder(at(r.get("holder"),PlacementsHolder.class));l.setFileName(null);if(i!=index(graph.get("root"),rows.size()))l.setLocalToParentTransform(null);}
            else if(v instanceof PlacementsHolder){keys(r,"type","definition","name","dimensions","profile","placements","children","pseudo","pads");PlacementsHolder h=(PlacementsHolder)v;h.setName(nullableText(r.get("name")));h.setDimensions(location(r.get("dimensions")));h.setFile(null);if(r.get("profile")!=null){GeometricPath2D path=h.getProfile();fillPath(path,object(r.get("profile")));h.setProfile(path);}}
            else if(v instanceof Placement)placementValues((Placement)v,r);
            else if(v instanceof BoardPad){keys(r,"type","name","location","side","kind","shape");BoardPad p=(BoardPad)v;p.setName(nullableText(r.get("name")));p.setLocation(location(r.get("location")));p.setSide(Side.valueOf(text(r.get("side"))));p.setType(BoardPad.Type.valueOf(text(r.get("kind"))));p.setPad(readPad(object(r.get("shape"))));}
            else if(!"PseudoPlacement".equals(r.get("type")))throw bad("Missing native model shell");
        }
        void topology(int i)throws Exception{Object value=objects.get(i);Map<String,Object> r=rows.get(i);if(value instanceof PlacementsHolderLocation){PlacementsHolderLocation<?> l=(PlacementsHolderLocation<?>)value;if(r.get("parent")!=null)l.setParent(at(r.get("parent"),PanelLocation.class));}
            else if(value instanceof PlacementsHolder){PlacementsHolder<?> h=(PlacementsHolder<?>)value;for(Object id:list(r.get("placements"),10000)){Placement p=at(id,Placement.class);h.addPlacement(p);edge(p,h,null);}if(h instanceof Panel){if(!list(r.get("pads"),10000).isEmpty())throw bad("Panel has board pads");for(Object id:list(r.get("children"),1000)){PlacementsHolderLocation<?> l=at(id,PlacementsHolderLocation.class);((Panel)h).addChild(l);edge(l,h,null);}}else {if(!list(r.get("children"),1000).isEmpty()||!list(r.get("pseudo"),10000).isEmpty())throw bad("Board has panel content");for(Object id:list(r.get("pads"),10000)){BoardPad p=at(id,BoardPad.class);((Board)h).addSolderPastePad(p);edge(p,h,null);}}}}
        @SuppressWarnings({"unchecked","rawtypes"})void locationDefinition(int i)throws Exception{PlacementsHolderLocation l=(PlacementsHolderLocation)objects.get(i),d=at(rows.get(i).get("definition"),PlacementsHolderLocation.class);if(l.getClass()!=d.getClass())throw bad("Location definition type differs");if(l.getDefinition()!=d)l.setDefinition(d);edge(d,l,null);}
        @SuppressWarnings({"unchecked","rawtypes"})void holderDefinition(int i)throws Exception{PlacementsHolder h=(PlacementsHolder)objects.get(i),d=at(rows.get(i).get("definition"),PlacementsHolder.class);if(h.getClass()!=d.getClass())throw bad("Holder definition type differs");if(h.getDefinition()!=d){h.setDefinition(d);d.removePropertyChangeListener(h);restoreListeners.add(()->d.addPropertyChangeListener(h));}edge(d,h,null);}
        void placementDefinition(int i)throws Exception{Placement p=(Placement)objects.get(i),d=at(rows.get(i).get("definition"),Placement.class);if(p.getDefinition()!=d)p.setDefinition(d);edge(d,p,null);}
        Placement pseudo(int i)throws Exception{if(objects.get(i)!=null)return(Placement)objects.get(i);if(!constructingPseudo.add(i))throw bad("Cyclic native pseudo construction");Map<String,Object> r=rows.get(i);Panel owner=at(r.get("pseudo_owner"),Panel.class);Placement p=own(new PseudoPlacement(owner,text(r.get("id"))));objects.set(i,p);Pair<List<PlacementsHolderLocation<?>>,Placement> pair=owner.getDescendantPlacement(p.getId());if(pair==null)throw bad("Native pseudo target absent");for(String key:List.of("location","side","id","part","type","placementsHolder","placement","child")){edge(pair.second.getDefinition(),p,key);for(PlacementsHolderLocation<?> l:pair.first){edge(l.getDefinition(),p,key);edge(l.getDefinition().getPlacementsHolder().getDefinition(),p,key);}}placementValues(p,r);placementDefinition(i);constructingPseudo.remove(i);return p;}
        void placementValues(Placement p,Map<String,Object> r)throws Exception{keys(r,"type","definition","pseudo_owner","id","location","side","part","kind","enabled","error","comments","rank");p.setLocation(location(r.get("location")));p.setSide(Side.valueOf(text(r.get("side"))));Part part=r.get("part")==null?null:config.getPart(text(r.get("part")));if(r.get("part")!=null)canonical(config,part);if(p.getPart()!=part)p.setPart(part);p.setType(Placement.Type.valueOf(text(r.get("kind"))));p.setEnabled(bool(r.get("enabled")));p.setErrorHandling(Placement.ErrorHandling.valueOf(text(r.get("error"))));p.setComments(nullableText(r.get("comments")));p.setRank(signedInteger(r.get("rank")));}
        void cleanup(){for(int i=edges.size()-1;i>=0;i--)edges.get(i).remove();edges.clear();}
    }
    static final String RECONSTRUCTION_FORMAT="openpnp-replacement-reconstruction-v2";
    private static final String LEGACY_RECONSTRUCTION_FORMAT="openpnp-replacement-reconstruction-v1";
    static final int MAX_RECONSTRUCTION_BYTES=Bridge.MAX_JOURNAL_RECORD_BYTES;
    private static void verifyReconstructionDependencies(Configuration config,Map<String,Object> bundle)throws Exception{
        Map<String,Object> parts=object(bundle.get("required_parts")),packages=object(bundle.get("required_packages"));
        if(number(bundle.get("schema_version"))==1){verifyDependencies(config,parts,packages);return;}
        Set<String> requiredPackages=new TreeSet<>();
        for(var entry:parts.entrySet()){Part part=config.getPart(entry.getKey());canonical(config,part);requiredPackages.add(part.getPackage().getId());if(!fingerprint(part).equals(hash(entry.getValue())))throw bad("Reconstruction Part dependency changed: "+entry.getKey());}
        if(!requiredPackages.equals(packages.keySet()))throw bad("Reconstruction Package dependency set differs from its canonical Parts");
        for(var entry:packages.entrySet())if(!reconstructionPackageFingerprint(config.getPackage(entry.getKey())).equals(hash(entry.getValue())))throw bad("Reconstruction Package dependency changed: "+entry.getKey());
    }
    /** In the pinned native Package, a null visionCompositing field means exactly a new
     * VisionCompositing's defaults. Native job initialization lazily allocates that field without
     * saving configuration. V2 treats those two representations identically, without calling the
     * lazy getter or mutating the live Package. Every other serialized field remains in the hash.
     * V1 bundles and candidate archives retain their original exact-byte fingerprint contract. */
    private static String reconstructionPackageFingerprint(org.openpnp.model.Package value)throws Exception{
        if(value==null||value.getClass()!=org.openpnp.model.Package.class)throw bad("Exact native Package required");
        org.w3c.dom.Element pkg=generatedXml(value),compositing=null;
        for(org.w3c.dom.Node node=pkg.getFirstChild();node!=null;node=node.getNextSibling())if(node instanceof org.w3c.dom.Element&&"vision-compositing".equals(node.getNodeName())){
            if(compositing!=null)throw bad("Duplicate native vision compositing field");compositing=(org.w3c.dom.Element)node;
        }
        if(compositing!=null)pkg.removeChild(compositing);else compositing=generatedXml(new VisionCompositing());
        if(!"vision-compositing".equals(compositing.getTagName()))throw bad("Pinned native compositing serialization changed");
        return digest(map("profile","native-package-effective-compositing-v1","package",xmlTree(pkg,new int[1],0),"effective_vision_compositing",xmlTree(compositing,new int[1],0)));
    }
    /** Input is exclusively fresh native serializer output, never request XML or a file path. */
    private static org.w3c.dom.Element generatedXml(Object value)throws Exception{
        ByteArrayOutputStream bytes=new ByteArrayOutputStream();Configuration.createSerializer().write(value,bytes);
        if(bytes.size()>MAX_BYTES)throw bad("Native dependency exceeds byte bound");
        javax.xml.parsers.DocumentBuilderFactory factory=javax.xml.parsers.DocumentBuilderFactory.newDefaultInstance();
        factory.setFeature(javax.xml.XMLConstants.FEATURE_SECURE_PROCESSING,true);
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);
        factory.setFeature("http://xml.org/sax/features/external-general-entities",false);
        factory.setFeature("http://xml.org/sax/features/external-parameter-entities",false);
        factory.setAttribute(javax.xml.XMLConstants.ACCESS_EXTERNAL_DTD,"");factory.setAttribute(javax.xml.XMLConstants.ACCESS_EXTERNAL_SCHEMA,"");factory.setXIncludeAware(false);factory.setExpandEntityReferences(false);
        return factory.newDocumentBuilder().parse(new ByteArrayInputStream(bytes.toByteArray())).getDocumentElement();
    }
    private static Map<String,Object> xmlTree(org.w3c.dom.Element element,int[] count,int depth)throws Exception{
        if(depth>32||++count[0]>100000)throw bad("Native dependency XML exceeds structural bound");
        Map<String,Object> attributes=new TreeMap<>();org.w3c.dom.NamedNodeMap names=element.getAttributes();
        for(int i=0;i<names.getLength();i++)attributes.put(names.item(i).getNodeName(),names.item(i).getNodeValue());
        List<Object> children=new ArrayList<>();boolean hasElements=false;
        for(org.w3c.dom.Node node=element.getFirstChild();node!=null;node=node.getNextSibling())if(node instanceof org.w3c.dom.Element)hasElements=true;
        for(org.w3c.dom.Node node=element.getFirstChild();node!=null;node=node.getNextSibling()){
            if(node instanceof org.w3c.dom.Element)children.add(xmlTree((org.w3c.dom.Element)node,count,depth+1));
            else if(node.getNodeType()==org.w3c.dom.Node.TEXT_NODE||node.getNodeType()==org.w3c.dom.Node.CDATA_SECTION_NODE){if(!hasElements||!node.getNodeValue().isBlank())children.add(map("text",node.getNodeValue()));}
            else throw bad("Unexpected generated native XML node");
        }
        return map("element",element.getTagName(),"attributes",attributes,"children",children);
    }
    /** Owns only newly constructed inert original objects and the unpublished candidate. The
     * transaction owner retains this wrapper until its own close. Candidate.publish() alone
     * transfers the candidate job; close never destroys an already published candidate. */
    static final class Reconstructed implements AutoCloseable {
        private final Configuration config;private final Decoder decoder;private final Job original;
        private final NativeReplacementJob.Candidate candidate;private final Map<String,Object> bundle;
        private final Map<String,Object> decodedProvenance;private boolean closed;
        private Reconstructed(Configuration c,Decoder d,Job original,NativeReplacementJob.Candidate candidate,Map<String,Object> bundle)throws Exception{config=c;decoder=d;this.original=original;this.candidate=candidate;this.bundle=bundle;decodedProvenance=new Encoder(c,original,true).provenance();}
        Job original(){if(closed)throw new IllegalStateException("Reconstruction is closed");return original;}
        NativeReplacementJob.Candidate candidate(){if(closed)throw new IllegalStateException("Reconstruction is closed");return candidate;}
        Map<String,Object> bundle(){return bundle;}
        void requireCurrent()throws Exception{owner(config);if(closed)throw bad("Reconstruction is closed");candidate.requireOriginal(original);verifyReconstructionDependencies(config,bundle);Encoder old=new Encoder(config,original,true),fresh=new Encoder(config,candidate.job(),false);
            if(!same(old.payload(),bundle.get("original_graph"))||!same(fresh.payload(),bundle.get("candidate_graph"))||!same(original.getPlacedStatusSnapshot(),bundle.get("original_history"))||!same(candidate.mapping(),bundle.get("source_mapping"))||!same(NativeBoardLoads.replacementModel(original),bundle.get("original_board_models"))||!same(old.provenance(),decodedProvenance))throw bad("Reconstructed native objects changed");}
        @Override public void close(){if(!closed){candidate.close();decoder.cleanup();closed=true;}}
    }
    /** Native capture only; no journal append, file access, native job installation or effects. */
    static Map<String,Object> captureReconstruction(Configuration config,Job original,NativeReplacementJob.Candidate candidate)throws Exception{
        owner(config);Objects.requireNonNull(candidate);candidate.requireOriginal(original);
        Encoder old=new Encoder(config,original,true),fresh=new Encoder(config,candidate.job(),false);
        Map<String,Object> history=frozen(new TreeMap<String,Object>(original.getPlacedStatusSnapshot())),oldGraph=old.payload(),newGraph=fresh.payload(),mapping=frozen(candidate.mapping()),provenance=old.provenance(),models=NativeBoardLoads.replacementModel(original);
        Map<String,Object> parts=new TreeMap<>(),packages=new TreeMap<>();Set<Part> dependencies=new LinkedHashSet<>(old.parts);dependencies.addAll(fresh.parts);for(Part part:dependencies){canonical(config,part);parts.put(part.getId(),fingerprint(part));packages.put(part.getPackage().getId(),reconstructionPackageFingerprint(part.getPackage()));}
        Map<String,Object> result=frozen(map("format",RECONSTRUCTION_FORMAT,"schema_version",2,"upstream_commit",Bridge.UPSTREAM,"original_graph_role","inert-historical-reconstruction",
            "original_graph",oldGraph,"original_graph_sha256",digest(oldGraph),"candidate_graph",newGraph,"candidate_graph_sha256",digest(newGraph),"original_history",history,"original_history_sha256",digest(history),"source_mapping",mapping,"source_mapping_sha256",digest(mapping),"original_board_models",models,"original_board_models_sha256",digest(models),"required_parts",parts,"required_packages",packages,"original_provenance",provenance,"original_provenance_sha256",digest(provenance),"job_installed",false,"native_job_initialized",false,"execution_authority_restored",false,"load_presence_verified",false,"sensing_authority_restored",false));
        validateReconstruction(result);candidate.requireOriginal(original);verifyReconstructionDependencies(config,result);return result;
    }
    /** Pure DTO validation for the forced intent reducer; never touches Configuration or models. */
    static void validateReconstruction(Map<String,Object> bundle)throws Exception{
        requireReconstructionBytes(bundle);keys(bundle,"format","schema_version","upstream_commit","original_graph_role","original_graph","original_graph_sha256","candidate_graph","candidate_graph_sha256","original_history","original_history_sha256","source_mapping","source_mapping_sha256","original_board_models","original_board_models_sha256","required_parts","required_packages","original_provenance","original_provenance_sha256","job_installed","native_job_initialized","execution_authority_restored","load_presence_verified","sensing_authority_restored");
        long version=number(bundle.get("schema_version"));if(!(version==1&&LEGACY_RECONSTRUCTION_FORMAT.equals(bundle.get("format"))||version==2&&RECONSTRUCTION_FORMAT.equals(bundle.get("format")))||!Bridge.UPSTREAM.equals(bundle.get("upstream_commit"))||!"inert-historical-reconstruction".equals(bundle.get("original_graph_role")))throw bad("Reconstruction format or pinned native version differs");
        for(String key:List.of("job_installed","native_job_initialized","execution_authority_restored","load_presence_verified","sensing_authority_restored"))if(!Boolean.FALSE.equals(bundle.get(key)))throw bad("Reconstruction cannot restore authority");
        for(String key:List.of("original_graph","candidate_graph","original_history","source_mapping","original_board_models","original_provenance"))if(!digest(object(bundle.get(key))).equals(hash(bundle.get(key+"_sha256"))))throw bad("Reconstruction digest differs: "+key);
        GraphShape old=new GraphShape(object(bundle.get("original_graph"))),fresh=new GraphShape(object(bundle.get("candidate_graph")));
        Map<String,Object> history=object(bundle.get("original_history"));if(history.size()>100000)throw bad("Complete original history exceeds bound");for(var e:history.entrySet()){text(e.getKey());bool(e.getValue());}
        Map<String,Object> parts=object(bundle.get("required_parts")),packages=object(bundle.get("required_packages"));if(parts.size()>10000||packages.size()>10000)throw bad("Reconstruction dependency bound");for(Map<String,Object> values:List.of(parts,packages))for(var e:values.entrySet()){text(e.getKey());hash(e.getValue());}
        Set<String> referenced=new TreeSet<>(old.parts);referenced.addAll(fresh.parts);if(!referenced.equals(parts.keySet())||parts.isEmpty()!=packages.isEmpty())throw bad("Reconstruction native dependency set differs");
        Map<String,Object> models=object(bundle.get("original_board_models"));if(models.size()>100||models.isEmpty())throw bad("Original board model bound");for(var e:models.entrySet()){text(e.getKey());hash(e.getValue());}
        validateReconstructionMapping(object(bundle.get("source_mapping")),history,old,fresh);validateProvenance(object(bundle.get("original_provenance")),old);
    }
    static Reconstructed reconstruct(Configuration config,Map<String,Object> supplied)throws Exception{
        owner(config);validateReconstruction(supplied);Map<String,Object> bundle=frozen(supplied);verifyReconstructionDependencies(config,bundle);
        Decoder decoder=new Decoder(config,object(bundle.get("original_graph")));NativeReplacementJob.Candidate candidate=null;
        try{Job original=decoder.build();restoreInertHistory(original,object(bundle.get("original_history")));if(!same(new Encoder(config,original,true).payload(),bundle.get("original_graph")))throw bad("Original reconstruction graph differs");
            candidate=NativeReplacementJob.build(config,original);if(!same(candidate.mapping(),bundle.get("source_mapping"))||!same(new Encoder(config,candidate.job(),false).payload(),bundle.get("candidate_graph"))||!same(NativeBoardLoads.replacementModel(original),bundle.get("original_board_models")))throw bad("Rebuilt candidate mapping, graph or original board model differs");
            Reconstructed result=new Reconstructed(config,decoder,original,candidate,bundle);result.requireCurrent();return result;
        }catch(Exception|Error failure){if(candidate!=null)candidate.close();decoder.cleanup();throw failure;}
    }
    /** Only a newly allocated inert Job receives this exact opaque map. Public placement APIs
     * cannot express removed/orphan keys; no existing Job or history is cleared or rewritten. */
    @SuppressWarnings("unchecked") private static void restoreInertHistory(Job job,Map<String,Object> history)throws Exception{
        if(job.getClass()!=Job.class||!job.getPlacedStatusSnapshot().isEmpty())throw bad("Only a fresh inert original Job may receive historical keys");java.lang.reflect.Field field=Job.class.getDeclaredField("placedStatusMap");if(!field.trySetAccessible())throw bad("Pinned complete native history field unavailable");Object raw=field.get(job);if(!(raw instanceof Map)||!((Map<?,?>)raw).isEmpty())throw bad("New original has unexpected native history");Map<String,Boolean> exact=new TreeMap<>();for(var e:history.entrySet())exact.put(text(e.getKey()),bool(e.getValue()));((Map<String,Boolean>)raw).putAll(exact);if(!exact.equals(job.getPlacedStatusSnapshot()))throw bad("Exact original history reconstruction failed");
    }
    private static void requireReconstructionBytes(Map<String,Object> value)throws Exception{
        // Reject object cycles/excessive depth before Gson can recursively traverse caller data.
        Set<Object> stack=Collections.newSetFromMap(new IdentityHashMap<>());int[] nodes={0};validateJsonTree(value,0,stack,nodes);
        byte[] bytes=new com.google.gson.GsonBuilder().serializeNulls().create().toJson(value).getBytes(StandardCharsets.UTF_8);if(bytes.length>MAX_RECONSTRUCTION_BYTES)throw bad("Reconstruction exceeds journal byte bound");
    }
    private static void validateJsonTree(Object value,int depth,Set<Object> stack,int[] nodes)throws Exception{
        if(depth>32||++nodes[0]>2000000)throw bad("Reconstruction JSON exceeds structural bound");if(value==null||value instanceof Boolean)return;if(value instanceof String){text(value);return;}if(value instanceof Number){decimal(value);return;}
        if(!(value instanceof Map)&&!(value instanceof List))throw bad("Reconstruction contains non-JSON value");if(!stack.add(value))throw bad("Cyclic reconstruction JSON");
        if(value instanceof Map){if(((Map<?,?>)value).size()>100000)throw bad("Reconstruction map bound");for(var e:((Map<?,?>)value).entrySet()){text(e.getKey());validateJsonTree(e.getValue(),depth+1,stack,nodes);}}
        else{if(((List<?>)value).size()>100000)throw bad("Reconstruction list bound");for(Object item:(List<?>)value)validateJsonTree(item,depth+1,stack,nodes);}stack.remove(value);
    }
    private static void validateReconstructionMapping(Map<String,Object> m,Map<String,Object> history,GraphShape old,GraphShape fresh)throws Exception{
        keys(m,"schema_version","origin","source_model_sha256","replacement_model_sha256","source_history_sha256","source_history_entries","source_completed_history_entries","replacement_history_entries","locations","placements","definitions_copied","registration_copied","files_bound","native_job_initialized","physical_load_verified");
        if(number(m.get("schema_version"))!=1||!"current-native-job-detached-copy".equals(m.get("origin"))||!hash(m.get("source_model_sha256")).equals(hash(m.get("replacement_model_sha256")))||!digest(history).equals(hash(m.get("source_history_sha256")))||number(m.get("source_history_entries"))!=history.size()||number(m.get("source_completed_history_entries"))!=history.values().stream().filter(Boolean.TRUE::equals).count()||number(m.get("replacement_history_entries"))!=0||number(m.get("definitions_copied"))<1)throw bad("Reconstruction mapping model/history differs");
        for(String key:List.of("registration_copied","files_bound","native_job_initialized","physical_load_verified"))if(!Boolean.FALSE.equals(m.get(key)))throw bad("Reconstruction mapping restores authority");
        Set<String> seen=new HashSet<>();for(Object item:list(m.get("locations"),1000)){Map<String,Object> row=object(item);keys(row,"source_location_id","replacement_location_id","source_definition","replacement_definition");String id=nullableText(row.get("source_location_id"));if(!seen.add(id)||!Objects.equals(id,nullableText(row.get("replacement_location_id")))||!old.expanded.containsKey(id)||!fresh.expanded.containsKey(id))throw bad("Reconstruction mapping location differs");number(row.get("source_definition"));number(row.get("replacement_definition"));}
        if(!seen.equals(old.expanded.keySet())||!seen.equals(fresh.expanded.keySet()))throw bad("Reconstruction mapping omits native locations");
        Map<String,String> expected=old.expandedPlacements();if(!expected.equals(fresh.expandedPlacements()))throw bad("Candidate placement identities differ");Set<String> placements=new HashSet<>();for(Object item:list(m.get("placements"),10000)){Map<String,Object> row=object(item);keys(row,"location_id","placement_id","part_id","source_placed","replacement_placed");String key=String.valueOf(nullableText(row.get("location_id")))+"⇒"+text(row.get("placement_id"));if(!placements.add(key)||!expected.containsKey(key)||!Objects.equals(expected.get(key),nullableText(row.get("part_id")))||bool(row.get("source_placed"))!=Boolean.TRUE.equals(history.get(key))||!Boolean.FALSE.equals(row.get("replacement_placed")))throw bad("Reconstruction mapping placement/history differs");}if(!placements.equals(expected.keySet()))throw bad("Reconstruction mapping omits placements");
    }
    private static void validateProvenance(Map<String,Object> p,GraphShape graph)throws Exception{
        keys(p,"role","job_file","job_dirty","nodes");if(!"inert-only; never opened or applied".equals(p.get("role")))throw bad("Original provenance role differs");nullableText(p.get("job_file"));bool(p.get("job_dirty"));Set<Integer> seen=new HashSet<>();
        for(Object value:list(p.get("nodes"),MAX_NODES)){Map<String,Object> row=object(value);int i=index(row.get("index"),graph.rows.size());String type=text(row.get("type"));if(!seen.add(i)||!type.equals(graph.rows.get(i).get("type")))throw bad("Original provenance node differs");
            if(type.endsWith("Location")){keys(row,"index","type","file","dirty","registration","registration_status");nullableText(row.get("file"));bool(row.get("dirty"));if(row.get("registration")!=null){List<?> matrix=list(row.get("registration"),6);if(matrix.size()!=6)throw bad("Original transform matrix bound");for(Object d:matrix)decimal(d);}oneOf(row.get("registration_status"),"NotSet","GloballySet","LocallySet");}
            else if(type.equals("Board")||type.equals("Panel")){keys(row,"index","type","file","dirty");nullableText(row.get("file"));bool(row.get("dirty"));}
            else if(type.equals("Placement")||type.equals("PseudoPlacement")){keys(row,"index","type","dirty");bool(row.get("dirty"));}
            else{keys(row,"index","type");}
        }if(seen.size()!=graph.rows.size())throw bad("Original provenance omits native nodes");
    }
    /** Closed generated graph validation using DTOs only. Native semantic reconstruction runs
     * again on the owning executor and must reproduce the exact candidate graph and mapping. */
    private static final class GraphShape {
        final List<Map<String,Object>> rows=new ArrayList<>();final Set<String> parts=new TreeSet<>();final Map<String,Integer> expanded=new LinkedHashMap<>();final int root;
        GraphShape(Map<String,Object> graph)throws Exception{
            keys(graph,"schema_version","root","error_handling","nodes","overrides");if(number(graph.get("schema_version"))!=1)throw bad("Reconstruction graph version");oneOf(graph.get("error_handling"),"Alert","Defer");for(Object value:list(graph.get("nodes"),MAX_NODES))rows.add(object(value));if(rows.isEmpty())throw bad("Empty reconstruction graph");root=index(graph.get("root"),rows.size());
            for(int i=0;i<rows.size();i++)validateNode(i);Map<String,Object> rr=rows.get(root);if(!"PanelLocation".equals(rr.get("type"))||rr.get("parent")!=null||index(rr.get("definition"),rows.size())!=root)throw bad("Reconstruction root ownership differs");int holder=ref(rr.get("holder"),"Panel");if(index(rows.get(holder).get("definition"),rows.size())!=holder)throw bad("Reconstruction root holder must own its definition");
            Set<Integer> reachable=new HashSet<>();ArrayDeque<Integer> queue=new ArrayDeque<>();queue.add(root);while(!queue.isEmpty()){int i=queue.remove();if(reachable.add(i))queue.addAll(references(rows.get(i)));}if(reachable.size()!=rows.size())throw bad("Unreachable reconstruction native node");
            expand(root,new HashSet<>());
            Set<Integer> overrides=new HashSet<>();for(Object value:list(graph.get("overrides"),1000)){Map<String,Object> r=object(value);keys(r,"location","enabled","check_fiducials","placements");int loc=ref(r.get("location"),"BoardLocation","PanelLocation");if(!overrides.add(loc)||!expanded.containsValue(loc))throw bad("Reconstruction override location differs");bool(r.get("enabled"));bool(r.get("check_fiducials"));Set<Integer> actual=new HashSet<>();for(Object pv:list(r.get("placements"),10000)){Map<String,Object> pr=object(pv);keys(pr,"placement","enabled","error");if(!actual.add(ref(pr.get("placement"),"Placement","PseudoPlacement")))throw bad("Duplicate reconstruction placement override");bool(pr.get("enabled"));oneOf(pr.get("error"),"Default","Alert","Defer");}if(!actual.equals(refSet(rows.get(index(rows.get(loc).get("holder"),rows.size())).get("placements"))))throw bad("Reconstruction placement override membership differs");}if(!overrides.equals(new HashSet<>(expanded.values())))throw bad("Reconstruction omits location overrides");
        }
        int ref(Object value,String...types)throws Exception{int id=index(value,rows.size());oneOf(rows.get(id).get("type"),types);return id;}
        Set<Integer> refSet(Object value)throws Exception{Set<Integer> out=new HashSet<>();for(Object v:list(value,10000))if(!out.add(index(v,rows.size())))throw bad("Duplicate graph membership");return out;}
        void validateNode(int i)throws Exception{Map<String,Object> r=rows.get(i);String type=text(r.get("type"));
            if(type.equals("BoardLocation")||type.equals("PanelLocation")){keys(r,"type","definition","parent","holder","id","location","side","enabled","check_fiducials");int d=ref(r.get("definition"),type);if(index(rows.get(d).get("definition"),rows.size())!=d)throw bad("Location definition must be self-owned");ref(r.get("holder"),type.equals("BoardLocation")?"Board":"Panel");nullableText(r.get("id"));validatePose(r.get("location"));oneOf(r.get("side"),"Top","Bottom");bool(r.get("enabled"));bool(r.get("check_fiducials"));Set<Integer> parents=new HashSet<>();for(Object next=r.get("parent");next!=null;next=rows.get(index(next,rows.size())).get("parent"))if(!parents.add(ref(next,"PanelLocation"))||parents.size()>1000||index(next,rows.size())==i)throw bad("Cyclic native parent chain");}
            else if(type.equals("Board")||type.equals("Panel")){keys(r,"type","definition","name","dimensions","profile","placements","children","pseudo","pads");int d=ref(r.get("definition"),type);if(index(rows.get(d).get("definition"),rows.size())!=d)throw bad("Holder definition must be self-owned");nullableText(r.get("name"));validatePose(r.get("dimensions"));if(r.get("profile")!=null)validatePath(object(r.get("profile")));for(Object id:list(r.get("placements"),10000))ref(id,"Placement","PseudoPlacement");for(Object id:list(r.get("children"),1000))ref(id,"BoardLocation","PanelLocation");for(Object id:list(r.get("pseudo"),10000))ref(id,"Placement","PseudoPlacement");for(Object id:list(r.get("pads"),10000))ref(id,"BoardPad");for(String key:List.of("placements","children","pseudo","pads"))refSet(r.get(key));if(type.equals("Board")&&(!((List<?>)r.get("children")).isEmpty()||!((List<?>)r.get("pseudo")).isEmpty())||type.equals("Panel")&&!((List<?>)r.get("pads")).isEmpty())throw bad("Native holder child types differ");}
            else if(type.equals("Placement")||type.equals("PseudoPlacement")){keys(r,"type","definition","pseudo_owner","id","location","side","part","kind","enabled","error","comments","rank");int d=ref(r.get("definition"),"Placement","PseudoPlacement");if(index(rows.get(d).get("definition"),rows.size())!=d)throw bad("Placement definition must be self-owned");if(type.equals("PseudoPlacement"))ref(r.get("pseudo_owner"),"Panel");else if(r.get("pseudo_owner")!=null)throw bad("Ordinary placement has pseudo owner");text(r.get("id"));validatePose(r.get("location"));oneOf(r.get("side"),"Top","Bottom");if(r.get("part")!=null)parts.add(text(r.get("part")));oneOf(r.get("kind"),"Placement","Fiducial","Place","Ignore");bool(r.get("enabled"));oneOf(r.get("error"),"Default","Alert","Defer");nullableText(r.get("comments"));signedInteger(r.get("rank"));}
            else if(type.equals("BoardPad")){keys(r,"type","name","location","side","kind","shape");nullableText(r.get("name"));validatePose(r.get("location"));oneOf(r.get("side"),"Top","Bottom");oneOf(r.get("kind"),"Paste","Ignore");validatePad(object(r.get("shape")));}else throw bad("Unknown reconstruction native type");
        }
        List<Integer> references(Map<String,Object> r)throws Exception{List<Integer> result=new ArrayList<>();for(String key:List.of("definition","parent","holder","pseudo_owner"))if(r.get(key)!=null)result.add(index(r.get(key),rows.size()));for(String key:List.of("placements","children","pseudo","pads"))if(r.containsKey(key))for(Object id:list(r.get(key),10000))result.add(index(id,rows.size()));return result;}
        void expand(int loc,Set<Integer> ancestors)throws Exception{if(!ancestors.add(loc)||ancestors.size()>1000||expanded.size()>=1000)throw bad("Cyclic/excessive expanded locations");String id=uniqueId(loc);if(expanded.put(id,loc)!=null)throw bad("Duplicate expanded native location");Map<String,Object> r=rows.get(loc);if("PanelLocation".equals(r.get("type")))for(Object child:list(rows.get(index(r.get("holder"),rows.size())).get("children"),1000))expand(index(child,rows.size()),ancestors);ancestors.remove(loc);}
        String uniqueId(int loc)throws Exception{List<String> ids=new ArrayList<>();for(int i=loc;;){Map<String,Object> r=rows.get(i);ids.add(nullableText(r.get("id")));Object parent=r.get("parent");if(parent==null)break;i=index(parent,rows.size());if(ids.size()>1000)throw bad("Unique native ID parent bound");}Collections.reverse(ids);String result=null;for(String id:ids)result=result==null?id:result+"⇒"+id;return result;}
        Map<String,String> expandedPlacements()throws Exception{Map<String,String> result=new LinkedHashMap<>();for(var e:expanded.entrySet()){Map<String,Object> holder=rows.get(index(rows.get(e.getValue()).get("holder"),rows.size()));for(Object id:list(holder.get("placements"),10000)){Map<String,Object> p=rows.get(index(id,rows.size()));String key=e.getKey()+"⇒"+text(p.get("id"));if(result.containsKey(key)||result.size()>=10000)throw bad("Duplicate/excessive mapped placements");result.put(key,nullableText(p.get("part")));}}return result;}
    }
    private static void oneOf(Object value,String...accepted)throws Exception{String actual=text(value);for(String item:accepted)if(item.equals(actual))return;throw bad("Invalid generated enum value: "+actual);}
    private static void validatePose(Object value)throws Exception{Map<String,Object> p=object(value);keys(p,"units","x","y","z","rotation");validateUnits(p.get("units"));for(String key:List.of("x","y","z","rotation"))decimal(p.get(key));}
    private static void validateUnits(Object value)throws Exception{oneOf(value,"Meters","Centimeters","Millimeters","Feet","Inches","Mils","Microns");}
    private static void validatePad(Map<String,Object> r)throws Exception{keys(r,"type","units","values");validateUnits(r.get("units"));Map<String,Object> values=object(r.get("values"));switch(text(r.get("type"))){case "Circle":keys(values,"radius");break;case "Ellipse":keys(values,"width","height");break;case "RoundRectangle":keys(values,"width","height","roundness");break;default:throw bad("Unsupported generated pad shape");}for(Object value:values.values())decimal(value);}
    private static void validatePath(Map<String,Object> p)throws Exception{keys(p,"units","winding","segments");validateUnits(p.get("units"));int winding=signedInteger(p.get("winding"));if(winding!=0&&winding!=1)throw bad("Invalid generated winding");boolean moved=false;for(Object value:list(p.get("segments"),10000)){Map<String,Object> r=object(value);keys(r,"kind","coords");int kind=signedInteger(r.get("kind"));if(kind<0||kind>4)throw bad("Invalid generated path segment");List<?> coords=list(r.get("coords"),6);int count=kind==4?0:kind==2?4:kind==3?6:2;if(coords.size()!=count||kind!=0&&!moved)throw bad("Invalid generated path sequence");for(Object c:coords)decimal(c);if(kind==0)moved=true;}}

    private static Map<String,Object> pose(Location l)throws Exception{return map("units",l.getUnits().name(),"x",finite(l.getX()),"y",finite(l.getY()),"z",finite(l.getZ()),"rotation",finite(l.getRotation()));}
    private static Location location(Object value)throws Exception{Map<String,Object> p=object(value);keys(p,"units","x","y","z","rotation");return new Location(LengthUnit.valueOf(text(p.get("units"))),decimal(p.get("x")),decimal(p.get("y")),decimal(p.get("z")),decimal(p.get("rotation")));}
    private static Map<String,Object> path(GeometricPath2D p)throws Exception{List<Object> segments=new ArrayList<>();PathIterator it=p.getPathIterator(null);double[] c=new double[6];while(!it.isDone()){if(segments.size()>=10000)throw bad("Outline segment bound exceeded");int type=it.currentSegment(c),n=type==PathIterator.SEG_CLOSE?0:type==PathIterator.SEG_QUADTO?4:type==PathIterator.SEG_CUBICTO?6:2;List<Object> coords=new ArrayList<>();for(int i=0;i<n;i++)coords.add(finite(c[i]));segments.add(map("kind",type,"coords",coords));it.next();}return map("units",p.getUnits().name(),"winding",p.getWindingRule(),"segments",segments);}
    private static void fillPath(GeometricPath2D path,Map<String,Object> p)throws Exception{keys(p,"units","winding","segments");path.reset();path.setUnits(LengthUnit.valueOf(text(p.get("units"))));int winding=signedInteger(p.get("winding"));if(winding!=PathIterator.WIND_EVEN_ODD&&winding!=PathIterator.WIND_NON_ZERO)throw bad("Outline winding invalid");path.setWindingRule(winding);for(Object raw:list(p.get("segments"),10000)){Map<String,Object> r=object(raw);keys(r,"kind","coords");int kind=signedInteger(r.get("kind")),n=kind==PathIterator.SEG_CLOSE?0:kind==PathIterator.SEG_QUADTO?4:kind==PathIterator.SEG_CUBICTO?6:2;List<?> coords=list(r.get("coords"),6);if(coords.size()!=n)throw bad("Outline coordinate count differs");double[] c=new double[n];for(int i=0;i<n;i++)c[i]=decimal(coords.get(i));switch(kind){case PathIterator.SEG_MOVETO:path.moveTo(c[0],c[1]);break;case PathIterator.SEG_LINETO:path.lineTo(c[0],c[1]);break;case PathIterator.SEG_QUADTO:path.quadTo(c[0],c[1],c[2],c[3]);break;case PathIterator.SEG_CUBICTO:path.curveTo(c[0],c[1],c[2],c[3],c[4],c[5]);break;case PathIterator.SEG_CLOSE:path.closePath();break;default:throw bad("Unknown outline segment");}}}
    private static Map<String,Object> pad(Pad p)throws Exception{Map<String,Object> values;if(p.getClass()==Pad.Circle.class)values=map("radius",finite(((Pad.Circle)p).getRadius()));else if(p.getClass()==Pad.Ellipse.class)values=map("width",finite(((Pad.Ellipse)p).getWidth()),"height",finite(((Pad.Ellipse)p).getHeight()));else if(p.getClass()==Pad.RoundRectangle.class)values=map("width",finite(((Pad.RoundRectangle)p).getWidth()),"height",finite(((Pad.RoundRectangle)p).getHeight()),"roundness",finite(((Pad.RoundRectangle)p).getRoundness()));else throw bad("Unsupported native pad shape");return map("type",p.getClass().getSimpleName(),"units",p.getUnits().name(),"values",values);}
    private static Pad readPad(Map<String,Object> r)throws Exception{keys(r,"type","units","values");Map<String,Object> values=object(r.get("values"));Pad p;switch(text(r.get("type"))){case "Circle":keys(values,"radius");Pad.Circle c=new Pad.Circle();c.setRadius(decimal(values.get("radius")));p=c;break;case "Ellipse":keys(values,"width","height");Pad.Ellipse e=new Pad.Ellipse();e.setWidth(decimal(values.get("width")));e.setHeight(decimal(values.get("height")));p=e;break;case "RoundRectangle":keys(values,"width","height","roundness");Pad.RoundRectangle rr=new Pad.RoundRectangle();rr.setWidth(decimal(values.get("width")));rr.setHeight(decimal(values.get("height")));rr.setRoundness(decimal(values.get("roundness")));p=rr;break;default:throw bad("Unknown native pad shape");}p.setUnits(LengthUnit.valueOf(text(r.get("units"))));return p;}
    private static byte[] json(Map<String,Object> p)throws Exception{byte[] bytes=new com.google.gson.GsonBuilder().serializeNulls().create().toJson(p).getBytes(StandardCharsets.UTF_8);if(bytes.length>MAX_BYTES)throw bad("Candidate manifest exceeds byte bound");return bytes;}
    private static byte[] zip(Map<String,byte[]> files)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();long total=0;try(ZipOutputStream z=new ZipOutputStream(out)){for(Map.Entry<String,byte[]> e:files.entrySet()){total+=e.getValue().length;if(total>MAX_BYTES)throw bad("Candidate document exceeds uncompressed bound");ZipEntry entry=new ZipEntry(e.getKey());entry.setTime(0);z.putNextEntry(entry);z.write(e.getValue());z.closeEntry();}}if(out.size()>MAX_BYTES)throw bad("Candidate archive exceeds byte bound");return out.toByteArray();}
    private static Map<String,byte[]> unzip(byte[] bytes,Map<String,String> hashes)throws Exception{if(!hashes.keySet().equals(Set.of("manifest.json","job.job.xml")))throw bad("Candidate archive entry schema differs");Map<String,byte[]> files=new LinkedHashMap<>();int total=0;try(ZipInputStream z=new ZipInputStream(new ByteArrayInputStream(bytes))){ZipEntry e;while((e=z.getNextEntry())!=null){String name=e.getName();if(e.isDirectory()||!hashes.containsKey(name)||files.containsKey(name))throw bad("Unknown or duplicate candidate archive entry");ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=z.read(buffer))!=-1){total+=n;if(total>MAX_BYTES)throw bad("Candidate archive expansion exceeds bound");out.write(buffer,0,n);}byte[] content=out.toByteArray();if(!sha(content).equals(hashes.get(name)))throw bad("Candidate entry hash mismatch");files.put(name,content);}}if(!files.keySet().equals(hashes.keySet()))throw bad("Missing candidate archive entry");return files;}
    private static byte[] read(Path file,int maximum)throws Exception{if(!Files.isRegularFile(file,LinkOption.NOFOLLOW_LINKS)||Files.size(file)>maximum)throw bad("Expected bounded regular candidate file");try(InputStream in=Files.newInputStream(file)){byte[] b=in.readNBytes(maximum+1);if(b.length>maximum)throw bad("Candidate file grew beyond bound");return b;}}
    private static String fingerprint(Object value)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();Configuration.createSerializer().write(value,out);if(out.size()>MAX_BYTES)throw bad("Native dependency exceeds byte bound");return sha(out.toByteArray());}
    private static String sha(byte[] b)throws Exception{StringBuilder out=new StringBuilder();for(byte v:MessageDigest.getInstance("SHA-256").digest(b))out.append(String.format(Locale.ROOT,"%02x",v&255));return out.toString();}
    private static Map<String,Object> map(Object...v){return NativeFaultedJobReplacement.map(v);}private static Map<String,Object> object(Object v)throws IOException{return NativeFaultedJobReplacement.object(v);}private static Map<String,Object> frozen(Map<String,Object> v)throws IOException{return NativeFaultedJobReplacement.frozen(v);}private static boolean same(Object a,Object b)throws IOException{return NativeFaultedJobReplacement.same(a,b);}private static String digest(Map<String,Object> v)throws IOException{return NativeFaultedJobReplacement.digest(v);}private static void keys(Map<String,Object> p,String...k)throws IOException{NativeFaultedJobReplacement.keys(p,k);}private static String hash(Object v)throws IOException{return NativeFaultedJobReplacement.hash(v);}private static String uuid(Object v)throws IOException{return NativeFaultedJobReplacement.uuid(v);}private static long number(Object v)throws IOException{return NativeFaultedJobReplacement.number(v);}
    private static String text(Object v)throws IOException{if(!(v instanceof String)||((String)v).length()>8192)throw bad("Bounded text required");return(String)v;}private static String nullableText(Object v)throws IOException{return v==null?null:text(v);}private static boolean bool(Object v)throws IOException{if(!(v instanceof Boolean))throw bad("Boolean required");return(Boolean)v;}private static List<?> list(Object v,int maximum)throws IOException{if(!(v instanceof List)||((List<?>)v).size()>maximum)throw bad("Bounded list required");return(List<?>)v;}private static int index(Object v,int count)throws IOException{long i=number(v);if(i>=count)throw bad("Candidate reference outside graph");return(int)i;}private static int signedInteger(Object v)throws IOException{try{if(!(v instanceof Number))throw new ArithmeticException();return new java.math.BigDecimal(v.toString()).intValueExact();}catch(ArithmeticException|NumberFormatException e){throw bad("Exact integer required");}}private static double decimal(Object v)throws IOException{if(!(v instanceof Number))throw bad("Finite number required");return finite(((Number)v).doubleValue());}private static double finite(double v)throws IOException{if(!Double.isFinite(v))throw bad("Finite geometry required");return v;}private static IOException bad(String s){return new IOException(s);}
}
